[0-1단계]
woowacourse/spring-roomescape-payment pull request #10
Opened 2024-05-29 05:26 UTC by takoyakimchi

2024-05-29 09:40 UTC, kimhodol requested changes
안녕하세요 트레 :) 오랜만이예요!

1단계 구현 잘 해주셨네요.

코멘트 확인 부탁드립니다~

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/controller/api/UserReservationController.java
> +        @AuthenticationPrincipal Member member) throws Exception {
질문) throws Exception은 왜 필요한가요?

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +    private static final String TOSS_PAYMENTS_URL = "https://api.tosspayments.com/v1/payments/confirm";
의견) url도 application property로 관리하는 것은 어떨까요? secret key와 함께 ConfigurationProperties를 사용하면 좋을 것 같네요.

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +                .header("Authorization", authorizations)
의견) `HttpHeaders.AUTHORIZATION`을 사용해도 괜찮겠네요.

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +    private final RestClient restClient;
질문) RestClient를 선택한 배경이 궁금해요. 다른 구현체들에 비해 어떤 장점/단점이 있나요?

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +        } catch (HttpClientErrorException e) {
질문) 문서를 봤을 때 RestClient는 RestClientResponseException를 발생시키는데, HttpClientErrorException 4xx 에러만 핸들링 할 수 있지 않을까요?

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +            PaymentErrorMessageResponse response = e.getResponseBodyAs(PaymentErrorMessageResponse.class);
의견) getResponseBodyAs는 nullable을 반환하는 것 같으니, 핸들링 로직을 작성해두면 좋을것 같아요.

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +            throw new RoomescapeException(response.message());
질문) 모든 예외를 메세지에 담아 유저에게 전가할 필요가 있을까요? [API 문서](https://docs.tosspayments.com/reference/error-codes)를 보고 발생할 수 있는 예외들을 확인하고 핸들링해두면 좋을 것 같아요.

2024-05-29 09:40 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +            restClient.post()
질문) API 응답이 비정상적으로 오래걸리면 어떻게 될까요?

2024-05-29 09:40 UTC, kimhodol commented on src/test/java/roomescape/controller/api/UserReservationControllerTest.java
> +    private PaymentService paymentService;
질문) Mock을 사용한 이유는 무엇인가요?

2024-05-29 09:40 UTC, kimhodol commented on src/test/java/roomescape/controller/api/UserReservationControllerTest.java
> +    private PaymentService paymentService;
의견) PaymentService도 Test API를 제공하니, 이를 이용해서 테스트를 작성해보면 어떨까요? 다른 코멘트에서 언급한 API 예외 처리를 여기서 TDD로 해봐도 좋겠네요!

2024-05-30 01:47 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +                .header("Authorization", authorizations)
이미 잘 정의된 상수가 있었군요! 😄

2024-05-30 01:56 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +        } catch (HttpClientErrorException e) {
### `retrieve()`
<img width="606" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/37261785/dc2bff9e-3a3d-4706-995b-1306108b5daa">

### `toBodilessEntity()`
<img width="624" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/37261785/3ea94d62-34bb-4750-803e-5e1ac4e1dc0b">

5xx 예외를 간과했네요...
문서를 잘 참고하여 발생할 수 있는 예외 처리를 적절하게 구성해보겠습니다!

2024-05-30 02:47 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/UserReservationController.java
> +        @AuthenticationPrincipal Member member) throws Exception {
맨 처음에 외부 api를 호출하는 코드에서 필요했던 부분인데요.
현재는 `paymentService.pay()`에서 적절하게 예외처리가 이루어지고 있기 때문에
필요없는 부분이네요!

불필요한 코드 삭제하겠습니다.

2024-05-30 04:31 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +    private static final String TOSS_PAYMENTS_URL = "https://api.tosspayments.com/v1/payments/confirm";
ConfigurationProperties 라는 것이 있군요! 적용해보겠습니다! 😄

2024-05-30 06:46 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +            PaymentErrorMessageResponse response = e.getResponseBodyAs(PaymentErrorMessageResponse.class);
<img width="812" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/37261785/9d24192b-023b-48f3-b8f8-a19267b92f9f">

`@Nullable`은 return value가 null일 수도 있음을 명시해주는 역할을 하는군요!
IDE warning이 뜨고 있었음에도, null이 들어오는 경우가 잘 상상되지 않았어서 null 처리를 잘 안 했었던 것 같아요.
문서를 잘 읽으면서 사용해야겠네요!

2024-05-30 12:37 UTC, takoyakimchi commented on src/test/java/roomescape/controller/api/UserReservationControllerTest.java
> +    private PaymentService paymentService;
외부 API의 경우 값을 제어할 수 없는 부분이라, 어쩔 수 없이 MockBean을 사용하였습니다!

2024-05-30 12:41 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +            restClient.post()
스프링 애플리케이션은 멀티스레드 기반으로 동작하는데
하나의 클라이언트에서 api 응답이 오래 걸리면 다른 클라이언트에서 해당 메서드를 호출했을 때
무한정 대기가 걸리는 사태가 벌어질 수 있습니다

2024-05-30 12:45 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +            restClient.post()
connection timeout -> 클라이언트가 서버에 접근하려고 하는데 연결이 안 되고 너무 오래 걸리면 연결을 끊음
read timeout -> 서버에 접근하기는 했는데 서버 측에서 로직 처리가 너무 오래 걸리면 연결을 끊음

해당 두 가지 타임아웃 적용하면 해결이 되겠네요!

2024-05-30 13:12 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +    private static final String TOSS_PAYMENTS_URL = "https://api.tosspayments.com/v1/payments/confirm";
환경변수의 관심사가 `@Value`를 사용하면 여러 군데로 분산되는 문제가 있었는데
`@ConfigurationProperties`를 쓰면 하나의 클래스에서만 관리하니 유지보수에 훨씬 용이하겠네요 !!

2024-06-01 10:33 UTC, takoyakimchi commented on src/test/java/roomescape/controller/api/UserReservationControllerTest.java
> +    private PaymentService paymentService;
`@RestClientTest`를 사용해서 테스트 코드 작성하였습니다!

2024-06-01 10:35 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +            throw new RoomescapeException(response.message());
`인증되지 않은 시크릿 키 혹은 클라이언트 키 입니다.`
`잘못된 요청입니다. ':' 를 포함해 인코딩해주세요.`

이러한 메시지는 사용자에게 표시되면 보안에 치명적일 것 같습니다.

하지만

`카드 정보를 다시 확인해주세요. (유효기간)`
`카드번호를 다시 확인해주세요.`

이러한 메시지들은 사용자에게 보여주는 편이 더 사용자 친화적이겠네요!

조금 더 처리가 필요할 것 같네요.

2024-06-01 10:45 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +    private final RestClient restClient;
RestClient와 RestTemplate을 각각 사용해보았는데요.
결론적으로 현재는 RestTemplate을 사용하도록 변경했어요.

처음에는 RestClient를 사용했었는데, 그 이유는 최근에 나온 인터페이스이기도 하고, RestTemplate이 deprecate 된다는 이야기가 있어서였어요. 또한 메서드 체이닝으로 여러 가지 설정값을 넣어줄 수 있다는 점에서 매력을 느꼈어요.

그런데 RestClient는 타임아웃을 설정하는 코드가 꽤나 길더라구요.
```java
public RestClient build() {
    return RestClient.builder()
        .requestFactory(timeoutFactory())
    // ...
}

private ClientHttpRequestFactory timeoutFactory() {
    SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
    factory.setConnectTimeout(CONNECT_TIMEOUT_DURATION);
    factory.setReadTimeout(READ_TIMEOUT_DURATION);
    return factory;
}
```

반면 RestTemplate은 RestTemplateBuilder에서 타임아웃 설정 메서드를 제공하고 있더라구요.
```java
builder
  .setConnectTimeout(CONNECT_TIMEOUT_DURATION)
  .setReadTimeout(READ_TIMEOUT_DURATION)
  .build();
```

이 밖에도 `@RestClientTest`로 테스트할 수 있다는 점, `RestTemplateBuilder`가 autowire 된다는 점,
deprecate된다는 명세가 현재는 삭제된 점 등의 이유로 현재는 RestTemplate으로 갈아타게 되었습니다 !

2024-06-01 10:48 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +            restClient.post()
<img width="830" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/37261785/79a801c8-13c9-4700-992f-55578a77cdab">

토스페이먼츠에서는 Read Timeout을 30~60초로 권장하고 있군요.

2024-06-01 16:28 UTC, takoyakimchi commented
안녕하세요 호돌! 리뷰 남겨주신 내용 반영해 보았습니다.
또한 리뷰 반영하는 과정에서 RestClient를 RestTemplate으로 변경하게 되었습니다.
Mock을 사용하는 테스트는 그대로 유지하였고, PaymentServiceTest에서 mock 서버를 사용하는 테스트를 추가하였습니다!

다만 해결이 잘 안 되는 부분이 하나 있었어서 도움 받고자 질문 따로 남기겠습니다...

잘 부탁드립니다 🙇‍♂️🙇‍♂️

2024-06-01 16:35 UTC, takoyakimchi commented on src/main/java/roomescape/service/TossPaymentService.java
> +            throw new RoomescapeException(response.message());
(질문)
저번에 구현했던 대로, 토스페이먼츠 측에서 응답받는 정보가 예외 메시지로 그대로 들어가도록 하고 싶었는데요.
어떤 이유에서인지 `response`가 계속 null이 되네요.

예약이 잘 진행되는 걸 보면 [요청 명세](https://docs.tosspayments.com/reference#%EA%B2%B0%EC%A0%9C-%EC%8A%B9%EC%9D%B8)를 맞추지 않은 건 아닌 것 같고,
[에러 객체 명세](https://docs.tosspayments.com/reference/using-api/req-res#%EC%97%90%EB%9F%AC-%EA%B0%9D%EC%B2%B4) 또한 응답 dto에서 맞추어 주었습니다.

바디 자체가 null로 들어오는데, 해결 방법에 대한 힌트를 얻을 수 있을까요?

2024-06-02 14:37 UTC, kimhodol requested changes
안녕하세요 트레 :)

피드백 잘 반영해주셨네요.

코멘트 확인 부탁드립니다!

2024-06-02 14:37 UTC, kimhodol commented on src/main/java/roomescape/service/TossPaymentService.java
> +            throw new RoomescapeException(response.message());
음.. 제가 테스트를 짜봤을 때는 UNAUTHORIZED_KEY 예외를 제외하고는 모두 응답 DTO대로 오고 있는 것 같은데 한번 학습 테스트(?) 같은 걸 짜볼까요? 진행이 어려우시면 말씀주세요~ 참고로 401 에러가 날때는 body가 null인 것 같은데 디버깅해보면서 확인해보면 좋을 것 같아요.

2024-06-02 14:37 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +    private final RestClient restClient;
아하, 변경을 의도하고 말씀드리는 것은 아니었긴했는데 ㅋㅋ 둘 다 공부해보면 좋죠.

그런데 RestTemplate 문서에 보면

> NOTE: As of 6.1, RestClient offers a more modern API for synchronous HTTP access. For asynchronous and streaming scenarios, consider the reactive org. springframework. web. reactive. function. client. WebClient.
> 
> RestTemplate and RestClient share the same infrastructure (i. e. request factories, request interceptors and initializers, message converters, etc.), so any improvements made therein are shared as well. However, RestClient is the focus for new higher-level features.

라고 되어있긴해서, 공식적으로는 RestClient 사용을 권장하는 것 같긴해요.

2024-06-02 14:37 UTC, kimhodol commented on src/main/java/roomescape/service/PaymentService.java
> +            restClient.post()
잘 적용해주셨네요. Connection TImeout은 사실 값은 저도 한 1초로 설정했던 것 같은데요, 굳이 굳이 따진다면 Round Trip Time * 3 정도로 하면 적절할 것이라는 생각은 들어요. 근데 그건 과한 것 같고.. 1초나 3초면 적당할 것 같아요.

2024-06-02 14:37 UTC, kimhodol commented on src/main/java/roomescape/service/config/TossPaymentConfigProperties.java
> +        this.testSecretKey = testSecretKey + ":";
질문) ":"는 왜 따로 넣어주나요?

2024-06-03 05:14 UTC, takoyakimchi commented on src/main/java/roomescape/service/PaymentService.java
> +    private final RestClient restClient;
앗 저도 그렇게 받아들이지는 않았었는데
테스트코드 작성하는 과정에서 RestTemplate이 더 편리했었습니다!!

2024-06-03 05:22 UTC, takoyakimchi commented on src/main/java/roomescape/service/config/TossPaymentConfigProperties.java
> +        this.testSecretKey = testSecretKey + ":";
[토스페이먼츠 문서](https://docs.tosspayments.com/reference/using-api/authorization#%EC%8B%9C%ED%81%AC%EB%A6%BF-%ED%82%A4%EB%A1%9C-%EC%9D%B8%EC%A6%9D%ED%95%98%EA%B8%B0)에서 시크릿 키 맨 마지막에 `:`를 붙이도록 하고 있는데요. yml 파일에서는 속성의 맨 끝에 `:`를 붙이지 못하도록 되어 있어서, 생성자에서 따로 넣어주고 있습니다.

2024-06-03 06:30 UTC, takoyakimchi commented on src/main/java/roomescape/service/TossPaymentService.java
> +            throw new RoomescapeException(response.message());
앗 그러네요 잘 받아오네요!!
body가 null인 경우만 디폴트 메시지를 던져주는 방식으로 일단은 처리해 보겠습니다.

2024-06-03 12:15 UTC, takoyakimchi commented on src/main/java/roomescape/service/config/TossPaymentConfigProperties.java
> +        this.testSecretKey = testSecretKey + ":";
yml에서도 따옴표 `""` 로 감싸면 `:`을 붙일 수 있군요. yml에서 직접 붙여보겠습니다!

2024-06-03 13:41 UTC, kimhodol approved these changes
안녕하세요 트레 :)

이쯤에서 슬슬 마무리해도 될 것 같네요.

코멘트 확인 부탁드립니다! 다음 단계에서 만나요~

2024-06-03 13:41 UTC, kimhodol commented on src/main/java/roomescape/controller/ControllerAdvice.java
> +        return ResponseEntity.internalServerError().body(response);
의견) 에러를 나누려고 한 의도는 알겠어요. 그런데 개인적으로는 일부러 500 에러를 반환하지는 않는데요, 모니터링 툴에서 500 에러들을 필터링할 때 가지는 기대는 "500 에러 = 서버 프로그래머가 미처 예외처리하지 못한 무언가"라고 생각하기 때문이예요.

2024-06-03 13:41 UTC, kimhodol commented on src/main/java/roomescape/service/util/TossPaymentErrorCodeUtils.java
> +    }
의견) enum으로 관리해도 괜찮을 것 같은 생김새네요! 굳이 String Set을 쓴 이유가 있나요?

2024-06-03 13:41 UTC, kimhodol commented on src/test/java/roomescape/controller/api/UserReservationControllerTest.java
> +    private PaymentService paymentService;
Mock이 아닌 Fake, Stub, Spy 등의 대안도 있을텐데, 어떤 장단점이 있는지랑 어떤 용도로 사용해보는지 공부해보면 좋을 것 같아요.

2024-06-03 13:41 UTC, kimhodol commented on src/main/java/roomescape/service/util/TossPaymentErrorCodeUtils.java
> +    }
(선택사항) 그리고 이런 모든 경우들을 Parameterized Test로 실제 API를 호출하는 테스트를 해보는 것도 괜찮을 것 같네요!

2024-06-03 13:41 UTC, kimhodol commented on src/main/java/roomescape/service/TossPaymentService.java
> +            TossPaymentResponseDto responseDto = restTemplate.postForEntity(
질문) 이 정상 응답결과값 Body는 따로 저장하거나 처리하고 있진 않은거죠?

2024-06-03 13:41 UTC, merged

2024-06-08 19:31 UTC, takoyakimchi commented on src/main/java/roomescape/service/TossPaymentService.java
> +            TossPaymentResponseDto responseDto = restTemplate.postForEntity(
말씀하신 바가 맞습니다!
다음 미션에서 필요할 것 같아 일단은 이렇게 코드를 작성했습니다.