[ 2 - 4단계 방탈출 결제 / 배포 ] 무빈(김현중) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #111
Opened 2024-06-08 16:31 UTC by hjk0761

안녕하세요 수달!

이전에 말씀드렸듯이, 1단계에서 결제가 추가되면서 수반되는 질문들을 이번 단계에서 해결하느라 시간이 많이 소모된 것 같습니다.

특히 필요 이상이라는 생각이 조금 들지만, 결제 대기 상태에서 결제하는 부분을 위해 프론트엔드 코드를 수정한 부분이 잘 모르는 부분이어서 오래 걸렸습니다.
프론트엔드의 코드를 이해하는 것 또한 중요하다고 생각했기에 스스로의 힘으로 해보려다보니 필요치않게 시간을 많이 쓰게 되어 아쉬웠습니다...

이번 미션은 2단계 예약 페이지 변경, 3단계 배포, 4단계 문서화로 이루어져 있습니다!
3단계 배포는 지금 제공받은 서버의 문제로 배포가 안되는 상황이라 문제가 해결되는 대로 바로 배포한 이후에 접속할 수 있도록 하겠습니다!
4단계 문서화와 관련해선, swagger 3.0 을 사용했기 때문에 서버 실행 이후에 `localhost:8080/swagger-ui/index.html`로 접속하면 볼 수 있습니다!

문서화와 관련해서, 처음 해보는 작업이어서 직접 모든 API 를 정리해야 하는지, 외부 라이브러리를 사용해도 되는지 고민이 깊었습니다.
직접 정리하는 것의 장점은 프로그램의 흐름을 직접 정리할 수 있고, 외부 라이브러리에 의해 잘못 표기될 걱정을 하지 않아도 된다는 것입니다.
하지만 단점으로는 수정 시에 유지보수에 대한 비용이 크고, 휴먼 에러로 인한 오기를 확인하기 어렵다는 것입니다.
이에 비해 외부 라이브러리를 쓰면 편하게 유지보수 할 수 있고, 변경에 유연한 문서를 만들 수 있다는 장점이 있습니다.
또한 외부 라이브러리를 사용하는 경험 또한 학습에 도움이 될 것 이라는 생각 또한 들어 외부 라이브러리를 사용하기로 결정했고, 크게 swagger와 rest docs 를 고민하게 되었습니다.
전자가 코드 세팅이 더 직관적이고, 왼성된 UI와 API 테스트를 제공한다는 점에서 장점이 더 크다고 생각해 이를 선택하게 되었습니다!

처음 보는 개념과 도구를 사용하게 되어 많이 부족하겠지만,
이번에도 리뷰 잘 부탁드리겠습니다!

2024-06-09 07:47 UTC, her0807 requested changes
안녕하세요 무빈!

리뷰어 수달입니다. 🙂
에고고, 화면부분 때문에 고생좀 하셨군요! 
저도 요즘 리엑트를 보고 있는데 무빈과 같은 기분을 종종 느낍니다! ㅠㅠ ㅎㅎ

전반적으로 구현은 잘 해주셨는데 스웨거 적용과 관련해서 조금더 활용해보면 좋을 것 같아서
코멘트 남겨두었어요~ 확인부탁드립니다!

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/controller/MemberController.java
> +        Member member = memberService.getMemberByEmailAndPassword(request);
적절한 메서드 명 👍🏻

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/model/PaymentInfo.java
> +    private String orderId;
`orderId `(주문ID)  방탈출에 주문이라는 개념이 적절한가 조금 고민해보면 좋을 것 같아요 😵‍💫

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
>          return ResponseEntity.noContent().build();
현재 예약 취소와 예약 삭제 행위가 모두 실행되거나 모두 취소 됨이 보장되고 있을까요?  🙂

`Transactional` 로 원자성을 보장하기 위해서 어떻게 하면 좋을지 한번 고민해보아요.

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/service/PaymentService.java
> +        paymentInfoRepository.deleteById(paymentInfo.getId());
예외처리로 인해서 가독성이 조금 떨어지는 것 같아요. 

각각 목적에 맞게 메서드로 추출해서 핸들링해볼까요? 😎

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/model/Reservation.java
> +        if (status == ReservationStatus.RESERVED) {
isReserved() 와 같은 메서드를 통해서 상태를 파악할 수 있도록 메세지를 날려볼까요?

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/model/Reservation.java
> +        this(null, date, time, theme, member, ReservationStatus.PAYMENT_WAITING);
다른 개발자가 시그니처만 보고
ReservationStatus 를 생략한 생성자로 객체를 생성할 때
예약의 기본 상태가  ReservationStatus.PAYMENT_WAITING  라는 사실을 파악할 수 있을까요?
이럴 때는 정적 팩터리 메서드로 메서드명에 해당 상태를 나타내면 조금 더 원활한 소통이 가능할 것 같습니다 🖐🏻

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/controller/request/ReservationWithPaymentRequest.java
> +        @Positive(message = "[ERROR] reservationId의 값이 1보다 작을 수 없습니다.")
Positive를 사용해서 음수가 들어오지 않도록 처리해주었군요? 👍🏻
reqeust 에서 기본적인 예외 검증과 행위 유도가 가능한 적절한 메세지 아주 잘하셨습니다.

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/config/SwaggerConfiguration.java
> +@Configuration
🖐🏻 스웨거를 적용하는 것 뿐만 아니라 활용해볼까요?
스웨거는 다른 개발자에게 해당 API 사용하는 방법을 설명해주는 용도로 쓰이는데요~
기본으로 적용되는 것 만으로는 스웨거가 문서의 용도로 쓰이기 아쉬운 부분이 많은 것 같아요. 

1. `@Tag ` 을 활용해서 도메인 별 API 나눠주기
어떤 도메인에 쓰이는 API 인지 명확하게 구분해주고, 도메인에 대한 설명을 추가함으로써 사용하는 개발자에게 
가이드를 제공해줄 수 있게 되어요.

2. Request 에 `@description`, `@example` 를 활용해서 데이터의 설명과 더불어서 어떤 형태로 데이터가 들어오면 좋은지를 
구체적으로 명시해보기.

요청에 필요한 값들이 어떤 형태로 들어와야하는지 구체적으로 가이드 해줄 수 있습니다. 

(참고사항) controller 에 적용할 수도 있는데 controller 에 사용하게되면 가독성이 떨어질 수 있어 
보통 requestDto 로 매핑해서 해당 오브젝트 내에서 선언해두곤 하는 것 같습니다. 


Parameter(description = "페이지 번호", example = "1")
<img width="672" alt="스크린샷 2024-06-06 오후 8 30 16" src="https://github.com/woowacourse/spring-roomescape-payment/assets/26570275/c80536ee-3bd1-4a79-b46c-45135799ae3c">

2024-06-09 07:47 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
>      @Transactional
어떤 Service 는 최상위에  `@Transactional` 을 해주고, 
어떤 Service 는 개별 메서드에  `@Transactional` 을 해주고 있네요~

통일성 있게 변경하면 좋을 것 같아요. 처음 팀플할 때 규칙으로 많이 정하곤 하는 주제인데요. 

저는 주로 read 기능을 하는 서비스와 write 기능을 담당하는 서비스를 나눠서 최상위에 각각 `@Transactional read only` 와 `@Transactional` 를 달아주곤 합니다.

장점은  명확한 행위 구분과 행위 보장이 된다는 것이고, 단점은 관리 포인트가 늘어난다는 점인데, `Transactional` 을 개발자의 실수로 누락하거나 잘못 적용하는 경우를 방지해준다는 점이 매력적이라 해당 방법을 선호하고 있어요. 🙂
무빈만의 규칙을 만들어보면 좋을 것 같아요!

2024-06-09 07:47 UTC, her0807 commented on src/main/resources/static/js/reservation-mine.js
> +    // @docs https://docs.tosspayments.com/reference/widget-sdk#renderpaymentmethods선택자-결제-금액-옵션
주석은 주로 메서드 위에 다는 것 같아요!
한줄 이상이면 아래와 같은 형태로 주석을 주로 다는 것 같습니다!

```java
/**
 * ------  결제위젯 초기화 ------
 * @docs https://docs.tosspayments.com/reference/widget-sdk#sdk-설치-및-초기화
 * @docs https://docs.tosspayments.com/reference/widget-sdk#renderpaymentmethods선택자-결제-금액-옵션
 */

```

2024-06-09 10:29 UTC, hjk0761 commented on src/main/java/roomescape/controller/ReservationController.java
>          return ResponseEntity.noContent().build();
> 현재 예약 취소와 예약 삭제 행위

혹시 위 말이 `결제 취소와 예약 삭제` 를 말씀하신 것이라면,
서로 다른 서비스의 메서드를 어떻게 한 트랜젝션으로 묶어야 할 지 질문 드리고 싶습니다!

`transaction`, `propagation`, `transaction between services` 등의 키워드로 검색해보니,
microservice 에서의 transaction 관련한 지식밖에 나오질 않았습니다...
또한 controller 에 transaction 을 거는 것 또한 해당 API로의 행동 자체가 락이 걸리게 되어 성능적인 측면에서 좋은 선택은 아니라고 생각이 듭니다.
두 서비스의 기능을 공유하는 새로운 서비스 계층 또한 생각해 보았지만, 외부 API 를 사용하는 결제 취소 기능이 다른 기능과 엮어 한 트랜젝션으로 관리된다면 이 또한 성능적으로 좋은 선택이 아닌 것 같습니다..
어떤 방식으로 이에 대한 접근을 해야 할 지 감이 잡히지 않는데, 혹시 키워드를 말씀해 주실 수 있으신가요?

2024-06-09 10:56 UTC, hjk0761 commented on src/main/java/roomescape/model/Reservation.java
> +        this(null, date, time, theme, member, ReservationStatus.PAYMENT_WAITING);
정적 팩터리 메서드를 잊고 있었네요!!
의미 전달을 위한 좋은 방법 짚어주셔서 감사합니다 ㅎㅎ
바로 수정해 보았습니다!

2024-06-09 10:58 UTC, hjk0761 commented on src/main/java/roomescape/model/Reservation.java
> +        if (status == ReservationStatus.RESERVED) {
이 부분도 수정해 보았습니다!
예약 상태 객체가 상태 파악에 대한 주체가 되는 게 더 적절하겠군요 ㅎㅎ

2024-06-09 11:21 UTC, hjk0761 commented on src/main/java/roomescape/service/PaymentService.java
> +        paymentInfoRepository.deleteById(paymentInfo.getId());
가독성은 올라간 것 같지만, 이전에 메서드 체이닝을 통해 사용하던 방법을 사용하지 못하는 것이 조금 아쉬운 부분인 것 같습니다.
그래도 어느 예외 처리인지 이름으로 알 수 있기에 각 예외상황 별로 메서드로 분리해 보았습니다!

2024-06-09 11:44 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
>      @Transactional
지금 구조는, 트랜젝션이 필요한 서비스 전부의 최상단에서 어노테이션을 적용한 이후에 메서드 별로 필요한 옵션에 따라 재적용해주었습니다.
[이전 리뷰](https://github.com/woowacourse/spring-roomescape-payment/pull/61#discussion_r1623433975) 를 통해, 해당 서비스에서 과반의 옵션을 최상단에 적용하고, 과반이 되지 않는 옵션을 메서드 별로 두도록 기준을 잡았습니다.

수달 말씀을 듣고 나니, 지금도 서비스 별로 과반에 따라 최상단에 달린 어노테이션이 다르다는 것을 알 수 있었습니다.
이는 서비스 별로 통일된 기준이 되지 못해 실수할 가능성을 높히는 것 같습니다!

수달께서 이런 방법을 선호하는 이유를 말씀해주셔서 감사해요!
저도 실수 방지라는 이유의 중요도가 더 크다고 생각해 분리해 보도록 하겠습니다!

2024-06-09 12:13 UTC, hjk0761 commented on src/main/resources/static/js/reservation-mine.js
> +    // @docs https://docs.tosspayments.com/reference/widget-sdk#renderpaymentmethods선택자-결제-금액-옵션
알려주셔서 감사합니다!!

다음에 주석 사용할 때에 유념해서 사용하겠습니다 ㅎㅎ
지금 주석은 만들면서 참고하려고 남겨둔 부분이라 삭제했습니다!

2024-06-11 06:36 UTC, hjk0761 commented on src/main/java/roomescape/config/SwaggerConfiguration.java
> +@Configuration
이 프로그램을 만든 입장에서 보았을 때 충분한 정보라고 생각했는데, 다른 개발자가 구조나 의도를 코드만 보고 파악하기 어려울 수도 있겠다는 생각이 들었습니다!
말씀주신 방향대로 API 분류와 Schema 를 통한 예시 요청 및 응답을 설명할 수 있도록 바꿔보았습니다!
훨씬 보기 편한 문서가 된 것 같아 감사합니다 ㅎㅎ

2024-06-11 06:40 UTC, hjk0761 commented on src/main/java/roomescape/model/PaymentInfo.java
> +    private String orderId;
예약이라는 행위에 대한 결제이므로 `reservationId` 가 적절한지 고민해 보았지만,
기존에 존재하는 도메인인 reservation 의 id 와 의미가 중복된다고 생각해 적용하지 않았습니다.

결제에 대한 identity 한 값이므로 이를 `paymentId` 로 표현하는 건 괜찮을 것 같다는 생각이 들어 수정해 보았습니다!
다만, toss payment API 명세 상 orderId 를 요구하기 때문에 PaymentRequest Dto 의 변수명은 수정하지 않았습니다.

2024-06-11 06:53 UTC, hjk0761 commented
이제 배포 서버가 정상 작동하여 배포도 최신 상태로 해보았습니다!
이제 3.38.98.245:8080 으로 접속하시면 배포된 서버 또한 보실 수 있습니다!!

2024-06-11 08:07 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
>          return ResponseEntity.noContent().build();
음 서로 다른 서비스에 있는 것이 문제일 수 있지 않을까요?🤔

Controller 에서는 비지니스 로직이 드러나지 않고 비지니스 로직을 수행하는 model( service) 에게 요청을 위임하는 역할만을 가지는게 적절하다고 생각합니다.  

JPA 에서도 OSIV 라고 하여 영속성 컨텍스트의 생명 주기를 Controller 이전까지 열어두는 것, 즉 서비스 레이어까지만 사용하는 것을 권장합니다. 

제가 생각하기에는 
`결제 취소와 예약 삭제` 가 하나의 서비스 내에 메서드에서 실행되고 그 메서드에 트랜잭션을 통해 원자성이 보장되어야한다고 생각합니다. 

`결제 취소`를 하기 위해 외부 API 호출시 응답값을 통해 실행 여부를 파악할 수 있기 때문에 에러가 반환되면 예외를 던져` 예약 삭제`도 롤백되는 것을 보장했으면 좋겠다는 의미였습니다!

2024-06-11 08:09 UTC, her0807 approved these changes
안녕하세요 무빈!

리뷰어 수달입니다. 

배포해주신 내역 잘 확인했습니다 ㅎㅎ 고생 많으셨어요. 
요구사항 모두 만족된 것 같아 머지하겠습니다.  👍🏻

(간단히 코멘트 남겨 두었어요. 확인 부탁드립니다!)

2024-06-11 08:09 UTC, merged