[1단계 방탈출 결제 / 배포] 로빈(임수빈) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #12
Opened 2024-05-29 06:53 UTC by robinjoon

안녕하세요 안돌! 리뷰 잘 부탁드립니다.

슬랙 채널에서 공유드린 것 처럼 Spring 을 이용한 웹 개발 및 배포 경험이 몇번 있습니다. 외부 API 호출하는 것 역시 해본적은 있지만, 예외를 잘 핸들링하는 시도는 이번에 처음 해봤습니다.

## 집중한 포인트

**기존 코드를 최대한 덜 수정하면서 새로운 기능을 추가하는 것을 목표**로 했습니다. 이런 이유로 기존 도메인에 필드를 추가한다던지 하는 방법으로 구현할 수 있더라도 새로운 도메인을 추가하는 방향으로 코드를 작성했습니다.

## 궁금한 부분

코드에 직접 코멘트 남겨두겠습니다!

2024-05-29 15:00 UTC, andole98 requested changes
상당히 잘 구현해 주셨네요 :+1:

새로운 개념인 Payment를 잘 추가해 주신것 같아요.

RestClient의 활용도 학습해보신것 같네요. 에러핸들러를 잘 사용하신것 같아요.

코멘트 남겼으니 살펴봐주세요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationController.java
> +        reservationRequest = new ReservationRequest(reservationRequest.date(), memberId, reservationRequest.timeId(),
여긴 큰 상관 없겠지만,

파라미터를 바꾸는 구현은 위험합니다. 클라이언트로부터 받은 request와 서비스에 넘겨야 하는 request가 다르다면, 타입을 다르게 하는게 좋을것 같아요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationController.java
> +        response.addAll(waitings);
이것도 사실상 controller가 로직을 알고 있다고 봐야 할것 같아요. 기존 reservationService / waitingService에 변경을 만들기 싫다면, 이부분을 담당할 MyReservationService 같은게 있으면 될것 같네요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/BaseEntity.java
> +    @PrePersist
지난 미션 주제이지만 jpa audit을 알아봐도 좋을것 같네요

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +    public int compareTo(Reservation other) {
Comparable 구현! 좋네요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Member member;
Reservation에도 member가 있지 않았나요? 예약자와 다른 사람이 결제할수도 있는건가요?

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentApiResponseErrorHandler.java
> +        ApproveApiError apiError = objectMapper.readValue(rawResponseBody, ApproveApiError.class);
이렇게 할수도 있겠네요
```suggestion
objectMapper.readValue(response.getBody(), ApproveApiError.class);
```

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentApiResponseErrorHandler.java
> +        ApproveApiError apiError = objectMapper.readValue(rawResponseBody, ApproveApiError.class);
더해서, ApiCallException으로 전달하기에는 조금 부족한것 같아요.

4xx에러인것과 5xx에러인것은, 에러 이후 어떻게 해야할지 플로우가 달라질것 같아요.

예를들어 잔액부족인 경우, 유저에게 적절한 조치후 재시도를 유도할 수 있지만
5xx에러인 경우, 유저가 재시도하면 더 복잡한 상황이 될수도 있으니까요. 결제가 두번 된다던지..

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +    private final RestClient restClient = RestClient.builder()
이걸 dependency inject 받으면 더 좋을것 같네요. 개별 테스트도 가능하구요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +    public Payment approve(PaymentApproveRequest paymentApproveRequest, Member member) {
이건 살짝 의문이 드네요. paymentClient가 payment도메인을 반환하는것 보다는, paymentResultDto 정도를 반환하고 디비처리 후 Payment가 되는건 어떤가요?

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +    public Payment approve(PaymentApproveRequest paymentApproveRequest, Member member) {
member 파라미터도 받을 필요 없을거고 api 인터페이스만 잘 적용해주니, Payment 변경에 대해서도 영향을 받지 않을것 같네요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +        ApproveApiResponse response = Optional.ofNullable(restClient.post()
Optional로 감싸는 이유는 무엇인가요? 리턴타입이 optional도 아니고, restClient의 결과도 optional하지 않은것 같은데요.

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +                        .onStatus(errorHandler)
에러핸들러를 잘 추가해 주신것 같아요 :+1:

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +                        .retrieve()
만약 결제하는데 1분 걸리면 어떻게 되나요?

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/exception/RoomescapeExceptionHandler.java
> +    @ExceptionHandler(ApiCallException.class)
apiCallException을 사용자까지 알아야 할까요?

정보은닉, encapsulation을 떠올려볼까요?

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/repository/JpaPaymentRepository.java
> +public class JpaPaymentRepository implements PaymentRepository {
요렇게 구현하는건 어떤 장점이 있어서 그런걸까요?

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/service/AvailableTimeService.java
> +@Transactional(readOnly = true)
이건 왜 필요한걸까요?

2024-05-29 15:00 UTC, andole98 commented on src/main/java/roomescape/service/PaymentService.java
> +        Payment payment = paymentClient.approve(paymentApproveRequest, paidMember);
트랜잭션 안에서 외부 api콜을 하면 어떻게 될까요? 만약 api가 10초 걸리면?

2024-05-29 15:00 UTC, andole98 commented on src/test/java/roomescape/fixture/MemberFixture.java
> +public class MemberFixture {
test fixture를 잘 활용했네요 :+1:

2024-05-29 15:00 UTC, andole98 commented on src/test/java/roomescape/infra/DBConnectionTest.java
> +public class DBConnectionTest {
이건 `@SpringBootTest` 가 붙는것 자체로 테스트할수 있을것 같네요.

나머지 스키마와 관련한건 jpa ddl 옵션으로도 대체할수 있겠고요.

2024-05-29 15:00 UTC, andole98 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +        PaymentClient paymentClient = new PaymentClient(new PaymentApiResponseErrorHandler(new ObjectMapper()));
스프링이 사용하는 ObjectMapper는 기본 ObjectMapper와 조금은 다릅니다.
타임 포맷이 달라지거나... 정의되지 않는 필드가 있거나 하면 문제가 될 수 있어요.

토스페이먼츠는 친절하네요 https://docs.tosspayments.com/reference/using-api/req-res#유의사항

2024-05-29 15:00 UTC, andole98 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    void approveFailWhenPaymentApiFail() {
이 테스트는 좋네요 :+1:

다만 성공하는 케이스도 검증해봤으면 좋았을것 같네요.

2024-05-29 15:02 UTC, andole98 commented
트랜잭션과 외부 api를 묶는것부터 질문을 드리고 싶네요.

사실, 현업에서도 이것 때문에 많은 문제가 발생하긴 해요. 다른 회사의 api를 사용하기도 하지만, 요즘 대부분의 회사들은 MSA 구조로 되어 있는 경우가 많아요. 멤버를 조회하려면 멤버 팀이 제공하는 api를 사용해야 한다든지...

외부 api는 네트워크를 이용해야 합니다. 네트워크와 local 코드 수행의 시간차이가 얼마나 나는지 아시나요??

트랜잭션이, 매~~~~~~우 느린 task와 묶인다면 어떤 문제가 있을까요??

2024-05-29 15:11 UTC, robinjoon commented on src/main/java/roomescape/domain/BaseEntity.java
> +    @PrePersist
지난 미션 리뷰어도 동일한 코멘트를 남겨주셨고, 학습했었습니다. 딱히 뚜렷한 장점이 있지 않아서 적용하지 않았습니다.

https://github.com/woowacourse/spring-roomescape-waiting/pull/101#discussion_r1610214739

2024-05-29 15:20 UTC, robinjoon commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +                        .retrieve()
> 만약 결제하는데 1분 걸리면 어떻게 되나요?

타임아웃을 고려해야겠군요. 토스 api 문서에 관련 내용이 나와있는지 확인해봐야겠네요!

2024-05-29 15:26 UTC, robinjoon commented on src/main/java/roomescape/repository/JpaPaymentRepository.java
> +public class JpaPaymentRepository implements PaymentRepository {
> 요렇게 구현하는건 어떤 장점이 있어서 그런걸까요?

기존의 레퍼지토리도 다 같은 형태로 되어있어서 그 구조를 따른 것 입니다. 

왜 기존 레퍼지토리가 지금과 같은 형태가 되었는지는 [이전 미션의 PR](https://github.com/woowacourse/spring-roomescape-waiting/pull/37) 과 [제 블로그 게시글](https://blog.robinjoon.xyz/2115d095-db8c-4401-b465-fd3026854c5c)에 잘 나와있어요!

2024-05-29 15:33 UTC, robinjoon commented on src/main/java/roomescape/service/AvailableTimeService.java
> +@Transactional(readOnly = true)
> 이건 왜 필요한걸까요?

readonly 옵션은 이 트랜잭션에서 읽기 작업만이 일어날 것이라는 힌트를 제공하는 역할을 합니다.

읽기 전용이므로 하이버네이트의 더티체킹이 동작할 이유가 없고, 따라서 객체의 스냅샷을 찍거나 쓰기지연저장소에 쿼리를 저장한다던지 할 필요도 없을 겁니다. 따라서 아주 약간의 성능 향상을 기대할 수 있습니다.

그런데, 사실 영속성 컨텍스트에서 많은 객체를 관리할 때나 큰 장점이지, 지금은 그다지 필요없을 것 같습니다. [이전 미션의 페어의 말에 따르면 readonly 옵션을 사용하더라도 저장이나 업데이트가 동작할 수 있다](https://github.com/woowacourse/spring-roomescape-waiting/pull/64#discussion_r1609469792)고 합니다. 그렇다면 이는 오히려 거짓말하는 양치기 소년처럼 개발자에게 받아들여질수도 있겠네요.

2024-05-29 15:36 UTC, robinjoon commented on src/main/java/roomescape/service/PaymentService.java
> +        Payment payment = paymentClient.approve(paymentApproveRequest, paidMember);
> 트랜잭션 안에서 외부 api콜을 하면 어떻게 될까요? 만약 api가 10초 걸리면?

음 트랜잭션이 완료되기까지 상당한 시간이 걸리고, 설정에 따라선 그 시간동안 데이터베이스에 락이 걸릴 수도 있을 것 같네요. 그렇다면 트랜잭션을 사용할 수 없는데, 데이터 정합성을 어떻게 챙겨야 할까요? 고민이네요.

2024-05-30 02:04 UTC, robinjoon commented on src/main/java/roomescape/controller/ReservationController.java
> +        reservationRequest = new ReservationRequest(reservationRequest.date(), memberId, reservationRequest.timeId(),
> 여긴 큰 상관 없겠지만,
> 
> 파라미터를 바꾸는 구현은 위험합니다. 클라이언트로부터 받은 request와 서비스에 넘겨야 하는 request가 다르다면, 타입을 다르게 하는게 좋을것 같아요.

**파라미터를 바꾸는 행위가 위험하다는 것이 어떤 의미인지 잘 모르겠습니다.** 만약 위 코드에서 파라미터의 메서드를 호출하여 상태를 바꾸는 행위라면 참조가 같기 때문에 위험하다는 것이 이해가 되지만, 현재는 깊은 복사가 이루어지고 있기 때문에 위험해보이지 않습니다.

타입을 다르게 할 경우의 장점 역시 있지만, 그렇게 되면 service 패키지 하위에 service 에서 사용하는 dto가 존재하는 것이 타당한 구조가 됩니다. **딱히 문제가 발생하지 않는 상황에서 구조만 복잡해지는 상황은 지양**해야 하지 않을까 라는 생각이 듭니다.

2024-05-30 02:06 UTC, robinjoon commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Member member;
> Reservation에도 member가 있지 않았나요? 예약자와 다른 사람이 결제할수도 있는건가요?

앗 그렇군요! 처음 설계할때는 단순하게 생각해서 필요할 것이라 생각했지만, 지금 구조에서는 필요하지 않겠네요

2024-05-30 03:30 UTC, robinjoon commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +        ApproveApiResponse response = Optional.ofNullable(restClient.post()
좀 더 찾아보니 안티패턴이라고 하네요. 개인적으로 더 읽기 좋아서 안티패턴이라는 주장에 동의하지 않으나, 제 기준에서도 if 를 이용한 코드가 크게 나쁘지는 않을 것 같아 Optional 은 제거하겠습니다.

2024-05-30 03:33 UTC, robinjoon commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +    public Payment approve(PaymentApproveRequest paymentApproveRequest, Member member) {
이 부분 설계는 조금 더 고민해보겠습니다. 다른 도메인들은 DTO 를 사용하지 않는 구조라서요. 만약 그렇다면 이 부분이 도메인으로 부르기 힘들지도 모르겠네요.

2024-05-31 17:02 UTC, robinjoon commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    void approveFailWhenPaymentApiFail() {
> 이 테스트는 좋네요 👍
> 
> 다만 성공하는 케이스도 검증해봤으면 좋았을것 같네요.

이전 미션들을 진행하면서 어떤 메서드가 성공했을 때, 부작용이 있는 경우가 아니라면 굳이 테스트하지 않았습니다. 하지만, 안돌의 코멘트대로, 외부 API 연동은 개발자가 컨트롤할 수 없는 부분인 만큼 성공했을 때의 처리도 테스트하는 것이 합당하다는 생각이 드네요!

2024-05-31 17:36 UTC, robinjoon commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +        PaymentClient paymentClient = new PaymentClient(new PaymentApiResponseErrorHandler(new ObjectMapper()));
> 스프링이 사용하는 ObjectMapper는 기본 ObjectMapper와 조금은 다릅니다. 타임 포맷이 달라지거나... 정의되지 않는 필드가 있거나 하면 문제가 될 수 있어요.
> 
> 토스페이먼츠는 친절하네요 [https://docs.tosspayments.com/reference/using-api/req-res#유의사항](https://docs.tosspayments.com/reference/using-api/req-res#%EC%9C%A0%EC%9D%98%EC%82%AC%ED%95%AD)

말씀해주신 문서에 나와있는 설정은 JSON에 알 수 없는 필드가 있더라도 오류가 발생하지 않도록 하는 설정입니다. 저는이런 상황에서 기본적으로 Spring Boot 에서는 아무 문제가 발생하지 않는 것으로 알고 있었습니다. 실제 실험 결과도 제가 아는대로 나왔습니다.

이후 몇가지 검색 과정에서 [스프링 팀의 깃허브 이슈](https://github.com/spring-projects/spring-framework/issues/16510)를 확인했습니다.

오래된 이슈라서 이후 변경이 있을 수도 있을 것이라 판단, 직접 코드에서 확인해 봤을 때도, 기본적으로 이 설정을 활성화 하고 있음을 확인했습니다.

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/45223837/496ac4a2-aa27-4676-91af-6cddacad48c3)

2024-05-31 18:00 UTC, robinjoon commented
안녕하세요! 안돌, 남겨주신 코멘트 확인 후 답변 및 반영했습니다. 주요 변경점은 다음과 같습니다.

1. 결제 API 예외 응답 방식 변경 : 남겨주신 코멘트를 통해 최종적으로 클라이언트에 전달되어야 할법한 오류들만 제대로 전달하고, 나머지는 포괄적인 표현으로 응답하도록 수정했습니다. 안내되어야 할 오류들 중 누락된 것이 있을 수도 있으나, 이는 결제 도메인에 특화된 사항이므로 이점 감안해서 리뷰해주시면 감사하겠습니다.
2. 결제 API 호출 로깅 추가 : 코치 솔라가 진행한 피드백 강의에서 외부 API 연동시 이를 로그로 남기는 것의 중요성에 공감해 로그를 남기도록 하였습니다.
3. 타임아웃 설정 : **connection timeout 과 read timeout 을 각각 3초**로 설정했습니다. 이런 설정을 한 이유는 국내에 있는 서버가 응답을 주기까지 6초를 넘긴다면 서버가 정상적인 상황이라고 판단되지 않고, 무엇보다 실제 서비스라면 "고객에게 6초넘게 기다리라고 요구"하는 것은 **서비스 타겟인 한국인 기준으로 너무 느리다**고 생각했습니다.

반면, [RestClient의 의존성 주입 관련한 코멘트](https://github.com/woowacourse/spring-roomescape-payment/pull/12#discussion_r1619003360)는 **다음과 같은 이유로 반영하지 않았습니다.**

1. `PaymentClient`에서 발생하는 예외 테스트는 이미 `PaymentApiResponseErrorHandler` 에서 검증이 되었다.
2. 연동하려는 외부 API 의 특성상 실제 원격 서버와의 통신 테스트가 불가능 하다. = 해당 부분을 테스트 더블로 검증해야 한다.

유효한 paymentKey 를 얻기 위해서는 QR 코드 스캔이 필요하기 때문에, 코드에서 성공하는 상황을 테스트 할 수 없습니다. 따라서, 이 부분은 요청이 성공했다는 가정 하에 PaymentService 가 정상 동작했는지 검증하는 방식의 테스트만 가능합니다. 이 상황에서 사용할 테스트 더블을 굳이 RestClient 의 테스트 더블을 만드는 방식을 사용할 필요가 없습니다. 

**"실제 PaymentService + PaymentClient 테스트 더블" 과 "실제 PaymentClient + RestClient 테스트 더블" 두 방식이 테스트 하는 내용이 완전히 동일하기 때문에, RestClient 를 의존 주입하여 테스트에서 이점을 얻는다고 볼 수 없습니다.**

2024-05-31 18:06 UTC, robinjoon commented
추가적으로 이번 단계에서 앞서 질문 드린 외부 "API 성공 이후 DB 저장 실패 시 처리하는 방법." 은 아직 때가 아니라는 생각이 들었습니다. 2단계 안내 내용을 보니, 애초에 데이터 저장이 2단계 요구사항이더군요 ^^;; 해당 부분은 코치 솔라가 진행한 피드백 강의에서 힌트를 얻은 것이 있어서, 스스로 좀 더 방법을 찾아보고자 합니다.

2024-06-01 02:32 UTC, andole98 commented on src/main/java/roomescape/domain/BaseEntity.java
> +    @PrePersist
💯 두 분 모두 훌륭하시네요

2024-06-01 02:45 UTC, andole98 commented on src/main/java/roomescape/service/AvailableTimeService.java
> +@Transactional(readOnly = true)
로빈이 이야기한 이유도 맞아요.

`AVailableTimeService`에서 사용하는 모든 쿼리들은, 이미 `@Transactional(readOnly = true)` 가 달려있어요(?? 어디에 ??)

그렇다면 서비스에서 `@Transactional(readOnly = true)` 는 그야말로 쓸모없는 코인거죠.

2024-06-01 02:46 UTC, andole98 commented on src/main/java/roomescape/service/PaymentService.java
> +        Payment payment = paymentClient.approve(paymentApproveRequest, paidMember);
그러니까 코치님들이 나중에 알아볼것을 권한게 아닐까요.... 🤔

2024-06-01 02:47 UTC, andole98 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +        PaymentClient paymentClient = new PaymentClient(new PaymentApiResponseErrorHandler(new ObjectMapper()));
제 말의 의미는, 
1. Spring이 사용하는 ObjectMapper는 문제가 안된다.
2. 1의 말 == 기본 ObjectMapper는 스프링이 사용하는거랑 다르다.
3. 여기서 쓴건 기본 ObjectMapper다 `new ObjectMapper();`

2024-06-01 04:15 UTC, andole98 approved these changes
상당히 잘 구현해 주셨네요~

이번 미션 뿐 아니라 코드 여러 군데에서 여러 고민과 배려가 느껴지네요.

의견교환도 이유와 함께 잘 남겨주셔서 리뷰가 재미있었어요.

코멘트 && 댓글 남겨두었으니 쓱 읽어보시고 다음 스텝 진행해주세요.

2024-06-01 04:15 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +            logger.error("payment API call ERROR!!!");
stack trace도 남길수 있으면 좋겠네요~

2024-06-01 04:15 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +                .withReadTimeout(Duration.ofSeconds(3));
connection / read timout을 설정하는 요령은 무엇이 있을까요?

커넥션에 시간이 오래걸릴까요 read에 시간이 오래걸릴까요?

2024-06-01 04:15 UTC, andole98 commented on src/main/java/roomescape/domain/payment/PaymentClient.java
> +    public ApproveApiResponse approve(PaymentApproveRequest approveRequest) {
`Payment`를 리턴하게 될때는 Payment, 시스템에서 정한 개념과 도메인이 외부 api의 맥락과 섞일수 있었던 것 같아요.

이렇게 되면 `PaymentClient`는 외부 api를 사용하는 역할에 충실해지겠네요.

2024-06-01 04:15 UTC, merged