[2 - 4 단계 방탈출 예약 결제 / 배포] 리니(이예린) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #122
Opened 2024-06-09 13:25 UTC by linirini

오랜만입니다, 피케이~!~!
벌써 레벨 2 마지막 pr이네요, 마지막까지 잘 부탁드립니다🙇‍♀️

이번 pr에 반영된 기능 변경 사항은 다음과 같습니다.
- 예약 취소 시 결제 취소
- 예약 취소 시 1순위 예약 대기자를 `예약대기`에서 `결제대기`로 변경
- `결제 대기`상태에서 결제 시 `예약`으로 변경

API 명세서와 ERD는 여기에 있습니다.

### 유저 정보
관리자
id: [admin@email.com](mailto:admin@email.com)
password: admin123

일반 유저
id: [pk@email.com](mailto:pk@email.com)
password: pkpk123

2024-06-10 19:25 UTC, pkeugine requested changes
안녕하세요 리니!
꽤나 많은 걸 해야하는 스텝이었는데,
정말로 readme 에 적어주신 부가기능도 전부 구현해주셨네요! 👍 👍 👍 
몇가지 리뷰 남겨보았으니 한 번 확인해주세요.
추가로 궁금한 점이나 리뷰가 이해되지 않는 부분이 있다면 언제든 DM 주시면 됩니다.
얼마남지 않은 level 2 마지막까지 파이팅해보죠!

2024-06-10 19:25 UTC, pkeugine commented on src/main/java/roomescape/service/reservation/ReservationCommonService.java
> +        return new ReservationConfirmedResponse(reservation);
검증부터 다 한 뒤에 `예약` 으로 바꾸는 과정 깔끔하게 잘 만들어주셨네요 👍

2024-06-10 19:25 UTC, pkeugine commented on src/main/java/roomescape/service/reservation/ReservationCommonService.java
>  public class ReservationCommonService {
service 클래스 범위로 `@Transactional` 어노테이션을 달아준다면,
모든 service 에 대해 동일한 옵션으로 달아주는건 어떨까요?
`readOnly` 옵션이 있을 때도 있고 없을 때도 있어서
어떤 메서드는 왜 `@Transactional` 이 달려있지 않을까 하는 생각이 들더라구요!

2024-06-10 19:25 UTC, pkeugine commented on src/main/java/roomescape/domain/dto/ReservationWithRank.java
> +    private final long rank;
다른 DTO 와는 다르게 이건 record 로 만들지 않은 이유가 있나요?

2024-06-10 19:25 UTC, pkeugine commented on src/test/java/roomescape/service/reservation/ReservationCommonServiceTest.java
> +    @DisplayName("결제 대기 상태의 예약을 결제 후, 예약 상태로 변경한다.")
테스트를 꼼꼼하게 잘 챙겨주셨네요! 💯 💯 💯 
그런데 같은 이름의 테스트가 몇 개 있는 것 같아요.
한 번 확인해보고 적절한 이름으로 바꿔볼까요?
<img width="385" alt="Screenshot 2024-06-11 at 3 58 56 AM" src="https://github.com/woowacourse/spring-roomescape-payment/assets/48251668/a3ae90b3-3f4c-43a0-9571-8e0bed2f1a72">

2024-06-10 19:25 UTC, pkeugine commented on README.md
> +# API 명세서
api 명세서에 작은 점이 있네요 😂 

<img width="545" alt="Screenshot 2024-06-11 at 4 01 21 AM" src="https://github.com/woowacourse/spring-roomescape-payment/assets/48251668/a256e3a4-9dc6-4563-b685-2f442f06ea13">

2024-06-10 19:25 UTC, pkeugine commented on README.md
> -## API 명세서
배포 깔끔하게 잘 진행해주셨네요 👏 👏 👏 
배포하면서 어려웠던 점이나 궁금한 점이 있었다면 그것도 남겨주셔도 좋습니다 :)

2024-06-11 10:03 UTC, linirini commented on README.md
> +# API 명세서
기존에 README.md를 API 명세서처럼 관리하고 있었어서 문서화하는데 가장 비용이 적게 들 방법을 선택했습니다.
RestDoc은 전에 사용해봤는데요, 처음부터 RestDoc으로 문서화를 하기로 약속하고 테스트를 관리하지 않으면 누락되는 케이스들에 대한 테스트를 추가하는 등의 비용 소모가 크다고 생각했어요. (지금 저에게 해당하는 상황이죠😅)
Swagger는 사용해보지 않았는데, 학습하고 적용하기에는 시간이 걸릴 것 같아서, 우선은 기존에 있던 api 명세서를 보충했습니다.

2024-06-11 18:44 UTC, pkeugine commented on src/main/java/roomescape/service/reservation/ReservationCommonService.java
>  public class ReservationCommonService {
클래스 단위로 로직을 파악할 때는 괜찮지만
메서드를 타고 들어가는 방식으로 작업하고 있을 때 조금씩 헷갈렸던 것 같아요 ㅋㅋㅋ

2024-06-11 18:46 UTC, pkeugine requested changes
안녕하세요 리니!
작업해주신 내용 확인했습니다 👍 
마지막으로 프로젝트에 반영하고 싶은 내용을 넣고
추가로 질문이 있다면 남겨주세요.
다음에 리뷰 요청해주시면 확인후 머지하도록 하겠습니다 :)

2024-06-12 04:40 UTC, linirini reviewed
swagger를 사용해보고는 싶은데, 버퍼 기간이라 방학 기간을 활용해서 공부가 부족했던 부분들도 같이 학습하고 붙여보려고 합니다.! 이만 머지 부탁드려도 될까요?😊
그동안 리뷰해주셔서 감사합니다🙇‍♀️

2024-06-12 21:11 UTC, pkeugine approved these changes
네, swagger 도입도 고민하시다니 대단하네요.
추가 학습하시는 것도 응원합니다.
지금까지 레벨 2 정말 고생 많으셨어요.
다음 레벨에서도 재밌는 경험하시길 바랍니다.
이만 머지할게요! 고생하셨어요 리니!

2024-06-12 21:11 UTC, merged