[ 2 - 4단계 방탈출 결제 / 배포 ] 페드로(류형욱) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #129
Opened 2024-06-09 18:32 UTC by hw0603

(추가예정)
https://github.com/swagger-api/swagger-editor/issues/1951#issuecomment-466399821

2024-06-10 14:21 UTC, choijy1705 requested changes
페드로 미션 잘 진행해주셨어요!
swagger가 controller 별로만 설명이 있고
api에 대한 설명은 없어서 
처음 문서를 보는 사람들은 쉽게 이해하기 어렵지 않을까? 라는 생각이 들었습니다
남긴 코멘트랑 여기에 대해서 한번 고민해보면 좋을것 같아요!

2024-06-10 14:21 UTC, choijy1705 commented on src/main/java/roomescape/controller/AdminReservationController.java
> +@Tag(name = "Reservation (Admin)", description = "관리자 예약 API 입니다.")
api별로의 설명은 필요 없을까요?

2024-06-10 14:21 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                    reservation.checkCancelAuthority(memberId);
checkCancelAuthority라는 메서드 명이 어떤 역할을 하는지 명확하게 전달되는 느낌은 아닌것 같아요
memberId를 파라미터로 넘겨서 memberId 가 같은지를 체크하기보다는
여기서 getMemberId를 하여서 memberId와 같은지를 체크하는게 더 명확하게 로직이 보이지 않을까 싶어요!

2024-06-10 14:21 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.cancel(reservation.getPayment());
delete한 reservation에 대해 cancel을 하는게 어색한것 같습니다
트랜잭션안에 묶여있어서 동작성에는 문제가 없을것 같지만
로직을 읽어내려가는 흐름에서는 조금 어색한것 같아요
결제를 취소하고 지우는게 바람직하지 않을까요?

2024-06-10 14:21 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationWaitingService.java
> +        paymentService.cancel(waiting.getPayment());
waiting도 결제를 받나요?

2024-06-11 02:30 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationWaitingService.java
> +        paymentService.cancel(waiting.getPayment());
예약 대기 등록 시 결제 여부를 말씀하시는걸까요? [직전 PR 본문](https://github.com/woowacourse/spring-roomescape-payment/pull/76#issue-2325056329)에서 잠깐 언급 드렸던 것과 같이, 예약 대기 시에도 항상 결제를 해야 대기를 등록할 수 있는 것으로 보고 진행했습니다!

2024-06-11 03:59 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.cancel(reservation.getPayment());
https://github.com/woowacourse/spring-roomescape-payment/pull/76#discussion_r1623674864 이곳에서 말씀해주셨던
> 외부 서비스에 요청하는 로직을 가장 마지막에 위치

로 볼 수 있지 않을까요? 예약 과정에서 예약을 먼저 저장하고 결제를 승인하는 것과 같은 맥락이라고 생각했어요.

만약 결제를 취소하고 DB에서 예약을 지우는 순서로 구현한다면, `DELETE` 중에 오류가 발생했을 때 `결제 취소`가 취소되지 않아 환불처리됐음에도 예약이 DB에 남아있는 경우가 생길 것 같은데 이 점은 어떻게 생각하시나요?

2024-06-11 04:28 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                    reservation.checkCancelAuthority(memberId);
서비스단으로 로직을 빼낸다면 검증이 어떻게 일어나는지는 명확하게 보인다는 장점이 있을 것 같아요. 다만 도메인에서 충분히 할 수 있는 일을 서비스에서 도메인의 값을 끄집어 내서 수행하고 있다는 느낌을 받았습니다.

이전 미션의 리뷰(https://github.com/woowacourse/spring-roomescape-waiting/pull/119#discussion_r1611750423)에서 비슷한 피드백을 받은 적이 있는데, 도메인이 할 수 있는 일이라면 도메인이 수행하게 해야 한다고 생각해서 현재와 같이 구현해 두었어요.

영이는 저러한 검증은 서비스의 역할이라고 보고 구현하시는 편인가요?
메서드 내에서 id 불일치 시 예외를 던지고 있으므로 단순히 check 보다는 validate로 보고, `validateCancelAuthority()`등의 메서드명을 사용한다면 좀 더 의미를 전달할 수 있을까요?

2024-06-11 04:29 UTC, hw0603 commented on src/main/java/roomescape/controller/AdminReservationController.java
> +@Tag(name = "Reservation (Admin)", description = "관리자 예약 API 입니다.")
오히려 설명을 추가한다면 각 API에 추가하는 것이 맞겠네요! 추가해 보겠습니다.

2024-06-11 04:43 UTC, hw0603 commented on src/main/java/roomescape/config/SwaggerConfig.java
> +                .version("0.0.1");
어떤 포인트에서 남겨주신 코멘트인지 확실히 이해하지는 못했습니다..🥲
버전 정보가 코드상에 하드코딩되어 있어 추후 업데이트를 놓칠 수 있다는 뜻으로 이해하고 `application.yml`에서 값을 받아오도록 변경하였는데, 리뷰 주신 부분이 이쪽이 맞을까요?

2024-06-11 05:29 UTC, hw0603 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private boolean deleted;
확실히 그게 더 의미있는 정보일 것 같아요. 반영했습니다!

2024-06-11 13:50 UTC, choijy1705 approved these changes
페드로 이번 미션은 여기서 머지하겠습니다
고생많으셨어요
질문 답변과 추가 코멘트 남겼는데 머지하더라도 한번 확인해보시면 좋을것 같아요!

2024-06-11 13:50 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                    reservation.checkCancelAuthority(memberId);
memberId를 parameter로 받아서 throw하는 역할은 도메인의 역할이 아니라고 생각했어요
도메인 로직이라면 도메인에 뭔가 값이변하거나 하는 능동적인 형태가 더 바람직하지 않을까라는 생각입니다

메서드명을 바꾸는것도 하나의 방법이 될 수 있을것 같습니다!

2024-06-11 13:50 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.cancel(reservation.getPayment());
넵 외부 서비스 요청을 마지막에 위치시키는게 가장 좋은 방법이라고 생각합니다
다만 지금은 삭제된 reservation을 사용하고 있고 delete 라는 메서드 내에서 reservation이 어떤 변경이 발생할지는 여기서 판단할 수 없을것 같습니다
```java
private void cancelReservation(Reservation reservation) {
    Theme theme = reservation.getTheme();
    Schedule schedule = reservation.getSchedule();
    long paymentId = reservation.getPayment().getId();
    boolean isPaid = reservation.isPaid();

    reservationRepository.delete(reservation);
    reservationWaitingRepository.findTopByThemeAndScheduleOrderByCreatedAt(theme, schedule)
            .ifPresent(this::convertFirstPriorityWaitingToReservation);

    if (isPaid) {
        paymentService.cancel(reservation.getPayment());
    }
}
```
안전한 사용을 위해서는 이런식으로 처리하는게 바람직할것 같아요

2024-06-11 13:50 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationWaitingService.java
> +        }
여기도 삭제된 객체를 가지고
뭔가 로직 처리를 하는것은 좋은 방법은 아닌것 같습니다
실제로는 DB에서 사라지는게 아니라고 하더라도요!

로직이 복잡하거나 도메인이 복잡해지면 알 수 없는 오류를 낼 가능성이 많을것 같아요!

2024-06-11 13:50 UTC, merged