[ 2 - 4단계 방탈출 결제 / 배포 ] 위브(김기범) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #131
Opened 2024-06-10 00:16 UTC by jimi567

.

2024-06-11 02:36 UTC, jamie9504 requested changes
안녕하세요, 위브 😄 리뷰어 제이미입니다.

깔끔하게 잘 구현해주셨네요 👏 👏 
간단한 코멘트들만 남겨두었어요!

오늘도 좋은 하루 보내세요!

2024-06-11 02:36 UTC, jamie9504 commented on src/main/java/roomescape/application/payment/PaymentService.java
> +                request.orderId(), reservationId, request.paymentKey(), request.amount()
> 결제 정보의 경우, 토스에서 저장하길 권장하는 paymentKey, OrderId를 포함하여, 결제 금액과, 해당 결제 정보가 어떤 예약에 대한 결제 정보인지 알기 위해 reservationId를 저장하도록 했습니다.
> 저는 결제 정보와 예약 정보는 관심사가 다르다고 생각해서 테이블을 서로 분리했습니다.
> reservationId만을 저장한 이유는, 결제 객체가 필드로 예약 전체를 가질 필요성이 없고, 예약 entity에서 관리하지 않은 이유는, 어드민이 예약을 할 경우, 결제 정보가 nullable해서 예약 entity에는 넣지 않았습니다.

객체 관점에서 ReservationPayment가 reservationId를 가지는 것과 reservation를 가지는 것 중 어떤 것이 더 자연스러운가요?

JPA를 사용하는 이유에 대해서도 같이 고민해보면 좋을 것 같아요!

2024-06-11 02:36 UTC, jamie9504 commented on src/main/java/roomescape/application/reservation/ReservationLookupService.java
>      public List<ReservationResponse> findByFilter(ReservationFilterRequest request) {
specification을 사용하지 않고도 충분히 조회할 수 있지 않을까요?

2024-06-11 02:36 UTC, jamie9504 commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
> +    private static final ReservationPayment EMPTY_INSTANCE = new ReservationPayment(null,null,null,0);
도메인에 validate는 없어도 되나요?
EMPTY_INSTANCE는 해당 도메인으로 적합한가요?

2024-06-11 02:36 UTC, jamie9504 commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
>      @JoinColumn(name = "reservation_id", nullable = false)
`@JoinColumn(name = "reservation_id", nullable = false)`을 사용한 이유가 있나요?

2024-06-11 02:36 UTC, jamie9504 commented on src/main/java/roomescape/domain/payment/ReservationPaymentRepository.java
> +    ReservationPayment getByReservationId(long id);
findBy~라던가 기본적으로 Jpa 관련 Interface를 상속해서 얻을 수 있는 메서드들을 사용하려면 모두 다 여기서 구현해줘야 서비스에서 사용할 수 있겠네요. 이 부분은 어떻게 생각하시나요?

2024-06-11 02:36 UTC, jamie9504 commented on src/main/java/roomescape/infrastructure/payment/ReservationPaymentJpaRepository.java
> +        return findByReservationId(id).orElse(ReservationPayment.getEmptyInstance());
getBy를 생성해서 `ReservationPayment.getEmptyInstance()`를 내려줬을 때의 이점이 무엇인가요?
비즈니스 로직이 repository에 인입되어있는 것이 아닌지 고민해볼만 하네요!

2024-06-11 17:43 UTC, jimi567 commented on build.gradle
> +    id 'org.asciidoctor.jvm.convert' version '3.3.2'
가장 크게 느껴진 단점은 초기 설정에 시간적 비용이 많이 든다는 점입니다. 특히 제가 처음 배우고 적용하는 입장이라 이 부분이 크게 체감 되었습니다.
또 테스트 기반으로 문서가 작성된다는 점이 개인적으로 장점으로 느끼지만, 단점일 수 도 있다고 생각하는게, 결국 테스트 작성을 하지 않으면 문서화에서 누락될 수 있다고 생각합니다. 개발자가 테스트 코드에 신경을 많이 쓸 필요가 있겠구나 싶었습니다.
마지막으로, 이걸 단점이라고 해야 될지 모르겠지만, 처음 사용해보는 입장에서 적용하기가 어려웠습니다.
groovy설정부터 막히고, 그 외에도 학습 해야 될 양이 어마어마하더라고요. 
그리고 작성해야 될 테스트가 많아지다 보니 ,문서화를 위해 시간을 이정도로 투자하는게 맞나? 라는 생각이 들더라고요. (아마 컨트롤러 단위 테스트를 처음부터 다시 작성해서 그렇게 느꼈을 수 도 있습니다. TDD를 열심히 했다면 이는 단점이 아닐 수 있겠네요.!)

2024-06-11 17:45 UTC, jimi567 commented on build.gradle
> +
restDocs 사용에 필요한 설정을 여러가지 실험하다가 불필요한 개행이 들어갔네요 .ㅎㅎ..
수정하겠습니다.!

2024-06-11 19:08 UTC, jimi567 commented on src/main/java/roomescape/application/payment/PaymentService.java
> +                request.orderId(), reservationId, request.paymentKey(), request.amount()
제이미의 코멘트를 보고 계속 고민을 해봤습니다. 결론부터 말씀드리면  JPA에 대한 이해도도 너무 얕은 상태라 아직 저만의 기준점을 명확하게 잡기가 어려운 것 같아요.

ReservationPayment가 Reservation을 가지게 된다면(직접적인 의존성이 생긴다면)
보다 자연스러울 수 도 있겠다는 생각입니다. 현재 미션 요구사항에서는 모든 예약에 대해 모든 결제 정보가 존재하지는 않지만(어드민이 예약) , 모든 결제에 대해서는 모든 예약이 생기게 됩니다.(도메인의 생명주기가 동일합니다.) 
이는 곧 cascade를 통해서 개발자가 편하게 구현할 수 있을 것 같습니다. (결제를 저장 및 삭제 하되, 결제에 대한 예약 정보 저장/삭제를 누락하는 등 실수를 방지)

만약 결제에 대한 예약 정보가 바뀔 수 있다는 요구 사항이 생긴다면(예약한 방탈출 시간대 변경 등) 결제 조회 -> changeReservationDate호출 이런 flow로 쉽게 요구 사항을 해결할 수 있을 것 같습니다.  물론 현재 도메인 특징 상, 같은 시간대에 같은 테마를 예약할 수 없기 때문에 비즈니스 레이어에서 이에 대한 검증이 필요해서 현실적으로 불가능 하겠지만요.

jpql로 조회할 때에 한해서는 Lazy 로딩을 통해 성능 개선도 가능하겠군요.

식별자를 통해서 두 엔티티간에 연관관계를 지정해주는 방식도 경험해보고 싶기도 했고, 현재 단계에서는 결제와 예약이 연관된 지점이 저장밖에 없기 때문에 최대한 의존성을 끊어주는 방식으로 Id를 가지는 방식을 선택했던 것 같아요. 

이 부분에 대해서 제이미와 많은 대화를 해보고 싶습니다. 
혹시 제가 생각한 부분에 오류가 있거나 하면 가감없이 말씀해주시면 제 성장이 많은 도움이 될 것 같아요.

2024-06-11 19:55 UTC, jimi567 commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
>      @JoinColumn(name = "reservation_id", nullable = false)
연관 관계를 위해 사용되는 column임을 명시해주려고 JoinColumn을 사용했습니다.
해당 Long타입 필드가 뭘 의미하는 값인지 어떻게 의미 전달을 할까 고민해서 이렇게 해봤는데
용도에 안맞게 사용한 것 같아서 수정했어요.

2024-06-11 19:59 UTC, jimi567 commented on src/main/java/roomescape/domain/payment/ReservationPaymentRepository.java
> +    ReservationPayment getByReservationId(long id);
repository 명세와 JPA 상속 받은 인터페이스를 구분하려고 이렇게 구성된 것 같아요.
페어 할 당시에 이렇게 구현한 이유를 물어봤을 때 나름 근거도 있고 괜찮다고 생각했습니다.
하지만 관리 포인트가 늘어나고, 과도한 추상화가 아닐까 라는 생각이 들기도 하네요.
애초에 JPA이라는 ORM을 사용하는 시점에는 infra에 repository 구현체를 둔다는 개념도 불필요한 것 같고요.
일단 base코드와의 일관성을 위해서 이런식으로 구현했습니다.

2024-06-11 20:06 UTC, jimi567 commented on src/main/java/roomescape/infrastructure/payment/ReservationPaymentJpaRepository.java
> +        return findByReservationId(id).orElse(ReservationPayment.getEmptyInstance());
이점은 구현하기 편했던 것 같아요... service 코드도 깔끔해지고요.
하지만 "관리자가 넣은 예약은 결제 정보가 없다." 라는 비즈니스가 repository에 들어가 있다는 점은 맞는 것 같습니다.
Optional로 반환하여, service에서 처리하는 것이 더 알맞을 것 같습니다. 
수정했습니다.!

2024-06-11 21:33 UTC, jimi567 commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
> +    private static final ReservationPayment EMPTY_INSTANCE = new ReservationPayment(null,null,null,0);
배포, 문서화 이후에 리팩터링 하려고 미뤘던 부분입니다..ㅎㅎ
배포,문서화에 너무 매몰돼서 2단계를 소홀히 했던 것 같습니다.
결제 도메인에 validate를 추가하면서 자연스럽게 EMPTY_INSTANCE를 삭제했습니다.

추가적으로 ReservationId와 Amount의 경우 VO로 감싸줄 수 있을 것 같아요.
이 부분은 [위 코멘트](https://github.com/woowacourse/spring-roomescape-payment/pull/131#discussion_r1634061016) 에 대한 피드백을 적용하는 과정에서 사라질 수 있다고 생각해서 일단 미루겠습니다..ㅠㅠ

2024-06-11 21:43 UTC, jimi567 commented on src/main/java/roomescape/application/reservation/ReservationLookupService.java
>      public List<ReservationResponse> findByFilter(ReservationFilterRequest request) {
지금 구조는 테이블이 분리되어 있고, 결제에서 reservationId로 연관 관계를 맺고 있는 형태라
조회하기 위해서 specification이 필요하다고 생각했습니다.

제가 아직 식견이 부족해서 어떤 방식으로 해결해야 되는지 감이 잘 잡히지가 않습니다.
Payment에 대한 쿼리 메소드 서비스를 만들어 서비스 끼리 협력하도록 하는 걸 의도하시는 걸까요?

2024-06-11 22:30 UTC, jimi567 commented on README.md
>  - [x] 같은 사람이 (날짜, 시간, 테마)가 같도록 여러 번 대기열에 등록할 수 없다.
request DTO의 필드가 VO일 때, VO 내부에서 발생되는 예외가 @Valid로 인해 
HttpMessageNotReadableException 핸들러로 매핑되고, 이 핸들러 내부에서 고정된 메세지를 클라이언트에 내려줘서 저런식으로 나오는 것 같습니다.
예외 메세지를 추출하여 내려주도록 변경했습니다.

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/28584160/7da08385-3f73-4861-82bb-ebee16d6af4c)

2024-06-11 22:35 UTC, jimi567 commented
안녕하세요. 제이미!
제가 이번 주 예비군을 하고 있어서 캠퍼스에 가지 못해 변경사항이 배포 환경에는 적용이 안됩니다.
리뷰 잘 부탁드립니다.

2024-06-11 22:45 UTC, jimi567 commented
안녕하세요. 제이미!
조금 더 고민하고 리뷰 반영을 하고 싶었지만 ,좀 더 제이미와 조금 더 많은 대화를 나누고 싶기도 하고,
제가 이번 주 예비군 일정이 있어서 리뷰요청을 일찍 보내게 됐습니다.
추가적으로, 캠퍼스를 가지 못해 변경사항이 배포 환경에는 적용이 안됩니다..ㅠ
리뷰 잘 부탁 드립니다

2024-06-11 22:46 UTC, jimi567 commented
안녕하세요. 제이미!
조금 더 고민하고 리뷰 반영을 하고 싶었지만 ,제이미와 더 많은 대화를 나누고 싶기도 하고,
제가 이번 주 예비군 일정이 있어서 리뷰요청을 일찍 보내게 됐습니다.
추가적으로, 캠퍼스를 가지 못해 변경사항이 배포 환경에는 적용이 안됩니다..ㅠ
리뷰 잘 부탁 드립니다

2024-06-12 19:24 UTC, jamie9504 approved these changes
안녕하세요, 위브 😄 리뷰어 제이미입니다!

2레벨 마지막 미션 고생 많으셨어요 👏 👏 
코멘트는 조금 남겨두었으니 시간되실 때 확인해주세요!

이번 미션 요구사항은 충족하여 이만 Approve & Merge합니다!

오늘도 좋은 하루 보내시고,
다음 레벨들도 즐겁고 행복하게 보내세요! 🎵

2024-06-12 19:24 UTC, jamie9504 commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
>      @JoinColumn(name = "reservation_id", nullable = false)
해당 필드를 위한 연간 관계를 위해 사용되는 Column을 명시하는 것이 JPA에 있을까요?
만약 찾아봐도 없다면, 이런 관리방식을 JPA에서 지향하고 있는지 생각해보는 것도 좋겠죠 😃

2024-06-12 19:24 UTC, jamie9504 commented on src/main/java/roomescape/domain/payment/ReservationPaymentRepository.java
> +    ReservationPayment getByReservationId(long id);
실용적인 부분을 중점으로 사용하는가 이론적인 부분을 중점으로 사용하는가 등의 기준으로 인해 설계가 달라질 수 있죠 😃 
어떤 방식을 선택한다고 문제가 되는 것은 아니지만, 어떠한 기술을 사용하기로 정했다면 그 기술을 최대한 사용할 수 있는 방향의 설계도 고민해보는 것도 좋을 것 같아요.
물론 그 기술이 자주 바뀌거나 다른 기술로 바뀔 수 있는 가능성이 높다면 기술에 의존했을 때 다른 기술로 변경한다면, 리소스가 많이 들 수도 있지만요 😉

2024-06-12 19:24 UTC, jamie9504 commented on src/main/java/roomescape/application/reservation/ReservationLookupService.java
> +                    long amount = optionalPayment.map(ReservationPayment::getAmount).orElse(0L);
상수일 것 같은 친구들이 보이네요!

2024-06-12 19:24 UTC, jamie9504 commented on src/main/java/roomescape/application/reservation/ReservationLookupService.java
> +                    );
map 내부가 너무 길어진다면 메서드로 추출하는게 더 깔끔할 수 있을 것 같아요.

2024-06-12 19:24 UTC, jamie9504 commented on src/test/java/roomescape/domain/payment/ReservationPaymentTest.java
> +    void invalidReservationId(Long input) {
경계값을 모두 테스트해주어야겠죠? (성공/실패)

누가 도메인을 2보다 작으면 예외가 발생하게끔 수정하더라도 이정도 테스트로는 예상치 못한 해당 변경을 잡을 수 없을 것 같아요.

2024-06-12 19:24 UTC, jamie9504 commented on src/main/java/roomescape/presentation/RoomescapeControllerAdvice.java
> +            }
특정 문자열로 검증해도 되지만,`getCause`를 이용해 cause를 추출한 후, `instanceof IllegalArgumentException`와 같이 예외의 종류로 구분해도 되겠죠 😃

2024-06-12 19:24 UTC, merged