[ 2 - 4단계 방탈출 결제 / 배포 ] 로키(정해성) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #136
Opened 2024-06-10 06:31 UTC by HaiSeong

안녕하세요! 오리!
2-4단계 미션도 잘 부탁드립니다!

### 데이터베이스 ERD
![Copy of roomescape](https://github.com/woowacourse/spring-roomescape-payment/assets/58177929/b147c552-f6a7-436c-b852-32cf62a84657)

### API 문서
[API 문서](http://43.202.2.128:8080/swagger-ui/index.html)

### 배포 링크
[배포 링크](http://43.202.2.128:8080)

### 계정

| 이름     | 이메일               | 패스워드 | 권한  |
|----------|----------------------|----------|-------|
| admin    | `[admin@email.com](mailto:admin@email.com)`      | `qwer`     | `ADMIN` |
| member1  | `[email1@email.com](mailto:email1@email.com)`     | `qwer`     | `MEMBER`|
| member2  | `[email2@email.com](mailto:email2@email.com)`     | `qwer`     | `MEMBER`|
| member3  | `[email3@email.com](mailto:email3@email.com)`     | `qwer`     | `MEMBER`|

### 이전 커밋 질문 답변

>connection timeout과 read timeout의 차이는 무엇인가요? 각각 3으로 설정된 이유가 있을까요?

2024-06-10 10:50 UTC, jinyoungchoi95 requested changes
안녕하세요 로키 😄

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-06-10 10:50 UTC, jinyoungchoi95 commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
openapi가 무엇인가요?

2024-06-10 10:50 UTC, jinyoungchoi95 commented on build.gradle
> +
```suggestion
```

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/ClientConfig.java
> +    @Autowired
`@Autowired`는 어떻게 동작하나요? `ClientConfig`는 1레벨때의 객체지향을 지키며 생성되고 있나요?

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/ClientConfig.java
> +    @Value("${toss.widget.secretKey}")
`@Value`의 사용법은 생성자에도 넣을 수 있습니다. 위 코멘트와 함께 고민해보세요.

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/SwaggerConfig.java
> +    }
다른 개발자가 문서만봐도 모든 스펙을 알 수 있게끔 추가할만한 다른 설정들은 없나요?

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/AdminController.java
문서에 예외 케이스에 대한 스펙이 있어야하지 않을까요?

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/AdminController.java
> +    @Operation(summary = "예약 등록 API", description = "예약을 등록합니다.")
<img width="415" alt="스크린샷 2024-06-10 오후 7 44 42" src="https://github.com/woowacourse/spring-roomescape-payment/assets/69106910/eb66f7a5-75b2-479c-9b0b-ab1e025c88f4">

mediatype은 `*/*`여도 되나요?

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/test/java/roomescape/infra/TossPaymentClientTest.java
> +        // when && then
예외를 발생시키지 않는다기보다는 `server.expect`로 값을 반환하고 있으니 이 값을 검증하는건 어떨까요?

2024-06-10 10:50 UTC, jinyoungchoi95 commented on src/main/java/roomescape/dto/MyReservationResponse.java
request, response body도 문서에 설명이 필요하지 않을까요?

2024-06-11 13:35 UTC, HaiSeong commented on src/main/java/roomescape/config/ClientConfig.java
> +    @Autowired
레벨1에서는 필드에 모두 `final`을 붙이려 노력했었는데 레벨2에 와서 레벨1의 습관을 잃어가는것 같아요. 주의하겠습니다.!

아래 커멘트까지 참고해서 생성자 주입을 사용하고 `final`을 붙이도록 하겠습니다

2024-06-11 13:45 UTC, HaiSeong commented on src/main/java/roomescape/controller/AdminController.java
> +    @Operation(summary = "예약 등록 API", description = "예약을 등록합니다.")
`application/json` 이 되어야 합니다.

@RequestMapping(consumes = "application/json", produces = "application/json")을 이용해서 `application/json` 요청가능하고 응답하도록 수정했습니다.

2024-06-11 14:54 UTC, HaiSeong commented on src/main/java/roomescape/config/SwaggerConfig.java
> +    }
인증정보에 대한 내용을 담아보겠습니다!

2024-06-12 14:48 UTC, HaiSeong commented on src/main/java/roomescape/controller/AdminController.java
넵! 추가하는중에 질문이 생겼습니다.

지금 저의 `Controller`에는 예외사항에 대한 코드가 없습니다. `GlobalExceptionHandler`(`ControllerAdvice`)에서 예외를 잡고있기 때문입니다. 그래서 `GlobalExceptionHandler`에 `@ApiResponse`를 추가해 예외 케이스에 대한 스팩을 추가하려 했습니다. 그러나 `GlobalExceptionHandler`에 `@ApiResponse`를 추가했더니 전혀 상관없는 (예를들어 404 상태코드를 반환할 일이 없는) API에도 이 스팩이 나타나는 문제가 생겼습니다. 그래서 각 메소드마다 `@ApiResponse`를 따로 따로 정의해주자니 너무 작업량이 많고 `Controller`가 지져분해지는 문제가 있는것 같습니다.

아래는 제가 생각해본 각 방법의 장단점입니다.

1. `GlobalExceptionHandler`에 `@ApiResponse` 정의
- 장점 : 응집도가 높아진다. (예외 상황을 처리하는 곳에 스팩이 정의되어있음. 예외코드를 변경할일이 있다면 `GlobalExceptionHandler` 만 변경 가능), 반복되는 코드 x 
- 단점 : 각 api 별로 세세한 설명 불가능, 필요없는 스팩이 줄줄이 생겨 문서의 가독성이 떨어짐
2. `Controller`에 예외상황에 대한 `@ApiResponse` 도 같이 정의
- 장점 : 각 api에 알맞는 설명 가능
- 단점 : 예외처리가 변경된다면 양쪽 모두 수정해줘야함 (실수 가능), 코드 반복이 너무 많아짐, 프로덕션 코드를 읽기 힘들정도로 복잡해짐

2024-06-13 02:03 UTC, HaiSeong commented
오리 안녕하세요!
남겨주신 코멘트 반영했습니다.

[배포 링크](http://43.202.2.128:8080)
[API 문서](http://43.202.2.128:8080/swagger-ui/index.html)

2024-06-13 03:24 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/AdminController.java
저는 `Controller`의 각 요청마다 발생가능성 있는 비즈니스적 예외는 모두 개별적으로 관리하고, 인증인가와 같은 부분에 대해서는 공통적으로 관리하는 편이에요.

api문서라는 것은 이 문서를 보고 api를 사용하는 입장에서 얼마나 이해하기 쉽도록 하느냐가 중요하다고 생각하는데요. 전체적으로 걸리는 예외의 경우에 대해서는 사용하는 측에서도 전체 공통처리를 하기 때문에 개별로 볼 필요가 없어요. 다만 그 요청들에 비즈니스적 예외들에 대해서는 예외에 대한 처리들을 개별적으로 처리해주어야하기 때문에 문서를 읽는 입장에서는 각 요청마다 그 예외를 명시해주는 것이 좋습니다.

2024-06-13 03:30 UTC, jinyoungchoi95 approved these changes
안녕하세요 로키 😄

현재 단계에 필요한 구현과 학습이 충분히 완료되신 것 같아 머지하겠습니다. 2레벨 수고하셨어요.

감사합니다 🙇‍♂️

2024-06-13 03:30 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/ClientConfig.java
> +                .baseUrl("https://api.tosspayments.com/v1/payments/confirm")
이런 url에 대한 정보들도 properties에 모두 넣어두고 사용한다면 요청 url이 변경되더라도 config에 영향도는 줄어들 수 있을 것 같아요.

2024-06-13 03:30 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/SwaggerConfig.java
> +    private Components getComponents() {
get은 일반적으로 "가져오다"의 의미를 내포하고 있어요. 현재는 가져오는 값이라기보다는 security scheme을 만들어내는 기능에 더 가깝기 때문에 get보다는 좀더 적절한 메소드 네이밍을 고려해보시면 좋을 것 같아요.

다른 get 메소드도 마찬가지입니다.

2024-06-13 03:30 UTC, jinyoungchoi95 commented on src/main/java/roomescape/dto/AvailableTimeResponse.java
> +public record AvailableTimeResponse(
dto들에도 `@Schema`를 통해 설명이 가능하겠네요.

2024-06-13 03:30 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/PaymentExceptionHandler.java
> +@ControllerAdvice(assignableTypes = PaymentController.class) // PaymentController의 메소드만 이 예외를 잡고싶어 =>
사용하지 않는 주석은 제거하는 것이 좋을 것 같아요

2024-06-13 03:30 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/PaymentExceptionHandler.java
> +    private final PrintWriter printWriter = new PrintWriter(stringWriter);
이런 방식도 좋기는한데 `PaymentExceptionHandler`에서 `StringWriter`를 테스트를 위해서 커스텀하는 등과 같은 작업을 위해서는 개인적으로 주생성자 하나를 사용하고 no-arg 생성자에 이 세팅을 하면 어떨까싶어요.

2024-06-13 03:30 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/PaymentExceptionHandler.java
> +        e.printStackTrace(printWriter);
stack trace를 모두 출력하면 어떤 문제가 발생하나요?

2024-06-13 03:30 UTC, merged