[ 2 - 4단계 방탈출 결제 / 배포 ] 폰드(권규택) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #138
Opened 2024-06-10 06:44 UTC by tackyu

**Database ERD**
![방탈출 예약 (1)](https://github.com/woowacourse/spring-roomescape-payment/assets/90441959/3b015e9a-3808-4086-ad55-faff080b852f)
**방탈출 예약**
http://3.39.229.184:8080/
**API 명세서**
http://3.39.229.184:8080/swagger-ui/index.html#/

안녕하세요 영이 폰드입니다.
이번 미션에서는 ```Payment``` 엔티티 분리, 배포, API 문서 작성을 하였습니다.

2단계에서 ```Reservation```과 ```Payment```를 분리하였습니다.
예약이 결제 정보를 알아야하는 책임을 갖을 필요가 없다고 판단했고,
```Payment```에 포함되어야 하는 정보가 추후 늘어날 수 있다고 생각했습니다.
또한 ```saveReservation```에서 ```Reservation```을 저장하고, 결제를 요청하게 되는데,
이 로직을 유지하려면 ```Payment```가 ```Reservation```의 키를 갖어야 한다고 생각했습니다.

배포 단계에서 DB를 MySQL로 변경하는 것은 아직 진행하지 못했습니다.

문서화는 Swagger를 통해서 진행하였습니다.
프론트엔드 개발자가 이해하기 좋은 형태로 만들라는 미션 요구 사항이 있었는데, 문서에 포함 되어야 하는 정보의 기준이 궁금합니다.
또한 문서화를 진행함에 있어 프로덕션 코드가 지저분해지는 것 같은데, 어떻게 개선 할 수 있을까요?

감사합니다🙇‍♂️

2024-06-10 15:13 UTC, choijy1705 requested changes
안녕하세요 폰드
미션 잘 구현해주셨어요!
몇가지 코멘트 남겼으니 확인 부탁드려요

2024-06-10 15:13 UTC, choijy1705 commented on src/main/java/roomescape/reservation/model/Payment.java
> +    private Long amount;
부동소수점 문제와 원화가 아닌 다른 통화로 결제가 일어날때를 대비해야할것 같네요!
long이 아닌 어떤 타입을 쓰면 좋을지 고민해보면 좋을것 같습니다

2024-06-10 15:13 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
결제를 하면서 같이 저장하는게 바람직하지 않을까요?
save하는 로직만 별도로 관리되는게 어색해보이네요!

2024-06-10 15:13 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    }
오늘 이전인지를 나타내는 메서드명이 되는게 좋지 않을까요!

2024-06-10 15:13 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                .map(r->{
reservation으로 구체적으로 적어주시는게 좋습니다...

2024-06-10 15:13 UTC, choijy1705 commented on src/main/java/roomescape/reservation/model/Payment.java
> +    }
도메인이 굳이 paymentRespone를 알고 있을 필요가 있을까요?
validation도 챙겨보면 좋겠네요!

2024-06-12 16:56 UTC, tackyu commented on src/main/java/roomescape/config/SwaggerConfig.java
> +                .version("1.0.0");
변경된 API와 명세서의 버전이 달라서 생기는 문제를 말씀하시는 건가요??
프로퍼티로 관리하라는 의미이신지 궁금합니다!

2024-06-12 17:31 UTC, tackyu commented on src/main/java/roomescape/reservation/model/Payment.java
> +    private Long amount;
이전 미션에서 통화를 다룰 때, BigDecimal에 대해 학습 했었는데 잊고 있었습니다🥲
감사합니다!

2024-06-12 17:40 UTC, tackyu commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                .map(r->{
변수 명도 신경써서 사용하겠습니다.
감사합니다!

2024-06-13 04:04 UTC, tackyu commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
외부 API호출과 결제 정보를 저장하는 pay 메서드를 생성하였습니다!

2024-06-13 04:23 UTC, tackyu commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    }
```validateReservationNotInPast```으로 변경하였습니다.

2024-06-13 04:37 UTC, tackyu commented on src/main/java/roomescape/reservation/model/Payment.java
> +    }
서비스 코드에서 직접 DTO를 넘겨주지 않고, 필요한 데이터만 넘겨주도록 변경하였습니다.
또한 `Reservation`과의 통일성을 위해 `checkRequiredData`메서드를 만들어 null 검증을 해주었습니다.

2024-06-13 05:56 UTC, tackyu commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
결제 요청 메서드에 결제 정보 저장하는 로직을 추가했습니다.
결제 요청 메서드가 2가지 일을 하는 것 같은데 괜찮을까요?

2024-06-13 12:16 UTC, choijy1705 approved these changes
폰드 피드백 잘반영해주셨습니다!
미션은 여기서 머지하겠습니다
고생많으셨습니다👍

2024-06-13 12:16 UTC, choijy1705 commented on src/main/java/roomescape/config/SwaggerConfig.java
> +                .version("1.0.0");
다양한 방법이 있을 수 있겠지만
하드 코딩된 값을 적어두면 분명 달라질거라서 코멘트 남겼습니다!

2024-06-13 12:16 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
제가 잘못봤네요 ㅠ
이전 방법이 더 적절할것 같습니다 🙏

2024-06-13 12:16 UTC, choijy1705 commented on src/main/java/roomescape/member/dto/MemberResponse.java
> +                             String email) {
```suggestion
public record MemberResponse(
    Long id, 
    String name,
    @Schema(example = "user@mail.com") String email
) {
```
한줄에 하나만 오도록 해주세요!
어던 파라미터가 있는지 파악하기 어렵습니다!

2024-06-13 12:16 UTC, merged