[ 2 - 4단계 방탈출 결제 / 배포 ] 마크(김승현) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #141
Opened 2024-06-10 07:26 UTC by seunghye218

안녕하세요 파랑! 

이번에 2 - 4 단계를 통해 추가 요구사항 구현과 배포 및 문서화를 진행했어요.

작성중...

## 테스트용 계정
| 이름  | 이메일              | 비밀번호 | 권한   |
|-----|------------------|------|------|
| 스티치  | [lxxjn0@test.com](mailto:lxxjn0@test.com)  | 123  | MEMBER |
| 파랑  | [parang@test.com](mailto:parang@test.com)  | 123  | MEMBER |
| 마크  | [mark@test.com](mailto:mark@test.com) | 123  | MEMBER |
| 메이슨 | [mason@test.com](mailto:mason@test.com)   | 123  | MEMBER |
| 어드민 | [admin@test.com](mailto:admin@test.com)   | 123  | ADMIN |

---

2024-06-10 16:33 UTC, summerlunaa requested changes
마크 안녕하세요~

배포도 해보시고 API 문서와 ERD까지 잘 공유해주셨습니다 👍 리뷰 남겼으니 확인 해주시고 더 궁금한 부분 있으면 코멘트나 DM으로 편하게 말씀해주세요!

2024-06-12 01:58 UTC, seunghye218 commented on src/main/java/roomescape/global/config/SwaggerConfig.java
> +public class SwaggerConfig {
API를 설명해주는 다양한 애너테이션들이 있었네요. 예시를 보니 제 문서가 상당히 불친절하게 느껴져요. 개발자가 API를 이해하고 사용하는 데 도움이 되도록 적용해보겠습니다!

2024-06-12 02:57 UTC, seunghye218 commented on src/main/java/roomescape/global/exception/PaymentFailException.java
> +        }
예기치 못한 문제를 발생시킬 수 있겠네요. stream을 이용하여 예상 가능한 방식으로 바꾸도록 하겠습니다.

2024-06-12 04:39 UTC, seunghye218 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    private Long reservationId;
현 상황에서 예약 없이 결제만 있을 수 없기에 Payment 가 Reservation 을 의존하도록 설계했어요~

id만 참조한 이유는 객체가 간단하고 가벼워지는 것으로 인한 이점과 (예약에 결제를 추가한다면) 순환 참조를 피할 수 있기 때문이에요. Payment에서 Reservation의 정보를 필요로 한다면 두 번의 쿼리가 필요하지만 그런 경우가 많이 생기지 않을 것이라 생각했어요. 

예약이 삭제된다면 결제도 따로 삭제하거나 논리 삭제를 통해 간접 참조로 인해 발생할 수 있는 문제를 예방 해야겠네요!

2024-06-12 06:27 UTC, seunghye218 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    private String paymentKey;
놓친 부분이네요...😅 아래 BigDecimal 과 함께 리팩터링 해볼게요.

2024-06-12 07:42 UTC, seunghye218 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        Stream<MemberReservationStatusResponse> waitingReservationResponses = reservationRepository.findAllReservationWaitingByMemberId(memberId)
기존 코드 베이스가 따로 조회하여 repository의 메서드가 다른 곳에서 사용한다고 생각했어요. 그래서 코드를 재사용 했었는데 다른곳에서 사용하지 않았네요. 한 번의 쿼리로 조회할 수 있도록 해볼게요!

2024-06-13 03:51 UTC, seunghye218 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    @Transactional
서비스 로직에서 여러 쿼리를 사용할 경우에 트랜잭션 롤백을 이용해 ACID 를 만족하여 데이터 무결성을 보장하기 위해 
 `@Transactional` 을 달아놨어요. 

몰랐는데 (Simple)JpaRepository 클래스에 `@Transactional(readOnly = true)` 가 달려있어 서비스의 다른 메서드에서도 사용되고 있다 볼 수 있었네요! 한 서비스 메서드에서 여러 쿼리를 날리지만 트랜잭션이 필요하지않은 경우가 있을지 모르겠지만... 가능하다고 생각하여 서비스의 필요한 부분에만 트랜잭셔널을 붙이는 것이 좋다는 생각이 들었어요.

2024-06-13 04:05 UTC, seunghye218 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +            @Valid MemberReservationWithPaymentAddRequest request) {
DTO에 습관적으로 달아버렸네요… 지우도록 하겠습니다.

2024-06-13 05:33 UTC, seunghye218 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        Stream<MemberReservationStatusResponse> waitingReservationResponses = reservationRepository.findAllReservationWaitingByMemberId(memberId)
한 번에 조회한다면 예약 정보, 예약 상태, 대기의 경우 순서, 예약의 경우 결제 정보를 하나의 객체에 담기에 크다고 생각했어요. 
ReservationWaiting 객체를 사용하여 예약 대기에는 rank 필드가 있어 순서에 대한 책임을 가지고 있어요. 이외의 상태에서는 순서가 없기 때문에 내 예약 정보 DTO에서 조립하게 됩니다.

2024-06-13 05:38 UTC, seunghye218 commented on src/main/java/roomescape/reservation/presentation/ReservationController.java
> +    @GetMapping("/reservations/v2/my")
내 예약 조회 요구사항이 바뀌면서 기존 코드를 유지해보고 싶어 v2 엔드포인트를 써봤어요. 하지만 기존 DTO에 추가 데이터만 생긴 것이라 호환될 것 같아 안쓰는 것이 맞는것 같아요. 이런 경우에는 API 문서에 1.1 버전으로 표현해도 되는걸까요?

2024-06-13 05:59 UTC, seunghye218 commented on src/main/java/roomescape/reservation/domain/Status.java
> +    PAYMENT_WAITING("결제대기"),
결제 대기 삭제하는 경우를 놓치고 있었네요... 상태를 추가하게 된다면 관련된 로직을 잘 확인하도록 하겠습니다.

2024-06-13 12:28 UTC, summerlunaa approved these changes
마크 안녕하세요~

리뷰 반영해주신 부분들 확인했습니다 :) 추가로 몇 가지 리뷰 더 남겨드리긴 했지만 이제 MR은 머지할게요. 더 궁금한 점 있으면 언제든지 DM 주세요.
드디어 레벨 2 마지막 미션도 끝이네요 🎊 방학동안 푹 쉬면서 충전하시고 남은 레벨도 잘 헤쳐나가시길 바랍니다~~ 넘 수고하셨습니다!! 👏

2024-06-13 12:28 UTC, summerlunaa commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    @Transactional
네 이런 경우 메서드 추가시 애노테이션을 빼먹지 않도록 신경 써줘야 합니다. 이미 지금도 여러 쿼리를 날리는 메서드들에서 `@Transactional`이 보이지 않아서요 👀

2024-06-13 12:28 UTC, summerlunaa commented on src/main/java/roomescape/reservation/presentation/ReservationController.java
> +    @GetMapping("/reservations/v2/my")
`Semantic Versioning`에 대해서 공부해보시면 도움이 될 것 같습니다 :)

2024-06-13 12:28 UTC, summerlunaa commented on src/main/java/roomescape/reservation/domain/Status.java
> +    PAYMENT_WAITING("결제대기"),
네 enum을 추가할 때에는 항상 영향 범위를 꼼꼼히 파악해야 합니다!

2024-06-13 12:28 UTC, merged