[2 - 4 단계 방탈출 결제 / 배포] 프린(남기범) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #144
Opened 2024-06-10 07:37 UTC by GIVEN53

안녕하세요 미르! 프린입니다 

### 링크

- [배포](http://54.180.201.43:8080/)
- [API Docs](http://54.180.201.43:8080/docs/index.html)
- [ERD]()

2024-06-11 14:11 UTC, ddu0422 requested changes
안녕하세요 프린! 미르입니다 :)

미션 구현 잘 해주셨네요.
몇 가지 코멘트 남겼으니 확인 부탁드립니다 :D

마지막까지 화이팅입니다 💪🏻

2024-06-11 14:11 UTC, ddu0422 commented on src/main/java/roomescape/service/ReservationWaitingService.java
> +        }
changeMember에서 확인하는건 어떨까요?

2024-06-11 14:11 UTC, ddu0422 commented on src/main/java/roomescape/service/dto/response/PersonalReservationResponse.java
> +                null
불필요한 내용이 전달되네요.
response를 별도로 생성하면 어떨까요?

2024-06-11 14:11 UTC, ddu0422 commented on src/test/java/roomescape/documentation/AdminApiDocumentationTest.java
> +                        )
header의 값도 명시적으로 문서화하면 어떨까요?

2024-06-11 14:11 UTC, ddu0422 commented on src/test/java/roomescape/documentation/ReservationApiDocumentationTest.java
> +                                fieldWithPath("list.[].paymentKey").description("결제 키 (결제 수단이 계좌이체가 아닐 경우 필수)").optional(),
optional로 지정한 내용이 문서에 반영이 안되는걸까요?

2024-06-13 13:02 UTC, GIVEN53 reviewed
안녕하세요 미르!
리뷰 반영과 함께 코멘트 및 궁금한 점 남겼습니다 리뷰 감사합니다 😊

2024-06-13 13:42 UTC, ddu0422 commented on src/docs/asciidoc/admin.adoc
불편한 점을 알고 이를 개선하려는 태도가 훌륭하네요 :D

> 4.adoc 결합

API 문서를 작성할 때, 필요한 내용을 정한 후 build.gradle에서 자동으로 문서를 만들었습니다.

2024-06-13 13:45 UTC, ddu0422 commented on src/main/java/roomescape/domain/payment/Account.java
> +    private String bankName;
객체 1개당 1개의 검증 로직을 만들기 위한 노력을 진행하고 있습니다.

관리해야 할 클래스가 늘어나겠지만, 클래스가 늘어난 것이지 관리할 포인트가 늘어났다고 생각하지 않습니다.
오히려 작은 단위로 객체를 나누어야 SRP 올바르게 지켰다고 생각해요.

2024-06-13 13:47 UTC, ddu0422 commented on src/main/java/roomescape/service/PaymentService.java
> +    }
아하 착각할 여지가 있겠네요. 좀 더 자세히 리뷰를 남겨드릴게요.

cancelReservation의 `@Transactional`을 선언하게 되면 cancle 한 내용이 적용이 되지 않을텐데 새로 데이터를 저장하는 이유가 궁금합니다.

2024-06-13 13:49 UTC, ddu0422 commented on src/main/java/roomescape/service/dto/response/PersonalReservationResponse.java
> +                null
네 맞습니다 :)

2024-06-13 13:50 UTC, ddu0422 commented on src/test/java/roomescape/documentation/ReservationApiDocumentationTest.java
> +                                fieldWithPath("list.[].paymentKey").description("결제 키 (결제 수단이 계좌이체가 아닐 경우 필수)").optional(),
아니요 잘 사용하지 않습니다.
하지만 알아서 나쁠 건 없죠 ㅎ-ㅎ
다양한 방면으로 알고 있다면 좋은 도구를 적절히 활용할 수 있기 때문입니다.

2024-06-13 13:55 UTC, ddu0422 approved these changes
안녕하세요 프린! 미르입니다 :)

미션 구현 잘 해주셨네요.
몇 가지 코멘트 남긴 부분은 시간 되실 때 고민해주시면 될 것 같습니다 :D

마지막 미션을 함께 할 수 있어서 영광이었습니다.
남은 우테코 기간 동안에 뜻하는 바를 이루었으면 합니다.
항상 응원하겠습니다. 🎉

2024-06-13 13:55 UTC, ddu0422 commented on Dockerfile
참고) jib 라는 내용도 추가 학습해보면 어떨까합니다.

2024-06-13 13:55 UTC, ddu0422 commented on src/main/java/roomescape/service/dto/response/PersonalReservationResponse.java
> +                PaymentResponse.empty()
해당 내용은 간단히 null로 선언해도 괜찮을 듯 합니다.
아니면 `예약 응답`과 `예약 대기 응답` Response를 나누어도 괜찮을 듯 합니다 :D

2024-06-13 13:55 UTC, merged