[2 - 4 단계 방탈출 결제 / 배포] 도라(추서연) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #146
Opened 2024-06-10 07:47 UTC by ChooSeoyeon

안녕하세요 범블비! 돌아온 도라입니다... 

1. [배포 서버](http://43.203.205.194:8080/)
2. [API 문서](http://43.203.205.194:8080/docs/index.html)
3. [ERD](https://www.erdcloud.com/d/i7o7W64kLhNj9TW5m)
<img width="1218" src="https://github.com/ChooSeoyeon/spring-roomescape-payment/assets/83302344/d46b96ef-b589-433c-90dd-5294d3f499f6">

---

이번 미션에선 해보고 싶은 작업과 해야 하는 작업을 구분하는 게 중요했던 거 같습니다.
미션 중간중간 고민이 깊어지는 부분들이 있었지만 시간 안에 주어진 요구사항에 맞춰 구현하기 위해 
리팩토링하고 싶은 부분 중 일부는 5단계라는 이름으로 남겨두었습니다.

2024-06-10 08:34 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                        reservationWaitingsWithRank.stream().map(ReservationMineResponse::new)
어떤 예약은 결제가 있고, 어떤 예약은 결제가 없다보니 각각 db에서 따로 찾아와 코드단에서 합쳐주는 현재의 로직이 만들어졌습니다. 

충분히 맥락상 말이 되지만 지속가능한 방식일지 의문이 들었습니다. 현재는 예약과 관계맺고 있는 테이블이 Payment, Waiting 두 개라 세 종류(reservationWithPayment, reservationWtihoutPayment, reservationWaitingWithRank)만으로 찾아왔지만, 만일 예약과 관계 맺고 있는 테이블이 더 늘어난다면 다섯 종류, 열 종류의 객체를 각각 찾아오는 방식이 될 것이기 때문입니다.

그럼에도 지금 방식을 사용한 이유는 예약과 관계 맺고 있는 테이블이 늘어난 상황에서 다섯 종류, 열 종류의 객체를 전부 찾아와야 한다면 테이블(혹은 객체) 설계가 잘못된 거일 수 있다 생각했기 때문입니다. 

범블비는 현재 코드가 지속가능하다 생각하시는지, 만일 지속가능하지 않다면 어떻게 개선(ex. 테이블 재설계, 쿼리 개선)할 수 있다 생각하시는지 궁금합니다!

2024-06-10 08:35 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/reservation/ReservationService.java
>                  = reservationWaitingRepository.findAllWaitingWithRankByMemberId(member.getId());
d

2024-06-10 08:46 UTC, ChooSeoyeon commented on src/test/java/roomescape/integration/ReservationWaitingIntegrationTest.java
> +                fieldWithPath("date").description("예약 날짜")
themeId와 timeId 의 경우 Number 타입인데.. 현재 RequestDTO가 아래처럼 구현되어 있어 전부 String 타입으로 문서에 나오는 문제가 있습니다. 이를 해결하기 위해선 bean validation을 적용해 기존의 validate을 대체하고, RequestDTO의 생성자에선 String이 아닌 Long 타입을 사용해야 할 거 같습니다. API 문서를 뽑던 중 DTO 구현이 잘못됐다 판단하고 기존의 프로덕션 코드의 전체적인 구현 방향을 고치는 건 괜찮은 선택일까요?

```
public class ReservationWaitingRequest {
    private final LocalDate date;
    private final Long timeId;
    private final Long themeId;

    public ReservationWaitingRequest(String date, String timeId, String themeId) {
        validate(date, timeId, themeId);
        this.date = LocalDate.parse(date);
        this.timeId = Long.parseLong(timeId);
        this.themeId = Long.parseLong(themeId);
    }
```

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/83302344/4688bb2a-f8fd-49c7-a8b9-bd78f2988302)

2024-06-10 08:51 UTC, ChooSeoyeon commented on README.md
> +- [ ] 테마 별 금액 적용
미션 진행 중 고민이 깊어졌지만, 다른 중요한 요구사항에 우선순위가 밀려 리팩토링 못한 부분들을 적어두었습니다.🥹

2024-06-10 11:54 UTC, ddaaac requested changes
안녕하세요 도라 👋 

구현 잘 해주셨습니다.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-06-10 11:54 UTC, ddaaac commented on src/test/java/roomescape/integration/ReservationWaitingIntegrationTest.java
> +                fieldWithPath("date").description("예약 날짜")
궁금한 점인데 문서화와 관계없이 "timeId": "1"로 요청을 보내는 게 맞는건가요? 아님 "timeId" : 1로 보내는게 맞는건가요?
"1"이면 type이 String이어야하는 것 같고, 1이면 Number가 맞는 거 같아보여서요.

2024-06-10 11:54 UTC, ddaaac commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                        reservationWaitingsWithRank.stream().map(ReservationMineResponse::new)
rank나 payment를 찾아오는 걸 쿼리로 풀려는 이유가 있을까요?
각각 가져와서 서비스단에서 합쳐주는 것과는 어떤 차이가 있을까요?

2024-06-10 11:54 UTC, ddaaac commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
> +    private Reservation reservation;
> 하나의 예약에 여러 회원의 결제 정보가 존재 가능한 테이블 구조를 설계해두었습니다. 
테이블 설계 방향에 맞춰 기존 삭제 로직을 변경(soft delete하도록 변경)하는 편이 좋을까요?

soft delete라고 해도 결제 내역은 지워진 취급을 해야합니다. `@ManyToOne`을 본 다른 개발자는 한 예약에 여러 결제가 있을 수 있다고 생각하지 않을까요?
- 우선 결제 내역을 지우지 말아야할 요구사항을 고민해보면 좋을 것 같아요.
- 이런 경우는 그냥 취소 결제 내역 테이블을 따로 파서 거기다가 저장해도 좋을 것 같기도 하구요.

여튼 soft delete는 인지하기 복잡하기도 하고, 개인정보 이슈가 있을 수도 있습니다. 요구사항이 없다면 구현을 하지 않는 편이 좋아보여요.

2024-06-10 11:54 UTC, ddaaac commented on src/main/java/roomescape/service/reservation/ReservationService.java
>                  = reservationWaitingRepository.findAllWaitingWithRankByMemberId(member.getId());
https://github.com/woowacourse/spring-roomescape-waiting/pull/112#discussion_r1615469581

이 쿼리에 대한 제 생각이에요.

2024-06-10 11:54 UTC, ddaaac commented on src/docs/asciidoc/reservation.adoc
> +operation::reservation-save-success[snippets="http-request,request-fields,http-response,response-fields"]
restdocs로 문서화를 잘 해주셨네요 👍 

201 대신에 성공 이런 제목을 써도 좋을 것 같아요.

2024-06-10 11:54 UTC, ddaaac commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        PaymentConfirmOutput output = paymentClient.confirmPayment(input);
Output보다는 Response 정도가 적당할 것 같아요.

2024-06-10 11:54 UTC, ddaaac commented on README.md
> +- [x] ERD 작성
erd 잘 그려주셨네요 👍

2024-06-10 11:54 UTC, ddaaac commented on src/main/java/roomescape/domain/payment/PaymentInfo.java
> +    private PaymentStatus status;
이 중에는 사용하지 않는 필드도 있어보이는데요, API 응답의 전부를 그대로 저장해주시는 이유가 있을까요?

2024-06-10 11:54 UTC, ddaaac commented on src/test/java/roomescape/helper/domain/DomainSupplier.java
> +    protected MemberFixture memberFixture;
Fixture들을 빈으로 관리해주는 이유가 있을까요?

2024-06-11 02:11 UTC, ChooSeoyeon commented on src/test/java/roomescape/integration/ReservationWaitingIntegrationTest.java
> +                fieldWithPath("date").description("예약 날짜")
`"timeId" : 1` 로 보내길 기대했습니다! 실제로 http 클라이언트를 사용할 때도 Number로 보내고 있었습니다!

2024-06-11 03:24 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        PaymentConfirmOutput output = paymentClient.confirmPayment(input);
- 직렬화/역직렬화 대상이 되는 DTO는 class로 구현한다
    - 네이밍 컨벤션: xxxRequest, xxxResponse
    - 목적: 직렬화/역직렬화에 필요한 코드만 제공하며 동작 원리 학습
- 직렬화/역직렬화 대상이 되지 않는 DTO는 record로 구현한다
    - 네이밍 컨벤션: xxxInput, xxxOutput

위와 같은 팀컨벤션을 정해두어 Output이라 명명했습니다! 직렬화/역직렬화 대상과 아닌 대상을 구분하기 위해 request/response와 input/output으로 차등해 명명합니다! 이상한가요..??

2024-06-11 03:36 UTC, ChooSeoyeon commented on src/main/java/roomescape/domain/payment/PaymentInfo.java
> +    private PaymentStatus status;
현재 API 응답을 로깅하고 있지 않아서 일단 db에 저장해뒀습니다! 

결제 정보는 동일한 상황을 재연하기 어렵기에 당시의 응답값을 로깅의 형태로든, db 컬럼의 형태로든 저장해두어야 합니다. 추후 고객으로부터 자신의 결제에 대한 문의가 들어왔을 때 응대 가능하게 해주고, 토스페이먼츠 측에 API 사용료를 정산할 때 토스페이먼츠 측만의 정보를 믿기보단 저희 측에서 실제 사용한 양을 저장해두는 편이 유리하기 때문입니다.

db에 영구적으로 저장해두기엔 그 성격이 적합하지 않은 데이터들은 로깅하는 방식으로 변경해두겠습니다!

2024-06-11 03:52 UTC, ChooSeoyeon commented on src/docs/asciidoc/reservation.adoc
> +operation::reservation-save-success[snippets="http-request,request-fields,http-response,response-fields"]
이전에 RestDocs로 OAS 문서를 만들고, StopLight로 렌더링해본 경험이 있습니다. 이때 response를 응답값 별로 구분해 문서화하는 걸 보고 Asciidoc 문서에도 이를 적용해보았습니다! 

말씀해주신 대로 성공, 실패 같은 일상어로 문서화하는 방식의 장점은 

201, 401, 404 같은 상태코드로 문서화하는 방식의 장점은

<img width="400" alt="스크린샷 2024-06-11 오후 12 42 52" src="https://github.com/woowacourse/spring-roomescape-payment/assets/83302344/e2299456-9ff8-466f-b3ef-60cd199ff769">

2024-06-12 06:33 UTC, ChooSeoyeon commented on src/test/java/roomescape/helper/domain/DomainSupplier.java
> +    protected MemberFixture memberFixture;
fixture 안에서 빈으로 등록되는 spring data jpa repository를 사용하고 있어 자연스레 fixture들도 빈으로 만들었습니다. 
```
@Component
public class MemberFixture {
    @Autowired
    private MemberRepository memberRepository;
```

1. spring data jpa repository 를 빈으로 등록하지 않고 사용할 방법이 있을까요??
2. 내부에 빈(repository)이 있기 때문에, 해당 클래스(fixture)까지 빈으로 만든단 건 적절한 이유가 되지 못할까요..?

2024-06-12 07:15 UTC, ChooSeoyeon commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
> +    private Reservation reservation;
결제 관련 요구사항을 정리해보면 아래와 같습니다.
- 예약 추가 시 결제를 진행한다
- 예약 취소 시 결제를 취소한다
- 예약 취소 시 대기자가 있다면 대기자가 예약자로 승격되고, 대기자는 기한 내에 결제를 진행한다

2024-06-13 05:33 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/reservation/ReservationService.java
>                  = reservationWaitingRepository.findAllWaitingWithRankByMemberId(member.getId());
`조인 혹은 서브쿼리를 이용한 한방쿼리`보다 `여러 번 나눠 쿼리`하는 게 더 나은 경우도 있군요. 그 차이가 어떤 포인트에서 발생하는지는 아직 잘 모르겠지만, 상황마다 다르다길래 제 코드에서 테스트해보았습니다. 테스트 결과 기존의 한방쿼리보다 여러 번 나눠 쿼리하는 게 더 성능이 좋단걸 알게 되어 여러 번 나눠 쿼리하도록 코드를 변경해주었습니다. 
```
durationSeveralQuery: 12_608_750 ns
durationSingleQuery: 58_698_250 ns
```

데이터가 1000개 일 때 5배~10배 정도 차이나는 걸 확인했는데, 사실 데이터가 워낙 적기도 하고 걸린 실행 시간 자체도 0.01초와 0.05초라는 근소한 차이라 무언가 다른 사소한 요인에 의한 차이일수도 있겠단 생각이 듭니다. 즉, 제가 테스트를 제대로 한 건진 잘 모르겠습니다..

아래 제 테스트코드를 리팩토링한다면 어떤 방향으로 리팩토링해볼 수 있을까요..? 범블비는 `실행 시간 측정을 위한 대용량 데이터 추가`와 `실행 시간 측정` 시 주로 어떤 방식을 사용하시는지도 궁금합니다,, 

```
class QueryTest extends ServiceTest {
    @Autowired
    private ReservationService reservationService;

    @Nested
    @DisplayName("한 방 조인 쿼리 vs 여러 개 쿼리 실행 시간 비교")
    class QueryTimeCompare {
        Member member;

        @BeforeEach
        void setUp() {
            ReservationTime reservationTime = reservationTimeFixture.createFutureReservationTime();
            Theme theme = themeFixture.createFirstTheme();
            member = memberFixture.createUserMember();
            Reservation reservation = reservationFixture.createFutureReservation(reservationTime, theme, member);
            waitingFixture.createDummyWaitings(reservation, memberFixture.createDummyMembers(10)); // repository.saveAll() 이용
            waitingFixture.createWaiting(reservation, member);
        }

        @Test
        void 한_방_조인_쿼리와_여러_개_쿼리_실행_의_시간을_비교한다() {
            long startTimeSingleQuery = System.nanoTime();
            ReservationMineListResponse response = reservationService.findMyReservation(member);
            System.out.println(
                    "response.getReservations().get(1).getStatus() = " + response.getReservations().get(1).getStatus());
            long durationSingleQuery = System.nanoTime() - startTimeSingleQuery;

            long startTimeSeveralQuery = System.nanoTime();
            reservationService.findMyReservationWithSeveralQuery(member);
            long durationSeveralQuery = System.nanoTime() - startTimeSeveralQuery;

            System.out.println("durationSeveralQuery: " + durationSeveralQuery + " ns");
            System.out.println("durationSingleQuery: " + durationSingleQuery + " ns");
        }
    }
}
```

2024-06-13 05:58 UTC, ChooSeoyeon commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                        reservationWaitingsWithRank.stream().map(ReservationMineResponse::new)
쿼리로 한 번에 푸는 것과 각각 가져와서 서비스단에서 합쳐주는 것의 차이는 db 부하냐 애플리케이션 부하냐의 차이라 생각합니다. 둘 중 택해야 하는 상황이라면, db를 여러 대로 확장하는 것보단 애플리케이션 서버를 여러 대로 확장하는 게 더 쉽기에 애플리케이션 부하를 택하는 편이 유리하다 생각합니다.

다만 저는 애초에 부하를 최소화하는 방법은 없을까? 라는 의문이 들었습니다. db 구조에 따라, 짜인 쿼리에 따라 부하가 최소화되지 않을까 싶었습니다. 지금 상황에서 db 구조 변경이나 쿼리 최적화를 어떻게 하면 좋을지는 잘 모르겠습니다만, 좋은 접근일지가 궁금했습니다!

만일 서비스단에서 합칠 데이터가 매우 많아서 애플리케이션 서버가 터지는 상황이 왔을 때, 범블비는 어떤 방식을 택하시는지 궁금합니다! 애플리케이션 서버를 스케일업하는 것밖에 방법이 없는걸까요??

2024-06-13 09:39 UTC, ChooSeoyeon commented
안녕하세요 범블비! 도라입니다!

로깅 관련해 트러블 슈팅이 오래 걸렸어서 리뷰 요청이 늦어졌습니다... 죄송합니다.
궁금한 게 많았어서 질문이 몇 가지 있습니다,, 마지막까지 잘 부탁드립니다!!

2024-06-13 11:07 UTC, ChooSeoyeon commented on src/main/java/roomescape/config/payment/ClientHttpResponseWrapper.java
> +        return new ByteArrayInputStream(body);
ClientHttpResponse.getBody 가 inputStream 으로 제공되는데,
inputStream은 한 번 사용하고 나면 재사용이 불가해
RestClient `인터셉터`와 `post 요청 보내는 곳` 두 곳에서 이를 함께 사용하는 것이 불가했습니다.
(전제 조건: 인터셉터에서 ClientHttpResponse body의 로깅을 하고 싶은 상황입니다)
```
private RestClient createRestClient() {
        return RestClient.builder()
                .requestInterceptor(new PaymentClientLoggingInterceptor())
                .build();
    }
```

```
public PaymentConfirmOutput confirmPayment(PaymentConfirmInput paymentConfirmInput) {
        return restClient.method(HttpMethod.POST)
                .uri("/confirm")
                .contentType(MediaType.APPLICATION_JSON)
                .body(paymentConfirmInput)
                .retrieve()
                .onStatus(new PaymentConfirmResponseErrorHandler())
                .body(PaymentConfirmOutput.class); 
// PaymentClientLoggingInterceptor 에서 ClientHttpResponse.getBody를 로깅을 위해 꺼내쓰면, 이 곳에선 꺼내 쓸 게 없어 null이 반환됨
    }
```

따라서 inputStream 을 사용하고 얻은 값을 저장해뒀다가 
필요한 상황에 새로운 inputStream을 만들어 반환해주는 해당 클래스를 만들어 사용했습니다.

크루들과의 논의를 통해 얻은 신박한 방법이지만, 
외부에서 받은 HttpResponse를 커스텀한단 점에서 저희가 고려 못한 사이드 이펙트가 있진 않을지 궁금합니다!

2024-06-13 12:31 UTC, ddaaac approved these changes
안녕하세요 도라 👋 

리뷰 반영 잘 해주셨습니다.

이번 미션은 여기서 머지할게요. 고생 하셨습니다!

2024-06-13 12:31 UTC, ddaaac commented on src/main/java/roomescape/domain/payment/ReservationPayment.java
> +    private Reservation reservation;
우선, 다시 한 번 말씀드리면 soft delete라고 해도 결제 내역은 지워진 취급을 해야합니다.
고객 cs가 오지 않는 이상 볼 일이 없어야겠죠.

만약 예약 정보를 포함한 취소된 결제 내역을 봐야하는 요구사항이 생긴다면 따로 테이블을 만들 것 같습니다. 따로 데이터를 보관하는 비용이 soft delete 구현에서 오는 부조화를 견뎌야하는 비용보다 훨씬 저렴할 것 같아요. 일정 기간이 지나면 지우기도 편할 것 같구요.

2024-06-13 12:31 UTC, ddaaac commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +                        reservationWaitingsWithRank.stream().map(ReservationMineResponse::new)
우선, 성능 관점에서 남긴 코멘트는 아니었어요. 요구사항이 변경되었을 때 쿼리를 수정하는 것과 어플리케이션 코드를 수정하는 것이 어떤 차이가 있을지 생각해보면 좋을 것 같아서 남긴 코멘트였습니다.
어플리케이션이 터진다고 하시는 상황이 너무 많은 데이터를 불러서 메모리 힙이 터지는 상황을 말씀하시는 게 맞을까요? 그렇다면 단순히 나눠서 몇 번에 걸쳐 쿼리하면 되는 것 같아요. 
그런데 몇백만 건 정도의 데이터를 한 번에 불러와야 메모리가 터질 것 같은데, 그 정도 데이터면 애초에 db 쿼리에서 타임아웃이 날거에요. 어차피 나눠서 불러오게 되어있습니다.

2024-06-13 12:31 UTC, ddaaac commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        PaymentConfirmOutput output = paymentClient.confirmPayment(input);
input/output 으로 명명된 클래스들도 client를 거치면서 직렬화/역직렬화 과정을 거치지 않나요...?
그 외에 페어와 정한 컨벤션이 있다면 지키는 건 얼마든지 좋은 것 같네요.

2024-06-13 12:31 UTC, ddaaac commented on src/test/java/roomescape/helper/domain/DomainSupplier.java
> +    protected MemberFixture memberFixture;
아하 저장까지 하는군요. 단순히 객체 정도만 생성하는 줄 알았어요.

조금 번거로워도 테스트 별로 필요한 데이터들만 저장하는 건 어떨까 싶긴해요. 저렇게 fixture에서 많은 데이터들을 저장하고 있으면 테스트 코드만 보고 어떤 테스트인지 파악하기 쉽지 않을때도 많아요. 최대한 하나의 테스트 코드만 보고도 그 테스트의 의미를 빠르게 파악할 수 있으면 좋을 것 같네요.

2024-06-13 12:31 UTC, ddaaac commented on src/main/java/roomescape/service/reservation/ReservationService.java
>                  = reservationWaitingRepository.findAllWaitingWithRankByMemberId(member.getId());
여기도 마찬가지로 성능보다는 요구사항이 변경되었을 때 쿼리의 변경과 코드의 변경 관점을 우선으로 생각해보시면 좋을 것 같네요. 이전 코멘트의 성능 관련 코멘트는 서브 쿼리 때문에 남긴 거긴 합니다.

또, xxxRepository는 xxx에 대한 Collection 개념 쯤으로 생각해두시면 좋을 것 같아요. xxxCollection에서 xyz 가 반환되면 어색하겠죠.

별개로 실행 시간을 직접 테스트해본 점은 좋네요 👍 
보통은 인덱스 타는 지 여부 정도 체크하고 넘기고, 시간을 따져봐야한다면 도라가 남겨주신 것처럼 비교하며 테스트하겠죠.

2024-06-13 12:31 UTC, ddaaac commented on src/main/java/roomescape/domain/payment/PaymentInfo.java
> +    private PaymentStatus status;
보통 로그는 롤링 방식으로 관리하기 때문에 시간이 지난 로그는 제거하는 게 보통입니다. 지우지 않고 관리하기에는 로그 양이 너무 많거든요.
만약 평생 갖고 있어야 할 정보라고 판단하셨다면 db에 저장하는 게 나을 것 같아요.

2024-06-13 12:31 UTC, ddaaac commented on src/test/java/roomescape/integration/ReservationWaitingIntegrationTest.java
> +                fieldWithPath("date").description("예약 날짜")
그렇다면 테스트의 요청 body가
Body:
{
    "date": "2000-04-08",
    "timeId": 1,
    "themeId": 1
}

Number 타입으로 가게 하면 되지 않을까요? 지금은 항상 String으로 고정되어있는 것 같네요. Object를 활용해보면 좋을 것 같아요.

별개로 String으로 온 문자열을 알아서 Long으로 바꿔주는군요... 이건 처음 알았네요.

2024-06-13 12:31 UTC, merged

2024-06-13 14:06 UTC, ChooSeoyeon commented on src/test/java/roomescape/integration/ReservationWaitingIntegrationTest.java
> +                fieldWithPath("date").description("예약 날짜")
테스트코드에서 쓰는 요청 body만 잘 바꿔줘도 표현 가능하겠군요! 좋네요!