방탈출 결제 / 배포 2 - 4단계] 카피(김상혁) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #148
Opened 2024-06-10 07:53 UTC by tkdgur0906

안녕하세요 찰리~ 카피입니다!
이번 미션은 구현 자체는 어렵지 않았지만 설계에 대한 고민을 꽤 했던 것 같습니다!

[배포 서버](http://54.180.201.172:8080)
[API 문서](http://54.180.201.172:8080/swagger-ui/index.html)

API 문서 작성 도구는 **swagger**를 사용했습니다!
rest docs도 고려해봤지만, 테스트 코드가 필수로 존재해야하기 때문에 적용에 시간이 걸릴 것 같아 간단하게 적용할 수 있는 swagger를 사용하였습니다.

2024-06-11 11:43 UTC, Gomding requested changes
안녕하세요 카피!
미션 깔끔하게 진행해주셨네요 😌
의견 나눠보고 싶은 부분에 코멘트 남겼으니 확인해주세요!

궁금한 점 있으면 언제든 DM이나 코멘트 남겨주세요🙌

2024-06-11 11:43 UTC, Gomding commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
> API 문서 작성 도구는 swagger를 사용했습니다!
> rest docs도 고려해봤지만, 테스트 코드가 필수로 존재해야하기 때문에 적용에 시간이 걸릴 것 같아 간단하게 적용할 수 있는 swagger를 사용하였습니다.

손으로 직접 작성하지 않고 도구를 사용한 점 👍 👍 👍 
말씀해주신대로 rest docs 의 단점은 `테스트 코드가 필수로 존재해야하기 때문에 적용에 시간이 걸릴 것 같아` 이것일것 같네요 :)
반대로 테스트 코드가 필수다 라는 부분이 장점이 될 수도 있구요! ㅎㅎ

Swagger 를 실제로 사용할 때 어떤 장단점이 느껴졌는지 궁금해요!

2024-06-11 11:43 UTC, Gomding commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +            Payment payment = paymentService.confirm(ConfirmPaymentRequest.from(createReservationRequest));
트랜잭션 내부에 외부 API 호출이 있으면 어떤 문제가 있을지 고민해보면 좋겠어요!
외부 API 호출 시간이 길어지면 어떤 일이 발생할까요 🤔

2024-06-11 11:43 UTC, Gomding commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @Operation(summary = "예약 삭제 API")
API 문서를 잘 작성해주신것은 좋아요!
토스 API 문서를 보셨겠지만 API 문서에는 성공하는 케이스를 명시하는것도 좋지만
호출하는 쪽에서 에러 핸들링할 수 있도록 에러에 대한 응답을 잘 명시하는것도 중요하다 생각해요!
에러 케이스도 문서에 포함해보면 좋곘어요 :)

2024-06-11 11:43 UTC, Gomding commented on docs/erd.png
데이터베이스의 ERD 로 테이블 정보를 잘 표현해주셨네요 👍

2024-06-11 11:43 UTC, Gomding commented on docs/erd.png
> Payment 테이블을 추가할 때 어떻게 설계해야 할지 고민했습니다.
> 우선 Reservation에 필드를 추가하는 방식과 테이블을 분리하는 방식을 고민했습니다.
> 결제 정보는 추가될 필드도 많고 카카오 결제 같은 방식이 추가됐을 때 테이블을 분리하는 것이 대응하기 좋을 것 이라 생각했습니다.
> 
> 다음으로 Reservation, Payment 를 일대일로 매핑하는데 외래키를 어느 쪽에서 들고 있을지 고민을 했습니다.
> 현재 결제 페이지도 없고 결제를 기준으로 조회하는 api도 없습니다.
> 따라서 예약 엔티티를 기준으로 주로 사용하기 때문에 외래키를 Reservation에 두었습니다.
> 
> 다만 다른 크루들의 이야기를 들어보면 Payment에 외래키를 두기도 하였는데, 아직 완벽하게 저의 의견을 피력하기 어려운 것 같습니다.
> 찰리라면 어떻게 설계하실 것 같고 그 이유에 대해 듣고 싶습니다!

우선 예약과 결제의 생명주기에 대해서 말해보면 좋을것같아요 :)
- 예약이 없는 결제가 존재할 수 있는가?
- 결제가 없는 예약은 존재할 수 있는가?


+) 서비스가 발전하여 예약 하나에 여러 결제가 생기는 구조(보증금 결제 + 잔금결제) 라면 어떻게 설계하는것이 유리할까요?

2024-06-11 11:43 UTC, Gomding commented on src/main/java/roomescape/payment/model/Payment.java
> +    private Long totalAmount;
결제 승인 API [응답에는 여러 값들](https://docs.tosspayments.com/reference#payment-객체)이 있는것으로 알아요!
이 중에서 아래 3가지 값을 매핑한 이유가 궁금해요!
- paymentKey
- orderId
- totalAmount

어떤 필요에 의해서 가져온 값인지?
어떻게 사용되는지 궁금해요 ㅎㅎ

2024-06-11 11:43 UTC, Gomding commented on src/main/java/roomescape/payment/model/Payment.java
> +    protected Payment() {
기본 생성자 protected 접근 제한자로 지정해주셨군요 👍

2024-06-11 11:43 UTC, Gomding commented on src/main/java/roomescape/payment/model/Payment.java
> +        return Objects.equals(id, payment.id);
엔티티는 id로 동등성 비교 👍 👍 👍

2024-06-12 07:07 UTC, tkdgur0906 commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
예전에 Swagger를 사용해본 적이 있는데 개인적으로 선호하진 않습니다!
이유는 작성해야할 api 문서의 정보가 많아질 경우에 프로덕션 코드에 많은 양의 추가 코드를 작성하야 하기 때문입니다.
컨트롤러에 어노테이션이 덕지덕지 붙어있는게 저는 별로 마음에 들지 않았습니다.

다만 Swagger 의존성만 추가해주면 자동으로 API 문서를 만들어 주고 사용방법만 알면 쉽게 사용할 수 있다는 게 장점이라고 생각합니다!

2024-06-12 07:27 UTC, tkdgur0906 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +            Payment payment = paymentService.confirm(ConfirmPaymentRequest.from(createReservationRequest));
트랜잭션에 외부 api 호출이 포함된 경우 외부 api 응답이 오지 않으면 대기하게 됩니다. 만약 db연결 코드가 있어 커넥션을 가지고 있게 되면 커넥션을 외부 api 응답이 오고 트랜잭션이 끝날 때 까지 가지고 있게 됩니다.
이런 상황을 피하기 위해 트랜잭션 내부에는 api 호출을 두지 않는 것이 좋다고 합니다!

현재 코드의 구조는 예약을 저장-> 결제 -> 예약에 결제 정보 업데이트의 과정으로 진행됩니다.
기존의 코드에서 결제 정보를 db에 저장하도록 수정했는데 `createMyReservationWithPayment`에 트랜잭션을 걸어주지 않으면 이미 `assignPayment`를 호출해도 트랜잭션이 끝났기 때문에 update 쿼리가 나가지 않았습니다.
그래서 현재로서는 다른 방안이 생각나지 않아 우선 트랜잭션 내부에 외부 api 호출을 넣어놨습니다!

다른 해결방안이 있을까요?

2024-06-13 06:23 UTC, tkdgur0906 commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @Operation(summary = "예약 삭제 API")
동의합니다! 정상케이스와 에러케이스 모두 api 문서에 포함되어 있어야 api 문서로의 역할을 제대로 할 수 있을 것 같습니다. 추가해주었습니다!

다만 역시나 프로덕션 코드가 너무 지저분해졌는데 Swagger를 쓰는 이상 어쩔 수 없는 부분인건가요?

2024-06-13 06:28 UTC, tkdgur0906 commented on src/main/java/roomescape/payment/model/Payment.java
> +    private Long totalAmount;
우선 3가지를 가져온 이유는 LMS에 적혀있는 api request에 해당 값 3개만 넘어오기 때문입니다.
미션이 아닌 실제 서비스에서 저희가 어떤 값을 매핑할지 정해야 하는 경우에는 많은 반환 값들 중에 직접 선택해야할 것 같습니다!

2024-06-13 06:36 UTC, tkdgur0906 commented on docs/erd.png
현재 서비스에서는 예약이 있어야만 결제가 존재합니다.
하지만 결제가 없어도 관리자가 직접 예약을 할 수 있습니다!

>  서비스가 발전하여 예약 하나에 여러 결제가 생기는 구조(보증금 결제 + 잔금결제) 라면 어떻게 설계하는것이 유리할까요?

만약 현재의 구조에서 여러 결제가 생기는 경우에 예약 하나가 여러 결제정보를 가지게 될 수 있습니다.
그러면 예약이 결제를 가지고 있는 현재 구조보다 결제가 예약을 가지고 있는 구조로 설계하는게 유리할 것 같습니다!
이런 측면으로 생각하니 후자가 좋은 것 같기도 합니다..?

2024-06-13 16:02 UTC, Gomding requested changes
안녕하세요 카피!
API 문서까지 꼼꼼하게 수정해주셨네요 👍 
추가로 몇가지 의견 남겼으니 확인해주세요 :)
다음 요청에는 머지할 것 같아요 ㅎㅎ
마지막까지 화이팅입니다 💪

2024-06-13 16:02 UTC, Gomding commented on src/main/java/roomescape/reservation/controller/AdminReservationController.java
> +                    """, content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
에러 응답 추가 쉽지않았을텐데 고생하셨어요! 👍 👍 👍 

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/57378410/38ea5084-2ddb-4e6a-bdfe-f0f6a4291a81)

2024-06-18 09:03 UTC, tkdgur0906 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +            Payment payment = paymentService.confirm(ConfirmPaymentRequest.from(createReservationRequest));
글 잘 읽었습니다!
애초에 트랜잭션을 외부 API로 묶은 이유가 예약과 결제정보를 db에 저장한 후 더티체킹으로 예약에 결제 정보를 저장하기 때문인데, 결제가 예약을 가지고 있도록 구조를 바꾸니 예약 생성(트랜잭션) -> 결제 정보 생성을 하면서 트랜잭션을 분리할 수 있었습니다!

2024-06-18 09:05 UTC, tkdgur0906 commented on docs/erd.png
이제 다른 사람에게 설명할 수 있는 명확한 이유가 생긴 것 같습니다😀
결제가 예약을 가지게 하도록 수정하였습니다!

2024-06-18 11:04 UTC, tkdgur0906 commented on src/main/java/roomescape/payment/model/Payment.java
> +    private Long totalAmount;
결제 정보를 저장할 때 같은 예약에 대해서도 여러가지의 결제 상태가 있을 수 있겠네요!
결제 db에 status도 같이 저장하여 관리해주도록 하였습니다!
또한 결제 상태가 승인이 되지 않았을 때 예약을 삭제하도록 기능을 추가하였습니다!

2024-06-18 11:09 UTC, tkdgur0906 commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    @Operation(summary = "예약 삭제 API")
api 문서 쪽도 공부할 부분이 많은 것 같네요😂
일단 기억해놓고 나중에 학습해보도록 하겠습니다!

2024-06-18 11:11 UTC, tkdgur0906 commented on build.gradle
>      implementation 'javax.xml.bind:jaxb-api:2.4.0-b180830.0359'
지금은 정상적으로 통과하는 것 같은데 다시 실패하면 말씀해주세요!

2024-06-19 13:42 UTC, Gomding approved these changes
안녕하세요 카피!
이번 미션 고생하셨어요 🙌
마지막으로 코멘트 하나 남기면서 이만 merge 하겠습니다~!
방학 잘 보내시고 다음 레벨도 화이팅입니다 🎉 🎉 🎉

2024-06-19 13:42 UTC, Gomding commented on src/main/java/roomescape/reservation/service/ReservationService.java
>          Reservation reservation = createReservation(createReservationRequest);
ReservationService 빈의 메서드 내부에서 ReservationService 의 내부 메서드를 호출하면  `@Transactional` 이 동작할지 고민해볼 수 있겠어요 :)
부가 설명을 하면 `createMyReservationWithPayment` 내부에서 `createReservation(@Transactional 사용)` 을 호출하고 있죠?!
과연 내부에서 호출하는 createReservation의 `@Transactional` 이 올바르게 동작하고 있을까요?

조금 어려운 개념일 수 있는데
이해한다면 스프링의 동작도 이해할 수 있어서 아래 글을 참고해보면 좋겠어요!

- [Spring 동일한 Bean(Class)에서 @Transactional 동작 방식](https://cheese10yun.github.io/spring-transacion-same-bean/)

2024-06-19 13:42 UTC, merged