[ 2 - 4단계 방탈출 결제 / 배포 ] 초롱(정회성) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #149
Opened 2024-06-10 07:57 UTC by HoeSeong123

안녕하세요 조앤! 늦었지만 두 번째 리뷰요청 드립니다!!

어느새 마지막 리뷰 요청이네요😭
저는 아직도 말하는 감자에 불과한데 언제 시간이 이렇게 흘렀을까요...
이제 레벨 2를 마무리하고 프로젝트에 뛰어들어야 한다는 사실이 정말 믿기지가 않네요 하하
그래도 마지막까지 힘내서 열심히 해보겠습니다!!😄

마지막 리뷰 요청 잘 부탁드립니다!!

# API 문서화
api 문서화 도구로 swagger를 사용하였습니다!!
RestDoc과 Swagger 둘 중에서 고민을 하였지만 시간 상의 이유로 swagger를 사용하게 되었습니다😢
만약 시간이 허락해준다면 RestDoc을 사용하도록 변경해보고자 합니다!!

[배포 링크](http://43.202.37.167:8080/)
[API 문서화 링크](http://43.202.37.167:8080/swagger-ui/index.html)

<img width="404" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/125939503/fa6f25cd-b1dd-4c50-b0cc-a6d473e713c6">

2024-06-10 11:15 UTC, seovalue requested changes
안녕하세요 초롱~
미션 잘 수행해주셨네요ㅎㅎ
몇가지 코멘트 남겼는데 확인 후 리뷰 요청 주세요!

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/auth/controller/AuthController.java
>  @RestController
<img width="1624" alt="Screenshot 2024-06-10 at 20 04 18" src="https://github.com/woowacourse/spring-roomescape-payment/assets/48412963/1d76ca67-0832-4275-a60d-950618565f8b">

회원가입 후 로그인을 하려고 하는데 안되네요..ㅎㅎ

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/global/config/SwaggerConfig.java
> +public class SwaggerConfig {
시간이 허락한다면 RestDocs로 변경하고 싶으신 이유는 뭐예요?

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +                       @PathVariable("id") @Min(1) long reservationId) {
Min을 사용하시는 이유가 궁금해요~

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/Payment.java
> +    private String approvedAt;
각 컬럼들을 추가하기로 설계해주신 이유가 궁금해요~
그리고 모두 nullable한 것도요!

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        if (member.getRole() == Role.USER && !Objects.equals(payment.getTotalAmount(), AMOUNT)) {
```suggestion
        if (member.isUser() && !payment.hasSameAmount(AMOUNT)) {
```

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/PaymentRepository.java
> +
불필요한 line?

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/repository/ReservationRepository.java
>      int findMyWaitingOrder(Long reservationId);
이건 이번 미션과는 별개긴 한데요ㅎㅎ
이 쿼리의 부하가 어느정도일까요? 
서브쿼리를 줄여볼 순 없을까요?

2024-06-10 11:15 UTC, seovalue commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                "adminApprovedAt");
필요한 이유가 궁금해요~
그리고 이런 static한 값은 Payment.admin() 이렇게 Payment 내부에 정의되어있어도 될 것 같아요.

2024-06-10 11:15 UTC, seovalue commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS payment
이 schema와 실제 Payment entity에 정의된 스키마가 같나요?

2024-06-10 11:15 UTC, seovalue commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
>      @DisplayName("예약 생성에 성공한다.")
추가된 결제 정보도 조회하는 테스트는 어디에 있나요?

2024-06-10 11:15 UTC, seovalue commented on README.md
> +### 필수 요구사항
aws 인스턴스에 배포하신 과정을 한번 설명해주세요~

2024-06-12 02:21 UTC, HoeSeong123 commented on src/main/java/roomescape/auth/controller/AuthController.java
>  @RestController
확인해봤는데 제가 했을 때는 잘 되는 것 같아서 혹시 다시 한 번 확인해주실 수 있을까요?😥

2024-06-12 02:25 UTC, HoeSeong123 commented on src/main/java/roomescape/global/config/SwaggerConfig.java
> +public class SwaggerConfig {
가장 큰 이유는 프로덕션 코드에 영향을 주지 않는다는 점입니다.
또한, RestDocs를 사용하려면 테스트 코드를 필수로 작성해야 하는 것으로 알고 있는데 TDD를 강조하고 있는 우테코의 교육 환경과 잘 어울린다고 생각했기 때문입니다.

그리고 이건 개인적인 생각이지만 RestDocs를 사용한 크루들의 UI를 확인해봤는데 더 깔끔한 것 같다는 느낌을 받았습니다😂

2024-06-12 04:29 UTC, HoeSeong123 commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +                       @PathVariable("id") @Min(1) long reservationId) {
해당 부분은 제가 작성한 코드는 아니여서 Min 어노테이션에 대해 찾아보았습니다.
제가 생각한 이유는 다음과 같습니다.

만약 Min이 없다면 삭제 요청시에 id에 0 이하의 값이 들어와도 아무런 값도 삭제되지 않고 에러도 발생하지 않습니다.
이를 방지하기 위해 0 이하의 값이 들어오면 에러가 발생하도록 해서 잘못된 값에 대해 제어할 수 있도록 한 것 같습니다.

2024-06-12 04:53 UTC, HoeSeong123 commented on src/main/java/roomescape/reservation/domain/Payment.java
> +    private String approvedAt;
제가 생각했을 때 가장 기본적으로 있어야 할 정보들이라고 생각했습니다.
paymentKey, orderId는 결제를 식별하는 역할을 하기 때문에 반드시 필요하고, 그 외의 내용들은 어떤 payment 값을 봤을 때 해당 payment가 어떤 것을 구매했고, 얼마를 구매했고, 언제 구매했는지 등을 파악할 수 있는 최소한의 정보들이라고 생각하여 추가해주었습니다.

nullable한 부분은 제가 hibernate의 ddl-auto 설정을 none으로 하고, 직접 테이블을 설계해주었는데 테이블을 설계할 때 NOT NULL 제약 조건을 적어주어서 프로덕션 코드에서는 별도로 작성하지 않았습니다.
하지만 생각해보니 그렇다고 하더라도 프로덕션 코드에도 추가해주는 게 맞는 것 같네요😅

2024-06-12 06:15 UTC, HoeSeong123 commented on src/main/java/roomescape/reservation/domain/repository/ReservationRepository.java
>      int findMyWaitingOrder(Long reservationId);
WHERE 절이 AND로 묶여있는데 각각이 서브쿼리로 작성되어 있어 많은 쿼리가 나갈 것으로 예상됩니다.
따라서 서브 쿼리를 한 번만 사용하는 방향으로 수정해보았습니다!!

2024-06-12 06:19 UTC, HoeSeong123 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                "adminApprovedAt");
해당 값이 없으면 Reservation 테이블의 payment 필드에 not null 제약 조건을 추가할 수 없어서 임의의 payment를 생성하도록 구현하였습니다.
추가로 payment 필드에 not null 제약 조건이 빠져있어서 추가해주었습니다.

2024-06-12 06:45 UTC, HoeSeong123 commented on src/test/java/roomescape/reservation/service/ReservationServiceTest.java
>      @DisplayName("예약 생성에 성공한다.")
테스트 코드 추가하는 것을 깜빡했네요..🥲바로 추가했습니다!!

2024-06-12 07:19 UTC, HoeSeong123 commented on README.md
> +### 필수 요구사항
제가 질문의 의도를 제대로 이해했는지 모르겠습니다!! 우선 제가 이해한대로 답변드리겠습니다. 혹시 잘못된 부분이 있다면 말씀해주시면 감사드리겠습니다!!

- 우선 아래와 같은 설정으로 aws ec2 인스턴스를 생성하였습니다.
  - 애플리케이션 및 OS 이미지: Ubuntu Server 24.04
  - 아키텍처: 64비트(Arm)
  - 인스턴스 유형: t4g.micro
- 그 후에는 ssh를 이용하여 ec2에 접속하였습니다.
- 이후 git에서 pull을 받은 후에 build하고, 생성된 jar 파일을 이용하여 애플리케이션을 실행시켰습니다

2024-06-12 07:20 UTC, HoeSeong123 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        if (member.getRole() == Role.USER && !Objects.equals(payment.getTotalAmount(), AMOUNT)) {
이런 부분은 레벨 1에서 충분히 배운 부분인데 아직도 실수를 하네요..😥

2024-06-13 08:33 UTC, seovalue commented on src/main/java/roomescape/auth/controller/AuthController.java
>  @RestController
오옹 이젠 잘되네요!

2024-06-13 08:34 UTC, seovalue commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +                       @PathVariable("id") @Min(1) long reservationId) {
오우 굿굿 초롱이 작성하신 부분 아닌데 찾아봐주신게 넘 좋네요.
👍

2024-06-13 08:37 UTC, seovalue commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                "adminApprovedAt");
불필요한 값이 들어가있는것과 nullable 한 것 간의 트레이드오프인 것 같아요ㅎㅎ

null이 들어가있는 경우와, 임의의 값이 들어가있는 경우를 데이터 관점에서 봤을 때 어떤게 더 나을까요? 어떻게 생각하시나요!

2024-06-13 08:45 UTC, seovalue approved these changes
안녕하세요 초롱~ 리뷰가 늦어져 죄송해요😢
남겨주신 코멘트에 몇가지 코멘트만 추가로 답변 남겨봤어요ㅎㅎ
이번 단계는 여기서 마무리해도 될 것 같아서~ 미션은 머지할게요!
고생 많으셨어요! 👍

2024-06-13 08:45 UTC, seovalue commented on src/main/java/roomescape/member/domain/Member.java
> +    @NotNull
흠. 이건 Validation의 notnull 아닌가요?
컬럼 제약조건으로 not null을 걸려면 @Column(nullable=false)로 해줘야하지 않을까요?

2024-06-13 08:45 UTC, seovalue commented on src/main/java/roomescape/reservation/service/WaitingReservationService.java
> +            return ReservationViewResponse.from(reservationWithStatus, waitingCount + 1);
0부터 시작이라 +1한건가요?

2024-06-13 08:45 UTC, merged