[1단계 방탈출 결제 / 배포] 잉크(이예찬) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #15
Opened 2024-05-29 07:50 UTC by yechop

2024-05-30 10:57 UTC, summerlunaa requested changes
잉크 안녕하세요~ 리뷰어 파랑입니다 🐳

오랜만에 뵙네요ㅎㅎ 1단계 빠르게 잘 구현해주셨습니다. 외부 API 연동 위주로 코멘트 남겼으니 확인 부탁드립니다.

궁금한 점 있으면 편하게 DM 주셔도 괜찮아요. 파이팅 💪

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    String authorizations;
```suggestion
    private final String authorizations;
```

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    @Value("${security.api.toss.secret-key}")
properties 파일로 key를 잘 분리해주셨네요 👍

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    private final RestClient restClient;
RestClient를 선택하신 이유가 궁금합니다 :)

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +        } catch (HttpClientErrorException e) {
HttpClientErrorException 외의 예외가 발생는 경우는 없나요? 발생하는 경우 어떻게 처리되나요?

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/config/AdminAuthInterceptor.java
>              throws Exception {
```suggestion
             {
```

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/exception/RoomescapeExceptionHandler.java
> +        e.printStackTrace();
디버깅용인가요?

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/exception/RoomescapeExceptionHandler.java
> +        return ResponseEntity.status(e.getHttpStatusCode())
tossPay에서 받은 statusCode를 똑같이 내려주는 이유가 궁금합니다. 
토스에서 어떤 경우 400을 주는지 확인해보니 아래와 같은 에러들도 있더라구요! 이런 것도 400 Bad Request 처리하는 게 맞을지 고민해보면 좋을 것 같습니다.

<img width="616" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/77425729/35b10b2e-61a7-4cab-b59a-88d56be4e5bd">

2024-05-30 10:57 UTC, summerlunaa commented on src/test/java/roomescape/service/FakePayment.java
> +public class FakePayment implements PaymentClient {
Fake 객체 잘 만들어서 테스트에 사용해주셨네요 👍

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    public void pay(PaymentRequest paymentRequest) {
잉크는 개발 과정에서 toss pay API 호출이 잘 되는지 어떻게 테스트 해봤는지 궁금합니다!

2024-05-30 10:57 UTC, summerlunaa commented on src/main/java/roomescape/config/PaymentConfig.java
> +        return new TossPaymentClient(RestClient.builder().baseUrl("https://api.tosspayments.com").build());
보통 URL은 properties나 yml 파일에서 관리하는데요, 환경변수를 사용하면 어떤 이점을 얻을 수 있는지 공부해봐도 좋겠네요 👍

2024-05-31 07:26 UTC, yechop commented on src/main/java/roomescape/api/TossPaymentClient.java
> +        } catch (HttpClientErrorException e) {
토스에서 던지는 예외 클래스인 HttpServerErrorException 를 추가로 잡아주었고 그 외 알 수 없는 오류를 고려해 Exception catch까지 추가헀습니다

2024-05-31 07:29 UTC, yechop commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    @Value("${security.api.toss.secret-key}")
리뷰요청 드릴 당시엔 잘 작동하는 것 같았는데, 지금 돌려보니 secret-key가 null인 상태로 생성자에서 authorizations 을 생성하느라 시크릿키 오류가 발생했습니다.
시크릿 키를 생성자 파라미터를 통해 주입받도록 변경했습니다!

2024-05-31 07:50 UTC, yechop commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    private final RestClient restClient;
미션에서 던져준 키워드 RestClient, WebClient, RestTemplate 의 각 특징들을 찾아봤습니다.
특징들이 잘 와닿지는 않았지만 RestClient 의 단점이 가장 적다고 판단되어 사용했습니다.
하나라도 사용에 익숙해지면 교체하는건 쉬울 것 같아 깊게 고민하고 선택하지는 않았습니다!

2024-05-31 08:00 UTC, yechop commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    public void pay(PaymentRequest paymentRequest) {
paymentKey 를 알 수가 없어서 toss pay API 의 호출은 테스트코드를 작성하지 못했습니다.
어플리케이션을 실행시켜 직접 QR을 찍어보는 방법 밖에 찾지 못했습니다.
테스트 해볼 수 있는 방법이 있을까요??

2024-05-31 08:01 UTC, yechop commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    public void pay(PaymentRequest paymentRequest) {
> 잉크는 개발 과정에서 toss pay API 호출이 잘 되는지 어떻게 테스트 해봤는지 궁금합니다!

paymentKey 를 알 수가 없어서 toss pay API 의 호출은 테스트코드를 작성하지 못했습니다.
어플리케이션을 실행시켜 직접 QR을 찍어보는 방법 밖에 찾지 못했습니다.
테스트 해볼 수 있는 방법이 있을까요??

2024-05-31 08:30 UTC, yechop commented on src/main/java/roomescape/exception/RoomescapeExceptionHandler.java
> +        e.printStackTrace();
printStackTrace 가 보안상 좋지 않나보네요! 로그를 사용해 에러를 추적하도록 변경했습니다

2024-05-31 10:31 UTC, yechop commented on src/main/java/roomescape/config/PaymentConfig.java
> +        return new TossPaymentClient(RestClient.builder().baseUrl("https://api.tosspayments.com").build());
환경변수 파일로 관리하면 설정을 한눈에 파악할 수 있고 프로젝트 전역에서 사용 가능하며 손쉽게 변경이 가능합니다.
시크릿 키 처럼 숨겨야 하는 정보들을 드러내지 않을 수 있는 점도 좋은 것 같습니다

2024-05-31 11:19 UTC, yechop commented on src/main/java/roomescape/exception/RoomescapeExceptionHandler.java
> +        return ResponseEntity.status(e.getHttpStatusCode())
> tossPay에서 받은 statusCode를 똑같이 내려주는 이유가 궁금합니다. 토스에서 어떤 경우 400을 주는지 확인해보니 아래와 같은 에러들도 있더라구요! 이런 것도 400 Bad Request 처리하는 게 맞을지 고민해보면 좋을 것 같습니다.
> 
> <img alt="image" width="616" src="https://private-user-images.githubusercontent.com/77425729/335151233-35b10b2e-61a7-4cab-b59a-88d56be4e5bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDAxMjgsIm5iZiI6MTcxNzEzOTgyOCwicGF0aCI6Ii83NzQyNTcyOS8zMzUxNTEyMzMtMzViMTBiMmUtNjFhNy00Y2FiLWI1OWEtODhkNTZiZTRlNWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA3MTcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZDA4MjAzYzExZjZhNDRlMjBmNGNlNzc1YjA4NjkwZTdjNzFlNmYwOWVmMzRiNTA1OGFkYWU4MzJhNWFjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RM35Qdswo7BSq9RSw1mFAyfz-FTK9_BC4y79bSJC5rY">

상태코드를 그대로 내려주면 요청 자체가 잘못되었다 생각할 수 있겠네요. 하나로 통일해서 줄 필요가 있을 것 같습니다. 
클라이언트 입장에서 생각해보면 요청을 보낸 서버의 문제인지 서버를 통한 외부 api 의 문제인지 몰라도 되니 500번대가 적합해 보입니다. 다만 500번대를 살펴보아도 딱 맞는 상황을 찾지 못했습니다.
하나로 통일해주는게 괜찮다면, 파랑은 어떤 상태코드가 적절하다고 생각하시나요?

2024-06-01 15:35 UTC, summerlunaa requested changes
잉크 안녕하세요~

리뷰 잘 반영해주셨습니다. 몇 가지 리뷰 더 남겨드렸으니 확인 부탁드려요! 대부분 잘 구현해주셔서 다음 리뷰 요청에서는 바로 머지하겠습니다 👍

2024-06-01 15:35 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    @Value("${security.api.toss.secret-key}")
넵 리뷰 드리지 않은 부분도 잘 챙겨주셨네요 👍

2024-06-01 15:35 UTC, summerlunaa commented on src/main/java/roomescape/api/TossPaymentClient.java
> +    public void pay(PaymentRequest paymentRequest) {
테스트코드를 반드시 작성해야 한다는 의미보다는 실제로 어떻게 테스트해봤는지가 궁금했습니다. 이번에 사용한 API는 payment key 때문에 테스트하기 더 어려웠을 것 같아요 🥲
하지만 설명해주신 것처럼 꼭 테스트코드가 아니더라도 구현할 때 직접 QR을 찍어보거나 이런 저런 방법을 사용해서 테스트를 해보셨을 거예요. 외부 API를 못 믿기 때문이라기 보다는 외부 API에서 요구하는 조건을 잘 맞춰서 '내가 코드를 잘 작성했나'를 확인하기 위함이었을 것 같아요. 만약 다른 사람이 와서 외부 API를 호출하는 부분을 수정한다면 또 테스트가 필요하겠죠.
paymentKey가 없는 단순히 필드만 채워서 호출하는 API였다면 어떻게 테스트 코드를 만들어볼 수 있을까요? 테스트를 돌릴 때마다 외부 API를 호출할 필요는 없으니 테스트를 만들어서 `@Disable` 처리해두고 필요할 때만 사용할 수도 있구요, 인텔리제이의 http 파일을 만들어서 누구나 외부 API 호출 테스트를 쉽게 할 수 있도록 만들어볼 수도 있어요. 이런 부분도 고민해보면 좋을 것 같습니다!

2024-06-01 15:35 UTC, summerlunaa commented on src/main/java/roomescape/config/PaymentConfig.java
> +        simpleClientHttpRequestFactory.setReadTimeout(30);
시간 단위는 분, 초, 밀리초 등등이 있는데 요건 단위가 어떻게 될까요?
connection timeout과 readtimeout의 차이는 무엇인가요? 
타임아웃 설정값도 환경변수를 통해 관리할 수 있어요 :) 환경변수를 통해 관리하면 외부 API별 타임아웃 설정을 한 파일에서 관리할 수 있고 기본 값을 설정해두고 범용적으로 사용할 수도 있습니다. 또 개발환경, 운영환경 등을 분리해서 관리하기도 편리합니다.

2024-06-01 15:35 UTC, summerlunaa commented on src/test/java/roomescape/config/TestPaymentConfig.java
> +import org.springframework.context.annotation.Configuration;
불필요한 import네용

2024-06-01 15:35 UTC, summerlunaa commented on src/main/java/roomescape/exception/RoomescapeExceptionHandler.java
> +        return ResponseEntity.status(e.getHttpStatusCode())
진짜 엄밀하게 하려면 모든 에러 코드를 세세하게 분리해서 4XX 에러, 5XX 에러 등으로 직접 나눠줄 수도 있구요, 내 서버가 단순히 중간 연결다리 역할만 수행한다면 받은 에러 코드를 그대로 내릴 수도 있고, 혹은 400이나 500 에러로 퉁칠 수도 있습니다. 상황에 따라 방법은 다양합니다. 
사실 이번 미션에서 모든 에러 코드를 세세하게 분리하는 것은 과하다고 생각해서 받은 statusCode를 그대로 내리는 것도 충분히 일리있다고 생각해요. 위와 같은 상황도 고민해보라는 의미에서 리뷰 드렸습니다 ㅎㅎ 꼭 하나로 통일해야 한다면 고쳐주신 것처럼 500 internal server error를 사용할 것 같긴 하네요!

2024-06-02 12:37 UTC, yechop commented on src/main/java/roomescape/config/PaymentConfig.java
> +        simpleClientHttpRequestFactory.setReadTimeout(30);
제가 밀리초로 설정했네요 😭
Duration.ofSeconds() 로 변경했습니다.

connectTimeout은 서버로 연결되는 시간을, readTimeout 은 서버로부터 응답을 받는데 소요되는 시간을 설정합니다.

어떤 설정값들을 환경변수로 관리하는게 좋을지 아직 기준이 확실하게 서지 않네요. 어떠한 값을 설정할 때 환경변수도 고려하며 설정해보겠습니다!

2024-06-02 16:05 UTC, summerlunaa commented on src/main/java/roomescape/config/PaymentConfig.java
> +        simpleClientHttpRequestFactory.setReadTimeout(30);
넵ㅎㅎ 어떤 값들을 환경변수로 설정할지 한번 고민해보시면 좋을 것 같습니다. 추가로 각각의 타임아웃을 1초로 설정해주셨는데 넘 짧지 않나 싶네요! 토스에서는 타임아웃을 몇초로 권장하고 있는지도 한번 찾아보면 도움이 될 것 같습니다.

2024-06-02 16:06 UTC, summerlunaa approved these changes
잉크 안녕하세요~

빠른 리뷰 반영 좋습니다 👍 타임아웃에 대해서 코멘트 하나 남겨두었으니 그 부분과 테스트만 추가로 확인해주세요. (환경변수도 추가 시 테스트 properties 파일도 같이 챙겨주세요) 1단계는 여기서 마무리하겠습니다 👏

2024-06-02 16:12 UTC, merged