[ 2 - 4단계 방탈출 결제 / 배포 ] 도도(김도선) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #152
Opened 2024-06-10 08:14 UTC by ehtjsv2

안녕하세요 현구막! 2~4단계가 완료되어 PR보냅니다!

* paymentKey와 amount 추가에 대해서 컬럼만 추가했습니다!
* api문서에 대해서 swagger를 사용했습니다. 큰 이유가 있던 것은 아니고 예전에 얕게 사용해본적이 있는데, 확실하게 한 기술에 대해서 깊게 공부해보고 싶어서 사용했습니다!

### 배포된 서버
[서버 접속](http://3.38.181.51:8080/)
[api문서](http://3.38.181.51:8080/swagger-ui/index.html)
Role | Email | Password
-- | -- | --
관리자 | [tenny@email.com](mailto:tenny@email.com) | 1234
멤버 | [nyangin@email.com](mailto:nyangin@email.com) | 1234

### ERD
![Untitled (6)](https://github.com/woowacourse/spring-roomescape-payment/assets/79188587/8d1eb6c7-58a9-4d15-b5a0-88ea6e9e39f2)

2024-06-11 09:27 UTC, Hyeon9mak requested changes
안녕하세요 도도! 마지막 미션 잘 구현해주셨습니다~
swagger 사용과 payment 정보 관련 코멘트 남겼으니 확인해주세요!
궁금하신 점 편하게 질문 남겨주세요~

2024-06-11 09:27 UTC, Hyeon9mak commented on src/main/java/roomescape/config/SwaggerConfig.java
> +    }
오호... 이렇게 관심사 단위로 묶는다면, API controller 를 관심사 단위로 다시 만드는 것도 방법이었을 것 같은데, GroupedOpenAi builder 를 이용한 이유는 학습을 위해서일까요? 😉

2024-06-11 09:27 UTC, Hyeon9mak commented on src/main/java/roomescape/controller/auth/AuthenticationPrincipal.java
> +@Parameter(hidden = true)
😉 👍  섬세하네용

2024-06-11 09:27 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/reservation/Reservation.java
별도 테이블을 분리하는 것과 도도가 선택해주신 방식에는 각각 어떤 장점과 단점이 있을까요?

예를 들면, 각 데이터가 적재되는 시점(예약이 처음 생성되는 시점과, paymentKey, amount 가 채워지는 시점)이 달라 생기는 불편함은 없으셨는지..? 😄

2024-06-11 09:27 UTC, Hyeon9mak commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
저도 개인적으로 rest docs 보단 swagger 같은 실용적인 프레임워크를 선호해요.
원래는 rest docs 파였는데... API 200 개 테스트 리팩터링 한번 겪어보고나서.. 😱

2024-06-11 09:27 UTC, Hyeon9mak commented on src/main/resources/data.sql
> +INSERT INTO reservation (member_id, date, time_id, theme_id, amount)
많은 정보들 가운데 paymentKey 와 amount 둘을 선택한 이유도 궁금해요!

2024-06-11 09:27 UTC, Hyeon9mak commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +        final Reservation reservation2 = new Reservation(MEMBER_CAT(), DATE_MAY_NINTH, RESERVATION_TIME_SIX(), THEME_COMIC(), "결제완",1000);
`1_000` 등으로 자리수를 표현해주면 가독성이 더욱 올라가겠네요 😄

2024-06-11 09:27 UTC, Hyeon9mak commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +                1000);
인수 테스트는 가능하면 실제와 가장 유사한 값을 사용하는게 좋다고 생각해요.
`결제완` 대신 실제 paymentKey 로 사용되는 값과 유사한 값을 활용해보는 건 어떨까요?

2024-06-11 09:27 UTC, Hyeon9mak commented on src/main/resources/data.sql
>  VALUES ('포켓몬', '매우 귀엽습니다.', 'https://i.pinimg.com/474x/b3/aa/d7/b3aad752a5fbda932dd37015bca3047f.jpg');
<img width="630" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/37354145/3898e13d-9465-4e1f-b78a-6672b15aa634">

제가 알던 꼬부기가 아닌디... ㅋㅋ

2024-06-12 02:18 UTC, ehtjsv2 commented on src/main/java/roomescape/config/SwaggerConfig.java
> +    }
GroupedOpenApi Builder를 공부하기 위함이 컸습니다!
GroupedOpenApi를 사용해서 swagger페이지의 오른쪽 상단에 원하는 그룹을 선택하는 기능이 매력적으로 보였거든요!
 
Api Controller를 관심사 단위로 다시 만든 다는 것은 ```pathsToMatch("/waiting/**", "/admin/waitings/**")``` 이 두가지 경로를 하나의 컨트롤러로 묶는 다는 것이 맞을까요??

2024-06-12 02:20 UTC, ehtjsv2 commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
제가 여쭤보고 싶던 부분을 답을 해주셔서 질문을 남겼었나 확인했네요..ㅎ
주변의 rest docs를 사용하는 크루들ㄷ API 테스트때문에 많이 애를 먹더라구요!
그래도 저도 rest docs를 경험해보고 싶은 마음은 있네요!

2024-06-12 03:56 UTC, ehtjsv2 commented on src/main/resources/data.sql
> +INSERT INTO reservation (member_id, date, time_id, theme_id, amount)
amount는 자주 보내줘야하는 데이터이기에 제 서버에 저장해두는 것이 편하다고 생각해서 저장했습니다!
paymentKey는 현재 웹화면상에 띄어줘야하기에 저장한 것도 있지만, paymentKey로 toss의 조회, 결제취소기능을 사용하기 위해 저장했다는 마음이 더 컸습니다!

웬만한 정보는 paymentKey로 모두 조회가능하다고 생각했기에 이외에 다른 정보는 저장하지 않았습니다.

2024-06-12 08:07 UTC, ehtjsv2 commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +                1000);
수정했습니다! MOCK을 사용하고 있어서 당장은 어떤 문자열이든 상관없지만, 이후에 변경가능성(MOCK을 사용하지 않게 될 수도)때문에 유사한 값을 사용하라는 것이 맞을까요?

2024-06-12 08:10 UTC, ehtjsv2 commented on src/main/java/roomescape/controller/auth/AuthenticationPrincipal.java
> +@Parameter(hidden = true)
이전에는 ArgumentReslover를 사용한적이 없어서 이러한 어노테이션을 쓸 기회가 없었는데 이번에는 필요하게 되더라구요!

2024-06-12 08:23 UTC, ehtjsv2 commented
이번에는 변경사항이 많지는 않네요!

[궁금한 점]
내 예약목록을 반환할 때 status라는 항목이 있습니다. 예약, 결제대기, 예약대기 세가지 String을 가지고 있는 필드입니다.
클라이언트 코드에서 이러한 status를 가지고 아래와 같은 코드가 나왔는데요,
```java

if (status !== '예약' && status !== '예약(결제대기중)') { // 예약 대기 상태일 때 예약 대기 취소 버튼 추가하는 코드, 상태 값은 변경 가능
            const cancelCell = row.insertCell(4);
            const cancelButton = document.createElement('button');
            cancelButton.textContent = '취소';
            cancelButton.className = 'btn btn-danger';
            cancelButton.onclick = function () {
                requestDeleteWaiting(item.reservationId).then(() => window.location.reload());
            };
            cancelCell.appendChild(cancelButton);
        } else { // 예약 완료 상태일 때
            row.insertCell(4).textContent = '';
        }

        if (paymentKey === null && status === '예약(결제대기중)') {
```
변경 가능성이 많은 String을 가지고 이렇게 로직을 구성할 것 같지 않습니다!
이런 코드를 보니 이래서 클라이언트와 서버간 커스텀 HTTP STATUS CODE를 약속하고 소통하나? 라는 생각이 들었는데 올바른 생각인 지 궁금합니다!

2024-06-13 12:21 UTC, Hyeon9mak approved these changes
안녕하세요 도도! 피드백 잘 반영해주셨어요 😄 

> 클라이언트와 서버간 커스텀 HTTP STATUS CODE를 약속하고 소통하나? 변화가능성이 큰 String이 아닌 status code로 클라이언트에서 로직구성이 가능할 것 같은데?라는 생각이 들었습니다.

이미 정답을 아시겠지만, 클라이언트분들과 협의를 하기 나름인거 같아요!

도도가 속하신 팀에서 전체적으로 HTTP status code 를 적극적으로 활용한다면
HTTP status codde 로 구분할 수도 있겠는데,
아무래도 HTTP status code 는 비즈니스 적인 예외도 모두 표현해줄 순 없으므로
서로 협의하에 적당한 custom code (response body 에 담아서) 로 만들게 되죠 😄 👍 
이 부분은 정답이 없는 부분이지만, 생각을 깊게 해주신 부분에서 이미 안심이 되네요 😉 

모든 요구사항이 완료되어 approve 합니다!
그동안 남겨드린 코멘트들이 도움이 되셨길 바라면서~~~
레벨2 잘 마무리하시고, 즐거운 마음으로 레벨3 맞이하시길!
고생 많으셨어요!!

2024-06-13 12:21 UTC, Hyeon9mak commented on src/main/java/roomescape/config/SwaggerConfig.java
> +    }
맞습니다!!

사용자에게 보여주고 싶은 집합 == controller 를 나누는 기준으로도 볼 수 있기 때문이라고 생각했어요 😄

2024-06-13 12:21 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/reservation/Reservation.java
아하~! 상상하고 있는 방식이 조금 달랐네요 🙏 도도가 그려주신 흐름대로라면 생명주기가 정확히 일치할 것 같아요 😄 

저는 예약이 우선 생성되고, 결제를 통해 그 예약이 확정되는 방식이라고 생각했어요!
(결제가 오래걸려서 예약하고 싶은 시간을 빼앗기는게 슬프니...)

2024-06-13 12:21 UTC, Hyeon9mak commented on src/main/resources/data.sql
> +INSERT INTO reservation (member_id, date, time_id, theme_id, amount)
> amount는 자주 클라이언트로 보내줘야하는 데이터이기에 제 서버에 저장해두는 것이 편하다고 생각해서 저장했습니다!

👍 👍 이게 가장 중요하죠~

2024-06-13 12:21 UTC, Hyeon9mak commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +                1_000);
> 변경가능성(MOCK을 사용하지 않게 될 수도)때문에 유사한 값을 사용하라는 것이 맞을까요?

동료 개발자들이 toss payments 문서를 읽고 테스트 코드를 읽는다면 더 좋겠지만! 테스트 코드만으로 동작을 파악하려는 경우도 있기 때문에, 그를 대비해서 최대한 배려를 해보자! 라는 코멘트였어요 😉

2024-06-13 12:21 UTC, merged