[2 - 4 단계 방탈출 결제 / 배포] 재즈(함석명) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #157
Opened 2024-06-10 08:46 UTC by seokmyungham

안녕하세요 썬~!
다시 돌아온 재즈입니다 😊

스텝 1을 진행하는 동안 결제와 취소 관련 기능을 구현함에 따라
이번에는 조금 더 요구사항에 집중하여 코드를 다듬고, 문서화에 신경써보았습니다.

## 예약 정책 설명

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/97608735/6441afed-11cb-448d-8b66-481a4025d770)

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/97608735/a8345a47-b8ae-45a0-899d-74447cca57c5)

Reservation의 상태는 `예약`, `결제 대기`, `대기`, `취소` 상태가 존재하고
예약을 시도할 시 결제를 완료해야 결제까지 완료되어야 합니다. 반면에 대기는 결제 없이 자유롭게 가능합니다.

예약자가 예약을 취소하면, 자동으로 대기 1번이 결제 대기 상태로 전환되고, 1시간 동안 결제를 할 수 있습니다.

이를 이벤트 스케쥴러를 이용하여 1시간 마다 결제 상태를 확인하고, 결제를 하지 않을 경우 취소 상태로 전환하도록 구현해보았습니다. 이 때 다음 대기자가 존재하면 다음 대기자를 결제 대기상태로 전환됩니다.

http://54.180.240.209/
http://54.180.240.209/docs/api.html

2024-06-10 11:39 UTC, seokmyungham commented
기존 1단계에서 2단계 요구사항을 반영하고 넘어옴에 따라, 
2단계 요구사항의 변경 기록이 File Changed에 남지 않는 것을 해결하고 싶어 리뷰를 위한 커밋 기록을 추가하였습니다.

결제 승인과 취소에 따른 리뷰를 [이곳](https://github.com/woowacourse/spring-roomescape-payment/pull/157/commits/c15abcd2f2a140471922158c93924cadfe43ae1f)에서 부탁드립니다. 😊

2024-06-10 11:49 UTC, seokmyungham commented on src/main/java/roomescape/infrastructure/payment/toss/TossResponseErrorHandler.java
> +        log.error(apiError.message());
[로그 리뷰](https://github.com/woowacourse/spring-roomescape-payment/pull/79#discussion_r1628791466)
이 부분을 어떻게 해결해야 할지 고민해봤는데 결론을 내리지 못했습니다 😥

제가 이 부분에 로그를 남긴 이유는 토스 에러 메시지를 제가 정의한 에러 메시지로 변환하기 전 로그로 출력하고 기록으로 남기기 위함이었습니다.

썬의 의도는 어떠한 값, 원인으로 에러가 발생했는지를 자세한 이유를 원하셨던 걸까요??
저는 그걸 토스로부터 받는 에러 메시지를 통해 확인할 수 있다고 생각했는데, 만약 아니라면 해당 원인 정보들을 어떻게 불러올 수 있을지 잘 모르겠습니다... 😭

2024-06-10 13:38 UTC, syoun602 requested changes
안녕하세요 재즈!

1단계에서 거의 구현되어서 2단계에 큰 변경사항이 없긴 하네요~ 잘 구현해주셨어요 👍
erd는 봤던 것 중에서 디자인도 그렇고 의도가 제일 잘 보이는 것 같네요. 툴 선택 💯
몇가지 코멘트 남겨두었으니 확인 부탁드립니다~!

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/application/CancelService.java
> +        reservation.cancel(memberInfo.id());
reservation 내부의 cancel()이 두개 있던데, 다음과 같이 작성해볼 수 있겠네요~!
```java
 public void cancel(Long memberId) {
        ...
        this.cancel();
    }
```

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/application/ReservationService.java
> +            reservation.setPayment(payment);
그냥 setter보다는 조금 의미있는 메서드명을 작성해봅시다~

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    }
딱히 payment에선 검증 로직이 없어도 되나요?

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private int amount;
tmi) 한번 알아두면 재미있는 잡지식
`1.1 + 0.1 = 1.2`가 맞을까요?
돈 또는 계산과 관련된 필드는 보통 BigDecimal을 사용합니다.

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/infrastructure/event/ReservationEventHandler.java
> +        taskScheduler.schedule(
내가 설정한 스케쥴러가 정상 동작하는 테스트도 작성해야 하지 않나요?

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/infrastructure/payment/toss/TossResponseErrorHandler.java
> +        log.error(apiError.message());
앗 이부분은 제가 남긴 코멘트의 위치가 조금 이상했네요 무시해주세요!
`GlobalExceptionHandler`에서 로깅 부분에 stacktrace를 남겨주어야 할 것 같아서 남긴 코멘트입니다~ 
잘 설정되어 있네요 👍

+한가지 )  `ERROR_PREFIX`의 {} 안에 값이 담겨져 있는게 맞나요~?
또한, customException의 경우에는 stacktrace를 남겨야 추적에 용이할 것 같은데 어떻게 생각하시나요?

2024-06-10 13:38 UTC, syoun602 commented on src/main/java/roomescape/application/CancelService.java
> +    private void updateFirstWaitingToPending(Reservation reservation) {
event가 들어가면 코드 추적이 확실히 복잡해집니다~ 
따라서 가독성/작업량/testability를 포기하고 정말 이벤트를 사용해야 하는 지에 대해 고민을 많이 해보면 좋을 것 같아요 😊
이건 그냥 드리는 얘기고 두가지가 궁금합니다.

1. 데이터베이스 정규화 관점에서 분리하고 싶었다고 하셨는데 정규화가 무엇인가요? 정말 정규화 관점에서 분리가 필요한게 맞나요? 하나의 예약은 하나의 결제만을 가지고 있는 것 같아서요 👀
2. 코드를 살펴보니 예약을 취소하게 되면 결제 정보도 그대로 가지고 있을 것 같은데 결제 정보를 삭제하거나 아니면 추적용 결제정보를 남기거나 일 것 같은데 (이 의도가 맞다면 1번도 이해가 갑니다) 둘 다 안하고 있는 것 같아서요~

2024-06-11 13:44 UTC, seokmyungham commented on build.gradle
> +asciidoctor {
조금 힘들긴했는데 열심히 만들어놓으니 예뻐보이고 뿌듯한 것 같아요 😂
마감은 역시... 😱 빠른 생산성이 요구 될때는 swagger도 고려해볼만 하겠군요 😎

2024-06-11 13:55 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        updateFirstWaitingToPending(reservation);
실행되는게 맞다고 생각합니다 😀 

`updateFirstWaitingToPending()` 메서드는 예약 대기 1번을 찾아 결제 대기 상태로 전환하고 이벤트를 발행하는 동작을 합니다.

- 어드민이 직접 예약을 추가했다면 결제를 거치지 않기에 결제 정보는 존재하지 않는다.
- 어드민이 회원의 예약을 직접 추가한 상황에서, 만약 회원이 그 예약을 취소하게 된다면 결제 취소 api를 호출하지는 않아도 다음 예약 대기자를 결제 대기 상태로 변경해야 합니다.

2024-06-11 13:56 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        updateFirstWaitingToPending(reservation);
실행되는게 맞다고 생각합니다 😀 

`updateFirstWaitingToPending()` 메서드는 예약 대기 1번을 찾아 결제 대기 상태로 전환하고 이벤트를 발행하는 동작을 합니다.

- 어드민이 직접 예약을 추가했다면 결제를 거치지 않기에 결제 정보는 존재하지 않습니다.
- 위 상황에서, 만약 회원이 그 예약을 취소하게 된다면 결제 정보가 존재하지 않기에 결제 취소 api를 호출하지는 않아도, 다음 예약 대기자를 결제 대기 상태로 변경해야 합니다.

2024-06-11 14:06 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        reservation.cancel(memberInfo.id());
반영하겠습니다!!

2024-06-11 14:18 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        reservation.cancel(memberInfo.id());
썬의 리뷰를 받고 혼자 생각해봤는데

cancel() 내부에 예약 주인을 검증하는 로직을 두어 분리해서 사용하는 것보다,  
이미 존재하는 validateOwner() 를 이용해서 cancel()을 하나로 관리할 수 있다면 서비스 코드 중복을 확 줄일 수 있겠다는 생각이 들었습니다! 

이렇게 줄여볼 수 있겠네요

```java
@Transactional
public void cancelReservation(Long reservationId, MemberInfo memberInfo) {
    Reservation reservation = reservationRepository.getReservationById(reservationId);
    reservation.validateOwner(memberInfo.id());
    cancelReservation(reservation);
}

@Transactional
public void cancelReservationByAdmin(Long reservationId) {
    Reservation reservation = reservationRepository.getReservationById(reservationId);
    cancelReservation(reservation);
}
```

2024-06-11 14:29 UTC, seokmyungham commented on src/main/java/roomescape/application/ReservationService.java
> +            reservation.setPayment(payment);
변경감지를 사용하는 과정에서 setter가 메서드 명으로 가장 명확할 것이라 판단했는데 제가 잘못 판단한 것 같아요 😫

시그니처를 더 활용할 수 있도록 이름을 updatePayment()로 변경했습니다!!

2024-06-11 14:40 UTC, seokmyungham commented on src/main/java/roomescape/domain/payment/Payment.java
> +    }
결제 금액은 검증이 필요해보이네요 😮
왜 놓쳤을까요...😱 추가하겠습니다!

2024-06-11 14:46 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +    private void updateFirstWaitingToPending(Reservation reservation) {
> event가 들어가면 코드 추적이 확실히 복잡해집니다~
따라서 가독성/작업량/testability를 포기하고 정말 이벤트를 사용해야 하는 지에 대해 고민을 많이 해보면 좋을 것 같아요 😊

최대한 다른 개발자가 봤을 때 이해하기 쉽도록 시그니처를 신경쓰려 노력했는데, 그럼에도 로직 자체가 복잡하다보니 쉽지 않았던 것 같아요.

썬 말씀대로 나중에 다시 사용하게 된다면 더 다른 방안을 고민해보고 신중히 사용해야 할 것 같아요.
언제나 코드를 처음 보는 개발자가 이해하기 쉬운 코드가 좋은 코드라 생각합니다!! 😄

조언 정말 감사드립니다 😊

2024-06-11 15:09 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +    private void updateFirstWaitingToPending(Reservation reservation) {
> 데이터베이스 정규화 관점에서 분리하고 싶었다고 하셨는데 정규화가 무엇인가요? 정말 정규화 관점에서 분리가 필요한게 맞나요? 하나의 예약은 하나의 결제만을 가지고 있는 것 같아서요 👀

데이터베이스 정규화 관점에서 말씀드린 이유는 다음과 같습니다!

현재 예약은 데이터 삭제 시 상태 변경을 통한 논리적 삭제를 수행하고 있습니다. (status = cancel)
그런데 만약 물리적 삭제로 변경이 일어났을 때, 결제 정보가 예약 테이블에 함께 존재한다면 (정규화x)
예약을 실제 삭제했을 시 결제 정보도 함께 삭제되는 삭제 이상현상이 발생하게 됩니다.

물리적 삭제와 논리적 삭제의 변환은 테이블 스키마를 변경하는 상황보다 더 충분히 일어날 수 있는 일이라 생각했습니다. 제가 논리적 삭제를 선택한 이유는 삭제된 예약 정보도 방탈출 어드민이 보관할 가치가 있다고 생각했기 때문입니다.

예약 정보가 존재하지 않는데 결제 정보만 가지고 있는게 의미가 있는가? 를 고려해야 한다면
우선 결제 정보는 돈과 관련된 민감한 사항이라고 생각하여  예약 삭제 여부와 상관없이 정보를 따로 저장할 필요가 있다고 생각하였습니다. 

돈을 직접 다룰 수 있을만한 경험이 없어 예상해서 결정해야 했던게 조금 어려웠던 것 같습니다. 😅 

결제와 결제 타겟에 대한 제 예상이 올바른지 궁금하네요 🤔
썬이 정말 잘 알고계실 것 같아 어떻게 생각하시는지 의견을 듣고싶습니다!! 😊

2024-06-12 02:34 UTC, seokmyungham commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private int amount;
금액이 소수가 되었을 때 부동 소수점 표기법으로 인해 오차가 발생할 수 있겠네요!!
변경하겠습니다.

2024-06-12 06:15 UTC, seokmyungham commented on src/main/java/roomescape/infrastructure/event/ReservationEventHandler.java
> +        taskScheduler.schedule(
추가했습니다!! 😊

2024-06-12 14:24 UTC, seokmyungham commented on src/main/java/roomescape/infrastructure/payment/toss/TossResponseErrorHandler.java
> +        log.error(apiError.message());
`ERROR_PREFIX`와 함께 에러를 출력하는 로그에 메시지를 호출하는 부분이 누락되어 있는 것을 수정했습니다. 😅

> customException의 경우에는 stacktrace를 남겨야 추적에 용이할 것 같은데 어떻게 생각하시나요?

저도 그렇게 생각합니다. 
현재 catched exception을 customException으로 변환하는 과정에서 기존 예외의 Throwable을 전달하지 않고 있는 것을 확인했습니다. 😣

모두 포함하도록 변경하고 stacktrace를 남기도록 변경하였습니다.

2024-06-12 14:59 UTC, seokmyungham commented on src/main/java/roomescape/infrastructure/payment/toss/TossResponseErrorHandler.java
> +        log.error(apiError.message());
ERROR_PREFIX와 함께 에러를 출력하는 로그에 메시지를 호출하는 부분이 누락되어 있는 것을 수정했습니다. 😅

2024-06-13 01:52 UTC, seokmyungham commented on src/main/java/roomescape/infrastructure/payment/toss/TossResponseErrorHandler.java
> +        log.error(apiError.message());
> +한가지 ) ERROR_PREFIX의 {} 안에 값이 담겨져 있는게 맞나요~?
또한, customException의 경우에는 stacktrace를 남겨야 추적에 용이할 것 같은데 어떻게 생각하시나요?

{} 때문에 trace가 출력되는 것도 아니고, 그렇다고 메시지를 출력하는 것도 아닌 이도저도 아닌 코드였네요,, 🤮
{} 를 삭제해서 stacktrace를 남기도록 변경했습니다!

그리고 전역으로 런타임 예외를 처리하는 부분에서 다른 예외들도 trace를 추적할 수 있도록 적절하게 레벨을 선택해서 stacktrace를 출력하였습니다.

2024-06-13 14:45 UTC, syoun602 requested changes
안녕하세요 재즈~!

우선 리뷰 코멘트 잘 반영해주셨네요 👍
우테코 레벨2가 내일이면 끝나는데, 충분히 의미있는 시간을 보내셨는지 궁금하네요 😊
이만 머지하고 푹 쉬셔도 될 것 같은데, 대체로 질문들을 남겨두었으니 답변해주시고 RC 주시면
머지하겠습니다! 고생 많으셨어요~ 남은 하루도 잘 마무리 하시길 바라고 프로젝트 화이팅입니다~!

2024-06-13 14:45 UTC, syoun602 commented on src/main/java/roomescape/application/CancelService.java
> +        updateFirstWaitingToPending(reservation);
그러면 결제 취소는 성공적이었는데 아래 update에서 예외 발생시 어떤 일이 일어날까요?~

2024-06-13 14:45 UTC, syoun602 commented on src/main/java/roomescape/application/CancelService.java
> +        reservation.cancel(memberInfo.id());
중복을 잘 제거해주셨네요 👍

2024-06-13 14:45 UTC, syoun602 commented on src/main/java/roomescape/application/CancelService.java
> +    private void updateFirstWaitingToPending(Reservation reservation) {
👍👍 결제와 같은 정보는 말씀하신대로 법적으로나 서비스적으로 민감한 부분이기 때문에 함부로 지울 수 없는게 맞습니다 😁
단순히 정규화라는 이유를 말씀해주셔서 재차 질문드렸는데 잘 고려해서 설계해주신 것 같아요. 
프로젝트를 진행할 때에도 코멘트 주신 것처럼 비즈니스적, 외부 요소 등을 감안해서 설계하시면 잘 진행하실 것 같습니다!

넵 마지막에 드린 얘기는 삭제를 진행했는데, 어디에도 삭제됐다는 표시를 남기지 않고 있어서 여쭤봤었는데, 당장은 cancel된 예약과 관계를 맺고 있으니 괜찮을 것 같습니다! 항상 생명주기가 같다면 지금처럼 두셔도 되지만, 결제가 예약과 별개로 이루어질 수도 있다면 확장성을 위해 따로 필드를 두고 관리해볼 수 도 있을 것 같아요 😊

2024-06-13 14:45 UTC, syoun602 commented on src/main/java/roomescape/domain/payment/PaymentAmount.java
> +public class PaymentAmount {
👍👍

2024-06-13 14:45 UTC, syoun602 commented on src/test/java/roomescape/domain/payment/PaymentTest.java
> +    @Test
`@ParameterizedTest`로 음수 값도 테스트해볼 수 있을 것 같아요~

2024-06-13 14:45 UTC, syoun602 commented on src/test/java/roomescape/infrastructure/event/ReservationEventHandlerTest.java
> +    void pp() throws InterruptedException {
테스트명이 여기만 식별이 불가능하네요 🥲

2024-06-13 14:45 UTC, syoun602 commented on src/test/java/roomescape/infrastructure/event/ReservationEventHandlerTest.java
> +        TimeUnit.SECONDS.sleep(2);
정확히 2초뒤에 테스트가 의도대로 완료되는 이유는 무엇인가요~?

2024-06-13 14:45 UTC, syoun602 commented on src/main/java/roomescape/application/ReservationService.java
>      public ReservationResponse saveReservation(UserReservationRequest request, Long memberId) {
반영 X)
트랜잭션이 선언된 메서드에서 외부 연동 로직이 들어가게 되면 어떤 문제들이 있을지 단순히 고민만해보고 알려주세요~!

2024-06-13 15:46 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        updateFirstWaitingToPending(reservation);
헉.. 😮😮😮 문제점을 깨달았습니다.
결제 취소는 성공했는데, 다음 대기자를 선정하는 과정에서 에러가 발생하면 
그대로 결제만 취소되고 그 외의 변경 내용들은 롤백되거나 실행되지 않는 문제가 발생하네요.

사용자 입장에서 결제 취소 알림은 왔는데, 예약 상태는 바뀌지 않거나 다른 사이드 이펙트가 발생합니다. 😨

결제 취소와 다음 대기자를 호출, 다른 두 관심사가 한 트랜잭션으로 묶여 발생한 문제라고 느끼고 있습니다.
- 사용자가 원하는 건 내 예약을 취소상태로 만들고, 돈을 돌려받는 것이다.
- 돈을 돌려받기 까지 문제가 발생하지 않았다면, 사용자 입장에서는 서비스 이용을 성공적으로 끝마쳤다 볼 수 있다.
- update 작업은 비즈니스 로직 흐름상 필요해보이지만, 예약을 취소하는 사용자 입장에서는 전혀 궁금하지 않은 일이다.

결제 취소와 update 호출 순서를 바꾼다해도, update에서 예외가 발생하면 결제 취소자체가 안되니 여전히 문제네요.
`(예약 취소, 다음 대기자 update)` / `(결제 취소)` 이렇게 관심사를 나눠야할 것 같다는 생각이 듭니다.

즉 결제 취소 api를 트랜잭션 내에서 분리하되, 위 일련 과정의 원자성은 지켜져야합니다. 
엄청 흥미로운 주제네요 🧐

2024-06-13 15:48 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        updateFirstWaitingToPending(reservation);
헉.. 😮😮😮 문제점을 깨달았습니다.
결제 취소는 성공했는데, 다음 대기자를 선정하는 과정에서 에러가 발생하면 
그대로 결제만 취소되고 그 외의 변경 내용들은 롤백되거나 실행되지 않는 문제가 발생하네요.

사용자 입장에서 실제로 결제 취소도 되었고 결제 취소 알림은 왔는데, 예약 상태는 바뀌지 않았거나 다른 사이드 이펙트가 발생합니다. 😨

결제 취소와 다음 대기자를 호출, 다른 두 관심사가 한 트랜잭션으로 묶여 발생한 문제라고 느끼고 있습니다.
- 사용자가 원하는 건 내 예약을 취소상태로 만들고, 돈을 돌려받는 것이다.
- 돈을 돌려받기 까지 문제가 발생하지 않았다면, 사용자 입장에서는 서비스 이용을 성공적으로 끝마쳤다 볼 수 있다.
- update 작업은 비즈니스 로직 흐름상 필요해보이지만, 예약을 취소하는 사용자 입장에서는 전혀 궁금하지 않은 일이다.

결제 취소와 update 호출 순서를 바꾼다해도, update에서 예외가 발생하면 결제 취소자체가 안되니 여전히 문제네요.
`(예약 취소, 다음 대기자 update)` / `(결제 취소)` 이렇게 관심사를 나눠야할 것 같다는 생각이 듭니다.

즉 결제 취소 api를 트랜잭션 내에서 분리하되, 위 일련 과정의 원자성은 지켜져야합니다. 
매우 흥미로운 주제네요!!! 😁

2024-06-13 15:50 UTC, seokmyungham commented on src/test/java/roomescape/infrastructure/event/ReservationEventHandlerTest.java
> +    void pp() throws InterruptedException {
아이고.. 😫😫😫 수정하겠습니다.

2024-06-15 14:23 UTC, seokmyungham commented on src/test/java/roomescape/infrastructure/event/ReservationEventHandlerTest.java
> +        TimeUnit.SECONDS.sleep(2);
해당 테스트는 이벤트에 설정한 시간이 지난 후 결과의 상태를 확인해서 메서드가 기대하는 동작을 수행했는지 확인하는 목적으로 작성했습니다!

그래서 정확하게 2초 이후를 예상했다기보다
이벤트 메서드 호출 -> 1초 후 작업 실행 -> 여러 시스템 지연시간 발생 예상 -> 2초 후 결과를 확인하게 되었습니다. 😀
실제 프로덕션 코드는 정상적인 동작을 마쳤는데
테스트 스레드 sleep 시간을 타이트하게 설정해서 간헐적으로 실패하는 것은 안정적인 테스트가 아니라고 생각했습니다.

그런데 썬 말씀을 듣고 생각해보니
설정 시간 1초와 예상 시간 2초 차이는 너무 큰 갭이 존재하는 것이 아닌가?? 라는 생각도 드네요 🤔
오히려 테스트 신뢰성이 낮다고도 볼 수 있을 것 같고, 만약 이러한 작업에 돈과 같은 민감한 도메인이 포함될 경우 문제가 될 가능성이 높을 것 같습니다.

```java
TimeUnit.MILLISECONDS.sleep(1150); // 성공
TimeUnit.MILLISECONDS.sleep(1100); // 실패
```

실패와 성공 임계점을 정확히 예상하려면 여러 지연시간들을 직접 계산해봐야할 것 같은데
1.15초와 1.1초를 기점으로 테스트가 성공, 실패하는 것을 확인할 수 있었습니다.

지연시간에는 트랜잭션 처리, 쿼리 실행, 가비지 컬렉션, 로직 수행시간 등등 여러가지 요인이 있을 것 같아요.
어느 정도의 기대 시간이 테스트 정확도가 가장 높다 볼 수 있을지 확신하기는 어렵지만
현재 기대하는 2초보다는 1.5초 정도가 더 합리적일 것 같아 시간을 수정했습니다.

제가 올바르게 생각한게 맞는지 궁금합니다!! 😊

2024-06-15 17:44 UTC, seokmyungham commented on src/main/java/roomescape/application/ReservationService.java
>      public ReservationResponse saveReservation(UserReservationRequest request, Long memberId) {
트랜잭션 내에 외부 연동 로직을 사용하게되면 
해당 외부 시스템에서 발생하는 지연시간과 통신 과정에서 발생하는 지연시간이 트랜잭션 내에 포함되게 됩니다.

트랜잭션의 시작과 끝은 DB 커넥션을 얻고 반환하는 행위에서 비롯되고, 커넥션은 TCP 연결을 유지하면서 풀링을 통해 관리되는 한정된 자원입니다. 

한정된 자원을 점유하는 시간이 늘어나면 자원이 점점 고갈되고 
이를 대기하는 클라이언트가 증가해서 평균 응답시간이 증가합니다. 이는 성능에 직접적으로 문제를 일으키게 됩니다.

또한 외부 api를 사용하면서 발생하는 지연시간으로 트랜잭션 시간이 길어지는 문제가 존재합니다.
트랜잭션 시간이 길어진다는 것은 테이블이나 레코드 락을 오래 점유하는 것을 의미하고 이로인해 데드락이 발생할 가능성이 증가합니다. MySQL 의 경우 로그파일도 계속 유지되고 크기도 증가하겠네요 😮

아직 깊게 학습해보지는 않았는데 해결방법을 고민해보면
외부 api를 트랜잭션 내부에서 분리하거나, 비동기로 처리하는 방법이 있을 것 같습니다.
꼭 학습해보고싶고 너무 재미있을만한 주제네요 😋

2024-06-15 17:47 UTC, seokmyungham commented on src/main/java/roomescape/application/ReservationService.java
>      public ReservationResponse saveReservation(UserReservationRequest request, Long memberId) {
트랜잭션 내에 외부 연동 로직을 사용하게되면 
해당 외부 시스템에서 발생하는 지연시간과 통신 과정에서 발생하는 지연시간이 트랜잭션 내에 포함되게 됩니다.

트랜잭션의 시작과 끝은 DB 커넥션을 얻고 반환하는 행위에서 비롯되고, 커넥션은 TCP 연결을 유지하면서 풀링을 통해 관리되는 한정된 자원입니다. 

한정된 자원을 점유하는 시간이 늘어나면 자원이 점점 고갈되고 
이를 대기하는 클라이언트가 증가해서 평균 응답시간이 증가합니다. 이는 성능에 직접적으로 문제를 일으키게 됩니다.

또한 외부 api를 사용하면서 발생하는 지연시간으로 트랜잭션 시간이 길어지는 문제가 존재합니다.
트랜잭션 시간이 길어진다는 것은 테이블이나 레코드 락을 오래 점유하는 것을 의미하고 이로인해 데드락이 발생할 가능성이 증가합니다. MySQL 의 경우 로그파일도 계속 유지되고 크기도 증가하겠네요 😮

아직 깊게 학습해보지는 않았는데 해결방법을 고민해보면
외부 api를 트랜잭션 내부에서 분리하거나, 비동기로 처리하는 방법이 있을 것 같습니다. 😊

2024-06-15 18:50 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
> +        updateFirstWaitingToPending(reservation);
결제 취소는 성공했는데, 다음 대기자를 선정하는 과정에서 에러가 발생하면
그대로 결제만 취소되고 그 외의 변경 내용들은 롤백되거나 실행되지 않는 문제가 발생하네요.

사용자 입장에서 실제로 결제 취소도 되었고 결제 취소 알림은 왔는데, 예약 상태는 바뀌지 않았거나 다른 사이드 이펙트가 발생합니다. 😨

결제 취소와 다음 대기자를 호출, 다른 두 관심사가 한 트랜잭션으로 묶여 발생한 문제라고 느끼고 있습니다.

- 사용자가 원하는 건 내 예약을 취소상태로 만들고, 돈을 돌려받는 것이다.
- 돈을 돌려받기 까지 문제가 발생하지 않았다면, 사용자 입장에서는 서비스 이용을 성공적으로 끝마쳤다 볼 수 있다.
- update 작업은 비즈니스 로직 흐름상 필요해보이지만, 예약을 취소하는 사용자 입장에서는 전혀 궁금하지 않은 일이다.

`(예약 취소, 결제 취소)` / `(다음 대기자 update)` 이렇게 관심사를 나눠야할 것 같다는 생각이 듭니다. 😀
코드를 수정했습니다!!

2024-06-16 08:34 UTC, syoun602 approved these changes
안녕하세요 재즈!

새벽까지 열심히 작업해주셨네요 😄
이번 미션은 이만 머지하겠습니다 수고 많으셨어요!
방학동안 푹 쉬시고 재충전한 뒤 프로젝트도 화이팅입니다 💪

2024-06-16 08:34 UTC, syoun602 commented on src/main/java/roomescape/application/ReservationService.java
>      public ReservationResponse saveReservation(UserReservationRequest request, Long memberId) {
넵 생각했던 대답들을 잘 고려해주셨어요 💯
추후 프로젝트때 더 고민해보면서 이런 것들을 고려하면 설계하면 좋을 것 같습니다 😄

2024-06-16 08:34 UTC, syoun602 commented on src/test/java/roomescape/infrastructure/event/ReservationEventHandlerTest.java
> +        TimeUnit.SECONDS.sleep(2);
말씀하신대로 여러가지 요인에 의해 테스트가 수행되지 않을 수 있다면 좋은 테스트인가요?
모든 사람의 환경에서 동일하게 성공이 나온다고 보장하기 힘들 것 같아요.
시간이 몇초가 걸리는지와 관계없이 항상 true를 반환하는 다른 방법은 없는지 조금 더 고민해보면 좋을 것 같습니다!

2024-06-16 08:35 UTC, merged