[1단계 방탈출 결제 / 배포] 초코칩(권기호) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #26
Opened 2024-05-29 08:52 UTC by Chocochip101

안녕하세요, 미르! 백엔드 6기 크루 초코칩입니다 🍪
레벨 1 마지막 체스 미션을 미르와 함께 했는데, 이번 레벨 2 마지막 미션도 리뷰어로 만나게 되어 반갑네요 😁

[이번 미션 커밋 변경 사항들](https://github.com/woowacourse/spring-roomescape-payment/pull/26/files/91bcef3facb87b3c6150814ba121e3dab06625b9..8ca04fd3373289fbfc6886bce9318a6addabdf25)입니다.

## 웹 개발 경험
- 웹 어플리케이션의 Restful 서버를 만들고 배포해 본 경험이 2회 있습니다.
- 미션에서 사용할 Springboot, Java, JPA, H2를 사용해본 적 있습니다.
- Springboot 공부 및 프로젝트를 시작한 지는 9개월이 조금 넘었습니다.

## ERD

![roomescape drawio](https://github.com/woowacourse/spring-roomescape-payment/assets/73146678/f114abfe-1434-4a71-8338-fc23d7f30b37)

## 고민사항
- 결제를 구현하는 과정에서 어떤 정보를 저장해야될지 페어와 고민하다가, 현재 단계에 필요한 정보인 결제 인증 성공 후의 반환 값을 저장하게 했어요. 기능이 추가될 때마다 DB의 스키마가 변경될 수 있다는 생각을 했어요. 하지만 무작정 모든 정보를 저장하는 것도 수고로움이 있다고 생각해요. 현재 단계에서 Payment 테이블에 저장된 정보가 적당한지 궁금해요.

## 계정 정보
### 관리자 계정
ID: admin@roomescape.com
PWD: admin

### 사용자 계정1
ID: dev.chocochip@gmail.com
PWD: 1234

### 사용자 계정2
ID: dev.eden@gmail.com
PWD: 5678

감사합니다 :)

2024-05-29 12:31 UTC, ddu0422 requested changes
안녕하세요 초코칩! 미르입니다 :)
다시 만나서 반가워요~

미션 구현 잘 해주셨네요 :)
몇 가지 코멘트 남겼으니 확인 부탁드립니다 ㅎ_ㅎ

>  결제를 구현하는 과정에서 어떤 정보를 저장해야될지 페어와 고민하다가, 현재 단계에 필요한 정보인 결제 인증 성공 후의 반환 값을 저장하게 했어요. 기능이 추가될 때마다 DB의 스키마가 변경될 수 있다는 생각을 했어요. 하지만 무작정 모든 정보를 저장하는 것도 수고로움이 있다고 생각해요. 현재 단계에서 Payment 테이블에 저장된 정보가 적당한지 궁금해요.

어떤 이유에서 테이블을 설계하고 데이터를 저장했는지가 중요하다고 생각해요.
무작정 많은 내용을 저장해야할 수도 있고 혹은 필요 없을 수도 있죠.
여러 관점에서 고민해보시면 될 것  같습니다 :)

저는 사용자 예약할 때 결제 내역을 확인할 수 있다는 점에서 괜찮다고 생각해요.
DB 스키마 변경 때문에 고민하시는 내용이라면, 그 때마다 DB 스키마를 변경하면 되지 않을까요?

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/payment/service/PaymentClient.java
> +                    .uri("https://api.tosspayments.com/v1/payments/confirm")
중복 url을 제거할 수는 없을까요?

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/payment/service/PaymentClient.java
> +                    .uri("https://api.tosspayments.com/v1/payments/confirm")
dev 환경, production 환경이 있을 때 환경마다 다른 url을 사용할 수는 없을까요?

| 환경 | 주소 |
|:---:|:---:|
| dev | dev-api.tosspayments.com |
| production | api.tosspayments.com |

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/payment/service/PaymentClient.java
> +            String cancelReason = "단순 변심";
슬픈 이유네요. ㅠㅡㅠ

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    private final TossPaymentProperties tossPaymentProperties;
인코딩은 결제 API(ex. toss api)와 관련된 내용이 아닐까요?
PaymentClient에서 진행하면 어떨까요?

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/payment/service/dto/PaymentRequest.java
> +        long amount,
PaymentAmount에선 BigDecimal로 선언하셨는데, long 타입으로 선언한 이유가 있을까요?
소수점이 포함된 금액은 결제할 수 없을까요?

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/reservation/controller/dto/MemberReservationRequest.java
> +        Long amount
NotNull인 경우라면 primitive type을 사용해도 괜찮지 않을까요?

2024-05-29 12:31 UTC, ddu0422 commented on src/main/java/roomescape/reservation/domain/Price.java
> +public class Price {
PayAmount와 동일한 내용인데, 하나로 통일하는건 어떨까요?

2024-05-30 00:37 UTC, Chocochip101 commented
PaymentClient의 에러핸들링 부분에서 가독성을 높이기 위해 try-catch에서toStuatus를 통해 예외를 던지게 했습니다.

2024-05-30 03:46 UTC, Chocochip101 commented on src/main/java/roomescape/global/config/RestClientConfig.java
> +    private static final int CONNECT_TIME_OUT = 2 * 1000;
외부 API 요청이 2초 정도면, 충분하다고 판단했습니다. 

여러 자료를 찾아보니 API timeout을 1~5초 정도로 두는 것을 확인할 수 있었습니다. 또한 일반 데이터 요청이 아닌, 결제 요청이기도 해서 5초로 변경했습니다.

2024-05-30 03:46 UTC, Chocochip101 commented on src/main/java/roomescape/global/config/RestClientConfig.java
> +//        restTemplate.setErrorHandler(new DefaultResponseErrorHandler());
삭제했습니다 😅

2024-05-30 03:47 UTC, Chocochip101 commented on src/main/java/roomescape/global/config/RestClientConfig.java
> +    private static final int CONNECT_TIME_OUT = 2 * 1000;
Duration 자료형을 통해 시간을 표현했습니다!

2024-05-30 03:47 UTC, Chocochip101 commented on src/main/java/roomescape/payment/domain/PayAmount.java
> +    }
Price 도메인 내에서 음수인지 검증하는 로직을 추가했습니다.

2024-05-30 03:47 UTC, Chocochip101 commented on src/main/java/roomescape/payment/domain/PaymentType.java
> +        throw new IllegalArgumentException(String.format("%s는 없는 값입니다.", value));
스트림을 통해 depth를 줄였습니다.

2024-05-30 03:52 UTC, Chocochip101 commented on src/main/java/roomescape/reservation/controller/dto/MemberReservationRequest.java
> +        Long amount
primitive type을 사용해도 충분히 가능합니다. 

그러나 null일 경우 특정한 에러 메시지를 사용자에게 전달해야 할 때, `@NotNull`을 사용하여 ControllerAdvice를 통해 일관된 에러 메시지를 전달할 수 있고, client 친화적인 에러 메세지를 전달할 수 있다고 생각해 붙이는 것이 괜찮다고 판단했습니다.

2024-05-30 03:52 UTC, Chocochip101 commented on src/main/java/roomescape/reservation/domain/Price.java
> +public class Price {
Price로 통일했습니다.

2024-05-30 03:53 UTC, Chocochip101 commented on src/main/java/roomescape/payment/service/PaymentClient.java
> +                    .uri("https://api.tosspayments.com/v1/payments/confirm")
application.yml 파일에서 local, dev, prod profile을 나누어 다른 base-url을 갖게 했습니다.

2024-05-30 03:56 UTC, Chocochip101 commented on src/main/java/roomescape/payment/service/dto/PaymentRequest.java
> +        long amount,
이전 미션에서 Request가 long이였는데, BigDecimal로 변환하는 것을 깜빡했네요 😅

2024-05-30 03:59 UTC, Chocochip101 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    private final TossPaymentProperties tossPaymentProperties;
말씀해주신대로 Encoder 결제 API와 관련된 정보나 구성을 담고 있다는 의견에 동감해 PaymentClient 클래스에서 해당 작업을 처리하게 변경했습니다.

또한 TossPaymentProperties도 마찬가지로 PaymentClient 클래스에서 처리하게 했습니다.

이렇게 변경하니 결제 API와 관련된 작업을 한 곳에 집중시켜 코드가 관리하기 쉽고 응집도가 높아졌습니다!

2024-05-30 04:01 UTC, Chocochip101 commented on src/main/java/roomescape/payment/service/PaymentClient.java
> +                    .uri("https://api.tosspayments.com/v1/payments/confirm")
application.yml 파일에서 환경 변수로 주입을 해주었습니다. 또한 url의 base-url과 뒷 부분인 path 부분을 따로 관리할 수 있게 수정했습니다.

```yml
payment:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    base-url: https://api.tosspayments.com/v1
    confirm-path: /payments/confirm
    cancel-path: /payments/%s/cancel
```

2024-05-30 04:13 UTC, Chocochip101 commented on src/main/java/roomescape/payment/domain/PayAmount.java
> +        return Objects.equals(getAmount(), payAmount.getAmount());
getter를 사용하지 않을 경우에는 조회한 엔티티가 프록시인 경우 필드에 직접 접근하면 원본 객체를 가져오지 못하고 프록시 객체의 필드에 직접 접근해버리게 됩니다. equals와 hashcode를 JPA 프록시 객체로 구현할 때 해당 값이 없으며 null이 나오게 됩니다. 하지만 getter를 통해 조회하면 프록시가 원본 객체를 호출해 의도한 로직이 수행되게 됩니다.

그래서 저는 equals와 hashcode 생성 시, 기본 설정으로 IntelliJ 내부에서 getter를 사용하게 설정했습니다. 위의 Amount에서는 PayAmount 자체가 엔티티가 아니기 때문에 상관 없지만, getter를 호출함으로써 성능상 단점은 없다고 생각해(있으면 가독성...?) 모든 equals와 hashcode에 getter를 사용하게 했습니다.

2024-05-30 04:27 UTC, Chocochip101 commented
> 저는 사용자 예약할 때 결제 내역을 확인할 수 있다는 점에서 괜찮다고 생각해요.
DB 스키마 변경 때문에 고민하시는 내용이라면, 그 때마다 DB 스키마를 변경하면 되지 않을까요?

지금 같이 처음 시작하는 개발환경에서는 현재 필요한 정보만 저장해도 충분한 것 같아요.

하지만 실제 운영환경에서 기능을 추가할때마다, DB의 스키마를 고치는게 어렵다고 생각했어요. 기능 추가할때마다 DB를 수정하고, 수정된 DB를 적용하기 위해 DB 수정(ALTER, BATCH UDPATE), 더 나아가 마이그레이션과 같은 작업을 해줘야 할 것 같아요.

DB 마이그레이션에 대해서는 아는 지식이 거의 없지만 테이블이 틀어지기도 해서 어려운 작업이라고도 들었어요. 이러한 요소들과 성능 등을 고려해서 DB 테이블을 설계하는게 재미있으면서도, 정말 어려운 것 같아요 😁

2024-05-30 12:11 UTC, ddu0422 approved these changes
안녕하세요 초코칩! 미르입니다 :)

미션 구현 잘 해주셨네요~
이만 머지 진행하겠습니다 :D

다음 미션에서 만나요 💪🏻

2024-05-30 12:11 UTC, ddu0422 commented on src/main/java/roomescape/global/entity/Price.java
> +        }
0의 상수를 재사용하면 어떨까요?

2024-05-30 12:11 UTC, ddu0422 commented on src/test/java/roomescape/global/entity/PriceTest.java
> +    @ParameterizedTest
올바르게 생성되는 테스트(경계값 테스트)도 진행해보면 어떨까요?

2024-05-30 12:11 UTC, ddu0422 commented
맞습니다 ㅜㅡㅜ 언제나 DB Table 설계는 어렵죠.
저는 Table이 빈번하게 주로 변경이 되어 마이그레이션, 코드 수정 등을 많이 진행하고 있습니다.. 😢 
Table 재설계도 가끔 진행한답니다.

2024-05-30 12:11 UTC, merged