[1단계 방탈출 결제/배포] 러쉬(이태훈) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #3
Opened 2024-05-28 10:52 UTC by xogns1514

안녕하세요 비밥! 러쉬입니다. 레벨 2 마지막 리뷰어로 만나뵈어 반갑습니다.
이번 미션을 수행하면서 외부 API 연결은 처음 경험해보았습니다.
빠르게 피드백 받고 코드 수정해보려 합니다.
궁금한 사항은 코드에 남겨두겠습니다!
마지막 미션 리뷰 잘 부탁드립니다🙇🏻‍♂️

[스프링 및 웹 개발 경험]
스프링을 이용해서 간단한 게시판 CRUD를 제작해본 경험이 있습니다. 하지만 스프링 개념은 많이 부족한 상태입니다.

[변경사항](https://github.com/woowacourse/spring-roomescape-payment/pull/3/files/d4ca6e297320f93e9c6f40df8fe55f90427b9773..4baafadf968744588b1e7f0bdcee6f6a647e47e0)

2024-05-28 11:59 UTC, xogns1514 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        }
[답변]
잘못된 secretKey로 API 요청시 toss에서 반환하는 오류는 다음과 같습니다.
<img width="829" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/66353672/c2102a5c-6487-4c88-8744-0ce9a284d36e">

하지만 실제 원인은 서버에서 잘못된 secretKey 설정이므로, 방탈출 예약 클라이언트에게는 Internal Server Error(500)을 반환해야 한다고 생각하는데요. 
비밥은 어떻게 생각하시나요?

2024-05-29 08:17 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        }
이 부분은 정의하기 나름인것 같습니다.

저도 500에러를 내보낼 것 같네요.

2024-05-29 08:39 UTC, pci2676 requested changes
반갑습니다. 🤠 

조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    private static final int READ_TIMEOUT = 40;
질문입니다. connection / read time out을 위와 같은 값으로 설정한 이유가 있을까요?

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    }
toss가 아닌 다른 결제사를 연동하는 경우에 새로운 ClientHttpRequestFactory가 필요해질것 같은데요

그러한 경우에도 동일한 timeout 설정값을 가지게 될 것 같은데 어떻게 생각하시나요?

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    }
또한 개발환경과 운영환경 등 환경에 따라 설정값이 달라질 수 있을때 어떻게 하면 대응이 용이할까요?

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
`@Value`를 이용하여 프로퍼티를 주입하는 방법도 있지만 `@ConfigurationProperties`또한 굉장히 많이 사용하는 방식이니 참고해주세요.

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
생성자에 특정한 로직이 들어가는것은 가능하면 지양하시는것이 좋습니다.

지금의 코드는 문제가 없을 수 있지만 위와 같이 생성자에서 특별한 로직이 들어가는 경우

제어할 수 있는 영역에서 많이 벗어나게 되기때문입니다.

2024-05-29 08:39 UTC, pci2676 commented on src/main/resources/application.properties
>  spring.jpa.properties.hibernate.format_sql=true
properties를 `.yml` 포맷으로 관리하는 방법에 대해 알고계실까요?

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +public class PaymentService {
해당 서비스에 대한 테스트가 없는것 같습니다. 테스트를 작성해주세요.

별개로 `MockRestServiceServer`를 이용하면 RestClient의 테스트를 수행하실 수 있습니다.

결제는 애플리케이션에서 가장 핵심이 되는 만큼 오류에 치명적이기도 합니다.

따라서 이번에 결제 관련된 도메인을 다룰때 꼼꼼하게 테스트를 해보시면 큰 도움이 될 것 같습니다.

2024-05-29 08:39 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        }
catch를 통해 에러에 대한 대응을 하려고 하시는군요 👍 

그런데 4xx status 코드와 함께 응답이 오면 exception이 발생하는것이 맞나요?

connection/read time out이 발생해도 해당 catch 구문에서 정상적으로 처리가 될까요?

2024-05-29 08:46 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +        return ClientHttpRequestFactories.get(settings);
get을 이용하여 구현체를 선택한 이유는 무엇일까요? 구현체중 후보로 생각해보신게 있으실까요?

2024-05-29 08:47 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        }
또한 가능하면 외부에서 발생한 에러의 경우 에러를 추적할 수 있도록 에러 전문을 로그로 남기시는것을 추천드립니다.

2024-05-31 06:10 UTC, xogns1514 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        }
[반영완료]
해당 부분은 500에러를 내보내도록 수정했습니다.

2024-05-31 07:24 UTC, xogns1514 reviewed
안녕하세요 비밥 러쉬입니다. 피드백 바탕으로 리팩토링했습니다. 
test를 진행하면서 많은 trouble이 있었네요.ㅎㅎ 
이번 리뷰도 잘 부탁드립니다.🙇🏻‍♂️

2024-05-31 07:24 UTC, xogns1514 commented on src/main/java/roomescape/payment/service/PaymentRestClientConfiguration.java
> +    }
[질문]
createRestClientBuilder 내부에서 factory를 주입해주면, `@RestClientTest`시 RestClient.Builder가 Mocking되지 않는 문제점을 발견했습니다. [링크](https://github.com/spring-projects/spring-boot/issues/38832) 해당 링크를 참고해 RestClientCustomizer를 사용하면 해결된다는 사실을 알게되었는데요. 내부에서 주입하면 왜 Mocking 되지 않는지 모르겠습니다. 혹시 비밥은 원인을 아시나요?

2024-06-01 06:56 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    private static final int READ_TIMEOUT = 40;
문서를 참고하여 적용하신 값이군요 좋습니다! 👍 

보통 API 를 제공하는 측에서 read time out까지 걸리는 시간이 10초라고 한다면 사용하는 측은 11초로 fit하게 설정하는 편이니 참고해주세요.

2024-06-01 07:04 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationCreateService.java
> +        paymentService.confirmPayment(PaymentConfirmRequest.from(request));
DB transaction 내에서 외부 통신을 하는 것은 지양하는 것이 좋은데요.

해당 이유에 대해서 한번 추측해보시고 답변해주시면 좋을것 같습니다. 😄

2024-06-01 07:04 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +        return ClientHttpRequestFactories.get(settings);
나중에 시간이 되시면 각 구현체 별 장단점에 대해 알아보시면 좋을것 같습니다.

검색해보시면 이미 많은 벤치마킹 조사결과가 있으니 쉽게 확인해보실 수 있을것 같습니다.

2024-06-01 07:06 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    }
저는 보통 Builder를 여러개 만들어서 일급 컬렉션으로 관리합니다. 그리고 일급컬렉션 객체를 bean으로 관리합니다.

일급 컬렉션 bean에서 원하는 빌더를 찾아와서 restClient를 생성하여 주입하는 편 입니다.

2024-06-01 07:08 UTC, pci2676 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    }
개인적으로 Qulifier를 좋아하지 않아서요 😄

2024-06-01 07:14 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        } catch (HttpClientErrorException | HttpServerErrorException exception) {
toss가 아닌 kakao pay를 이용한다면 이 서비스를 그대로 사용할 수 있을까요?

의존성 역전을 이용하여 조금 더 추상화해보면 좋을것 같습니다.

2024-06-01 07:14 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentRestClientConfiguration.java
> +    }
정확히 기억은 안나는데 아마 builder에 대해서 mocking을 진행하는 것으로 알고 있는데요.

RestClient는 이미 완성된 객체라서 mocking이 안되는 것으로 알고 있습니다.

customizer는 전역으로 적용되기때문에 mocking할 builder가 customizer를 타고 먼저 반영이 되고

clientRequestFactory를 mockFactory로 변경하면서 mocking이 수행되는것으로 알고 있습니다.

2024-06-01 07:19 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentRestClientConfiguration.java
> +    }
지금 잠깐 디버그를 해보니까 mock의 시점이 다른것때문인것 같네요.

builder -> `restClientCustomizer()` -> mocking -> `createRestClientBuilder()`

mocking 이후에 builder에서 명시적으로 factory를 설정해주기때문에 mocking이 안되는것으로 보입니다. 😄 

그래서 customizer에는 baseurl, defaultHeader와 같은 설정을 안해주어도 상관없습니다.

2024-06-01 07:31 UTC, pci2676 requested changes
질문에 대한 답변과 추가 리뷰를 조금 남겨두었으니 확인해주세요.

2024-06-01 07:31 UTC, pci2676 commented on src/test/java/roomescape/payment/service/PaymentServiceTest.java
> +    private PaymentService paymentService;
1. MockRestServiceServer는 전역으로 함께 사용하는 의존성 객체인것 같습니다. 테스트의 생명주기를 이용해서 원상태로 돌릴 수 있는 장치를 추가해보시면 좋을것 같습니다.

2. 위와 같이 테스트를 구성하면 테스트를 수행하기 위해 새로운 spring context를 수행해야하는 문제가 있습니다. 지금은 비용이 적을 수 있지만 수십, 수백개의 테스트가 생성되면 무시하기 힘든 비용이 될 수 있습니다.  MockRestServiceServer를 직접 구성하여 단위 테스트를 수행할 수 있으니 해당 방법에 대해서도 한번 알아보시면 좋을것 같습니다. (꼭 반영하실 필요는 없습니다.)

2024-06-01 07:31 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentRestClientConfiguration.java
> +                .requestFactory(clientFactory())
이 customizer는 전역으로 적용이 되기때문에 여러개의 RestClient에서 모두 동일하게 설정되기를 바라는 설정이 아니라면 피하는 것이 좋을것 같습니다.

각 결제사마다 다른 설정값을 필요로 하는데 모두 같은 clientFactory를 사용하면 조금 곤란한 상황이 될것 같습니다.

2024-06-02 15:52 UTC, xogns1514 commented
안녕하세요 비밥! 러쉬입니다. 피드백 바탕으로 리팩토링 해보았어요.
크게 변경된 사항은` ResClientBuilder bean 등록 방식` `결제 서비스 test` 부분 입니다.
일급 컬렉션 bean 등록 방식으로 바꾸면서, 객체지향을 간과하고 스프링에 어노테이션에 너무 의존하고 있었나? 라는 생각이 들기도 했습니다..🥲
리뷰 잘 부탁드립니다🙇🏻‍♂️

2024-06-02 15:54 UTC, xogns1514 reviewed
안녕하세요 비밥! 러쉬입니다. 피드백 바탕으로 리팩토링 했습니다. 
크게 변경된 부분은 `RestClientBuilder bean 등록 방식`, `결제 서비스 test` 부분입니다.
특히 일급컬렉션 bean 등록 방식으로 변경해보면서, 객체지향을 잊고 너무 spring 어노테이션에 의존하고 있나? 라는 생각이 들었네요🥲
리뷰 잘 부탁드립니다🙇🏻‍♂️
[변경사항](https://github.com/woowacourse/spring-roomescape-payment/pull/3/files/b3c7d1420e677e3bbe2716861ef808169c337238..116508409519951151b8c7b065e271b374bee96d)

2024-06-02 15:54 UTC, xogns1514 commented on src/main/java/roomescape/payment/service/PaymentRestClientConfiguration.java
> +                .requestFactory(clientFactory())
[반영완료]
RestClientCustomizer 를 통해 Builder를 setting 하는 부분은 삭제되었습니다.

2024-06-02 15:54 UTC, xogns1514 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    }
[답변]
Bean 여러개를 등록하는 방법말고 일급 컬렉션으로 관리하는 방법이 있군요..! 생각하지 못한 방법입니다.
`@Quailifer` 를 사용하면 코드 작성은 간단하나, Spring에 강결합(?) 하는 느낌도 있긴하네요. 붙여야할 어노테이션이 많아지기도 하고요. 일급 컬렉션 한번 적용해보겠습니다.!

[반영완료]
RestClientBuilders 일급 컬렉션을 이용해, bean 등록시 각 property에 맞게 Builder를 생성하고 추가해주었습니다.

2024-06-02 15:54 UTC, xogns1514 commented on src/test/java/roomescape/payment/service/PaymentServiceTest.java
> +    private PaymentService paymentService;
[반영완료]
기존 `@RestClientTest`을 사용하던 방식에서 `@BeforeEach` 를 통해 MockRestServiceServer에 필요한 설정을 수동으로 추가했습니다. 또한 `@AfterEach`를 통해 메서드 종료 이후, MockRestServiceServer를 초기화 해주었습니다.

2024-06-03 10:32 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationCreateService.java
> +        paymentService.confirmPayment(PaymentConfirmRequest.from(request));
추측해주신 부분 모두 맞습니다 👍 

가장 큰 이슈는 적어주신 것처럼 외부 통신이 모종의 이유로 긴 시간동안 통신을 하게되는 경우 db connection을 너무 오랫동안 점유하게 되면서 connection pool의 connection이 고갈되면서 장애로 번지는 경우가 있습니다.

>당장 떠오르는 방법으로는 ReservationService, PaymentService를 갖고있는 상위 service에서 두가지를 처리하는 방식이 떠오릅니다.

저는 위와 같은 방식으로 처리하는 편입니다 😄

2024-06-03 10:37 UTC, pci2676 approved these changes
지난 리뷰에 대한 반영을 깔끔하게 해주셨네요.

트랜잭션 분리에 대한 부분은 다음 단계를 진행할때 먼저 선행해주시면 좋을것 같습니다.

이번 단계에서 나누어볼 이야기는 모두 나눈것 같아 merge 하겠습니다. 🚀

2024-06-03 10:37 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationCreateService.java
> +    }
지난 리뷰에서 이야기를 나눈 것 처럼 트랜잭션내에서 외부 api의 호출을 분리해주시면 좋을것 같습니다.

2024-06-03 10:37 UTC, pci2676 commented on src/main/java/roomescape/payment/config/PaymentRestClientConfiguration.java
> +    }
👍

2024-06-03 10:37 UTC, pci2676 commented on src/test/java/roomescape/payment/service/TossPaymentServiceTest.java
> +class TossPaymentServiceTest {
👍

2024-06-03 10:38 UTC, merged