[1단계 방탈출 결제 / 배포] 엘라(오숙현) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #31
Opened 2024-05-29 09:30 UTC by oshyun00

안녕하세요 비밥! 백엔드 6기 엘라입니다.☺️
레벨 2 마지막 미션으로 만나뵙게 되어 정말 반갑습니다!

이번 미션은 페어의 코드로 진행했습니다.

예약 대기 시 결제 처리 여부, 예약 취소 시 환불과 같은 부분도 구상했었는데 이번 단계에서는 주어진 요구사항을 우선적으로 반영해보고자 했습니다.
추가 기능들이 필요하다면 구현해 볼 예정입니다!

이번 미션의 변경사항은 다음과 같습니다: 링크

잘 부탁드리겠습니다.🙇🏻‍♀️

---

### 웹개발경험
Java, 스프링 기반으로 간단한 웹 애플리케이션을 만든 경험이 있습니다.
배포 없이 로컬에서만 서버를 띄워봤습니다.
학습 자료를 따라하는 방식으로 학습하여 스프링의 개념이나 원리에 대해 깊게 알고있지는 못합니다.

---

### 테스트용 계정
```
일반 회원
아이디: kaki@email.com
비밀번호: 1234

관리자 회원
admin@email.com
1234
```

2024-05-30 03:28 UTC, pci2676 requested changes
반갑습니다. 🤠 

조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인해주세요.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/config/PaymentConfig.java
> +    }
toss가 아닌 다른 결제수단을 사용하는 경우 RestClient가 여러벌이 생길 수 있을것 같은데 이를 관리하기 좋은 구조를 고민해보셔도 좋을것 같습니다.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
`@Value`도 좋지만 `@ConfigurationProperties`도 한번 알아보시면 좋을것 같습니다.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                .onStatus(HttpStatusCode::is4xxClientError, (request, response) -> handleClientErrorResponse(response))
onStatus를 이용해서 4xx대 에러를 핸들링해주시는군요 👍 

connection/read timeout은 이 부분에서 핸들링이 될까요?

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
Authorization은 항상 고정된 값을 가지고 있는것 같은데 builder를 이용해서 고정시켜두는것도 하나의 방법이 될 수 있을것 같습니다.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .build();
지금처럼 RestClient를 생성하는 경우 실제 통신을 담당하는 객체를 선택하지 않고 기본 구현체를 사용하게 되는데 이는 의도하신 부분일까요?

아니라면 선택할 수 있는 구현체들에 대해 알아보시면 좋을것 같습니다.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
이 부분은 하나의 인터페이스 구현체로도 보이는 것 같습니다.

구현체를 만들고 테스트를 추가해보면 좋을것 같습니다.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +public class PaymentService {
해당 서비스의 테스트가 없는것 같습니다.

참고로 `RestClient`는 `MockRestServiceServer`를 이용하면 테스트할 수 있으니 참고해주세요.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        restClient.post()
timeout 관련 설정이 보이지 않는것 같은데 timeout에 대해 알고 계실까요? 

모르고 계신다면 찾아보시고 설정을 추가해주세요.

2024-05-30 03:28 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    private void handleClientErrorResponse(ClientHttpResponse response) throws IOException {
에러에 대한 처리를 하실때는 에러에 대한 추적이 용이하도록 전문을 남기는것도 큰 도움이 되니 참고해주세요.

2024-05-31 04:50 UTC, oshyun00 commented on src/main/java/roomescape/config/PaymentConfig.java
> +    }
RestClient를 필드로 갖는 결제수단별 클래스를 정의하고, Config에서 RestClient를 주입하는 방식으로 수정했습니다.
만약 다른 결제수단이 추가된다면 PaymentRequest에 `결제 방식`에 대한 정보를 추가하고, 해당되는 xxxClient를 사용하도록 작성할 수 있을 것 같습니다! (혹은 결제수단별로 Service를 정의하고 상위 Service를 둘 수도 있을 것 같아요.)

2024-05-31 04:54 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
`@ConfigurationProperties`를 사용하면 관련 값을 한번에 가져올 수도 있네요! 

`@ConfigurationProperties`로 사용할 속성을 정의하고, Config에서 `@EnableConfigurationProperties`로 해당 속성을 사용할 수 있도록 했습니다.

알아보니 애플리케이션 수준에서 `@ConfigurationPropertiesScan`를 사용해 `@ConfigurationProperties`로 등록된 모든 설정을 등록할 수도 있다고 하는데 혹시 어떤 방식이 더 선호되는지 궁금합니다!
(혹은 제가 사용한 방법이 잘못되었거나, 더 좋은 방법이 있으면 공유해주셔도 좋을 것 같아요🙇🏻‍♀️)

2024-05-31 04:56 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
Toss에 요청을 보내려면 항상 Authorization을 설정해주어야하므로 RestClient에서 고정된 값을 갖는게 좋은 것 같습니다! defaultHeader로 설정해줄 수 있어서 적용해보았습니다.

2024-05-31 06:07 UTC, oshyun00 commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .build();
RestClient를 생성할 때 사용하는 HTTP library나 message converter 등을 설정해줄 수 있네요!
RestClient는 Http요청을 보낼 때 client HTTP library를 사용하는데, `JdkClientHttpRequestFactory`, `HttpComponentsClientHttpRequestFactory`, `JettyClientHttpRequestFactory`, `ReactorNettyClientRequestFactory`, `SimpleClientHttpRequestFactory(default)` 등이 있었습니다.

이번 프로젝트는 규모가 작고 요청이 많지 않아 별도 라이브러리 설정이 필요 없는 JdkClientHttpRequestFactory를 사용했습니다. 요청이 많거나 복잡한 설정이 필요한 경우 HttpComponentsClientHttpRequestFactory를 사용할 것 같습니다.

2024-05-31 06:19 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        restClient.post()
Connection timeout은 설정 시간까지 연결되지 않으면 발생하는 Timeout, Read Timeout은 설정 시간까지 서버에서 응답이 오지 않으면 발생하는 Timeout입니다. 
토스 문서에서 제안한대로 Read Timeout은 30초로 설정하고, Connection Timeout은 서버에 연결할 수 없는 상황을 빠르게 감지하기 위해 5초로 설정했습니다.

2024-05-31 08:07 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    private void handleClientErrorResponse(ClientHttpResponse response) throws IOException {
예외를 처리할 때 로그를 남기도록 수정했습니다. 잘못된 파라미터 입력 등의 사용자 차원에서의 예외들은 warn 레벨로 남기도록 하였으나, 외부 API를 사용하는 예외, 그 외 처리되지 않은 예외는 빠르게 확인하고 대처할 수 있도록 error 레벨을 사용했습니다.
혹시 말씀하신 방식이 이 내용이 맞을까요? 혹시 제가 잘못 이해했다면 말씀 부탁드립니다!🙇🏻‍♀️

2024-05-31 18:28 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +public class PaymentService {
`MockRestServiceServer`를 사용해서 테스트 코드 추가하였습니다. 그런데 그 과정에서 RestClient를 Bean으로 등록하는 방식을 수정하게 되었는데요, 말씀하신 방식이 이 방식이 맞는지 궁금합니다.
이 외에 다른 방법들로 테스트해봤을 때 RestClient가 Mocking 되지 않아 테스트가 정상적으로 수행되지 않았습니다. 혹시 추가로 학습해보거나 시도할 수 있는 다른 방법이 있으면 말씀해주시면 좋을 것 같아요!

2024-05-31 18:33 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                .onStatus(HttpStatusCode::is4xxClientError, (request, response) -> handleClientErrorResponse(response))
Timeout 등 리소스 접근에 실패하면 ResourceAccessException이 발생했습니다. RestClient를 테스트하려고 mock을 주입하는 과정에서 mock 설정이 제대로 안돼서 ResourceAccessException를 마주했었습니다.😅 이 경우는 서버에서 에러 응답을 주는 경우가 아니라 onStatus에서 처리되지 않습니다. try-catch문으로 이 부분에 대한 예외 처리를 추가했습니다. 그런데 그러다보니 예외 처리가 일관되지 못한 것 같다는 생각이 들기도 합니다. (토스 서버에서 주는 에러는 onStatus에서, 요청 중 발생한 에러는 try-catch에서 처리) 혹시 timeout에 대한 처리는 보통 어느 클래스, 어떤 레이어에서 수행하는지 궁금합니다!

2024-05-31 18:44 UTC, oshyun00 commented
안녕하세요 비밥! 엘라입니다.
남겨주신 리뷰를 통해 많이 학습하고 있습니다! 감사합니다. 처음 접하는 내용이 많아 시간이 꽤 걸렸습니다.😭
피드백 반영 내용과 궁금한 부분은 코멘트로 남겨두었습니다. 이번 리뷰도 잘 부탁드립니다.

2024-06-01 07:38 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        paymentService.pay(PaymentRequest.from(reservationSaveRequest));
DB transaction 내에서 외부 통신은 지양하시는 것이 좋은데요.

이유에 대해 알고계실까요? 모르신다면 한번 추측해서 답변을 해주시면 좋을것 같습니다. 😄

2024-06-01 07:38 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                .onStatus(HttpStatusCode::is4xxClientError, (request, response) -> handleClientErrorResponse(response))
알아보신 대로 api가 내려주는 응답이 아니라서 timeout과 같은 socketException의 경우 try-catch로 별도 처리를 해주는 것이 보편적인 방식입니다.

혹은 interceptor를 통해 interceptor 내부에서 try-catch를 하는 방법도 있을것 같네요.

명세에 대한 처리만 해당 client handler 설정으로 해준다고 생각하고 봐주셔도 좋을것 같습니다.

2024-06-01 07:39 UTC, pci2676 commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .build();
좋네요 👍 

이미 알아보셨을수 있지만 해당 구현체들에 대한 성능 벤치마크 결과는 많은 사람들이 해주어서 쉽게 검색하여 찾아볼 수 있으니

시간적 여유가 있으시면 한번쯤 알아보시는 것을 권장드립니다. 😄

2024-06-01 07:55 UTC, pci2676 commented on src/main/java/roomescape/config/PaymentConfig.java
> +    }
이렇게 customizer를 설정하면 생성하려는 모든 restClient에 동일한 설정이 적용될 것 같은데요.

toss가 아닌 restClient에도 tossErrorHandler를 설정하려는 것은 의도하지 않은 방향일것 같습니다.

아마 customizer를 설정하신 이유는 테스트에서 mocking이 잘 되지 않았기 때문일것 같은데요.

mocking을 하려는 부분은 requestFactory이니 다른 설정값들이 모든 restClient에 동일하게 적용될 것이 아니라면 여기서 설정하지 않는게 더 좋지 않을까 싶습니다.

그리고 여기서 requestFactory를 설정하는 것도 모든 restClient가 같은 requestFactory를 사용하게 되는 것이니 이 부분또한 과연 의도한 방향일지 고민해보시면 좋을것 같습니다.

timeout과 같은 속성은 api를 제공하는 측마다 다를 수 있기 때문입니다.

2024-06-01 07:55 UTC, pci2676 commented on src/main/java/roomescape/config/PaymentConfig.java
> +
해당 값들은 애플리케이션이 실행되는 환경별로 달라질 수 있어서 고정된 값을 설정하는 것보다 다른 방향으로 개선하시는것을 권장드립니다. 😄 

그리고 보통 api를 제공하는 측에서 공유한 readtimeout보다는, 지금의 경우 30초, 정확히 요청에 대한 처리가 완료되는 경우를 감안해서 1초의 여유를 두시는 것이 안정적입니다. 

10초 -> 11초의 read time out

2024-06-01 07:55 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +public class PaymentService {
좋습니다. 👍 

저는 작성해주신 방법을 적극적으로 활용하는 편은 아닌데요.

spring context가 새롭게 생성되어야 하는 단점이 있습니다. 비용이 값싸 보일 수 있지만 테스트의 개수가 늘어나면 이 또한 무시못할 비용으로 작용할 수 있습니다.

그래서 저는 MockRestServiceServer를 직접 생성하여 테스트 하는 방법을 더 선호합니다. 단위테스트로도 수행할 수 있어 빠르고(물론 통합테스트도 가능합니다.) customizer와 같은 방식을 사용하지 않고도 수행할 수 있거든요.

그래서 저는 RestClient를 Bean으로 생성하지 않고 RestClient.Builder를 여러개 생성해서 일급컬렉션 Bean을 생성하여 관리하는 편입니다. (여러곳과 외부통신을 해야하기 때문에 일급컬렉션으로 관리하고 있습니다.)

2024-06-01 07:55 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    private void handleClientErrorResponse(ClientHttpResponse response) throws IOException {
좋습니다.

한가지 첨언을 드리자면 parsing이 실패했을때를 대비한 로그도 추가로 남겨주시면 더 좋을것 같습니다. 😄

2024-06-01 07:56 UTC, pci2676 requested changes
질문에 대한 답변과 리뷰를 조금 남겨두었으니 확인해주세요.

2024-06-02 01:39 UTC, oshyun00 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        paymentService.pay(PaymentRequest.from(reservationSaveRequest));
두가지 이유가 있을 것 같습니다.
**1. 트랜잭션이 외부 API 호출을 롤백하지는 않는다.** 
결제 이후 애플리케이션 로직에서 예외가 발생하더라도, 결제가 취소되지는 않습니다. 하나의 트랜잭션 관리되고 있지만, 외부 API와의 작용은 데이터베이스 트랜잭션이 아니므로 별도로 관리해야합니다.
**2. 외부 API와의 통신 시간이 트랜잭션 시간에 영향을준다.** 
데이터베이스와 통신하기 위해 커넥션을 사용하는데, 하나의 트랜잭션에서 외부 API 호출까지 수행하게 되면 호출 시간동안 해당 커넥션을 잡고있게 됩니다. 커넥션 풀은 제한적이므로 여러개의 요청이 발생하면 커넥션을 획득하지 못한 요청은 대기해야하고, 애플리케이션 성능이 저하됩니다.
예약을 위한 하나의 동작 단위라고 생각해서 트랜잭션으로 묶어두었는데, 위와 같은 관점에서 분리해주는게 맞을 것 같습니다. 혹시 다른 이유나 잘못된 부분이 있다면 말씀해주시면 감사드리겠습니다!

2024-06-02 05:45 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    private void handleClientErrorResponse(ClientHttpResponse response) throws IOException {
실제로 파싱 과정에서 에러가 발생했었고, 그걸 해결하기 위해  ObjectMapper에 `configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);` 설정을 추가했었는데요.😅 이렇게 처리하기 보다는 잘못된 응답이 온 것 또한 예외상황이니 로그를 남기고 예외처리를 하는게 더 좋은 것 같습니다! 파싱 에러를 처리하고 로그를 남기도록 수정했습니다.

2024-06-02 09:18 UTC, oshyun00 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +public class PaymentService {
`MockRestServiceServer.bindTo(testBuilder).build();` 방식으로 테스트코드에서 MockRestServiceServer를 생성할 수 있었습니다. test용 RestClient.Builder를 만들어서 MockServer에 넣어주면 되고, 마찬가지로 TossPayRestClient에도 testBuilder를 넣어서 사용할 수 있었습니다. 그 결과 spring context의 생성 없이 단위테스트 할 수 있었어요.
여러개의 결제 업체가 있다고 하면 RestClient도 여러개 생성되어야하는데요, 현재 방식이라면 리팩터링 전과 마찬가지로 하나의 RestClient 밖에 생성할 수 없었네요.🥲 말씀해주신 것 처럼 Builder를 생성해서 Bean 등록하는 방법으로 수정했습니다.

2024-06-02 09:25 UTC, oshyun00 commented on src/main/java/roomescape/config/PaymentConfig.java
> +    }
RestClient를 Bean으로 등록하고 나니 mocking이 되지 않아서 적용했던 방식인데요, 다른 리뷰에서 말씀해주신 것 처럼 Builder를 Bean으로 등록해두고 RestClient를 생성할 때 적절한 Builder를 주입받도록 하니 mocking이 가능했습니다!
그리고 timeout 관련 속성도 property로 분리했는데요, RestClient, RequestFactory가 해당되는 property에 따라 생성되도록 수정했습니다.

2024-06-02 09:28 UTC, oshyun00 commented on src/main/java/roomescape/config/PaymentConfig.java
> +
처리 완료 시간을 고려할 수 있다는 점도 알게 되었네요. 감사합니다.😊
통신하는 외부 업체별로 url, timeout 등을 적용하도록 설정 파일을 분리하고, read timeout에 여유 시간 추가하였습니다!

2024-06-02 10:17 UTC, oshyun00 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        paymentService.pay(PaymentRequest.from(reservationSaveRequest));
추가로, 지금은 결제 로직을 예약 서비스에서 분리해서 결제 부분은 트랜잭션에서 제외되도록 했습니다. 그런데 상황에 따라 `DB 저장은 완료되었으나 이후에 결제에 실패하면 DB 저장을 rollback`하거나, 반대로 `결제 이후 DB 관련 로직에서 예외가 생기면 결제를 취소`하는 로직이 필요할 수도 있을 것 같은데요, 이런 처리들은 어떤 방식으로 하시는지 궁금합니다! (혹시 제가 너무 복잡하게 생각한걸까요🤔 )

2024-06-02 22:38 UTC, pci2676 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    }
> `@ConfigurationProperties`로 사용할 속성을 정의하고, Config에서 `@EnableConfigurationProperties`로 해당 속성을 사용할 수 있도록 했습니다.
> 
> 알아보니 애플리케이션 수준에서 `@ConfigurationPropertiesScan`를 사용해 `@ConfigurationProperties`로 등록된 모든 설정을 등록할 수도 있다고 하는데 혹시 어떤 방식이 더 선호되는지 궁금합니다! (혹은 제가 사용한 방법이 잘못되었거나, 더 좋은 방법이 있으면 공유해주셔도 좋을 것 같아요🙇🏻‍♀️)

`@EnableConfigurationProperties` 을 사용해서 최소한의 범위에서 사용가능하도록 하는것을 선호하는 편입니다. 😄

2024-06-02 22:43 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        paymentService.pay(PaymentRequest.from(reservationSaveRequest));
찾아주신 이유가 맞습니다. 👍 

>그런데 상황에 따라 DB 저장은 완료되었으나 이후에 결제에 실패하면 DB 저장을 rollback하거나, 반대로 결제 이후 DB 관련 로직에서 예외가 생기면 결제를 취소하는 로직이 필요할 수도 있을 것 같은데요
..
(혹시 제가 너무 복잡하게 생각한걸까요🤔 )

좋은 고민입니다 👍 

어떠한 전략을 취할 것이냐에 따라 여러가지 방법이 있을것 같은데요.

보편적인 방법으로는 타 시스템과 대사(compare, reconsiliation)를 통하여 데이터 불일치 상태에 대한 처리를 하곤 합니다.  
여기서는 결제사와의 대사 작업이 되겠네요.  
이러한 작업을 위해 결제 전후로 데이터를 남기곤 합니다.

2024-06-02 22:47 UTC, pci2676 approved these changes
리뷰로 남긴 내용에 대해 깔끔하게 반영해주신 것 같고

이번 단계에서 나누어볼만한 내용은 모두 나누어본것 같습니다.

merge 하겠습니다. 🚀

2024-06-02 22:47 UTC, pci2676 commented on src/main/java/roomescape/exception/TossPayErrorHandler.java
> +        this.objectMapper = new ObjectMapper();
`configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)`는 왜 제거하셨을까요??

혹시 제가 parsing이 실패할때를 염두한 리뷰를 남겨서였을까요?

제가 parsing이 실패하는 경우를 말씀드린 이유는 `PaymentErrorResponse`의 형태가 아닌 다른 형태의 응답을 파싱하려했을때를 가정한 실패를 말씀드린것이었습니다.

2024-06-02 22:47 UTC, merged