[1단계 방탈출 결제 / 배포] 구름(김민수) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #4
Opened 2024-05-28 11:09 UTC by alstn113

안녕하세요 찰리! 구름 ⛅️ 입니다.

1단계는 외부 결제 연동이었어요.
예약 금액이나 기타 부가적인 것들은 2-4단계에서 내용인 것 같아서 제외하고 개발했어요.

결제 승인에 대해서 테스트를 하고 싶었지만 paymentKey같은 것을 도저히 받을 수 없어서 테스트할 수 없었어요. 
어떻게 처리하면 좋을까요?

미리 리뷰 감사합니다! 😊

2024-05-29 12:22 UTC, Gomding reviewed
안녕하세요 구름!
미션 빠르게 진행해주셨는데 리뷰가 늦어서 죄송합니다 🥲
몇가지 코멘트 남겼으니 확인해주세요!

궁금한 점 있으면 편하게 DM이나 코멘트 남겨주세요!

2024-05-29 12:23 UTC, Gomding requested changes
안녕하세요 구름!
미션 빠르게 진행해주셨는데 리뷰가 늦어서 죄송합니다 🥲
몇가지 코멘트 남겼으니 확인해주세요!

궁금한 점 있으면 편하게 DM이나 코멘트 남겨주세요!

2024-05-29 13:44 UTC, alstn113 commented on README.md
> +## 미션 4 요구사항
아래는 결제 요청 과정이에요.
![image](https://github.com/woowacourse/spring-roomescape-payment/assets/75781414/5653e80f-22f5-46bf-99a6-efae7ba66209)

클라이언트에서 토스 페이먼츠에 위젯을 통해 `결제 요청`을 하고 응답으로 paymentKey등을 받아요.
> 결제 요청 시 실제 휴대폰으로 QR을 찍고 결제를 해요.

그 값으로 방탈출 서버에 `결제 정보 전달`을 포함한 예약 요청을 해요. 
서버에서는 예약 생성과 토스 페이먼츠에 `결제 승인`을 보내요.

이 과정에서 paymentKey를 받아서 처리하기가 힘들더라구요.
테스트를 할 필요가 있는 부분인지도 모르겠어요.

2024-05-29 13:46 UTC, alstn113 commented on src/main/java/roomescape/application/PaymentClient.java
> +public interface PaymentClient {
토스가 아닌 다른 결제사를 사용할 수도 있고, 요청 방법이 달라질 수도 있다고 생각했어요.
그래서 service에는 interface로 빼고, 구현은 infra에 뒀어요.

그리고 실제로 하지는 않았지만 Fake 객체를 만들어서 테스트할 수도 있겠다고 생각했어요.

2024-05-29 13:49 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +            @Value("${payment.read-timeout-ms}") int readTimeoutMs
개인적으로 전전 미션부터 ConfiguartionProperties를 사용해볼려고 했으나 이점을 아직 못 느꼈어요.
우선 properties에 대한 depth도 깊지 않고, IDE로 바로 값을 확인할 수 없을 뿐만 아니라 테스트할 때도 properties 객체를 따로 만들어줘야하는게 귀찮더라구요.

물론 ConfiguartionProperties로 관리하면 객체로 관리할 수 있고, 검증도 할 수 있다는 장점이 있다는 것을 알아요.

2024-05-29 13:56 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +    public RestClient restClient(
우선 페어와 저 모두 java spring으로는 외부 요청 API를 처음 사용해봤어요.
그래서 의존성이 없는 RestTemplate, RestClient을 학습 테스트로 먼저 공부했어요.
RestTemplate에 비해 RestClient가 예외 처리도 쉽고, 직관적이더라구요. 
개인적으로 다른 것들을 사용해볼려고 찾아봤으나 의존성이 필요했고, 추가적인 학습?이 필요하더라구요.

그래서 RestClient를 사용해게 되었습니다.

2024-05-29 14:09 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +                .setSoTimeout(Timeout.ofMilliseconds(readTimeoutMs))
Read Timeout은 클라이언트에서 설정한 시간까지 서버에서 응답이 오지 않으면 발생해요. 클라이언트와 서버가 연결은 됐지만, 서버가 클라이언트의 요청을 정상적으로 처리 못 했을 때 일어나요. Read Timeout은 클라이언트에서 너무 많은 데이터를 조회했거나, 서버가 요청을 처리하는데 시간이 오래 걸려서 발생하는 경우가 많아요.

Read Timeout은 연결은 됐지만 서버가 요청을 처리하지 못할 때 일어나요. 
특히 서버가 요청을 처리하는데 시간이 오래 걸려서 주로 발생한다고 생각해요.

토스 페이먼츠 문서에 Read Timeout은 30-60초로 설정하면 된다고하더라구요.
제 일반적인 경험 상 크게 오래 걸린 적이 없는 것 같아서 최소 값인 30초로 정했어요.

[토스 페이먼츠 타임아웃 문서](https://docs.tosspayments.com/resources/glossary/timeout)
![image](https://github.com/woowacourse/spring-roomescape-payment/assets/75781414/fe7062b2-77ea-48af-bef4-be4c314f4b3b)

2024-05-29 14:16 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +                .setConnectTimeout(Timeout.ofMilliseconds(connectionTimeoutMs))
Connection Timeout은 클라이언트에서 설정한 시간까지 서버에 연결되지 않으면 발생해요.

이 부분을 보는게 맞는지 모르겠지만 Connection Timeout이 3분으로 되어있더라구요.
일반적으로 어느 정도로 설정하는지 확인해보니 5~30초로 설정하더라구요. 
그래서 5초면 적절할 것이라 판단했습니다.

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/75781414/cef0c109-ee1b-4128-9cd0-2696af1fd0e3)

2024-05-29 14:54 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +            @Value("${payment.base-url}") String paymentBaseUrl,
baseUrl은 프로퍼티니까 변경가능하다고 생각했었습니다.
근데 결제뿐만 아니라 더 범용적으로 사용할 수 있겠네요.

baseUrl을 TossPaymentClient로 이동시키고, timeout부분도 payment가 아니라 client라는 이름으로 변경했습니다.

https://github.com/woowacourse/spring-roomescape-payment/pull/4/commits/e6824683dc246708d078a8995bc74de84543fc3a

2024-05-29 14:54 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +        connectionManager.setDefaultConnectionConfig(connectionConfig);
createConnectionManager으로 분리했습니다!

2024-05-29 15:26 UTC, alstn113 commented on src/test/java/roomescape/application/ReservationServiceTest.java
> +    private PaymentClient paymentClient;
외부 API 요청이 들어가면 컨트롤러나 서비스에서 적절하게 가짜 객체를 이용해서 단순하게 테스트를 하는게 맞다고 생각합니다. 
그래도 한 번쯤은 실제 요청을 끼고 전체 동작을 테스트해야 신뢰성이 생긴다고 생각했어요.

2024-05-29 15:59 UTC, alstn113 commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +                    throw new PaymentException(errorResponse.message());
흠,,, 정확히 의미를 모르겠어요. 
의미를 모르겠다기 보다는 어느 정도까지 처리를 하는게 맞는지 궁금해요.

토스 페이먼츠 결제 승인에 [예외 코드](https://docs.tosspayments.com/reference/error-codes#%EA%B2%B0%EC%A0%9C-%EC%8A%B9%EC%9D%B8)들이 많이 있어요.

클라이언트 에러 부분에 대해서는 클라이언트한테 그대로 넘기고, 
서버 에러 부분에 대해서는 "결제 승인 에러입니다."와 같은 특정한 예외 메세지를 넘기는 것을 방법이 좋은 걸까요?

다른 방법이 잘 떠오르지 않네요 ,,,

2024-05-29 16:00 UTC, alstn113 commented
추가 변경 사항입니다.

1. 'AUTHORIZATION'을 HttpHeaders.AUTHORIZATION으로 변경했습니다. https://github.com/woowacourse/spring-roomescape-payment/pull/4/commits/f1eb62d3f5a28d316cac6d923085f4772a7b7dcc

2. 결제 금액을 Long에서 BigDecimal로 변경했습니다. https://github.com/woowacourse/spring-roomescape-payment/pull/4/commits/11a91ac673815dae175cd29b112e2de35390e805

2024-05-30 08:27 UTC, alstn113 commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +                    throw new PaymentException(errorResponse.message());
클라이언트와 서버 에러로 분리해서 처리해줬습니다. 

https://github.com/woowacourse/spring-roomescape-payment/pull/4/commits/9955535611aa74b4cbe9061c8d25028a5d1d568f

2024-05-30 14:34 UTC, Gomding commented on README.md
> +## 미션 4 요구사항
자세한 설명 감사해요! 😊
테스트 관련해서는 이후 코멘트에서 다뤄볼게요!

2024-05-30 14:34 UTC, Gomding commented on src/main/java/roomescape/application/PaymentClient.java
> +public interface PaymentClient {
> 토스가 아닌 다른 결제사를 사용할 수도 있고, 요청 방법이 달라질 수도 있다고 생각했어요.
> 그래서 service에는 interface로 빼고, 구현은 infra에 뒀어요.

DIP를 활용해서 멋지게 구현해주셨네요 :)
구름이 말하는 infra 계층은 어떤 계층일까요?

2024-05-30 15:39 UTC, alstn113 commented on src/main/java/roomescape/application/PaymentClient.java
> +public interface PaymentClient {
제가 생각하는 인프라 계층은 다른 계층을 지원하고, 외부 시스템과의 통합, 기술적 세부 사항을 관리하는 역할을 한다고 생각해요.
예를 들어 application에 있는 인터페이스 PaymentClient의 구현체인 TossPaymentClient와 같이 외부 요청 API가 있고, 구체적으로 어떻게 통신하는지를 관리한다고 생각해요.

2024-05-30 15:45 UTC, alstn113 commented on src/main/java/roomescape/config/ClientConfig.java
> +                .setConnectTimeout(Timeout.ofMilliseconds(connectionTimeoutMs))
Read Timeout의 경우에는 5초가 짧은 것 같은데 Connection Timeout의 경우 5초 정도면 문제가 있는 것이 아닌가 생각이 들었어요(개인적인 생각)

하염없이 기다리면 스레드 풀의 스레드를 계속 점유하는 문제가 생겨요. 이것은 스레드 풀의 고갈로 이어질 수 있고 서버가 응답하지 못하는 상황으로 연결될 수 있어요.

2024-05-30 16:06 UTC, alstn113 commented on src/main/java/roomescape/application/ReservationService.java
> +
어떤 부분을 말하시는걸까요?

save 다음 개행을 한 이유는 생성과 지불이라는 성질이 달라서 입니다.
paymentClient.confirmPayment 다음 개행을 한 이유는 return이 잘 보이라고 항상 return 위를 띄우는 편입니다.

2024-05-30 16:16 UTC, alstn113 commented on src/main/java/roomescape/application/dto/request/ReservationRequest.java
> +        String paymentType,
조금 복잡해지긴 했지만 추후 확장을 생각하면 좋은 것 같아요.
참고로 AdminReservationWebRequest, ReservationWebRequest라는 Web Dto가 있고, 서비스로 줄 때 ReservationRequest로 변경해서 줍니다. 혹시 헷갈리실 것 같아서요. 

외부 API 요청에 사용하는 것들을 PaymentApiResponse, PaymentApiRequest로 변경했습니다.

https://github.com/woowacourse/spring-roomescape-payment/pull/4/commits/d04d15898156656cbc3538bdbff3477be409bc78

2024-05-30 16:27 UTC, alstn113 commented on src/main/java/roomescape/application/dto/request/ReservationRequest.java
> +        BigDecimal amount,
다른 리뷰에서 금액으로 소수점이 나오면 어떻게 할거냐는 피드백을 봤어요.
그래서 저도 그것을 대응하고자 소수점 정밀도가 높은 BigDecimal을 사용했어요. 금액에서 자주 사용하기도 하구요. :)

2024-05-31 00:33 UTC, alstn113 commented on src/main/java/roomescape/application/ReservationService.java
> +        paymentClient.confirmPayment(new PaymentRequest(request.paymentKey(), request.orderId(), request.amount()));
다음 단계에서 공부하고 적용해본 후 알려드리겠습니다 ㅎㅎ,,,

2024-05-31 07:08 UTC, alstn113 commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +                    throw new PaymentException(errorResponse.message());
클라이언트에 보낼만한 것들은 예외 메세지를 보내도록하고 나머지는 "결제 승인 중 오류가 발생했습니다"로 응답했습니다.
추가로 빠른 대응을 위해서 로그를 사용했습니다.

https://github.com/woowacourse/spring-roomescape-payment/pull/4/commits/19a731a4c12c61cb5dc9076701f23d055df96c93

2024-06-01 01:31 UTC, Gomding commented on src/main/java/roomescape/application/PaymentClient.java
> +public interface PaymentClient {
훌륭하네요!
PaymentClient 로 추상화 해놨기때문에 앞으로 결제API를 변경하거나 추가될 수 있는데
PaymentClient 인터페이스에 맞춰서 구현만 하면 다른 결제 API 도 쉽게 사용할 수 있겠네요~ 👍 

PaymentClient가 여럿 생긴다면 이렇게 주입받아 볼 수도 있겠네요 :)

```java
@Service
@Transactional(readOnly = true)
public class ReservationService {

    private final ReservationRepository reservationRepository;
    private final ReservationTimeRepository reservationTimeRepository;
    private final ThemeRepository themeRepository;
    private final MemberRepository memberRepository;
    private final WaitingRepository waitingRepository;
    private final List<PaymentClient> paymentClient;

}

@Component
public class APaymentClient {
}

@Component
public class BPaymentClient {
}
```

2024-06-01 02:22 UTC, Gomding approved these changes
안녕하세요 구름!
코멘트 반영하느라 고생하셨어요 👍 👍 👍 
요구사항은 다 만족하셔서 이번 단계는 이만 머지할게요 :)
다음단계도 화이팅입니다~

2024-06-01 02:22 UTC, Gomding commented on src/main/java/roomescape/application/dto/request/ReservationRequest.java
> +        String paymentType,
변경사항까지 설명해주셔서 감사해요!
리뷰어를 배려하여 반영 커밋 링크까지 남겨주시는것이 너무 친절하네요 👍

2024-06-01 02:22 UTC, Gomding commented on src/main/java/roomescape/infra/payment/TossPaymentClient.java
> +            RestClient restClient,
잘 수정해주셨네요!! 👍

2024-06-01 02:22 UTC, merged

2024-06-01 03:09 UTC, alstn113 commented on src/main/java/roomescape/infra/payment/PaymentConfirmErrorCode.java
> +public enum PaymentConfirmErrorCode {
아 그러네요! 
Infra인데 구체적으로 적는 걸 깜빡했네요