[1단계 방탈출 결제 / 배포] 리브(김민주) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #52
Opened 2024-05-30 04:00 UTC by Minjoo522

안녕하세요, 아서! 리브입니다. 😊
벌써 마지막 미션이네요 😭
1단계 구현 완료하여 PR 보냅니다.
잘 부탁 드립니다!

## 이번 미션 변경 사항
링크

## 웹 개발 경험
- Django를 사용하여 로컬에서 동작하는 웹 애플리케이션을 구현해 본 경험이 있습니다.
- Spring은 레벨 2에서 처음 사용해봤습니다.

## 0 단계 기본 코드 준비
- 타인의 코드를 기반으로 요구사항을 구현하는 경험이 의미 있다고 생각하여 페어인 `비토`의 코드로 선택하였습니다.
- **제 코드 작성 스타일과 다른 부분이 있었지만 이번 미션의 요구사항에 집중하기 위해 최대한 기존 코드의 컨벤션을 따르고 변경이 꼭 필요한 부분이 아니라면 변경하지 않았습니다.**

## 1 단계 예약 시 결제단계 추가
- 예약이 취소되면 가장 첫 번째 예약 대기의 `status`가 `RESERVATION`으로 변경되며 `자동 승인`되는 구조였습니다.
  - 결제가 추가되며 결제 대기(`PAYMENT_WAITING`) `status`를 추가하여 예약이 취소되면 첫 번째 예약 대기 `status`를 `PAYMENT_WAITING`으로 변경하도록 변경했습니다.
- REST API 호출을 위하여 `RestClient`를 사용했습니다.
  - 학습 테스트와 공식 문서를 통해 `RestTemplate`, `WebClient`도 알게 되었는데 추가로 의존성을 주입할 필요도 없으며 가독성이 좋은 `RestClient`를 선택했습니다.
- `HttpInterface`를 사용하여 선언적으로 HTTP 서비스를 정의할 수 있도록 했습니다.
- 결제 실패 시 API에서 전달 받은 에러 객체를 `TossExceptionResponse`로 만들어 클라이언트에 전달하도록 구현 했습니다.
- LMS에 따르면 실제 결제라면 반드시 고려해야 할 보안, DB 트랜잭션 측면의 이슈 등은 이번 미션에서 다루는 범위가 아니기 때문에 고려하지 않았습니다.
- 시크릿키는 커밋하지 않아야 하지만 테스트용 시크릿키이기 때문에 테스트 및 리뷰 편의를 위해 커밋하였습니다.

## 웹 테스팅 시 로그인 정보
|구분|아이디|비밀번호|
|--|--|--|
|ADMIN|admin@wooteco.com|wootecoCrew6!|
|일반회원|member@wooteco.com|wootecoCrew6|

2024-05-31 11:32 UTC, Hyunta requested changes
안녕하세요 리브,
레벨2 마지막 미션 리뷰를 맡게된 아서입니다.
몇가지 커멘트 남겼는데 확인 부탁드립니다.
이해가 안가거나 궁금한점이 있으면 알려주세요!

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +    public PaymentService paymentService(RestClient.Builder restClientBuilder) {
PaymentService는 다른 서비스와 다르게 Configuration을 통해 빈주입을 해준 이유가 있을까요?

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .build();
외부 API가 지연되거나, 네트워크가 느려졌을 때도 고려해야하지 않을까요?
timeout 설정에 대해서 알아봅시다.

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +        String authorization = "Basic " + new String(encodedBytes);
엑세스 토큰을 만드는 일련의 과정을 메서드로 뽑아내면 가독성이 좋아질 것 같네요.

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .baseUrl("https://api.tosspayments.com/v1/payments")
어떤 변수는 application.yml에서 관리하고 어떤 변수는 클래스내에서 작성해주셨는데 어떤 기준으로 나누셨을까요?
해당 변수도 상수로 뽑아내서 의미를 담아봅시다.

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +public class PaymentConfig {
Configuration에서 비즈니스 로직을 좀 많이 갖고 있는 것처럼 보이는데,
Service를 별도로 만들어주면 어떨까요?

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/controller/ReservationController.java
> +    private final PaymentService tossPaymentService;
해당 컨트롤러에서 toss로 결제하는 것을 알 필요가 있을까요?

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/controller/ReservationController.java
> +        ReservationResponse response = reservationService.saveReservationByClient(loginMember, reservationRequest);
결제를 하고 예약을 등록하는 것은 비즈니스 로직 아닐까요?
컨트롤러에서 흐름을 제어하는 것에 대해서 어떻게 생각하시나요?

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/dto/payment/PaymentRequest.java
> +}
금액을 int로 해주셨는데 int의 최대치는 몇인가요? 그것보다 큰 값이 들어오면 어떻게 될지 알아봅시다.
추가로 돈을 나타내기 위해서 어떤 클래스를 사용하면 좋을지 고민해봅시다.

2024-05-31 11:32 UTC, Hyunta commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
결제 에러가 Toss에 종속적으로 설계된 것 같은데 어떻게 생각하시나요?

2024-05-31 11:32 UTC, Hyunta commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +        mockServer.expect(requestTo("https://api.tosspayments.com/v1/payments/confirm"))
baseUrl을 application.yml에서 관리하고 있다면 재사용할 수 있지 않을까요?

2024-05-31 11:32 UTC, Hyunta commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    private MockRestServiceServer mockServer;
외부 API 테스트 구성까지 꼼꼼하게 잘 해주셨네요!

2024-06-02 08:22 UTC, Minjoo522 commented on src/main/java/roomescape/config/PaymentConfig.java
> +    public PaymentService paymentService(RestClient.Builder restClientBuilder) {
사실 `PaymentService`가 이름이 `Service`일 뿐 toss API를 호출하기 위한 RestClient였습니다. 😅
현재 요구사항에서는 `Service`와 `Client`를 분리하더라도 단순 `Client` 메서드를 호출하는 일만 하게 될 것 같아 구분하지 않고 `Service`로 명명했습니다.
하지만, API 호출 이외에 추가 로직이 생길 수 있음을 고려해 `PaymentClient`와 `PaymentService`를 분리하고 `PaymentService`는 `@Service` 어노테이션을 이용해 빈 등록 해주었습니다.

2024-06-02 08:58 UTC, Minjoo522 commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .build();
타임아웃 설정하였습니다. 😊
네트워크 문제나 외부 API 지연 문제가 발생 했을 때 오랜 시간 멈춰있을 필요가 없다 고 생각해서 connection timeout, read timeout 각각 5초로 설정했는데 아서는 보통 어떤 기준으로 timeout 시간을 정하시는지 궁금합니다!

2024-06-02 08:58 UTC, Minjoo522 commented on src/main/java/roomescape/config/PaymentConfig.java
> +        String authorization = "Basic " + new String(encodedBytes);
분리하였습니다! 감사합니다. 😊

2024-06-02 09:07 UTC, Minjoo522 commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .baseUrl("https://api.tosspayments.com/v1/payments")
toss payment 관련 변수들을 `application.yml`에 관리하고 `@ConfigurationProperties` 객체를 만들어서 사용하도록 변경했습니다. 😊

2024-06-02 09:12 UTC, Minjoo522 commented on src/main/java/roomescape/config/PaymentConfig.java
> +public class PaymentConfig {
Configuration에서는 공통 로직을 관리하고 toss API에 특화된 로직은 따로 빼주었습니다.
Client 생성 로직이 Service에 있는 게 다소 어색하게 느껴져 `TossPaymentClientFactory` 클래스를 생성했습니다.
이 과정에서 최대한 toss에 종속적이지 않게 만들고자 `PaymentClientFactory` 인터페이스를 만들어 `TossPaymentClientFactory`가 구현하도록 했는데 조금 과한 추상화로 보이진 않을지 궁금합니다. 😊

2024-06-02 09:13 UTC, Minjoo522 commented on src/main/java/roomescape/controller/ReservationController.java
> +    private final PaymentService tossPaymentService;
`ReservationService`에서 `PaymentService`를 주입 받아서 사용하도록 변경했습니다.

2024-06-02 09:15 UTC, Minjoo522 commented on src/main/java/roomescape/controller/ReservationController.java
> +        ReservationResponse response = reservationService.saveReservationByClient(loginMember, reservationRequest);
`ReservationService`에서 `PaymentService`를 주입 받는 로직으로 변경하면서 관련 로직도 `ReservationService`로 이동했습니다!

2024-06-02 09:26 UTC, Minjoo522 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +        mockServer.expect(requestTo("https://api.tosspayments.com/v1/payments/confirm"))
application.yml로 옮겨주었습니다!

2024-06-02 10:53 UTC, Minjoo522 commented
안녕하세요, 아서! 리브입니다.
리뷰 감사합니다. ☺️

리뷰 주신 내용 반영하여 코멘트 달아두었습니다.

이번에 리팩토링을 하면서 공통 로직을 모아두고 추상화를 조금 더 신경썼습니다.
특히 RestClient를 생성하는 로직이 한 곳에 있는 게 나은지 나누는 게 나은지 고민을 많이 했던 것 같습니다.
리뷰 잘 부탁드립니다. 😊

2024-06-02 10:56 UTC, Minjoo522 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
```java
@ExceptionHandler(PaymentException.class)
public ResponseEntity<PaymentExceptionResponse> exceptionHandler(PaymentException exception) {
    logError(exception);
    return ResponseEntity.status(exception.getHttpStatus())
            .body(exception.getPaymentExceptionResponse());
}
```

위와 같이 좀 더 global한 네이밍으로 변경했습니다.
혹시 다른 payment API를 사용하게 된다면 응답값은 변경될 수 있기 때문에 `PaymentExceptionResponse`도 추상화 해야하는지 고민했지만 클라이언트 코드에서 code와 message가 응답된다는 상황을 가정하고 있기 때문에 클라이언트와 합의가 된 응답 구조라고 생각하여 유지하였습니다. 😊

```js
}).catch(function (error) {
  // TOSS 에러 처리: 에러 목록을 확인하세요
  // https://docs.tosspayments.com/reference/error-codes#failurl 로-전달되는-에러
  alert(error.code + " :" + error.message + "/ orderId : " + error.orderId);
    });
```

2024-06-02 13:13 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +    public PaymentService paymentService(RestClient.Builder restClientBuilder) {
적절하게 구조를 잘 바꿔주신 것 같네요.
추가로 이런 고민도 해보셨으면 좋겠습니다, 지금 Toss를 통해서 결제하고 있는데 만약 Kakao로 변경된다면 지금 어디어디를 변경해야하나요? 혹시 이 포인트를 줄일 수 있는 방법이 있을까요?

2024-06-02 13:18 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +                .build();
사용하는 서버의 상황을 모르기 때문에 connection timeout 값을 설정할 때 처음에는 따로 설정을 하지 않고 저 또한 기본값인 5초 정도를 세팅해둘 것 같습니다.
초기에 로깅을 통해서 대략적인 성공에 필요한 connection 타임의 평균과 최대치를 보고 값을 조정할 것 같습니다.

read timeout의 경우는 조금 더 넉넉하게 잡을 것 같아요. 결제가 성공적으로 되는 중인데 단순히 서버의 지연으로 5초가 지나서 실패하게 된다면 CS가 많이 인입될 것 같아서요. 차라리 오래걸리더라도 성공하는게 낫지, 아예 실패해버리면 개발자가 처리를 해줘야하기 때문에 초기에는 넉넉하게 잡고 사용을 해보면서 적절한 값을 찾는게 낫지 않을까 싶습니다.

지금은 학습하는 단계이고, 미션 요구사항에 있어서 요청을 드렸습니다. 외부 api에 연동을 해야하는 경우가 종종 있는데 실제로는 timeout까지는 고려하기에는 시간이 모자라서 따로 설정은 하지 않을 때가 많았던 것 같네요ㅎㅎ

2024-06-02 13:21 UTC, Hyunta commented on src/main/java/roomescape/config/PaymentConfig.java
> +public class PaymentConfig {
결제수단은 늘어날 가능성이 다분하니 추상화를 통해 풀어주신 점은 잘하신 것 같습니다.
위에도 남긴 질문이긴한데 지금 확장성에 용이한 구조인지는 한번 고민해보시면 좋을 것 같습니다.

2024-06-02 13:24 UTC, Hyunta commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
적절하게 잘 반영해주셨습니다!

2024-06-02 13:26 UTC, Hyunta approved these changes
안녕하세요 리브,
피드백 반영 잘 해주셨네요ㅎㅎ
관련해서 몇가지 커멘트 남겼는데 확인바랍니다.
다음 단계 하시기전에 구조에 대해서 한번 고민해보시면 좋을 것 같습니다!
이해가 안가거나 궁금한 점이 있으면 알려주세요.

2024-06-02 13:26 UTC, merged