[1단계 방탈출 결제 / 배포] 상돌(이상진) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #53
Opened 2024-05-30 04:26 UTC by pricelees

.

2024-05-30 19:14 UTC, Deocksoo requested changes
안녕하세요 상돌, 러너덕입니다.
외부 API를 사용하는 미션 요구사항에 집중하여 깔끔하게 코드 작성해주셨네요 👍 
고민해보시면 좋을 만한 부분들 리뷰 남겨두었으니, 확인 한 번 부탁드려요~

2024-05-30 19:14 UTC, Deocksoo commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    private final RestClient restClient;
API Client로 RestClient를 사용하셨군요.
이 Client를 사용하신 이유가 있을까요?

2024-05-30 19:14 UTC, Deocksoo commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    private String widgetSecretKey;
@Value 를 사용하는 경우에 설정값에 하드코딩된 문자열로 접근하기 때문에, 해당 설정값에 접근하는 곳이 여러 군데 생기면 관리하기가 어려워진다는 단점이 있어요.
@ConfigurationProperties를 대신 사용해보는 것은 어떤가요?

2024-05-30 19:14 UTC, Deocksoo commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +        paymentService.confirm(reservationRequest);
재미있는 상황을 한번 생각해볼까요 :)
어느날 갑자기 toss payment쪽에서 장애가 나서 API 요청을 했는데 정상 응답을 주지도 않고, 에러도 발생하지 않고, 그냥 가만히 기다리고만 있는 상태가 되었다고 상상해볼게요.
그러면 어떤 문제가 생길까요?

2024-05-30 19:14 UTC, Deocksoo commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .retrieve();
이렇게만 처리를 하면 토스쪽에서 에러가 발생하는 경우 (=RestClient에서 에러가 발생하는 경우) 그 에러문구 그대로 500에러가 발생할 것 같은데요.
사용자가 상황을 파악할 수 있도록 적절하게 처리해주는 것은 어떤가요?

2024-05-30 19:14 UTC, Deocksoo commented on src/test/java/roomescape/reservation/controller/ReservationControllerTest.java
> +public class ReservationControllerTest {
이 테스트를 포함해서 모든 테스트가 실패하고있는것같아요.
테스트가 잘 동작하도록 한번 쭉 체크해봐주시면 좋겠네요~

2024-06-02 14:57 UTC, pricelees reviewed
러너덕 안녕하세요! 6기 상돌(이상진) 입니다.
우선, 금요일에 좋은 말씀 많이 해주셔서 감사드립니다! 
사용자 입장에서 생각했던 것들을 직접 구현하는 입장에서 고민할 수 있어 있어 좋았고, 사전에 여러 포인트를 말씀해주신 덕분에 마음 편하게 미션을 진행할 수 있었습니다 ㅎㅎ

기본적으로는 남겨주신 커멘트 위주로 수정하였고, 금요일 오전 강의에서 나온 `커스텀 예외는 하나만 설정`하는 것만 추가적으로 수정하였습니다!

새로운 한주도 즐겁고 활기차게 보내세요!
감사합니다🙇

2024-06-02 14:57 UTC, pricelees commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    private final RestClient restClient;
> API Client로 RestClient를 사용하셨군요. 이 Client를 사용하신 이유가 있을까요?

학습 테스트에 있는 RestTemplate와 RestClient를 간단하게나마 사용해봤고, 체이닝을 사용하여 구현하는 점이 조금 더 매력적으로 느껴졌던 것 같습니다!(최신이라는 것도 있습니다..ㅎㅎ)

2024-06-02 14:57 UTC, pricelees commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .retrieve();
> 이렇게만 처리를 하면 토스쪽에서 에러가 발생하는 경우 (=RestClient에서 에러가 발생하는 경우) 그 에러문구 그대로 500에러가 발생할 것 같은데요. 사용자가 상황을 파악할 수 있도록 적절하게 처리해주는 것은 어떤가요?

우선 토스쪽에서의 응답이 400번대인지, 500번대인지에 따라 처리를 조금 다르게 하도록 수정했습니다! [링크](https://github.com/woowacourse/spring-roomescape-payment/blob/49481dee3ccbf4d8d8d251a73a38d89378824103/src/main/java/roomescape/payment/TossPaymentClient.java)

러너덕께서 말씀하시는 것은 토스쪽에서의 500에러를 저희 프로그램에서도 그대로 내릴 필요가 없다는 것일까요? 일단 응답 코드는 토스에서 주는대로 그대로 반환하도록 구현했는데 조금 애매하게 느껴지기는 하네요!😅

2024-06-02 14:57 UTC, pricelees commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    private String widgetSecretKey;
> @value 를 사용하는 경우에 설정값에 하드코딩된 문자열로 접근하기 때문에, 해당 설정값에 접근하는 곳이 여러 군데 생기면 관리하기가 어려워진다는 단점이 있어요. @ConfigurationProperties를 대신 사용해보는 것은 어떤가요?

금요일에 말씀드렸던 것 처럼, 지난 미션에서 반영했던 대로 수정해봤습니다! 
[커밋 - 시크릿키 관리 객체 생성](https://github.com/woowacourse/spring-roomescape-payment/pull/53/commits/19ebb370ca2365bb47164d0603f50ed82c255038)
[커밋 - 별도의 Configuration 객체 생성](https://github.com/woowacourse/spring-roomescape-payment/pull/53/commits/d69ea72389c9b6b5f3a4aeecd8b9d278c26db22a)

이 두 커밋을 확인해주시면 감사하겠습니다!!

2024-06-02 14:57 UTC, pricelees commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +        paymentService.confirm(reservationRequest);
> 재미있는 상황을 한번 생각해볼까요 :) 어느날 갑자기 toss payment쪽에서 장애가 나서 API 요청을 했는데 정상 응답을 주지도 않고, 에러도 발생하지 않고, 그냥 가만히 기다리고만 있는 상태가 되었다고 상상해볼게요. 그러면 어떤 문제가 생길까요?

금요일에 강조하셨던 부분이군요..!! 
아무 응답이 없다면 차라리 미리 끊어주는게 좋다는 생각인데, timeout 설정이 해결책이 될 수 있다는 것을 알게 되어 바로 반영해 보았습니다 ㅎㅎ 
[커밋 - timeout 설정](https://github.com/woowacourse/spring-roomescape-payment/pull/53/commits/dab9d5e2dd8ef4a62676175bfe5328f72e352a1a) 을 확인해주시면 감사하겠습니다!

2024-06-02 14:57 UTC, pricelees commented on src/test/java/roomescape/reservation/controller/ReservationControllerTest.java
> +public class ReservationControllerTest {
> 이 테스트를 포함해서 모든 테스트가 실패하고있는것같아요. 테스트가 잘 동작하도록 한번 쭉 체크해봐주시면 좋겠네요~

외부 API 도입을 생각하지 못했습니다🥲 이 부분은 MockBean 어노테이션으로 수정하였고, 나머지 테스트가 모두 정상 동작하는것을 확인하였습니다. 다음부터는 조금 더 꼼꼼하게 반영하도록 하겠습니다.🙇

[커밋 - 테스트 수정](https://github.com/woowacourse/spring-roomescape-payment/pull/53/commits/6d86f1406bc9d53f243b57ecb541da527a283f57) 을 확인해주시면 감사하겠습니다!

2024-06-03 11:43 UTC, Deocksoo approved these changes
안녕하세요 상돌, 러너덕입니다.
리뷰 드린 부분들 잘 반영해주셨네요 👍 
다음 미션 계속 진행해주시면 되겠습니다.
간단한 리뷰 몇 개 남겨두었으니, 다음 미션 진행하시면서 확인한번 부탁드려요.

2024-06-03 11:43 UTC, Deocksoo commented on src/main/java/roomescape/payment/PaymentConfig.java
> +                .withConnectTimeout(Duration.ofSeconds(3L));
timeout을 잘 설정해주셨군요 👍 
타임아웃을 3초로 설정한 이유는 무엇인가요?

2024-06-03 11:43 UTC, Deocksoo commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .retrieve();
토스페이먼츠 API 응답이 400대 응답이 오더라도 서버측에서 제대로 전환하지 않으면
500대 에러가 발생할것같아서 드린 리뷰였어요.

400대와 500대를 잘 구분했다면 충분할 것 같네요.

2024-06-03 11:43 UTC, Deocksoo commented on src/main/java/roomescape/payment/TossPaymentClient.java
> +                .header("Authorization", getAuthorizations())
이런 헤더들은 요청때마다 매번 만들어주지 않고 default header로 빼두어도 괜찮겠네요.

2024-06-03 11:43 UTC, merged