[1단계 방탈출 결제 / 배포] 안나(김민겸) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #56
Opened 2024-05-30 05:32 UTC by Mingyum-Kim

안녕하세요 제이미 !
레벨1 체스 미션에 이어서 또 만나게 되었네요.  🤩🤩  다시 만나서 너무 반갑습니다.

저는 스프링을 사용해서 서비스를 만들고 배포까지 해본 경험이 있지만, 스프링을 깊게 공부한 적이 없어 다양한 기술 사용에 미숙합니다. 

### 방탈출 예약 정책 및 구현 소개

##### 사용자 / 관리자 예약 시 

* 사용자 예약 시 결제해야만 예약이 가능합니다. 
* 관리자 예약 시 결제하지 않아도 예약이 가능합니다. 
* 예약 대기는 결제하지 않아도 가능합니다.
* 예약 취소 시 환불 기능은 따로 구현하지 않았습니다. 

##### 관리자 예약 대기 승인 시

* 수동 승인으로 구현하였습니다.
* 예약 대기 상태의 예약을 수동 승인하였을 때, `결제 대기` 상태로 전환되도록 하였습니다.
* 결제 대기 상태의 예약을 UI에서 확인하는 것은 따로 구현하지 않았습니다. 우선 데이터베이스에서 확인해주시면 감사하겠습니다.
* 이미 결제 대기 중인 예약이 있거나 확정된 예약이 있으면 수동으로 다른 예약을 승인할 수 없습니다.

### 로그인 정보

##### 관리자 로그인

아이디 : admin@email.com
비밀번호 : 1234

##### 사용자 로그인 

아이디 : jojo@email.com
비밀번호 : 1234

이번 미션의 변경 사항을 참고해서 리뷰해주시면 편할 것 같습니다. 😎
궁금한 점은 코드에 남겨놓겠습니다. 

감사합니다!

2024-05-30 06:25 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
[질문] 

토스의 외부 API에 요청을 보내는 해당 기능을 테스트할 필요가 있는 지 궁금합니다. 저는 페어와 토론한 후 외부 API를 굳이 테스트할 필요가 없다고 생각해서 예약을 저장하는 기능에서는 해당 부분을 Mocking하였습니다. 제이미의 생각은 어떠신가요? 외부 API 에서 실제로 결제 승인이 이루어지고 있는 지 확인할 필요가 있을까요?

2024-05-31 05:15 UTC, jamie9504 requested changes
안녕하세요, 안나 😄 리뷰어 제이미입니다.

2레벨에서 다시 만나게 되어 반갑습니다!
간단하게 코멘트 남겨두었습니다.

오늘 하루도 좋은 하루 보내세요~!

2024-05-31 05:15 UTC, jamie9504 commented on src/main/java/roomescape/startup/DataFixture.java
> +    public static final Member MEMBER_JOJO = new Member(null, Role.MEMBER, new MemberName("조조"), "jojo@email.com",
DataFixture를 사용했을 때의 이점은 무엇이 있나요?

2024-05-31 05:15 UTC, jamie9504 commented on src/main/java/roomescape/common/exception/PaymentException.java
> +    private final int statusCode;
HttpStatusCode를 그냥 저장해주지 않는 이유가 있나요?

2024-05-31 07:35 UTC, Mingyum-Kim commented on src/main/java/roomescape/common/exception/PaymentException.java
> +    private final int statusCode;
[답변] 

굳이 HttpStatusCode 객체를 저장할 필요는 없다고 느꼈습니다. 어짜피 int 형 변수 하나만 쓰여서 그 외의 필드를 클래스가 알 필요가 없다고 생각했어요.
다른 커스텀 예외 클래스들과의 통일성도 하나의 이유였습니다!

2024-05-31 07:36 UTC, Mingyum-Kim commented on src/main/java/roomescape/startup/DataFixture.java
> +    public static final Member MEMBER_JOJO = new Member(null, Role.MEMBER, new MemberName("조조"), "jojo@email.com",
[답변] 

가독성이 좋다는 장점이 있었습니다. 데이터 저장 역할을 하는 클래스 (DataLoader)와 데이터 객체 생성 역할을 하는 클래스 (DataFixture) 를 나누어서 유지보수가 좋아진다고 느꼈습니다.

2024-05-31 07:54 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +        this.encodedSecretKey = encodeSecretKey(encodedSecretKey);
[반영 완료] 

앗 그러네요 😅😅 수정하였습니다!

2024-05-31 07:57 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/domain/Status.java
> +    }
[반영 완료] 

`==`을 사용해 비교하도록 수정하였습니다!

2024-05-31 07:58 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/controller/dto/request/ReservationPaymentSaveRequest.java
> +        @NotNull long themeId,
[반영 완료]

`long`타입은 null 이 들어오지 않기 때문에 @NotNull이 도달하기 전에 오류가 생기네요 👍 
`Long` 타입으로 수정하고 @NotNull을 사용해 오류를 처리하도록 수정하였습니다.

2024-05-31 08:17 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public ReservationResponse saveByAdmin(ReservationSaveRequest saveRequest) {
[답변]  

관리자와 다르게 사용자는 예약 시 결제를 합니다. 그래서 파라미터가 달라지는데, 이러한 차이가 있기 때문에 메서드를 합치는 것이 오히려 불편하다고 느꼈습니다.
현재는 예약 로직이 간단해서 중복 로직이 많이 생기지는 않지만, 예약 로직이 복잡해지면 메서드를 합칠 필요가 있겠네요.  컨트롤러에서 예약 DTO와 결제 DTO를 분리해서 서비스에 주입해주는 방식을 사용할 수 있을 것 같습니다. 하지만 관리자 예약 시 결제 DTO에 null이 들어가야한다는 점이 조금 불편하고, 지금 단계에서는 두개의 메서드를 사용하는 게 더 나아보여요. 
혹시 제 의견에 대해 제이미는 어떻게 생각하시나요? 메서드를 합칠 더 중요한 이유가 있을까요?

2024-05-31 08:55 UTC, Mingyum-Kim commented on src/main/java/roomescape/common/exception/ExceptionApiController.java
> +        return ResponseEntity.status(exception.getStatusCode())
[반영 완료] 

아니요! 외부 API 에서 제공하는 상태코드를 그대로 사용하면 경우에 따라서 사용자 입장에서  혼란이 생기는 문제가 있을 수 있겠네요. 서버 오류에 해당하는 에러코드를 따로 분리하여 일치하는 경우 500 에러로 반환하도록 하였습니다.

2024-05-31 08:56 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/controller/dto/request/ReservationSearchCondRequest.java
> +@ValidDateRange
[반영 완료] 

이름이 조금 불명확했던 것 같네요 😅 `@ValidDateSearchPeriod` 로 네이밍하였습니다.

2024-05-31 11:27 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +        this.restClient = RestClient.builder().baseUrl(paymentBaseUrl).build();
[답변]

처음에는 RestClient가 더 최신식(?)이라고 해서 채택했던 것 같습니다. 😀 사용하다보니 빌더 패턴을 사용할 수 있는 장점과 이를 이용한 함수 체이닝으로 깔끔하게 헤더를 설정, 오류를 핸들링할 수 있다는 것이 장점으로 느껴졌습니다.

RestClient로 타임아웃 설정이나 인증, 요청 필터링 등을 처리할 수 있다는 것을 알게되었습니다!

2024-05-31 11:29 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
[답변] 

크루들과 토론해본 결과 외부 API를 테스트할 필요가 없다는 결론을 얻었습니다. 😅
외부 API의 동작 여부가 서버 기능의 테스트의 실패, 성공에 영향을 주는 것이 테스트 불안정성을 높일 것이기 때문입니다.

2024-05-31 11:38 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .header("Authorization", encodedSecretKey)
해당 지점에 
`.header("TossPayments-Test-Code", "INCORRECT_BASIC_AUTH_FORMAT")` 

아래와 같이 에러 코드를 함께 추가하여 요청을 보내면 에러 상황을 시뮬레이션할 수 있습니다! 😀

2024-06-01 11:01 UTC, jamie9504 commented on README.md
>  # 방탈출 기능 요구 사항
// todo

2024-06-01 11:01 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
그렇다면 외부 API를 테스트하지 않는다면,
예를 들어 외부 API의 SPEC에 변경이 있다던가 했을 때는 어떻게 알아차릴 수 있을까요?

2024-06-01 11:02 UTC, jamie9504 commented on src/main/java/roomescape/common/exception/ExceptionApiController.java
> +        return ResponseEntity.status(exception.getStatusCode())
// todo

2024-06-01 11:23 UTC, jamie9504 requested changes
안녕하세요, 안나 😄 리뷰어 제이미입니다!

코멘트 간단하게 조금 더 남겨두었어요.
다음 리뷰 요청시엔 Approve & Merge 예정입니다.

즐거운 주말 보내세요!

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
그렇다면 외부 API를 테스트하지 않는다면,
예를 들어 외부 API의 SPEC에 변경이 있다던가 했을 때는 어떻게 알아차릴 수 있을까요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    public ReservationResponse saveByAdmin(ReservationSaveRequest saveRequest) {
두 방법 모두 옳다/그르다는 아닙니다!
안나가 적어준대로 다른 방법의 장점이 있을 수 있기에 이런 저런 가정을 해보면 좋을 것 같아서 적어둔 코멘트였어요.

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/controller/dto/request/ReservationSearchCondRequest.java
> +@ValidDateRange
기준 기간은 애너테이션을 보았을 때 바로 확인이 되지 않는데, 이 부분은 어떻게 생각하시나요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/startup/DataFixture.java
> +    public static final Member MEMBER_JOJO = new Member(null, Role.MEMBER, new MemberName("조조"), "jojo@email.com",
그렇다면, DataLoader & DataFixture을 사용한 조합과 data.sql으로 sql을 명시한 방법은 어떠한 장/단점이 있을까요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +            throw new RuntimeException();
예외 메시지는 작성해주지 않아도 될까요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .withReadTimeout(Duration.ofSeconds(30));
ConnectTimeout과 ReadeTimeout을 각각 1ms, 30s으로 설정한 이유는 무엇인가요?

(정정) 이후 commit에서 변경되어 30s, 30s로 설정했네요! 이렇게 설정한 이유는 무엇인가요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/resources/application.yml
> -        format_sql: true
로그에 sql을 출력하지 않는 이유가 있나요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +                .build();
만약 여러 Service에서 RestClient를 사용하고자 한다면, 해당 방식은 어떻게 변경될까요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +                    .body(PaymentErrorResponse.class);
`.toBodilessEntity()`를 사용하는 것과 어떤 차이가 있을까요?

2024-06-01 11:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +        if (customErrorCode.isPresent()) {
ifPresent를 이용해봐도 되겠네요!

2024-06-01 15:58 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/controller/dto/request/ReservationSearchCondRequest.java
> +@ValidDateRange
[답변]

음 애너테이션에서 `LIMIT_DAY` 상수로 정의하면 해결이 될 것 같네요. 😀
하지만 제가 생각했을 때는 기준 기간이 얼만큼인지 알고 있는 역할은 애너테이션이라기보다 `DateSearchPeriodValidator` 가 더 적합할 것 같아요. 그래서 애너테이션에서 구체적인 정보를 확인하지 않아도 될 것 같은데요, 
아니면 제이미가 리뷰를 남긴 의도가 애너테이션에서 기간을 검증하는 방법 자체에 대한 부분이었을까요 ?

2024-06-01 16:15 UTC, Mingyum-Kim commented on src/main/java/roomescape/startup/DataFixture.java
> +    public static final Member MEMBER_JOJO = new Member(null, Role.MEMBER, new MemberName("조조"), "jojo@email.com",
[답변] 

기존에 data.sql를 사용하여 더미데이터를 삽입하였는데, 느낀 장단점은 아래와 같습니다. data fixture와 data.sql은 반대의 장단점을 가지고 있다고 보셔도 될 것 같아요.

##### 장점 
* 중복 코드가 사라진다. 
* 불필요한 메모리 로딩이 필요 없다.

##### 단점 
* 객체의 유효성 검사를 거치지 않아 올바르지 않은 데이터가 들어갈 수 있다. 
* 스키마 변경 시 컴파일 시점에서 오류를 잡지 못한다.

기능 변경 시 data fixture를 사용한 방식이 더 효과적일 것이라고 생각하여 data loader와 fixture를 사용하였습니다.

2024-06-01 16:39 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +            throw new RuntimeException();
[반영 완료] 

로그에 에러가 발생한 이유를 남길 필요가 있겠네요 😅 ResouceAccessException이 의미하는 바에 대한 예외 메시지를 추가하였습니다. 

[질문] 

타임아웃에 대한 예외 핸들링을 의도로 해당 catch block을 추가하였는데 타임아웃 이외의 다양한 문제로 인해 진입될 수 있다는 것이 문제점이었어요. RuntimeException으로 예외 전환 시 조금 더 구체적인 메시지를 담고 싶은데 그러지 못한다는 것이 아쉬웠습니다. 
`그러지 못한다는 것이 아쉽다` 하고만 넘기는 게 기술 부채가 될 수 있는 부분일까요? 아니면 RestClient의 한계점이라고 인식하고 다른 Client를 사용하여 보완해야할 부분일까요? 유사한 문제가 있을 때 현업에서는 어떻게 에러 로깅을 처리하는 지 궁금합니다.

2024-06-01 16:55 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .withReadTimeout(Duration.ofSeconds(30));
[답변] 

토스의 [타임아웃 관련 문서](https://docs.tosspayments.com/resources/glossary/timeout)에서 타임아웃은 30초 - 60초 사이에서 설정하는 것이 좋다는 글을 보았습니다. 일반적인 도메인의 타임아웃보다 긴 이유는 결제 도메인이기 때문인 것 같아요. 만약 read timeout이 너무 짧다면 실제로 토스 서버에서 결제승인이 되었는데 사용자에게는 결제 오류가 생겼다고 뜰 것이기 때문입니다.

하지만 사용자 입장에서 대기 시간이 길어진다면 불편함이 생길 것 같아서 30초로 설정하였는데요, 적절한 판단이었는지 제이미의 생각이 궁금하네요!

2024-06-01 17:00 UTC, Mingyum-Kim commented on src/main/resources/application.yml
> -        format_sql: true
[답변] 

요청할 때마다 로그가 콘솔에 쌓임으로써 다른 로그를 확인하기 불편한 것 같아 해당 설정을 제거하였습니다. 처음에 JPA로 전환할 때 내 요청이 어떤 쿼리로 날라가고 있나? 가 궁금해서 학습 차 달아놓은 설정이였기 때문입니다.

2024-06-01 17:01 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +                .build();
[답변] 

외부 config 패키지에서 ClientConfig 클래스를 생성하고 빈 주입을 하는 방식으로 진행할 것 같습니다!

2024-06-01 17:02 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +                    .body(PaymentErrorResponse.class);
[반영 완료] 

`.toBodilessEntity()`를 사용하면 바디에 값을 넣지 않고 반환하는 군요 ! 반환 값을 굳이 사용하지 않고 있으니 조언해주신대로 수정하였습니다. 감사합니다!

2024-06-01 17:11 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +        if (customErrorCode.isPresent()) {
[답변] 

좋은 의견 감사합니다! 하지만 자바에서 람다식 안에서 throw를 할 수 없어서 위와 같이 코드를 작성했습니다. 혹시 다른 회피 방안(?) 을 사용해서 예외를 throw하는 것을 기대하신 걸까요?

2024-06-01 17:54 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
[답변] 

외부 API SPEC이라고 함은 URI나 에러 응답 등이 해당 되겠죠 ? 😂 변경이 되었을 때 알아차리지 못하는 것은 문제가 될 수 있겠네요. 이를 테스트하기 위해 RestClientTest를 사용하는 등 여러 시도를 해보았으나 쉽지 않았네요. 
paymentKey 등의 정보가 없으니 통합 테스트도 역시 쉽지 않은 것 같습니다. 

외부 API 테스트 작성에 대한 제이미의 팁이 있다면 전달해주시면 감사하겠습니다 😅

2024-06-01 20:28 UTC, jamie9504 commented on README.md
> -- [API 요청 폴더 바로가기](api-test)
// todo

2024-06-01 20:28 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +    }
// todo

2024-06-01 21:01 UTC, jamie9504 approved these changes
안녕하세요, 안나 😄 리뷰어 제이미입니다.

이번 미션에서 구현해야 하는 부분들은 충족된 것 같아서 Approve & Merge합니다.
코멘트는 조금 더 남겨두었으니, 확인해보시고 관련한 부분(추가 코멘트 & 작업)은 다음 단계에서 같이 진행해주세요!

행복한 주말 보내세요. 😉

2024-06-01 21:01 UTC, merged

2024-06-05 11:35 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +            throw new RuntimeException();
[반영 완료] 

ResourceAccessException이 던지는 Throwable 객체를 `getCause()` 메서드를 통해 확인할 수 있었네요 😀 보다 정확한 로깅을 위해 catch 블럭에서 로깅을 처리해주었습니다.

2024-06-05 11:37 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/client/PaymentService.java
> +        if (customErrorCode.isPresent()) {
[반영 완료] 

아 한번 변수를 꺼낸 뒤에 람다식을 이용한 것을 말한 것이었군요! 이해했습니다 😄

2024-06-05 11:45 UTC, Mingyum-Kim commented on src/main/java/roomescape/common/exception/ExceptionApiController.java
> +    }
[답변]

별개의 Exception을 잡기 위해서는 서로 다른 핸들러 메소드를 사용해야한다고 생각했던 것 같습니다. 😅 하나의 메서드로 합쳤습니다 👍

2024-06-05 11:47 UTC, Mingyum-Kim commented on src/main/java/roomescape/common/exception/ExceptionApiController.java
> +        return ResponseEntity.status(500).body("서버 내부 오류입니다.");
[반영 완료] 

그러네요! internalServerError()가 있다는 사실을 간과했습니다. 수정하였어요 😄

2024-06-05 11:54 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/service/PaymentService.java
> +                .withReadTimeout(Duration.ofSeconds(30));
[답변]

Connection Timeout은 서버와의 연결이 지연될 때 실패라고 가정하는 시간 기준을 의미합니다. Read Timeout과 다르게 Connection Timeout은 오래 기다린다고 해결될 수 있는 부분이 없는 것 같네요 😓 사용자 경험 상 Connection Timeout을 짧게 설정하고 빠르게 실패시키는 편이 나을 것 같습니다. Connection Timeout은 10초로 수정하였습니다.

2024-06-05 11:56 UTC, Mingyum-Kim commented on src/main/java/roomescape/startup/DataFixture.java
> +    public static final Member MEMBER_JOJO = new Member(null, Role.MEMBER, new MemberName("조조"), "jojo@email.com",
[답변]

그렇다면 ddl-auto를 update로 설정하고 import.sql에서 정의된 INSERT문을 실행하거나, 실행하지 않는 방식으로 수정을 해야할 것 같네요 ! 현재 방식은 무조건 데이터 로딩이 일어나기 때문에 가정하신 상황에 적합하지 않을 것 같습니다 👍