[1단계 방탈출 결제 / 배포] 포케(이무송) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #59
Opened 2024-05-30 06:45 UTC by fromitive

안녕하세요 썬😄 레벨2 마지막 리뷰 리뷰이 포케입니다!

레벨 2의 마지막을 함께할 수 있어 영광입니다 ㅎㅎ

#### 스프링 학습 경험
저는 이전의 프로젝트 경험은 없으며, 테크코스를 하면서 스프링 공부를 시작했습니다!

#### 0단계 설명 및 코드 변경사항
코드는 페어인 무빈의 코드로 미션을 진행했습니다! 이전 미션에서 보셨을 지도 모르겠습니다 😁

변경 사항은 [링크]()를 참고하면 될 것 같습니다 😃

---

그 외, 코드에 대한 궁금한사항이나 고민되는 부분이 있을경우 코드에 코멘트를 남겨 놓겠습니다 😊

레벨 2 마지막 잘 부탁드립니다. 감사합니다!

2024-05-30 07:07 UTC, fromitive commented on src/test/java/roomescape/repository/ReservationTimeRepositoryTest.java
>          List<ReservationTime> allReservedTimes = reservationTimeRepository.findAllReservedTimes(LocalDate.now().plusDays(1), 1L);
이번 미션의 목표는 결제 API를 연동하는 부분이 목표라고 생각하여 최소한의 기능으로 구현했고 페어의 코드를 이해하는데 시간을 쏟았습니다 😄

그 중 제일 먼저 고치고 싶었던 부분은 테스트 코드였습니다! 사전에 작업해줘야하는 데이터가 많아서 요구사항 변경으로인해 컬럼값이 변경될경우 테스트가 많이 깨지게 되었습니다.

이는 요구사항이 변경될 때 마다, 고쳐야 하는 테스트가 많아지면 오히려 코드를 변경하는 것에 대해 거부감을 느끼게 되었고 사전에 사용되는 테스트 데이터(given, when, then 중 given)을 테스트 메서드에서 정의하는 것 보다, 테스트 데이터는 sql에 저장하고 이를 꺼내도록 변경했습니다.

이럴 경우, 테스트가 간결해지는 장점을 얻을 수 있고 코드를 최소한으로 작성할 수 있어 테스트를 추가하거나, 프로덕션 코드 변경이 쉬워질 수 있다고 생각합니다. 

한 편으로는 sql구문을 비즈니스 규칙에 맞춰서 삽입해줘야 하고 처음 테스트 코드를 접하는 개발자 한테는 sql 구문을 분석해야하는 어려움이 존재할 것 같은데, 썬은 이러한 테스트 코드를 봤을 때 어떻게 느껴졌는지 궁금합니다 😃

2024-05-31 15:12 UTC, syoun602 requested changes
안녕하세요 포케! 만나게되서 반가워요 👋

1단계 잘 진행해주셨습니다 😊
몇가지 고민해볼만한 부분 코멘트로 남겨두었으니 확인 후 재요청 주세요~

2024-05-31 15:12 UTC, syoun602 commented on src/main/java/roomescape/service/PaymentService.java
> +                }).toBodilessEntity();
```suggestion
                .onStatus(HttpStatusCode::is4xxClientError, (req, res) -> {
                    throw new PaymentException("결제 정보가 일치하지 않습니다.");
                })
                .onStatus(HttpStatusCode::is5xxServerError, (req, res) -> {
                    throw new PaymentException("결제 시스템이 원활하게 동작하지 않습니다.");
                })
                .toBodilessEntity();
```
민감한 정보에 대해서 적절히 추상화 해주셨네요 👍
하나 더 생각해볼 부분은 만약 외부 API에서 문제가 발생해 수십초간 응답이 오지 않는다면 어떻게 될까요?
Connection Timeout과 Read Timeout은 어떤 차이가 있나요?

2024-05-31 15:12 UTC, syoun602 commented on src/test/java/roomescape/controller/WaitingControllerTest.java
> +@Sql("/controller_test_data.sql")
매번 설정들을 다시 선언해주고 있는데, 테스트 환경을 추상화한 abstractController 클래스를 만들어보는건 어떨까요?

2024-05-31 15:12 UTC, syoun602 commented on src/test/java/roomescape/repository/ReservationTimeRepositoryTest.java
>          List<ReservationTime> allReservedTimes = reservationTimeRepository.findAllReservedTimes(LocalDate.now().plusDays(1), 1L);
TestFixture에 대해서도 알고 계시는지 궁금합니다!
만약 알고 계신다면, 두 방법 중 현재 방식을 선택하신 이유가 있는지, 아니라면 학습해보고 어떤 방식이 더 좋은 것 같은지 공유해주세요 😊

2024-05-31 15:12 UTC, syoun602 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +public class PaymentServiceTest {
외부 연동된 서비스에 대한 테스트는 없나요?
토스 페이먼츠 자체를 테스트한다기보다는 해당 서버에서 4xx, 5xx에 대한 예외가 났을 때,
현재 포케가 만드신 서비스는 어떤 예외를 내릴 지 정의해둔 것 같아서요 🤔

> hint: mockito, MockRestServiceServer

2024-05-31 15:12 UTC, syoun602 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
개발자에게 예외에 대한 추적이 필요할 것 같은데, 어떻게 할 수 있을까요?

> hint: 로깅

2024-06-01 05:44 UTC, fromitive commented on src/main/java/roomescape/service/PaymentService.java
> +    private final static long RESERVATION_PRICE = 1999999;
경제적 자유를 목표로 두고 있기때문에,, 굵고 짧게 해보려고 합니다 😁

2024-06-03 01:59 UTC, fromitive commented on src/main/java/roomescape/service/httpclient/TossPaymentRestTemplate.java
> +}
`RestTemplate`와 `RestClient`가 수행하는 기능이 똑같아 보였습니다. 

둘을 비교하던 중 RestClient가 Stream API와 똑같이 메서드 체이닝 방식의 코드를 작성할 수 있는 것에 매력을 느껴 사용하게 되었습니다.

RestClient와 RestTemplate를 비교하기 위해 Wrapper객체인 `TossPaymentClient`를 만들었습니다.

좀 더 학습을 해보니, 설정을 할 수 있는 빌더를 제공해주었고  *로깅, 에러 핸들링 그리고 타임아웃*을 설정하는데 있어 차이가 없었습니다. [관련 commit TossPaymentConfiguration.java 링크](https://github.com/woowacourse/spring-roomescape-payment/pull/59/commits/571955266ef974f63888027f8c2ac3af6f87962c)

`RestClient`와 다르게 `RestTemplate`는 한 줄로도 의도 전달이 충분함을 느꼈고, 최종적으로 `RestTemplate`를 사용하게 되었습니다 😄

2024-06-03 02:04 UTC, fromitive commented on src/main/resources/toss.yml
> +  connect-timeout: 3
설정 파일로 관리하게 되면 테스트와 프로덕션 환경의 설정을 프로덕션 코드 변경 없이 설정할 수 있다는 장점이 있다고 생각합니다 😃 

그러나, 현재 상황에서는 테스트 시크릿 키를 프로덕션과 테스트 환경 둘다 사용하고 있기 때문에 큰 메리트를 느끼지 못했습니다.

파일로 보관해야 하는 또 다른 이유는, 실제 사용하는 시크릿 키를 사용할 경우 `.gitignore`를 이용하여 코드를 push할 때 제외 할 수 있기에 동작하는 소스코드만 올릴 수 있게 설정할 수 있습니다 😄

2024-06-03 02:06 UTC, fromitive commented on src/test/java/roomescape/controller/AbstractControllerTest.java
> +        MemberLoginRequest request = new MemberLoginRequest(password, email);
`AbstractController`에 대해서 찾다가 자료를 찾을 수 없었습니다. 😢

대신, 공통적으로 처리하는 부분을 추상 클래스에서 설정 하는 말씀을 곰곰이 생각했고, 추상 클래스를 정의하여 공통 처리 부분을 한 곳에 묶었습니다. 혹시 의도하신 부분이 이 부분이 맞으실까요?

2024-06-03 02:20 UTC, fromitive commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +        ReservationRequest request = ReservationRequestBuilder.builder().build();
Fixture를 적용하니, 테스트에 필요한 데이터를 미리 만들어서 테스트 용이성을 향상시킬 수 있었습니다 😄 

또한 어떻게 해야 `Fixture`를 효과적으로 사용할 수 있을지 고민해봤습니다. 값을 미리 만들어 테스트 코드 작성 시간을 단축시킬 수 있었지만, 값이 고정되어있어서 필요한 값을 변경하는 데에 제약사항이 많았습니다. (test를 위해 setter를 등록해야 하는가에 대한 고민) 😢 

이를 해결하기 위해 빌더를 만들게 되었고 테스트 별로 어떤 속성 값을 테스트 하는지 의도를 전달할 수 있다고 생각되는데, 이러한 TestFixture는 괜찮아 보이는지 피드백 부탁드립니다 🙇

2024-06-03 02:43 UTC, fromitive commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +        mockServer = MockRestServiceServer.createServer(restTemplate);
4xx와 5xx 응답값을 테스트하기 위해 MockRestServiceServer라는 것을 활용하게 되었습니다 😄 

RestClient(혹은 Template)가 잘못 동작할 때 발생하는 예외가 아니였고, API 응답 값을 바탕으로 예외를 발생시켜야하는 것에 어려움을 느꼈습니다. 😢 

따라서 가짜 API 서버(mockRestServiceServer)와 통신하도록 변경하였고, 어떤 요청이 오던 4xx, 5xx에러를 반환하도록 mocking하였더니 원하던 예외가 발생하게 처리했습니다 😄

혹시 썬이 생각하는 다른 적절한 방법이 있다면 피드백 부탁드립니다 🙇

2024-06-03 02:51 UTC, fromitive commented on src/main/java/roomescape/interceptor/LoggingInterceptor.java
> +        return response;
`RestTemplateBuilder`를 통해 로깅을 등록하였습니다. 😄 

4xx, 5xx 오류 가 어떤 원인에서 발생했는지 한 눈에 확인할 수 있었고, 200 응답값을 받을 때 각 결제 정보가 어떤 상태를 띄고 있는지 확인할 수 있었습니다. 

API 응답을 기다리는 중 timeout이 될 경우(read-timeout) 결제를 취소하기 위한 orderId와 paymentKey를 쌓기 위해 request 또한 로깅했습니다.

썬의 경험을 바탕으로  별도로 로깅 하면 좋은 부분이 어떤 것들이 있는지 궁금합니다 😄

2024-06-03 02:54 UTC, fromitive commented on src/main/java/roomescape/interceptor/LoggingInterceptor.java
> +        response.getStatusCode(); // restTemplate에서 4xx, 5xx에러 발생시 .getBody()에서 IOException을 방지하기 위함
restTemplate는 4xx, 5xx발생 시 `response.getBody()`를 호출하면 IOException이 발생하여 이를 방지하기 위해 getStatusCode를 한 번 호출하는 것으로 방지할 수 있어서 추가했습니다 😅  [관련 링크](https://stackoverflow.com/questions/47429978/resttemplate-response-getbody-throws-exception-on-4-and-5-errors-for-put-and)

2024-06-03 02:59 UTC, fromitive commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +                .defaultHeader("Authorization", buildAuthHeader())
상수 적용 완료했습니다 😄

2024-06-03 03:32 UTC, fromitive commented on src/main/java/roomescape/config/TossPaymentConfiguration.java
> +        return simpleHttpRequestFactory;
> 하나 더 생각해볼 부분은 만약 외부 API에서 문제가 발생해 수십초간 응답이 오지 않는다면 어떻게 될까요?

응답이 오지 않고 계속 기다리고 있으면 시스템에서도 자원을 계속 사용해야 하고, 이로 인해 시스템의 가용성을 저하시킬수 있다고 생각합니다 😃  

현재 생각할 수 있는 부분은 이 정도 인 것 같습니다 😅 썬이 생각하기에는 좀 더 고려해야 하는 부분이 있는지 궁금합니다

2024-06-03 03:38 UTC, fromitive commented
안녕하세요 썬 😄  포케입니다 

리뷰 반영사항은 [링크](https://github.com/woowacourse/spring-roomescape-payment/pull/59/files/1651d01cc124edc3a547717c81d946818846ff45..3b552564a7c6e213eedb65d4e26a9f2581bb9bb8)와 같습니다 😊 

리뷰 주신 부분에 대한 수정사항은 별도로 코멘트를 남겼으니 확인부탁드립니다 🙇 

생각해 볼 만한 것들에 대해 리뷰해주셔서 감사합니다 😄

2024-06-03 15:08 UTC, syoun602 approved these changes
안녕하세요 포케 👋

리뷰 반영도 잘해주시고, 학습도 많이 해보신 것 같네요 👍👍
1단계는 충분히 학습하신 것 같아 이만 머지하겠습니다!
답변 및 코멘트 드렸는데, 다음 단계 PR에서 알려주세요~!

앗 그리고 코멘트를 달때 제가 남긴 코멘트 밑에 바로 남겨주시면 이전 질문에 대한 컨텍스트가 한눈에 들어와서 리뷰하기가 더 편할 것 같습니다 😁

2024-06-03 15:08 UTC, syoun602 commented on src/main/java/roomescape/config/TossPaymentConfiguration.java
> +        return simpleHttpRequestFactory;
말씀하신대로 블로킹으로 인한 스레드 대기, 성능 저하 등으로 인해 응답이 오지 않을 때에 대한 시간 제한을 두는게 보편적이죠. 
각각 3초, 3초로 두셨던데 어떤 이유인지 궁금합니다~
참고로 토스 공식 문서에서는 read의 경우 30~60초 사이를 권장하고 있습니다 
![image](https://github.com/woowacourse/spring-roomescape-payment/assets/67397679/17e3bc19-851c-43f6-a094-a8637d962542)

2024-06-03 15:08 UTC, syoun602 commented on src/main/java/roomescape/exception/TossPaymentErrorHandler.java
> +}
no new line 경고 👀

2024-06-03 15:09 UTC, merged

2024-06-04 00:41 UTC, fromitive commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +        ReservationRequest request = ReservationRequestBuilder.builder().build();
테스트 데이터를 만드는 방식이 다양하군요..! 좋은 자료 주셔서 감사합니다!!