[ 1단계 방탈출 결제 / 배포 ] 무빈(김현중) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #61
Opened 2024-05-30 07:06 UTC by hjk0761

안녕하세요 수달!
레벨 2 마지막 미션 리뷰이 무빈입니다!

리뷰에 앞서, 저는 스프링과 웹 프로그래밍 경험이 처음임을 먼저 말씀드립니다.

외부 API 를 연동하는 과정이 1단계의 중점이라고 생각해서,
결제 연동이 추가되면서 연쇄적으로 생기는 고민은 아직 해결하지 않았습니다.
가령 예약대기가 예약이 될 때 결제를 어떻게 할 것인지, 결제된 예약이 취소 되었을 때 환불과 같은 과정은 다음 단계의 질문으로 남겨두었습니다!

외부 API 를 사용하는 지금의 미션에서 책임 분리가 잘 된 것인지, 고려하지 못한 부분이 더 있는지 짚어 주시면 감사하겠습니다.

## 질문

마지막 커밋이 테스트 데이터를 셋업하는 방법을 바꾼 것인데,
실제로 현업에서는 어떻게 테스트 데이터를 관리하는 지 궁금합니다!
가시성과 셋업 데이터의 의존을 줄이기 위해 테스트 메서드 마다 관리하는지,
지금처럼 sql 로 분리하여 테스트의 목적을 가시화하고 길이를 간결하게 하는지,
픽스쳐 등을 만들어 테스트 하고 싶은 데이터를 만들어 사용하는지,
혹은 다른 방법을 사용하는지 알고 싶습니다.
그리고 수달은 어떤 의도에서 어느 방법을 선호하시는 지도 알려주시면 감사하겠습니다!

## 미션 범위

이번 미션에 대한 커밋 범위는 [다음]()과 같습니다!

이번 리뷰도 잘 부탁드립니다 ㅎㅎ

2024-05-30 22:03 UTC, her0807 requested changes
안녕하세요 무빈!

리뷰어 수달입니다. 
요청해주신 내용 참고하여 간단한 리뷰 남겨두었습니다. 
혹시 리뷰를 보고 너무 어렵거나, 더 고민해보고 싶은 부분이 있으면
빠르게 리뷰 요청이나 DM 통해서 연락주세요 🙏

2024-05-30 22:03 UTC, her0807 commented on src/test/java/roomescape/repository/WaitingRepositoryTest.java
> +
결제 요청에 대한 테스트가 없는 것 같은데요!

제어할 수 없는 부분에 대한 테스트, 어떻게 해볼수 있을까요?

외부 API 테스트를 모킹이 아니라 실제 요청을 보내는 테스트 필요할까요?



사용하는 외부 API 에 유형을 파악하기 위해서, 혹은 테스트는 문서에 기능이자, 외부 API 헬스 체크의 기능도 할 수 있기 때문에 주는 구현을 하는 편입니다. 그대신 해당 서비스위 문제가 저희가 구현한 서비스의 문제가 아니기 때문에 테스트 전체를 돌릴 때는 불필요하다고 판단된다면 로컬에서만 돌리고 @Disabled 처리를 해두는것도 방법일것 같아요!

팁 :
tosspayments-test-code 헤더에 원하는 에러코드를 넣으면
```
curl -X POST --location "https://api.tosspayments.com/v1/payments/confirm" \
    -H "Authorization: Basic dGVzdF9za196WExrS0V5cE5BcldtbzUwblgzbG1lYXhZRzVSOg==" \
    -H "Content-Type: application/json" \
    -H "tosspayments-test-code: INVALID_CARD_LOST_OR_STOLEN" \
    -d '{
          "amount": "1000",
          "orderId": "orderId",
          "paymentKey": "paymentKey"
        }'
```
요렇게 나옴
```
{
  "code": "INVALID_CARD_LOST_OR_STOLEN",
  "message": "분실 혹은 도난 카드입니다."
}
```

참고 : [https://docs.tosspayments.com/resources/glossary/http-header#에러-시나리오-테스트하기](https://docs.tosspayments.com/resources/glossary/http-header#%EC%97%90%EB%9F%AC-%EC%8B%9C%EB%82%98%EB%A6%AC%EC%98%A4-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0)

2024-05-31 04:39 UTC, hjk0761 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +                .defaultHeader("Authorization", buildAuthHeader())
해당 상수가 존재하는지 몰랐습니다! 알려주셔서 감사해요 ㅎㅎ
바로 바꾸어 보았습니다!

2024-05-31 04:49 UTC, hjk0761 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    private final static String PAYMENT_URL = "https://api.tosspayments.com/v1/payments";
외부 API 스펙 변경이 내부 코드에 까지 영향을 주지 않아야 한다는 말씀에 동의해,
설정 파일로 이들을 옮겨 보았습니다!

설정 파일을 잘 사용해본 적이 없어 해당 설정 변수명이 적절한지 확신이 없는데, 괜찮은 네이밍이 있다면 제안 부탁드립니다!

또한, 이전에 jwt 비밀키도 설정파일에서 관리했기에 이 기조를 가져가고자 토스 API 비밀키도 설정파일로 옮겼습니다.

2024-05-31 04:53 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
> +                .uri("/confirm")
해당 url 도 이전과 같이 설정 파일로 옮겨보았습니다!

2024-05-31 04:55 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
> +    private final RestClient restClient;
RestClient가 비교적 최근에 나온 기술이라 RestTemplate 보다 참고할 자료가 적었지만, 구조적인 부분에서 채택하게 되었습니다.

메서드 체이닝을 통하여 설정하고 사용하는 방법이 Stream API 를 사용하는 것 처럼 의미를 이해하기 쉽다는 페어의 의견에 동의해 사용하게 되었습니다 ㅎㅎ

2024-05-31 06:03 UTC, hjk0761 commented on src/main/java/roomescape/controller/request/PaymentRequest.java
> +}
이전에 문자열을 받는 request 를 NotEmpty 로 검증했기에
새로 추가된 부분도 NotEmpty 를 사용하도록 수정했습니다!

2024-05-31 08:09 UTC, hjk0761 commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +        long themeId,
wrapper 클래스인 Long 을 사용하는 이유는, 입력이 null 인 경우 이 null 을 그대로 전달할 수 있기 때문입니다. long 을 사용할 경우, null 을 기본값인 0으로 처리하기 때문에, 실제 입력이 0인지 null 인지 알 수 없습니다.

리뷰 주신 부분 외에도 request 에서 null 과 0 을 구분해야 하는 부분 모두 wrapper 클래스로 수정했습니다!

2024-05-31 08:16 UTC, hjk0761 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    private final static String SECRET_KEY = "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6";
비밀키와 같은 정보는 말씀주신 것 처럼 퍼블릭으로 올라가지 않는 것이 중요할 것 같습니다.
특히 서비스가 커지면서 외부 API 와 소통할 일이 많아질수록 이런 정보량이 많아질 것이라고 생각이 듭니다....

아직 웹 서비스를 다루어 본 경험이 없어, 개인적인 생각과 함께 이에 대해 주변 크루에게 물어보았습니다.

먼저, 현재의 설정 파일에서도 올라가도 되는 정보(외부 API 도메인 등)와 올라가면 안되는 정보(비밀키 등) 이 있기 때문에, 설정 파일의 분리가 필요할 것 같습니다.
이후에 gitignore 설정등을 통해 민감한 정보를 담고 있는 설정 파일이 유출되지 않도록 한 이후, 배포하는 서버에 수동으로 이 설정파일을 옮기는 방식을 생각해 볼 수 있었습니다.

혹시 이런 방법 외에 수달이 생각하신 좋은 방안이 있다면 말씀 주시면 감사하겠습니다!
실제로 현업에서도 저런 정보를 어떻게 처리하는지 궁금합니다 ㅎㅎ

질문과 별개로, 리뷰의 '(참고)' 부분은 이 리뷰가 참고의 의미에서 주신 부분이라는 뜻인가요, 아니면 무언가 참고할 자료를 표시하시려는 것이었는지 궁금합니다!

2024-05-31 08:31 UTC, hjk0761 commented on src/test/java/roomescape/repository/WaitingRepositoryTest.java
> +
외부 API 에 대한 헬스 체크가 없었던 이유는, 외부 API 가 정상적으로 돌아간다는 믿음 아래에 현재 미션이 돌아간다고 생각했기 떄문입니다.
하지만, 외부 API 를 사용하는 것 또한 하나의 문서화의 대상으로 본다면 이는 테스트로 기록될 필요가 있다고 생각해 주신 리뷰에 동의합니다.

다만 의문이 드는 부분은, 현재 사용하는 토스 API 는 에러 코드를 정말 세세하게 나눠두었고, 생각할 수 있는 거의 모든 상황에 대해 에러 코드가 따로 정의되어 있습니다.
테스트의 역할이 토스 API 의 헬스 체크라면 단순히 서버가 응답을 잘 반환함을 확인해도 된다고 생각하지만, 테스트를 문서의 시점에서 보았을 때 상정할 수 있는 오류 상황에 대해 체크해야 하는것인가 에 대한 의문이 생겼습니다.

수달께서도 외부 API 에 대한 테스트를 구현하는 편이라고 말씀해 주셨는데, 혹시 어느 기준에서 어느 범위까지 테스트 하시는지 궁금합니다!

2024-05-31 09:09 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
> +                    throw new PaymentException("결제 시스템이 원활하게 동작하지 않습니다.");
같은 PaymentException 을 사용하는 부분에서 상황에 대한 해석이 너무 추상화된 것 같아 해당 예외 상황을 분리해 구체적으로 표현할 수 있도록 수정해 보았습니다!

말씀주신 가독성과 확장성의 측면에서, 결제 상황에서 다른 예외 핸들링이 필요할 때에 지금처럼 PaymentException 을 상속받는 다른 예외를 생성해 해결할 수 있다는 생각이 들어 이렇게 구현해 보았습니다.

이런 방향이 의도하신 방향이 맞는지 궁금합니다!

2024-05-31 09:16 UTC, hjk0761 commented on src/test/resources/reservation_data.sql
> +VALUES ('썬', 'MEMBER', 'sun@email.com', '1111');
말하자면 긴 이야기인데... 사실 저는 썬 리뷰어님을 만난 적이 없습니다..ㅎㅎ

저번 미션에서 제 코드가 아닌 페어의 코드를 사용하기로 했었는데, 그때 페어의 전 리뷰어가 썬이였기 때문에 데이터에 들어있던 것입니다

이전까지 user와 admin 이라는 딱딱한 명명을 사용했던 제 코드에서 좀 활기가 생긴 것 같아 따로 수정하지 않고 두었던 부분입니다

제 지금 리뷰어는 수달이기에, 수달로 빠르게 수정해 보았습니다 ㅎㅎ 테스트 하실 때에도 수달 계정을 사용하시면 됩니다!

2024-06-02 14:00 UTC, her0807 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +                .defaultHeader("Authorization", buildAuthHeader())
HttpHeaders 에 그 외에도 활용할수 있는 상수들이 많이 있더라구요~ 🙂
관련한 핸들링이 필요할 때, 한번 들여다보아도 좋을 것 같습니다!

2024-06-02 14:02 UTC, her0807 commented on src/main/java/roomescape/config/RestClientConfiguration.java
> +    private final static String SECRET_KEY = "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6";
아아 ㅎㅎ 이 내용은 이후 배포 단계에서 민감정보 은닉에 대한 내용을 다룰 것 같아서 
미리 고민해보면 좋을 것 같아서 ` 리뷰의 '(참고)' 부분은 이 리뷰가 참고의 의미에서 주신 부분` 에 의미로 작성해두었습니다 ㅎㅎ


저도 예전 경험을 떠올려보면 gitignore 로 설정해두고 리뷰어 분께 민감 정보는 따로 전달해드렸던 기억이 나네요! ㅎㅎ

2024-06-02 14:21 UTC, her0807 requested changes
안녕하세요 무빈!

엄청 빠르게 리뷰 반영해주셨네요 👍🏻
조금더 얘기 나누면 좋을 것 같아서 request changes 요청해두었어요. 
다음 단계에서도 고민해볼 부분이 많은 것 같아서 간단한 내용이니 
빠르게 반영하고 재요청 해주시면 다음단계로 넘어가겠습니다 🙇🏻‍♀️

2024-06-02 14:21 UTC, her0807 commented on src/main/resources/application.properties
> +payment.toss.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
🖐🏻 properties 보다 yaml 을 써보는 건 어떨까요?

설정들을 보통 계층이 나뉘어져 있는데요~ properties 를 사용하다보니 계층이 눈에 잘 띄지 않는 것 같습니다.

2024-06-02 14:21 UTC, her0807 commented on src/main/resources/application.properties
> +payment.toss.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
그 외에 네이밍을 추천해달라고 하셨었는데 지금도 충분히 괜찮은 것 같아요! ㅎㅎ

2024-06-02 14:21 UTC, her0807 commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +        long themeId,
래퍼 타입 클래스와 프리미티브 타입 클래스를 사용할 때 각각의 주의할 점을 잘 설명해주셨네요!

프리미티브 타입은 null 자체가 매핑되지 않아서 
request 서블릿에서 요청이 들어올 때 바로 에러를 뱉으니
request 데이터 중에서 어떤 것이 누락되었는지, 혹은 타입이 잘못되었는지 정확한 행위를 유도하기 위한 메세지를
내려주기 위해서 래퍼타입을 받고 핸들링하곤 했던 것 같아요.

2024-06-02 14:21 UTC, her0807 commented on src/main/java/roomescape/service/PaymentService.java
> +                    throw new PaymentServerErrorException();
굿굿 적절하게 재사용성도 올리면서, 어떤 에러가 나는지도 파악하기 좋아진 것 같아요~

2024-06-02 14:21 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +                .orElseThrow(() -> new NotFoundException("아이디가 %s인 테마가 존재하지 않습니다.".formatted(request.themeId())));
이렇게 테마나 예약을 찾고 없으면 예외를 반환하는 로직이 중복되어서 진행되고 있는것 같아요. 
private method 로 추출해서 재사용성을 올리고, 가독성이 더욱 좋아지도록 변경해볼까요?

2024-06-02 14:21 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional
@Transactional 이 중복되면 클래스 최상위에 선언해줌으로써 전체 메서드에 적용시킬 수 있어요. 
그리고 변경해주고 싶다면 변경이 필요한 메서드 위에  @Transactional(readOnly = true) 와 같이 적어주면 변경되어 적용됩니다!


   @Transactional(readOnly = true) 할지,    @Transactional을 할지 ,
혹은 read service 와 write service 를 나눠 볼지 등등을 고민해보면 좋을 것 같습니다~!

2024-06-02 14:21 UTC, her0807 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +
불필요한 개행이나 컨벤션들이 있는지 전체적으로 한번 둘러볼까요? 🙂

2024-06-02 14:21 UTC, her0807 commented on src/main/resources/data.sql
> +VALUES ('수달', 'otter@email.com', 'MEMBER', '1234');
ㅎㅎㅎ 수달 추가해줘서 고마워요 🤩

2024-06-02 14:21 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +    private final RestClient restClient;
RestTemplate 외에도 FeignClient 라는 선택지도 있는데요! 각각 어떤 장단점이 있고 어떻게 써보면 좋을지 조금더 고민해고 공유해주시면 좋을 것 같아요!

2024-06-02 14:21 UTC, her0807 commented on src/test/resources/reservation_data.sql
> +VALUES ('썬', 'MEMBER', 'sun@email.com', '1111');
ㅎㅎㅎ 헉 그렇군요~! 수달 계정 추가해주셔서 감사합니다 😊

2024-06-02 14:21 UTC, her0807 commented on src/test/java/roomescape/repository/WaitingRepositoryTest.java
> +
> 🖐🏻외부 API 에 대한 헬스 체크가 없었던 이유는, 외부 API 가 정상적으로 돌아간다는 믿음 아래에 현재 미션이 돌아간다고 생각했기 떄문입니다.

이런 기준이 있었다면 저도 동의합니다. 문서화 용도로만 사용한다면 모킹을 통해서 우리가 핸들링 해야할 예외에 대한 행위 테스트를 모두 할 것 같습니다. 지금 무빈이 작성해주셨던 4xx, 5xx 을 커스텀해서 예외를 발생시켰던 부분에 대해서요!

그러나 실제 동작 가능한지를 모두 테스트 하려면 유추할 수 있는 모든 부분에 대해서 실제 요청을 날리도록 테스트를 작성하고, @disabled 처리 해둘 것 같아요 .

2024-06-04 05:26 UTC, hjk0761 commented on src/main/resources/application.properties
> +payment.toss.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
yaml 파일로 수정해보니 개행으로만 계층을 나누던 properties 보다 훨씬 직관적인 것 같습니다!

2024-06-04 06:15 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
> +                .orElseThrow(() -> new NotFoundException("아이디가 %s인 테마가 존재하지 않습니다.".formatted(request.themeId())));
ReservationService 에 특히 중복되는 코드가 많은 것 같아 수정해 보았습니다.

이렇게 수정하는 과정에서 `validateExistReservation` 메서드의 수정과 관련해서 궁금한 점이 생겼습니다!
기존에 예약을 찾는 과정과 예약이 존재하는지 확인하는 과정 모두 같은 구조, 같은 에러를 뱉어내는데,
findById 를 사용하는지, existsById 를 사용하는지만 달랐습니다.
둘의 구조가 비슷한 바, existsById 사용을 없애고, findById 를 통해 없는 경우 예외를 발생시키고, 리턴을 전달하지 않음으로 existsById 를 사용할 때와 같은 효과를 낼 수 있었습니다.
이전에 existsById 와 findById 를 따로 사용했던 이유는, 각 메서드가 하는 일이 존재확인과 객체찾기로 다르다고 생각했기 때문인데, 이번에 코드 중복을 줄이면서 이 부분이 눈에 밟혀 수정해 보았지만 성에 차지는 않는 것 같습니다.
혹시 수달께서는 이런 경우에 바뀐 코드가 괜찮다고 생각하시나요? 코드의 중복은 줄일 수 있었지만 메서드의 목적을 넘어 사용한 듯한 기분이 들어 질문 남기게 되었습니다!

2024-06-04 06:21 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +
미션에 집중하다보니 정작 중요한 부분을 신경쓰지 못했네요 ㅠㅠ
전체적으로 컨벤션이 맞도록 수정해 주었습니다!
짚어주셔서 감사드립니다 🙂

2024-06-04 06:32 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional
전체적으로 readOnly 가 true 인 사용이 더 많았기 때문에,
클래스 최상위에 `@Transacational(readOnly = true)` 로 선언해주고, readOnly 가 false 여야 하는 곳엔 `@Transactional` 어노테이션을 따로 붙여주었습니다!

클래스에 붙은 어노테이션보다 메서드에 붙은 어노테이션의 적용 순위가 높고, `@Transacational` 메서드의 readOnly 의 디폴트가 false 이므로 지금과 같이 중복을 줄여보았습니다!

2024-06-04 06:54 UTC, hjk0761 commented on src/main/java/roomescape/service/ReservationService.java
> +    private final RestClient restClient;
마침 동기에게 FeignClient 에 대해 들었던지라, 이와 함께 공부한 부분을 정리해 보겠습니다!

일단 spring jpa 처럼 인터페이스로 선언하여 사용하므로 직접 구현체를 구현하지 않아도 된다는 장점이 있고,
세팅이 된 시점에서 이후 여러 외부 API 를 사용하는 것이 편리하다고 들었습니다.

다만, spring cloud 스펙이기 때문에 따로 의존성 추가가 필요하고, 기존의 restClient 보다 초기 세팅에 손이 좀 더 간다는 단점도 있었습니다.

FeignClient 의 시작이 Netflix 의 수많은 MSA 간의 소통에서의 편리함인 것을 생각하면, 서비스가 커지고 외부 API 와 소통할 일이 많을 수록 FeignClient 의 사용이 편리할 수도 있을 것 같습니다!
다만, 지금 규모에서 이런 장점을 경험하지 어렵고, 통신 과정이 추상적이어서 외부 API 를 사용하는 방법을 학습한다는 차원에서 아직 저에게 불필요한 부분인 것 같습니다!
새로운 선택지 알려주셔서 감사드리고, 이후에 잊지않고 적용해보는 경험 해보겠습니다 ㅎㅎ

2024-06-04 08:11 UTC, hjk0761 commented on src/test/java/roomescape/repository/WaitingRepositoryTest.java
> +
수달의 기조 말씀주셔서 감사합니다 ㅎㅎ

외부 API 테스트에 대해 좀 더 공부해 봐야겠다는 생각이 드네요!

말씀 주신 것 처럼 예외에 대한 핸들링 테스트를 추가해 보았고, 이는 외부 API 통신이 아니더라도 필요한 부분이라는 생각이 들어 추가하게 되었습니다.

조금 더 궁금한 부분은, 현재 PaymentService.confirmReservationPayments 메서드 자체에서 request 만을 받아 외부 API 와 통신한 이후에 에러 핸들링까지 해주는데, 이를 부분적으로 테스트 할 방법이 있는지 궁금합니다!
가령 위에 적어주신 것 처럼 헤더에 에러 코드를 담아 보내거나, 결제정보를 다르게 해 외부 API 에서 진짜 4XX, 5XX 에러를 터뜨리는 것과 같은 행동을 테스트할 수 있는지 궁금합니다.
혹시 가능하다면, 키워드를 말씀주신다면 공부해 보고 싶습니다 ㅎㅎ

2024-06-04 23:57 UTC, her0807 commented on src/test/java/roomescape/repository/WaitingRepositoryTest.java
> +
헤더를 통해 제어가 가능한 방법이 있기는 하나,, 토스 내부에서 테스트를 위해 사용하는 방법이라
범용적으로 권장드리는 방법은 아닙니다 ㅠㅠ 지금 작성해주신 내용도 충분한 것 같아요~

2024-06-05 00:01 UTC, her0807 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +    private ReservationTime findById(Long id) {
### Find vs get
주로 값이 없으면 예외를 반환하는 것은 get, 값이 없어도 되는 것은 find 라고 명명하는 것 같습니다!

[스프링 Data의 CRUD repository](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html) 인터페이스는 Optional<T>를 반환한다.

```java
public interface CrudRepository<T,ID> {
    ...
    Optional<T> findById(ID id);
    Iterable<T> findAll();
    ...
}
```
반면 같은 스프링 Data의 [JPA repository](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html)에서는 T를 반환한다.

```java
public interface JpaRepository<T,ID> {
    ...
    T getOne(ID id);
    List<T> findAll();
    ...
}
```
CrudRepository는 찾는 값이 없을 경우 빈 Optional을, JpaRepository는 찾는 값이 없을 경우 예외를 발생한다는 차이가 있다. 여기서 볼 수 있듯이 일반적으로 반환 값이 없을 수 있는 경우 find을, 항상 있어야 하는 경우 get을 붙인다. find를 쓰면 api 사용자에게 이름을 통해 반환값이 없을 수 있음을 알려 줄 수 있는 것이다.
반면, 반환형이 List같은 컬렉션이라면 값이 없어도 null이 아닌 빈 컬렉션을 반환하면 된다.ind vs get
[스프링 Data의 CRUD repository](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html) 인터페이스는 Optional<T>를 반환한다.
```java
public interface CrudRepository<T,ID> {
    ...
    Optional<T> findById(ID id);
    Iterable<T> findAll();
    ...
}
반면 같은 스프링 Data의 [JPA repository](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html)에서는 T를 반환한다.

public interface JpaRepository<T,ID> {
    ...
    T getOne(ID id);
    List<T> findAll();
    ...
}
CrudRepository는 찾는 값이 없을 경우 빈 Optional을, JpaRepository는 찾는 값이 없을 경우 예외를 발생한다는 차이가 있다. 여기서 볼 수 있듯이 일반적으로 반환 값이 없을 수 있는 경우 find을, 항상 있어야 하는 경우 get을 붙인다. find를 쓰면 api 사용자에게 이름을 통해 반환값이 없을 수 있음을 알려 줄 수 있는 것이다.
반면, 반환형이 List같은 컬렉션이라면 값이 없어도 null이 아닌 빈 컬렉션을 반환하면 된다.

2024-06-05 00:04 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +                .orElseThrow(() -> new NotFoundException("아이디가 %s인 테마가 존재하지 않습니다.".formatted(request.themeId())));
existsById, find 는 DB 에서 내부 동작 자체에도 차이가 있어요. 

find 를 하게되면 jpa 에 연관 관계 매핑에 따라 엮여 있는 데이터까지 또 찾아서 (join 을 하거나..) 비용이 더 들게 되는데 exists 는 해당 컬럼이 존재하는지만 알면 프로세스가 끝나고 바로 boolean 값을 반환하게됩니다. 

그래서 저는 이럴 경우는 분리해서 사용하는 것이 맞고, 해당 중복은 우발적 중복 혹은 중복이 아니라고 생각됩니다!

2024-06-05 00:05 UTC, her0807 approved these changes
안녕하세요 무빈~

리뷰 꼼꼼하게 잘 반영해주셨군요!
다음 단계로 넘어가도 될 것 같아요. 

남겨주신 질문에 대해서는 답글달아두었어요.
다음 미션 하면서 참고해주시면 감사하겠습니다.
좋은 하루 보내세요 :)

2024-06-05 00:05 UTC, merged