[1단계 방탈출 결제 / 배포] 로키(정해성) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #72
Opened 2024-05-30 08:21 UTC by HaiSeong

2024-05-30 11:33 UTC, jinyoungchoi95 requested changes
안녕하세요 로키 😄

방탈출 결제 / 배포 미션의 리뷰어를 맡은 오리입니다.

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/PaymentException.java
> +        return new PaymentException(HttpStatus.BAD_REQUEST, paymentErrorResponse.code(), paymentErrorResponse.message());
1. Exception이 어떤 http status를 반환해야할 지 web 계층의 정보를 판단해도 되나요? 예외는 controller layer인가요?
2. 400의 경우 bad request로 잘못된 요청을 했다라는 것인데 error code에 속하지 않으면 잘못된 요청이란 것을 어떻게 판단하셨나요?

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/infra/PaymentRestClient.java
> +    }
항상 동일한 값을 반환할 것으로 보이는데 요청때마다 메소드를 호출하고 불필요한 자원을 생성하는 로직이 될 것 같아요.

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/infra/PaymentRestClient.java
> +        return response.toPayment();
`RestClient`는 반환값이
```java
        @Nullable
        <T> T body(ParameterizedTypeReference<T> bodyType);
```
로 nullable하여 

<img width="677" alt="스크린샷 2024-05-30 오후 8 16 29" src="https://github.com/woowacourse/spring-roomescape-payment/assets/69106910/ea50d9bd-851d-40fe-bae4-c5801caeecda">

와 같은 경고문구가 나오네요.

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/ClientConfig.java
> +                        .baseUrl("https://api.tosspayments.com/v1/payments/confirm")
`PaymentRestClient`는 결제를 위한 client로 보이는데요. toss라는 url이 들어가있고 toss에 의존적인 것으로 보이네요. 카카오뱅크로 갈아타야한다면 구현체에 의해 변경점이 발생하지 않을까요?

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/PaymentService.java
> +    public PaymentResponse savePaymentAndUpdateReservationStatus(PaymentRequest request) {
`savePaymentAndUpdateReservationStatus`는 메소드의 구현내용을 그대로 담는 네이밍이에요. 메소드의 구현내용이 만약에 달라지면 메소드명도 달라지는거죠. 메소드명은 구현내용에 의존적이기보다는 기능 자체를 전달할 수 있는 네이밍을 고려해보세요.

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/test/java/roomescape/domain/PaymentTest.java
> +                        .hasMessage(EMPTY_PAYMENT_KEY.getMessage())
테스트는 하나의 실행이 되는 단위에요. "무엇을 테스트하겠다"가 하나의 단위인거죠.

이때 null이면 예외가 발생하는 것과 공백이면 예외가 발생하는 것은 각각 다른 테스트로 판단되어요. 두 값은 엄연히 다른 상황이고 다른 테스트니까요. null인지 공백인지를 판단하는 것은 각각 다른 로직이기 때문에 가능하면 다른 로직에 대해서는 테스트는 분리되어아해요.

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/test/java/roomescape/repository/JpaPaymentRepositoryTest.java
> +        assertThat(saved.getId()).isNotNull();
하나의 `@Transactional`로 묶인 상태일 때 saved는 정말 "잘 저장된" 값이 맞나요?

로키가 생각되는 데이터베이스에 저장된 기준은 무엇인가요? Transaction의 commit과 관련하여 이야기해주시면 좋을 것 같아요.

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/controller/PaymentController.java
`PaymentController`는 테스트가 필요없을까요?

2024-05-30 11:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/PaymentService.java
> +        reservation.updatePayment(payment);
이미 결제가 `RESERVED_COMPLETE`처리된 값에 대해서 또 호출이 들어오면 또 결제가 되어도 되나요?

2024-05-31 05:42 UTC, HaiSeong commented on src/main/java/roomescape/infra/PaymentRestClient.java
> +    }
그렇네요!
자원이 중복 생성되지 않도록 처리해보겠습니다!

2024-06-02 03:06 UTC, HaiSeong commented on src/main/java/roomescape/infra/PaymentRestClient.java
> +        return response.toPayment();
```java
if (response == null) {
            throw new RoomescapeException(EMPTY_RESPONSE_FROM_TOSS_API);
        }
```

response가 null인지 여부를 검사해 경고 문구를 제거했습니다!

2024-06-02 03:35 UTC, HaiSeong commented on src/main/java/roomescape/config/ClientConfig.java
> +                        .baseUrl("https://api.tosspayments.com/v1/payments/confirm")
인정합니다. `PaymentRestClient`를 인터페이스로 분리한 후 `PaymentClient` 로 이름을 변경했습니다. Rest 라는 이름을 부르면 내부적으로 `RestClient`를 사용한다는것을 명시하는것 같아요. 

그 후에 기존의  toss에 의존적인 클라이언트는 `TossPaymentClient`로 만들어 구현해줬습니다!

2024-06-02 03:44 UTC, HaiSeong commented on src/main/java/roomescape/service/PaymentService.java
> +    public PaymentResponse savePaymentAndUpdateReservationStatus(PaymentRequest request) {
말씀하신대로 구현을 그대로 담는 이름인것 같습니다.
예약을 결제한다는 의미를 담아 `payReservation`이라는 네이밍을 적용해보겠습니다!

2024-06-02 04:01 UTC, HaiSeong commented on src/main/java/roomescape/service/PaymentService.java
> +        reservation.updatePayment(payment);
결제 완료, 예약 대기 상태에서 결제를 할 . 수없도록 처리했습니다!

2024-06-02 04:55 UTC, HaiSeong commented on src/main/java/roomescape/exception/PaymentException.java
> +        return new PaymentException(HttpStatus.BAD_REQUEST, paymentErrorResponse.code(), paymentErrorResponse.message());
> 1. Exception이 어떤 http status를 반환해야할 지 web 계층의 정보를 판단해도 되나요? 예외는 controller layer인가요?

Service에서 발생시킨 예외가 web 계층의 정보를 판단해 자신이 스스로 반환할 HTTP 상태코드를 정하고 있네요. 확실히 잘못된 부분이라 생각됩니다. 상태코드를 정하는 것은 GlobalExceptionHandler 같은 controller layer에서 처리하도록 해보겠습니다.

2024-06-02 05:03 UTC, HaiSeong commented on src/main/java/roomescape/exception/PaymentException.java
> +        return new PaymentException(HttpStatus.BAD_REQUEST, paymentErrorResponse.code(), paymentErrorResponse.message());
> 2. 400의 경우 bad request로 잘못된 요청을 했다라는 것인데 error code에 속하지 않으면 잘못된 요청이란 것을 어떻게 판단하셨나요?

`if (SERVER_ERROR_CODES.contains(paymentErrorResponse.code()))` 

이 조건에 해당하는 경우는 토스가 제공하는 메시지가 사용자에게 전달되어도 사용자가 처리할 수 없는 경우라고 생각했습니다. 예를들어 "내부 시스템 처리 작업이 실패했습니다. 잠시 후 다시 시도해주세요.", "잘못된 시크릿키 연동 정보 입니다." 같은 메시지 입니다.

 반면에 그게 아닌 경우는 "잔액이 부족합니다.", "정지된 카드 입니다." 같은 문제는 사용자가 "돈이 없구나", "다른 카드로 시도해야겠다." 라는 판단을 할 . 수있어 사용자가 다시 결제를 시도하도록 400대 에러를 반환했습니다.

2024-06-02 05:20 UTC, HaiSeong commented on src/test/java/roomescape/domain/PaymentTest.java
> +                        .hasMessage(EMPTY_PAYMENT_KEY.getMessage())
주문 아이디가 `null`인 경우와 `공백`인 경우에 대해 각각 다른 테스트로 분리했습니다. 말씀하신대로 두 상황이 서로 다른 상황인것 같아요.

그런데 혹시 두 테스트 메서드가 테스트 되는 로직이 일치하고 결국 `주문 아이디에 유효하지 않은 값이 들어갔을때 예외가 발생한다.` 라는것을 테스트 한다는 관점에서 두 테스트가 합쳐질 수 있다고 생각이 들었습니다.

이런경우에 `ParameterizedTest`로 두 테스트를 묶어줘도 괜찮을지 질문하고 싶습니다!

2024-06-02 05:38 UTC, HaiSeong commented on src/test/java/roomescape/repository/JpaPaymentRepositoryTest.java
> +        assertThat(saved.getId()).isNotNull();
`@Transactional`을 테스트 메서드에 붙이게 되면 `auto commit` 기능이 해제되고 Transactional을 commit  하기 이전에 rollback 한다고 알고 있습니다. 지적해주신대로 "잘 저장된 값이 아니"죠. 

그러나 `save` 라는 메서드를 호출한 이후에 `saved`에는  id값이 부여되었습니다. 그 의미는 `saved`가 영속성 컨텍스트에 의해 관리되는 영속상태가 되었다는 것을 의미합니다. 

처음에는 영속성 컨텍스트에의해 관리되어 id를 받았다면 저장되었겠지 라고 생각했는데 질문을 답하는 과정에서 실제 저장이 되고 그 값을 읽어올 수 있는지를 확인해봐야겠다 라는 생각이드네요.

우선 `@Transactional`을 제거하고 다시 테스트를 작성해보겠습니다.

2024-06-02 07:25 UTC, HaiSeong commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    private ThemeRepository themeRepository;
의존성을 불러오는 부분이 너무 길다고 생각했었습니다.
sql을 이용해서 테스트 데이터를 추가하겠습니다!

오리는 sql을 이용하는 경우와 의존성을 불러와 코드로 데이터를 넣는 경우를 구분하는 기준이 있는지 궁금합니다!

2024-06-02 07:31 UTC, HaiSeong commented on src/main/java/roomescape/controller/PaymentController.java
PaymentController 가 없었네요. 추가했습니다!

2024-06-02 09:16 UTC, jinyoungchoi95 commented on src/test/java/roomescape/domain/PaymentTest.java
> +                        .hasMessage(EMPTY_PAYMENT_KEY.getMessage())
네 `@ParameterizedTest`로 감싸주어도 괜찮을 것 같아요.

개인적으로는 null체크와 blank 체크는 다른 검증이라고 생각하기 때문에 별도의 테스트로 분리하는 편이에요. null과 blank에 특정한 의미를 담는 경우도 있어요.

2024-06-02 09:26 UTC, jinyoungchoi95 commented on src/test/java/roomescape/repository/JpaPaymentRepositoryTest.java
> +        assertThat(saved.getId()).isNotNull();
이미 정의되어있는 `save`는 굳이 테스트하지 않아도 된다고 생각해요. 말씀하신대로 이미 정의되어있는 spring data jpa의 기능이니까요 (엄밀히 따지면 jpa가 아닌 spring data jpa의 기능입니다.)

이미 정의된 메소드만 사용하기 때문에 `PaymentRepository`를 테스트하지 않아도된다라는 내용에 대해서는 공감하는데, 현재 남긴 코멘트는 그 의도는 아니에요.

`@Transactional`을 사용하게 되는 경우 테스트 메소드에 있는 모든 기능이 하나의 영속성 컨텍스트를 공유해요. given절의 호출도 when절의 호출도 영속성 컨텍스트를 공유하는거죠.

그럼 돌아와서 같은 영속성 컨텍스트 내에서 테스트하게 되면 어떤 문제가 발생할지 보면 given으로 넣은 영속성 컨텍스트로 인해 when절에서 find호출을 하는 경우 db를 찌르는게 아니라 영속성 컨텍스트 내에 있는 데이터를 찔러요. 실제 기능은 "find  호출은 database를 찔러 반환해야한다"인데 말이죠. 그래서 jpa에서는 같은 트랜잭션에 묶이게 되는 경우 영속성 컨텍스트를 테스트메소드내의 모든 기능이 공유한다는 문제가 있어 드린 코멘트였어요.

2024-06-02 09:27 UTC, jinyoungchoi95 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    private ThemeRepository themeRepository;
가능하면 sql을 사용합니다. given 절이 테스트 데이터로 인해 굳이 길어질 필요가 없다고 생각해요.

2024-06-02 09:51 UTC, jinyoungchoi95 requested changes
안녕하세요 로키 😄

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Payment.java
> +        if (amount < 0) {
최소 양에 대한 상수처리가 필요해보이네요.

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/ClientConfig.java
> +                paymentErrorHandler()
이렇게 호출이 되면 위에서 bean등록을 할 필요가 있을까싶어요.

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
`ReservationStatus`가 어떤 상태이던 payment가 변경이 가능해보이는데 특정 상태에서만 가능하도록 해야하지 않을까요?

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
getter밑에 해당 메소드가 있는데 메소드를 정렬하는 기준이 있을까요?

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/ReservationStatus.java
> +            return RESERVED_UNPAID_MESSAGE;
상태가 100개되면 if문이 *100줄이 될 것 같은데요. `ReservationStatus`각각이 message만드는 function을 들고 있고 `values()`를 돌아가면서 만들어서 반환하면 되지 않을까요?

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/PaymentErrorHandler.java
> +        return response.getStatusCode().is4xxClientError() || response.getStatusCode().is5xxServerError();
`isError()`를 사용하여도 되지 않을까요?

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/PaymentException.java
> +    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
`ObjectMapper`를 따로 생성하여 사용하는 것에 대해서 고민해보세요.

spring에서 bean으로 등록된 `ObjectMapper`가 있는데 다른 값을 사용하게 되는 경우 의도한 바와 다르게 설정값이 다를 수 있고, 불필요한 객체 생성이 될 수 있어요.

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +    public Payment requestPaymentApproval(PaymentRequest request) {
`RestClient`를 원하는대로 호출했는지 테스트는 필요 없을까요?

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/PaymentService.java
> +        reservation.updatePayment(payment);
하나의 `@Transactional`로 묶여있을 때 `paymentClient.requestPaymentApproval`이 지연된다면 어떤 문제가 발생할까요?

2024-06-02 09:51 UTC, jinyoungchoi95 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    @Sql(scripts = {"/data/clean-up.sql", "/data/unpaid-reservation.sql"})
메소드단에서 sql script들을 설정한 이유가 있을까요? 불필요한 코드의 중복이 아닐까요?

2024-06-02 10:10 UTC, HaiSeong commented on src/test/java/roomescape/repository/JpaPaymentRepositoryTest.java
> +        assertThat(saved.getId()).isNotNull();
아하 `@Transactional`을 붙였을때 저장 후 조회를 해도 
```
Hibernate: 
    insert 
    into
        payment
        (amount, order_id, payment_key, id) 
    values
        (?, ?, ?, default)
```
이런 로직이 나가는 이유가 같은 영속성 컨텍스트를 공유하기 때문이죠.
데이터가 잘 저장되었는지 확인하려면 
```
Hibernate: 
    insert 
    into
        payment
        (amount, order_id, payment_key, id) 
    values
        (?, ?, ?, default)
Hibernate: 
    select
        p1_0.id,
        p1_0.amount,
        p1_0.order_id,
        p1_0.payment_key 
    from
        payment p1_0 
    where
        p1_0.id=?

```
이렇게 실제 쿼리가 나가야 하는지 확인 해야 된다는 말씀이시군요! 좋은 리뷰 감사합니다 👍

2024-06-02 10:59 UTC, HaiSeong commented on src/main/java/roomescape/domain/Reservation.java
> +    }
앗 ide의 자동생성 기능을 사용했더니 getter 아래로 내려가 버렸네요..! 확인하고 수정하겠습니다!

2024-06-02 11:29 UTC, HaiSeong commented on src/main/java/roomescape/domain/Reservation.java
> +    }
좋은 생각인것 같습니다.

updatePayment시 상태에 대한 검증을 reservation 도메인으로 옮겼습니다. 그러니 PaymentService의 검증로직을 삭제할 수 있었습니다.

2024-06-02 11:41 UTC, HaiSeong commented on src/main/java/roomescape/domain/ReservationStatus.java
> +            return RESERVED_UNPAID_MESSAGE;
사실 갯수가 아직 많지 않아 고려하지 않았었는데 확장성을 위해서 미리 만드는것도 좋은생각인것 같습니다. 반영하겠습니다!

2024-06-02 11:43 UTC, HaiSeong commented on src/main/java/roomescape/exception/PaymentErrorHandler.java
> +        return response.getStatusCode().is4xxClientError() || response.getStatusCode().is5xxServerError();
오!! 이런 메서드가 있었네요!

```
public boolean isError() {
        int hundreds = this.hundreds();
        return hundreds == 4 || hundreds == 5;
    }
```

유용하게 잘 쓸수 있을것 같아요. 감사합니다!

2024-06-02 13:14 UTC, HaiSeong commented on src/main/java/roomescape/config/ClientConfig.java
> +                paymentErrorHandler()
빈 등록이 잘 안되었었네요..! 수정했습니다!

2024-06-02 13:14 UTC, HaiSeong commented on src/main/java/roomescape/domain/Payment.java
> +        if (amount < 0) {
PaymentAmount 객체를 만들어 처리해보겠습니다.

2024-06-02 13:18 UTC, HaiSeong commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    @Sql(scripts = {"/data/clean-up.sql", "/data/unpaid-reservation.sql"})
"/data/clean-up.sql" 에 대해서는 중복이 맞는것 같습니다.

하지만 "/data/unpaid-reservation.sql"의 경우는 각각에 알맞은 데이터를 넣어주기 위해 필수적이라고 생각이 듭니다.

혹은 3가지 경우의 데이터를 모두 한 sql파일에 넣고 클래스 단위로 sql script를 설정하라는 의미 이신가요?!

2024-06-02 13:36 UTC, HaiSeong commented on src/main/java/roomescape/service/PaymentService.java
> +        reservation.updatePayment(payment);
앞서 find해온 reservation에 락이 걸려 다른 요청에서의 수정 작업이 불가능할것 같습니다.

또한 `paymentClient.requestPaymentApproval`가 지연되어 커넥션을 계속 가지고 있어 문제가 될것 같습니다.

오래 지연되지 않도록 timeout을 설정해주고

```
        Payment saved = paymentRepository.save(payment);
        reservation.updatePayment(payment);
```
이 두 작업에 대해서만 Transaction을 걸어주먄 좋을것 같습니다.

2024-06-02 15:36 UTC, HaiSeong commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +    public Payment requestPaymentApproval(PaymentRequest request) {
`RestClient`가 제가 설정한대로 잘 호출되는지 여부의 테스트를 말씀하신건가요?! 필요한 작업인것 같습니다. 

다만 저녁시간동안 고민해보았는데 방법을 잘 모르겠습니다.
내일까지 더 고민해보고 꼭 적용해보겠습니다.

혹시 그 동안 다른 부분에 대해 피드백 받을 수 있을까요??!

2024-06-02 16:18 UTC, jinyoungchoi95 commented on src/test/java/roomescape/service/PaymentServiceTest.java
> +    @Sql(scripts = {"/data/clean-up.sql", "/data/unpaid-reservation.sql"})
`/data/clean-up.sql`에 대해서 우선적으로 말씀드린 코멘트였어요.

sql 파일을 통채로 하나를 사용하게되면 관리가 안되는건 맞지만 그렇다고 모든 sql을 상황에 따라 분리하면 그건 그거대로 관리가 안될 수 있는데요. 상황마다 sql을 만들기보다는 entity 별로 sql을 만들어 사용할 수도 있을 것 같아요.

2024-06-02 16:22 UTC, jinyoungchoi95 commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +    public Payment requestPaymentApproval(PaymentRequest request) {
mocking할 수도 있고, interface이니 fake를 만들 수 있고 [지원해주는 방법](https://www.baeldung.com/restclienttest-in-spring-boot)을 사용하는 방법도 있고 다양할 것 같아요.

2024-06-02 16:42 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/PaymentService.java
> +        reservation.updatePayment(payment);
오래 지연되지 않도록 timeout을 건다고 하더라도 지연이 생기는건 마찬가지에요.

`@Transactional`이라는 것은 데이터베이스의 커넥션을 관리하는 범위가 되는 것이고, 이 범위가 데이터베이스가 아닌 요청에 의해 지연이 되는건 생각보다 큰일이에요. 트랜잭션이 아닌 호출이 트랜잭션을 물고 있고, 이로인해 커넥션을 물고있으니 다른 호출이 써야할 커넥션을 점유하고 있는 상황인거죠.

해결을 바라고 드렸던 코멘트는 아니었고 `@Transcational`을 외부호출과 함께 두었을때의 문제에 대해서 짚고 넘어가셨으면 해서 남긴 이야기여서 이정도로 넘어가도 좋을 것 같아요.

2024-06-02 16:49 UTC, jinyoungchoi95 approved these changes
안녕하세요 로키 😄

다음 미션 진행을 위해 머지하겠습니다. 현재 코멘트에서 궁금하신 내용은 다음 pr에 코멘트로 담아주세요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-06-02 16:49 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/ClientConfig.java
> +                .withReadTimeout(Duration.ofSeconds(3L));
connection timeout과 read timeout의 차이는 무엇인가요? 각각 3으로 설정된 이유가 있을까요?

2024-06-02 16:49 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/ReservationStatus.java
> +                .orElseThrow(() -> new RoomescapeException(ExceptionType.NOT_FOUND_RESERVATION_STATUS));
(반영하지 않으셔도 됩니다) message말고 functional interface를 사용하면 21라인에 있는 if문도 제거될 것 같아요.

2024-06-02 16:49 UTC, jinyoungchoi95 commented on src/main/java/roomescape/infra/TossPaymentClient.java
> +    private static final String WIDGET_SECRET_KEY = "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6";
이런 설정값은 보통 `application.properties`에 담아두고 profile별로 관리하여 주입하도록 사용되어요. 테스트에 필요한 key와 운영, 베타 등과 괕은 환경에 필요한 key들은 다를 수 있기 때문이에요.

2024-06-02 16:50 UTC, merged