[1단계 방탈출 결제 / 배포] 페드로(류형욱) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #76
Opened 2024-05-30 08:26 UTC by hw0603

2024-05-30 16:17 UTC, choijy1705 requested changes
안녕하세요 패드로
미션 잘 진행해주셨네요👍
취소까지 처리해주셨더군요👍
몇가지 코멘트 남겼으니 확인 부탁드립니다!

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentRestClient.confirm(reservationRequest);
PaymentService 를 만들어서 그안에서 client를 통해 confirm하는게 어떨까요?

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +        }
4XX 상태코드인 경우 RestClientResponseException으로 throw가 되나요??

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +        headers.set("Authorization", "Basic " + header);
HttpHeaders.AUTHORIZATION

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +    }
굳이 메서드로 만들기보단 cancel안에서 처리하는게 더 가독성 좋을것 같네요

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +                    .uri("/" + payment.getPaymentKey() + CANCEL_ENDPOINT)
```suggestion
                    .uri(String.format("/%s/cancel", payment.getPaymentKey()))
```
uri 는 보통 이렇게 처리하는게 가독성이 좋습니다!

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +    public void cancel(Payment payment) {
payment의 null 체크 필요해보이네요!

취소는 따로 요구사항에 없는거죠?? 다른 크루들은 안한것 같아서 한번 물어봅니다 ㅎㅎ

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +    }
여기도 마찬가지로 confirm안에서 처리하는게 더 가독성 좋을것 같습니다

2024-05-30 16:17 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +                    .uri(CONFIRM_ENDPOINT)
uri 는 상수처리하기보다 그냥 보여지는게 가독성이 더 좋은것 같아요!

2024-05-31 05:32 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        reservationRepository.save(reservation);
제가 조금 설명을 애매하게 했었네요😅 말씀하신 것과 같이
> 대기자에게 이벤트를 주고 결제를 하면 예약이 되거나 일정시간 지나면 취소되는 방향

이 방법이 1번이였습니다! 요구사항에는 없었지만 예약자나 방탈출 관리자 입장에서 생각했을 때 저러한 흐름이 존재하는 것이 자연스러울 것 같아 최소한의 고민만 한번 해 봤어요🙂

지금은 다음과 같이 잡을 돌리는 방법으로 간단하게 구현되어 있습니다. 레디스를 활용하는 방법도 있었네요. 답변 감사드려요ㅎㅎ
```java
// ReservationWaiting.java
@Scheduled(cron = "${resetwaiting.schedule.cron}")
private void deleteTodayWaiting() {
    List<ReservationWaiting> waitingOfToday = reservationWaitingRepository.findBySchedule_Date(LocalDate.now());
    waitingOfToday.forEach(w -> deleteById(w.getId()));
}
```

2024-05-31 05:34 UTC, hw0603 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +                    .uri("/" + payment.getPaymentKey() + CANCEL_ENDPOINT)
오.. 저 부분이 좀 마음에 들지 않았었는데 훨씬 깔끔한 것 같아요 감사합니다.

2024-05-31 05:45 UTC, hw0603 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +    }
URI를 상수로 분리하지 않는 것과 마찬가지로, 한 메서드 안에 있는 것이 읽기 편할 것 같네요. 반영했습니다!

2024-05-31 06:03 UTC, hw0603 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +        }
`HttpClientErrorException` 내에 정의되어 있는 각 상태코드별 예외 메시지가 던져집니다!

상속구조가 `BadRequest (final)` -> `HttpClientErrorException` -> `HttpStatusCodeException` -> **`RestClientResponseException`** -> `RestClientException` -> `...` 과 같이 되어 있어서 일단 `catch` 문에서 잡히긴 했던 거였네요😅

`HttpClientErrorException`을 잡아 주는 것이 나을 것 같아 변경했습니다.

2024-06-02 14:25 UTC, hw0603 commented on src/main/java/roomescape/config/RestClientConfig.java
> +    }
처음 미션을 진행할 때는 생각하지 못했던 부분이에요😂 외부 API를 호출하는 것이기 때문에 타임아웃 설정이 필요하다고 생각합니다.

- ConnectTimeout: TCP 연결 수립의 과정이기 때문에 길어질 이유가 없다고 생각하여 3초로 설정하였습니다.
- ReadTimeout: [토스 API 문서](https://docs.tosspayments.com/resources/glossary/timeout)의 권장사항에 따라 30초로 설정하였습니다.

2024-06-02 15:17 UTC, hw0603 commented on src/main/java/roomescape/service/payment/PaymentRestClient.java
> +    public void cancel(Payment payment) {
네네 취소는 요구사항은 아니였어요! 예약 대기 취소 기능이 분명 존재하는데, 예약 대기를 걸 때는 결제를 하고 대기 취소 시 환불이 안되는게 이상하게 느껴져서 추가해 봤습니다🙂

2024-06-02 16:57 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentRestClient.confirm(reservationRequest);
결제 와 예약 은 분리하여 생각하는 것이 맞을 것 같아서 결제가 하나의 Service 계층을 가지는 것에는 어색함이 없다고 생각합니다. 이미 독립된 테이블 역시 가지고 있기도 하구요. `Payment` 엔티티 영속화를 호출하기 위해서라도 PaymentSerivce가 있는 것이 이해하기 쉽고, 관리하기 편할 것 같아요.

헌데, 해당 `PaymentSerivce`가 생기면서 `ReservationSerive`에서 해당 서비스를 새롭게 의존하게 되는 구조가 되었습니다.
영이는 이와 같이 한 서비스에서 다른 서비스를 의존하는 상황을 어떻게 생각하시나요?
현재는 결제 서비스에서 주문 서비스를 의존할 일이 없으므로, 순환 참조 문제가 발생할 여지가 적다고 볼 수 있으니 단순히 '결제 서비스는 주문 서비스의 하위 서비스다' 라고 생각해도 될까요?

2024-06-03 00:10 UTC, choijy1705 requested changes
페드로 피드백 잘 반영해주셨습니다
몇가지 추가 코멘트남겼으니
확인해보시면 좋을것 같아요!

2024-06-03 00:10 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +    }
두개의 메서드가 거의 똑같은것 같습니다
중복으로 코드가 관리된다는 문제점과 코드의 의도가 명확하게 보이지 않는다는 문제점이 있을것 같습니다!
다른 사람이 봤을때 권한에 따라 결제가 되고 안된다는 점을 쉽게 이해할 수 있을까요??
if문 분기를 통해 권한에 따라 결제가 되거나 안되거나를 코드로 나타내면 어떨까요?

2024-06-03 00:10 UTC, choijy1705 commented on src/test/java/roomescape/service/reservation/ReservationServiceTest.java
> +class ReservationServiceTest extends ServiceTestBase {
결제에 대한 테스트는 어떻게 처리되나요?

2024-06-04 07:03 UTC, hw0603 commented on src/main/java/roomescape/config/RestClientConfig.java
> +    public PaymentRestClient paymentRestClient(ClientHttpRequestFactory factory, ObjectMapper objectMapper) {
현재 토스 결제 API에 종속되어 있으니 그게 더 올바른 이름이겠네요.
`PaymentClient` 인터페이스를 만들고 추상화를 해야 할지도 고민했었는데 아직은 토스페이 하나만 연동되어 있으므로 추상화가 필요한 단계는 아니라고 판단해서 따로 추가하지 않았습니다!

2024-06-04 07:21 UTC, hw0603 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private long amount;
외화로 결제하는 기능 등이 추가될 경우, 결제금액이 소수가 될 수 있음을 고려한 코멘트가 맞으실까요?

소수를 저장할 수 있는 타입 중, 부동소수점 오차가 가장 적은 `BigDecimal`로 변경해 두었습니다.

2024-06-04 07:39 UTC, hw0603 commented on src/main/java/roomescape/service/payment/PaymentService.java
> +        paymentRepository.deleteById(payment.getId());
어.. 2단계까지 같이 진행한 것은 아니고, 예약 대기 시 결제가 필수조건이 되면서 사용자가 예약 대기를 취소할 때 이를 환불해 주는 요구사항을 만족시키기 위해 `Payment` 테이블에 결제정보를 저장하는 과정이 추가됐다고 보시는 게 더 나을 것 같아요!

실제로 2단계 요구사항인 "내 예약 페이지에서 결제 정보 조회" 기능은 아직 구현되어 있지 않습니다🥲

hard delete vs soft delete 중에서는 Payment 정보의 경우 현재는 soft delete가 좀 더 적절하다고 생각하는데, 혹시 이 부분은 2단계를 구현하면서 좀 더 고민해 보고 반영해도 될까요?

2024-06-04 07:53 UTC, hw0603 commented on src/main/java/roomescape/service/payment/PaymentService.java
> +    public void cancel(Payment payment) {
DB에서 결제정보를 삭제했는데 결제 취소 API 호출 중 오류가 발생하면 모순적인 상태가 발생할 수 있겠네요.
하나의 트랜잭션으로 묶어 주었습니다!

2024-06-04 08:02 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        Reservation savedReservation = reservationRepository.save(reservation);
하나의 트랜잭션 안에서 `예약정보 검증 -> DB에 예약정보 저장 -> 결제 승인 API 호출` 의 순서로 실행되도록 변경하였습니다.

질문) 트랜잭션 내에서 외부와 통신할 때, 통신 시간만큼 DB 커넥션을 해당 트랜잭션이 잡고 있게 되는데 이러한 오버헤드는 고려하지 않아도 될까요? 아니면 예외 발생 시 롤백을 지원하기 위한 트레이드오프라고 생각해야 할까요?

2024-06-04 13:01 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +    }
초기에는 오버로딩을 통해 깔끔하게 작성했다고 생각했는데 결제 기능이 들어오고 이런저런 요구사항이 추가되면서 오버로딩된 두 메서드가 점점 산으로 가긴 하더라구요..🥲

`Payment`와 `Reservation`이 일대일 관계이기 때문에, 어드민에 의한 예약이라도 어드민에 의한 결제라는 정보를 구분하여 저장해 주어야 하므로 `PaymentType`에 `ADMIN` 을 추가하여 `PaymentService`에서 분기하도록 변경했습니다!

2024-06-04 18:44 UTC, hw0603 commented on src/test/java/roomescape/service/reservation/ReservationServiceTest.java
> +class ReservationServiceTest extends ServiceTestBase {
처음에는 예약 / 예약 대기 시 결제과정만 추가된 것이라 `ReservationServiceTest` 에서는 의미 있는 테스트를 구상하기가 애매했어요.  
이번 피드백을 반영하면서 예약 생성과 결제 승인이 하나의 트랜잭션으로 묶였고, 결제 승인에서 오류가 발생한 경우 예약이 생성되지 않음을 테스트하는 코드를 작성했습니다.

추가로, `TossPaymentClient`를 시나리오별로 실제 API와 유사하게 Mocking 하고, 각 케이스에 대한 `PaymentService` 에 대한 테스트를 추가해 두었습니다!

2024-06-04 18:46 UTC, hw0603 commented
안녕하세요😄 피드백 주셨던 부분들을 수정하여 다시 리뷰 요청 드립니다!
매 번 빠르고 친절한 리뷰 감사합니다! 😊

2024-06-04 19:02 UTC, hw0603 commented
미션과 직접적인 관련이 있는 내용은 아니지만, [토스 API 연동하기](https://docs.tosspayments.com/guides/payment-widget/integration#%EA%B2%B0%EC%A0%9C-%EC%9A%94%EC%B2%AD%ED%95%98%EA%B8%B0) 문서 를 읽다가 궁금한 점이 생겼습니다.

결제정보의 무결성 검증을 위해 다음과 같은 설명이 있었는데요,
> 결제 버튼 이벤트 설정
결제를 요청하기 전에 orderId와 amount를 서버에 임시로 저장하세요. 결제 요청과 승인 사이에 데이터 무결성을 확인할 때 필요해요.

해당 정보들은 최대 10분(고객이 결제를 해야 하는 시간) 동안만 유효하므로, 결제가 정상적으로 완료됐거나 10분이 니가 결제가 만료됐다면 의미 없는 정보가 됩니다.

고객이 결제 버튼을 누르는 순간 방탈출 서버로 데이터 전송이 일어나 `orderId`와 `amount`를 저장하게 되고, 그 직후 토스 API 호출을 통해 고객에게 결제 알림을 보내게 될 텐데요,

이러한 상황(우리 서버에 결제 예정 정보가 저장된 상황)에서 고객이 결제하지 않아 타임아웃이 된다면 결제 예정 정보를 db에서 제거할 방법이 없을 것 같아요.
(결제 예정 정보를 다루는 api와 결제 승인 api 가 경로부터 다를 확률이 높고, 전체 사이클이 매우 긴 시간(최대 10분)을 차지하는 만큼 한 트랜잭션으로는 관리가 불가능하다고 생각합니다. 애초에 사용자가 결제를 하지 않으면 토스 API 상에서 결제 시간 만료를 저희쪽으로 알릴 수 있는 방법도 없구요)

그렇다면 이 정보들은 보통 로그성 데이터로 보고 디비에 계속 쌓아두게 되나요? 아니면 PR 본문에서 드렸던 질문과 마찬가지로 레디스 등의 외부 도구를 사용하거나 잡을 돌려서 일정 주기마다 제거시키나요?

2024-06-05 14:46 UTC, choijy1705 approved these changes
페드로 피드백 반영 잘해주셨습니다👍
질문에 대한 답변과
몇가지 코멘트 남겼는데
다음 단계 진행하시면서 확인해봐주세요!
이번 단계는 여기서 머지할께요

2024-06-05 14:46 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        Reservation savedReservation = reservationRepository.save(reservation);
질문1) 흠... 트랜잭션을 잡고있으면 다른 요청을 처리 못한다고 생각하셨을까요? 작은 단위의 트랜잭션으로 처리된다면 크게 문제 될 부분이 없고 당연히 그렇게 처리되어야한다고 생각이들어서요.

질문2) 말씀 주신 상황에서는 먼저 외부에 요청하여 데이터를 받고 save를 하면 될것 같습니다. 아마도 완벽한 해결책은 없겠지만 재시도를 한다던가 아니면 다시 원복하는 api를 쏜다거나 하는 방법으로 처리를 해야할것 같아요

2024-06-05 14:46 UTC, choijy1705 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private long amount;
넵 맞습니다!
근데 부동소수점 오차가 가장 작은이라고 표현해주셨는데 BigDecimal 도 오차가 발생할 수 있나요??

2024-06-05 14:46 UTC, choijy1705 commented on src/main/java/roomescape/domain/payment/PaymentType.java
> +    public boolean isByAdmin() {
isAdmin이 적절할 것 같습니다

2024-06-05 14:46 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/PaymentService.java
> +        if (paymentRequest.paymentType().isByAdmin()) {
paymentRequest.isAdmin() 이 되도록 하는게 더 깔끔할것 같네요

2024-06-05 14:46 UTC, choijy1705 commented on src/main/java/roomescape/service/payment/TossPaymentClient.java
> +    }
제일 하단에 위치시키는게 좋아보여요!

2024-06-05 14:46 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.confirm(reservationRequest.toPaymentRequest());
confirm 안에서 admin 여부를 체크하는걸로 봤는데요
여기서 admin인지 체크하고 아닌경우 confirm이 호출되도록하는게 좋지 않을까 싶습니다!

2024-06-05 14:46 UTC, merged

2024-06-08 11:10 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        Reservation savedReservation = reservationRepository.save(reservation);
> 트랜잭션을 잡고있으면 다른 요청을 처리 못한다고 생각하셨을까요?

이렇게 생각했던 것은 아니긴 한데, DB 커넥션 자체도 나름 비싼(?) 자원이다 보니 한 트랜잭션 내에서 외부 API를 호출하게 되면 외부 API의 응답 소요시간에 따라 DB 커넥션을 다시 반환하는 시간도 지연될 것 같아서 드렸던 질문이였어요! 트랜잭션 단위로 작업을 관리하기 위해서는 감수해야 될 부분일 것 같기도 하네요🙂

2024-06-08 11:15 UTC, hw0603 commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private long amount;
`new BigDecimal(0.1)` 과 같이 부동소수점을 직접 명시하여 초기화하면 오차가 발생할 수 있는 것으로 알고 있어서 저렇게 표현을 했었는데, 생각해 보니 `BigDecimal`의 문제라고는 볼 수 없겠네요ㅎㅎ

2024-06-08 11:38 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.confirm(reservationRequest.toPaymentRequest());
현재 `Reservation` 테이블과 `Payment` 테이블이 분리되어 있으며 일대일 관계로 매핑되어 있습니다.
관리자에 의한 Reservation 이라도 결제정보가 존재해야 한다고 생각했고, 그 결제정보를 DB에 저장하기 위한 요청의 책임은 `PaymentService`라고 판단하여 `PaymentService`에서 관리자의 여부를 검증하여 분기하는 구조를 잡은 것이였어요. 

개인적인 의견이지만 `ReservationService`에서 "'관리자의 예약인 경우 결제 승인 과정 없이 '관리자 결제 정보'를 DB에 저장해!" 하는 것 보다는 `PaymentService` 안에서 "관리자의 결제 요청인 경우 외부 API 호출 없이 바로 DB에 저장해!" 하는 것이 좀 더 자연스러운 것 같아요. 애초에 `ReservationRequest`에서 이 요청이 관리자임을 확인할 수 있는 방법은 `String 'Payment'Type` 을 검사하는 방법밖에 없기도 하구요..!

2024-06-10 13:55 UTC, choijy1705 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.confirm(reservationRequest.toPaymentRequest());
결제를 하지 않았는데 결제 정보를 저장한다는것은 많이 이상한것 같습니다
로그성 정보를 원하는거라면 payment가 아닌 다른 테이블에 정보를 저장하도록 해야할것 같습니다!

admin 여부는 paymentService나 reservationService나 어디든 판단은 할 수 있을것 같습니다
개인적으로는 admin의 여부는 굳이 paymentService에서 알 필요가 없고 나중에 관리자, 일반회원이 아닌 다른 등급이 생겼을때 confirm 메서드안에서 새로운 분기를 추가하기보다는 호출하기 전에 확인하는게 더 명확할거라 생각했어요

2024-06-11 02:26 UTC, hw0603 commented on src/main/java/roomescape/service/reservation/ReservationService.java
> +        paymentService.confirm(reservationRequest.toPaymentRequest());
아아 여러 등급이 생겼을 때를 생각해 보면 좀 더 명확해지네요!

> 결제를 하지 않았는데 결제 정보를 저장한다는것은 많이 이상한것 같습니다

이 말도 맞는 말인 것 같아 관리자 예약의 경우 DB에 결제정보를 저장하지 않고, 관리자의 검증 역시 `ReservationService`에서 수행하도록 변경해 두었습니다 :)