[1단계 방탈출 결제 / 배포] 재즈(함석명) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #79
Opened 2024-05-30 08:54 UTC by seokmyungham

2024-05-31 16:16 UTC, syoun602 requested changes
안녕하세요 재즈 👋
방탈출 결제/배포 리뷰를 맡게된 썬입니다~
몇가지 코멘트 남겼으니 확인부탁드려요

2024-06-01 07:37 UTC, seokmyungham commented on README.md
> +- 결제 대기 상태에서 1시간 이내로 결제를 하지 않으면 자동으로 취소 상태로 변경되고, 다음 예약 대기가 결제 대기 상태로 변경된다.
저도 썬이 하시는 생각과 마찬가지로 테스트를 정말 중요하게 생각하고 있습니다. 

1단계부터 3단계까지는 계속 제 코드를 사용해왔었습니다. 그에따라 레벨 1에서 학습했던 TDD, 단위테스트의 중요성을 너무 잘 알기에 "입력과 출력이 존재한다면 모든 메서드는 테스트 대상이 될 수 있다." 는 기준으로 테스트 160개를 작성하고 커버리지 95% 이상을 유지하려 노력했습니다.

![image](https://github.com/woowacourse/spring-roomescape-payment/assets/97608735/b6dda89f-65bf-4325-bd9e-5c55fb960a84)

레벨 2 마지막 미션을 시작하기 전, 다른 사람의 코드를 처음 맞딱드렸을 때 나는 어떻게 대처할 수 있는지. 처음 보는 코드일지라도 유연하게 유지보수 해 나갈 수 있는지를 경험해보고 싶었고 처음으로 페어의 코드를 선택하게 되었습니다. 

> 추후에 테스트 없는 서비스를 유지보수 해야하는 사람 입장에서 막막하지 않을까요?

말씀해주신 부분을 이번에 직접 몸소 겪었던 것 같습니다. 선택한 코드는 테스트가 많이 미흡했습니다. 테스트 없이 코드를 작성하는 경험은 이번이 처음인데, 미션을 진행하는 동안 많이 힘들었고 테스트가 없으니 사소한 기능 하나하나 정상적으로 작동하는지 파악할 수 없었습니다. 도메인 검증이 정상적으로 이루어지는지를 판단하기 위해 서버를 실행시키는 것은 말이 안됩니다. 오히려 이러한 경험을 통해 테스트가 얼마나 중요한지 다시 한 번 깨닫게 되었던 것 같습니다. 

스스로 코드를 봤을 때 테스트가 비어있는건 저도 용납을 못하는 성격입니다.. 😥
코드를 선택하게 된 배경과 테스트를 바라보는 시각에 대해 PR에 작성한 설명이 많이 미흡했던 것 같아 걱정되면서도 죄송하네요.. 

마지막 미션을 진행하며 지금까지 학습했던 내용들을 모두 활용하여 올바른 목적을 가진 테스트를 작성해보겠습니다.

2024-06-01 07:49 UTC, seokmyungham commented on README.md
> +- 결제 대기 상태에서 1시간 이내로 결제를 하지 않으면 자동으로 취소 상태로 변경되고, 다음 예약 대기가 결제 대기 상태로 변경된다.
> 고도화는 요구사항을 먼저 만족하고 진행하는게 맞는 것 같습니다. 이번 미션의 핵심은 외부 API와의 연동,예외 처리, 3자의 장애 전파에 대한 고려와 이를 어떻게 테스트할지, 어떤 목적으로 작성된 테스트인지를 구분하는 것 같아요. 미션의 본질에 초점을 맞추고 안정적인 기반을 먼저 구축하는 것은 어떨까요?

처음 기능을 사용할 당시에는 본질을 파악하지 못하고 기능 사용에만 급급했던 것 같습니다.
말씀해주신 부분들에 초점을 맞추어 문제를 고민해보고 학습하겠습니다.

2024-06-01 08:01 UTC, seokmyungham commented on src/main/java/roomescape/application/ReservationService.java
> +    public synchronized ReservationResponse saveReservationByAdmin(ReservationRequest request) {
멀티 쓰레드 환경에서 발생할 수 있는 동시성 관련 문제를 고려하여 사용하게 되었습니다.

리뷰를 받고 생각해보니 synchronized 키워드가 꼭 필요한 블록이 아닌 메서드 레벨에 사용되어 발생하는 병목현상, 외부 api가 추가됨에 따라 발생할 수 있는 지연을 고려한다면 해당 키워드를 제거하고 다른 방식을 고려해봐야 할 것 같습니다.

추가로 어드민의 기능도 동시성을 고려해야할까? 를 생각해보면 아닐 것 같다는 생각도 드네요.
현재 미션 요구사항에 맞지 않는 영역이기도 하구요.
해당 키워드를 모두 제거하겠습니다.

2024-06-01 08:26 UTC, seokmyungham commented on src/main/java/roomescape/application/CancelService.java
>      private final CancelEventPublisher eventPublisher;
현재 예약 취소 발생 시 다음 대기자를 자동으로 예약상태로 변경하는 자동 승인 방식을 사용하고 있습니다.

이번 미션에서 결제가 추가됨에 따라 예약이 취소되었을 때 결제 되지않은 다음 대기자를 바로 예약 상태로 변경하면 문제가 발생합니다. 이를 중간에 `결제 대기` 상태를 추가하고, 일정 시간 마다 결제 상태를 확인하여 `결제 대기` 상태에서 결제를 하지않으면 `예약 취소` 이벤트를 발행하는 방식으로 문제를 해결해보았습니다.

리뷰를 받고 이벤트 발행 없이 처리하는 방법을 오래 고민해보았는데 마땅한 방법이 잘 떠오르지 않네요.. 🤔
예약 대기도 결제가 필요하도록 하는 방법이 있을 것 같은데 서비스 측면에서 좋은 방법은 아닐 것 같아요.
썬 생각은 어떤지 궁금합니다!

2024-06-01 08:36 UTC, seokmyungham commented on src/main/java/roomescape/infra/InfraConfiguration.java
> +                .withReadTimeout(Duration.ofSeconds(5));
`connectTimeout`은 클라이언트 - 서버 관계에서 서버에 설정된 시간까지 서버에 연결에 실패하면 발생하는 것으로 알고있고 `readTimeout`은 연결에는 성공했지만 서버로부터 응답이 돌아오지 않으면 발생하는 것으로 학습했습니다.

커넥션을 얻는 시간이 3초가 넘어가면 사용자를 대기 화면에서 방치하는 것이 아니라 적절한 응답을 내리고 다시 결제를 시도하도록 하는게 적절하다고 생각했습니다.

또한 토스 페이먼츠에서 권장하는 `readTimeout`은 30~60초인데 왜 이러한 시간을 권장하는지 잘 모르겠어요. 
https://docs.tosspayments.com/reference 

예약 서비스 사용자가 결제 되기까지 30초를 기다릴 수 있을지를 생각하면 말이 안된다 생각해요.
토스로부터 돌아오는 응답이 5초 이상 걸리면 해당 요청안에서 해결 불가능한 문제가 발생했다고 판단하고 타임아웃을 발생시켜 다시 결제를 시도하도록 해야할 것 같아요. 

제가 잘못 생각하고 있는지 궁금하고 가르침을 받고 싶습니다. 🙇‍♂️

2024-06-01 09:09 UTC, seokmyungham commented on src/main/java/roomescape/infra/repository/MemberRepositoryImpl.java
> +    private final MemberJpaRepository memberJpaRepository;
`MemberRepository` 는 도메인 명세를 나타내도록 하고 위치를 도메인 계층에 두어 `application` 계층에서 저수준의 `respository` 의존성을 끊어낼 수 있었어요. 이번에 처음 시도해 본 방법인데 느낀 점은 다음과 같습니다.

- 레벨 1에서 학습했던 것 처럼 MemberRepository를 일급 컬렉션으로 사용할 수 있다.
- 도메인 명세를 상속하도록 하고 저수준의 구현체를 필드로 두어 application은 도메인을 의존하도록 할 수 있다.
- application 계층이 특정 기술에 의존하는 것을 벗어나 변경에 유연하다.
- 하지만 계층과 의존성을 분리하기 위해 추가로 객체를 생성하는 비용이 필요하다.
- 현재 spring jpa를 사용하고 있는 관점에서 유지 보수하기 힘들고 메서드를 사용할 때 실수할 가능성이 존재한다.

항상 뭐든 트레이드 오프가 존재하고, 그 사이에서 비용을 투자하고 회수할 수 있는지를 판단하는게 중요하다고 생각돼요.
스프링으로 넘어오면서 레벨 1처럼 객체 지향을 했었던 부분과 거리가 있다고 느꼇고 이러한 시도를 해보게 되었어요.

썬도 이러한 고민을 하셨었나요..? 어떻게 생각하시는지 궁금해요

2024-06-01 09:22 UTC, seokmyungham commented on src/main/java/roomescape/infra/InfraConfiguration.java
> +    private final PaymentProperties paymentProperties;
저는 보통 controller service repsotiry domain 으로 계층을 나누곤 했는데
페어는 web application domain infra로 계층을 선택하는 것 같았고, 페어의 코드를 선택한 만큼 변경하지 않고 페어의 의도를 존중하고자 했어요.

각 객체를 역할에 맞게 계층에 분배하면서 `infra`가 조금 모호한 계층이라고 느껴졌던 것 같아요.
`infrastructure` 계층을 의도해서 어플리케이션 전반으로 기술적으로 문제를 해결하기 위한 객체가 모인 집합으로
이해하고 미션을 진행했는데 올바르게 계층을 사용한게 맞을까요?

2024-06-01 09:25 UTC, seokmyungham commented on src/main/java/roomescape/domain/payment/PaymentRepository.java
> +}
앗 2단계에 DB연동이 있었군요.... 😅

`요구사항에 나와있지 않은 부분들은 스스로 고민하고 해결한다.` 는 
우아한 테크코스의 취지를 생각해서 결제 정보를 저장하는 일은 당연하다고 생각했는데, 의도치 않은 변경을 만들었네요.. 😥

2024-06-04 13:36 UTC, seokmyungham commented
안녕하세요~ 썬 😀

엄청 만족스럽지는 않지만 반드시 필요하다 생각되는 부분들의 테스트를 모두 작성했습니다!

그리고 말씀해주신 에러 메시지 관련 리뷰를 토스에서 내려주는 StatusCode와 Enum을 활용해서 매핑해보았고
결제 벤더들이 추가 될 가능성을 염두하여 `@ConfigurationProperties`와 `RestClient Builder` 추상화에 신경써보았습니다.
적절히 잘 했는지 궁금합니다.

DB 저장은 다음 단계 요구사항을 미리 보지 않는 방식을 선호해서, 잘못 판단하게 되었는데 일단 남겨두었습니다.. 😥

긴 글과 코드 읽어주셔서 감사드리고
리뷰 기다리겠습니다. 🙇‍♂️

감사합니다 😊

2024-06-06 05:47 UTC, syoun602 approved these changes
안녕하세요 재즈~

우선 리뷰가 조금 늦어져서 죄송해요 😭
1단계 요구사항은 충족된 것 같아 이만 머지해도 될 것 같습니다!
테스트 추가에 요구사항 반영까지 할게 많았을텐데 잘 진행해주셨네요 👍
몇가지 코멘트 남겨두었는데, 2단계 pr이나 코멘트에서 답변 주세요!

2024-06-06 05:47 UTC, syoun602 commented on src/main/java/roomescape/infra/repository/MemberRepositoryImpl.java
> +    private final MemberJpaRepository memberJpaRepository;
말씀하신대로 유지보수와 비용에 더 초점을 맞추는게 맞을 것 같습니다. 스프링이 객체지향의 끝판왕이긴 한데, 어떤 점에서 벗어나고 있었다고 생각했는지 궁금하네요. 저라면 굳이 분리를 하지는 않았을 것 같습니다. 말씀한 변경에 유연하다는 장점이 지금은 없을 것 같아서요. 미션이기 때문에 이것저것 시도의 목적으로 해본 것이라면 괜찮지만, 불필요한 작업이었다고 생각되면 롤백하는 것도 좋아보여요.

2024-06-06 05:47 UTC, syoun602 commented on src/main/java/roomescape/infra/InfraConfiguration.java
> +    private final PaymentProperties paymentProperties;
말씀주신 패키징은 ddd의 내용인 것 같아요. 지금은 ddd를 의식하지 않고 현재 미션의 제공하는 학습 내용에 초점을 맞추는게 더 좋아보입니다~! 올바르게 사용했다고 보기는 힘들 것 같아요. 의존성을 분리하기 위해 repository를 분리했는데, infrastructure 레이어에 남아있을 필요가 있을까요?

2024-06-06 05:47 UTC, syoun602 commented on src/main/java/roomescape/infrastructure/payment/TossPaymentClient.java
> +                    .uri("https://api.tosspayments.com/v1/payments/confirm")
공통되는 url의 경우 yml에 추가해볼 수 있을 것 같습니다~

2024-06-06 05:47 UTC, syoun602 commented on src/main/java/roomescape/infrastructure/payment/toss/TossResponseErrorHandler.java
> +        log.error(apiError.message());
로깅 👍 여기에 구체적으로 어떤 이유로 예외가 발생했는지 알기 위해 추가적인 작업이 필요하지 않을까요~?

2024-06-06 05:47 UTC, syoun602 commented on src/test/java/roomescape/infrastructure/payment/TossPaymentClientTest.java
> +    PaymentClient tossPaymentClient;
접근 제어자와 beforeEach에서만 사용되는 필드들 정리가 필요해보입니다

2024-06-06 05:47 UTC, syoun602 commented on src/test/java/roomescape/infrastructure/payment/TossPaymentClientTest.java
> +        mockRestServiceServer = MockRestServiceServer.bindTo(builder).build();
잘찾아서 학습해주셨네요 👍

2024-06-06 05:47 UTC, merged