[2 ~ 4 단계 방탈출 예약 결제 / 배포] 백호(전호건) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #83
Opened 2024-06-04 10:50 UTC by Arachneee

안녕하세요 범블비!
백호입니다!

### 웹개발 경험
Spring 과 JPA로 게시판을 로컬에서 만들어본 경험이 있습니다. 외부 API 연동 및 배포한 경험은 없습니다.

도메인 정책, ERD, API 문서는 README에 적어 두었습니다.

[배포 URL](http://43.201.59.111:8080)

### 테스트 계정

어드민 계정
ID : `admin@admin.com`
PW : 1234

유저 계정
ID : `user1@user.com`
PW : 1234

질문은 코멘트에 남겨두겠습니다.

2024-06-04 11:09 UTC, Arachneee commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Long memberId;
이전 예약 대기 미션에서 생명주기가 다른 엔티티의 경우 꼭 연관관계를 가지지 않아도 된다는 피드백을 받았습니다.
제 생각에 예약이 취소되어도 결제 내역은 계속 남아있어야하므로 생명주기가 다르다고 생각합니다. 또한 서로의 관심사와 도메인 자체가 다르다고 생각합니다. 그래서 예약과 결제가 연관관계를 가질 필요가 없다고 생각합니다.

실제로 분리를 해서 설계를 해보니 결제 입장에서 예약의 상세내역이나 회원의 상세내역을 알 필요가 없기때문에 id만으로 충분히 자신의 역할을 할 수 있었습니다.

범블비는 이런 구조에 대해 어떻게 생각하시나요?

2024-06-04 11:47 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    private List<WaitingMember> waitingMembers = new ArrayList<>();
이전 미션까지는 Reservation을 단순히 예약 내역으로 생각했습니다. 
하지만 결제 도메인이 생기고 나서 Reservation은 더 이상 예약 내역만을 의미하지 않고 하나의 상품이라고 생각하게되었습니다. 
그래서 하나의 상품에 대해 결제한 내역이 존재하는 것이고 상품을 예약한 한명의 사람과 예약 대기를 하고 있는 사람들이 생긴것으로 도메인을 이해했습니다.

범블비는 이런 도메인 구조에 대해 어떻게 생각하시나요?

2024-06-04 11:47 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
양방향 연관관계를 이용해서 도메인 로직을 도메인 내부에서 처리할 수 있도록 했습니다.
도메인 로직을 도메인 내부로 위치시키면 서비스 계층이 깔끔해진다는 장점이 있습니다.
하지만 범용적이지 않은 도메인 로직이 도메인 내부로 들어가게되면 도메인의 재활용이 어려워집니다.

범블비는 양뱡향 연관관계를 이용한 도메인 로직처리에 대해 어떻게 생각하시나요?

2024-06-04 11:47 UTC, Arachneee commented on src/main/java/roomescape/service/ReservationPaymentService.java
> +public class ReservationPaymentService {
1단계와 비슷하게 ReservationService에서 PaymentService를 호출하는 형태로 할 수 도 있었지만 두 서비스를 모두 사용하는 새로운 서비스로 계층화 시켰습니다.

Reservation과 Payment를 분리하고 싶다는 생각이 있었습니다. 그래서  ReservationPaymentService를 만들었습니다. 하지만 컨트롤러 입장에서 ReservationPaymentService,  ReservationService, PaymentService 중 어떤 것을 사용해야할지 알기 어려울 것 같습니다.

해당 서비스 객체에 대해 범블비는 어떻게 생각하시나요?

2024-06-04 11:47 UTC, Arachneee commented on src/main/java/roomescape/controller/ReservationController.java
> +    private final ReservationPaymentService reservationPaymentService;
하나의 컨트롤러에서 2개의 서비스를 호출하고 있습니다. 컨트롤러 입장에서 2개 중 어떤 서비스를 사용해야할지 헷갈릴 것 같습니다.
이럴 때 컨트롤러를 분리하는 것이 좋을까요? 
아니면 컨트롤러의 메소드를 ReservationPaymentService 만 호출하는 구조로 통일하고 ReservationPaymentService에서 ReservationService를 호출해서 바이패스하는 형태로 하는 것이 좋을까요?

2024-06-05 11:09 UTC, ddaaac requested changes
안녕하세요 백호 👋 

구현 잘 해주셨네요

몇 가지 코멘트 남겼으니 확인부탁드려요.

2024-06-05 11:09 UTC, ddaaac commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Long reservationId;
반대로 Reserv -> Payment를 의존하게 할 수도 있었을 것 같아요. 이 설계의 이유가 궁금힙니다.

2024-06-05 11:09 UTC, ddaaac commented on README.md
> +![ERD.png](ERD.png)
erd는 어떤 툴로 그려주신 걸까요? 일대다 등의 관계가 어떻게 표시되는지 궁금하네요.

2024-06-07 05:51 UTC, Arachneee commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Long memberId;
그런데 엔티티가 객체 중심의 구조가 아니라 단순히 테이블과 매핑되는 용도로만 사용되는 것처럼 보입니다.
또한 reservationId가 실제 존재하는 예약의 ID 인지도 확실하지 않게 되고요.
이에 대해서는 어떻게 생각하시나요?

2024-06-07 06:26 UTC, Arachneee commented on src/main/java/roomescape/controller/ReservationController.java
> +    private final ReservationPaymentService reservationPaymentService;
ReservationController 에서 예약과 예약 대기가 ReservationPaymentService와 ReservationService로 분리되어 있습니다.
예약은 결제가 필요하지만 예약 대기는 결제가 필요하지 않기 때문입니다.
그래서 컨트롤러를 예약과 예약 대기로 나누는 것이 좋을 것 같습니다.

2024-06-09 04:45 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
적절한 예시인지는 잘 모르겠지만 ReservationTime이 `List<Reservation>`을 양방향연관관계로 가지고 있어 예약된 시간인지 판별하는 로직을 도메인으로 넣을 수 도 있을 것 같습니다.

위 예시와는 별개로 현재 고민인 부분은 도메인 로직을 도메인에 위치시키는 것이 좋을지 Service 객체에 위치시키는 것이 좋을지 입니다.
저는 최대한 도메인 스스로 처리할 수 있는 로직은 도메인 객체에 위치하는 것이 더 좋다고 생각합니다.
테스트에도 용이하고 POJO 로 작성할 수 있기 때문입니다.

그런데 다른 도메인과의 협력이 필요한 로직들이 있습니다. 이런 로직을 양뱡향 연관관계를 사용하여 도메인 내부에서 처리할 수 있다면   최대한 도메인 내부에서 처리하는 것이 좋을지 아니면 Service 객체에서 처리하는 것이 좋을지 고민입니다.

상황마다 다르겠지만 그 기준을 어떻게 세우는 것이 좋을까요?
범블비는 양뱡향 연관관계를 언제 사용하시나요? 언제 필요하다고 느끼시는지 궁금합니다.

2024-06-09 05:14 UTC, Arachneee commented on README.md
> +[API 문서](https://documenter.getpostman.com/view/28524192/2sA3Qy69if)
spring rest docs와 swagger는 이전에 사용해 본 적이 있습니다.
swagger는 애너테이션만 추가하여 간편하게 API 문서를 만들 수 있는 장점이 있지만 프로덕트 코드를 수정해야하는 단점이 있습니다.

rest docs는 프로덕트 코드를 건드리지 않고 테스트 코드를 추가하여 API 문서를 만들 수 있습니다. 하지만 추가해야하는 테스트 코드의 양이 많고 문서 작성만을 위한 테스트 코드를 추가해야합니다.

postman은 별도의 코드 작성 없이 api 호출 몇번으로 문서를 만들 수 있는 장점이 있습니다.

문서를 계속 유지보수해야 한다면 rest docs를 선택할 것 같습니다. 하지만 현재는 유지보수를 할 필요가 없기 때문에 빠르게 생성할 수 있는 postman을 선택했습니다.

2024-06-09 07:53 UTC, Arachneee commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private String orderId;
결제 승인 API를 호출할 때 orderId가 필요합니다.
나중에 결제 실패 시 재시도를 할 수 있으므로 저장했습니다.

2024-06-09 08:00 UTC, Arachneee commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Long reservationId;
예약에게 결제는 필수 요소가 아니지만 결제는 예약이 필수 요소라고 생각합니다.
또한 예약에게 결제는 주 관심사가 아니라고 생각합니다. 예약은 어떤 날짜, 시간, 테마에 누가 예약했는지가 관심사이지 결제 정보는 관심사가 아닙니다.
반면에 결제는 누가 무엇을 결제했는지가 관심사로 예약을 의존해야합니다.

Reserv -> Payment 로 의존을 하게 되면 예약은 예약 정책과 결제정책 2가지에 의해 변경될 수 있게 되어 단일 책임 원칙에 위배된다고 생각합니다.

범블비는 어떤 의존방향이 더 유지보수에 유리하다고 생각하시나요?

2024-06-09 11:51 UTC, Arachneee commented on README.md
> +![ERD.png](ERD.png)
Intellij 기능 중 Persistence 의 erd를 분석해주는 툴을 사용했습니다.
일대다와 일대일 관계가 구분이 안되는게 조금 아쉽긴하네요.
범블비는 어떤 툴을 주로 사용하시나요?

2024-06-10 11:12 UTC, ddaaac requested changes
안녕하세요 백호 👋 

리뷰 반영 잘 해주셨네요.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-06-10 11:12 UTC, ddaaac commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
양방향 관계를 꼭 잡아야하나 싶긴 해요. 객체 간에 순환참조가 생기는 점이 가장 걸립니다.

```java
        Reservation reservation = findReservation(reservationRequest.date(), reservationRequest.timeId(), reservationRequest.themeId());
        ...
        BookedMember bookedMember = reservation.book(member);
        bookedMemberRepository.save(bookedMember);
        return ReservationResponse.createByBooked(bookedMember);
```

여기 코드를 보면 예약을 찾고, 예약 멤버를 만들어서 저장하고, createByBooked 내부에서는 다시 member에서 예약을 꺼내서 사용하고 있어요. 이 예약이 어떤 예약인지 member 안의 예약과는 다른건지 신경써야하는 부분들이 생깁니다. 
그래서 다른 걸 떠나서 이런 코드가 읽기 쉬운지, 유지보수가 쉬운지에 대해서는 잘 모르겠네요. 
JPA를 쓰기 때문에 양방향 관계가 적절해보이는건지, 원래 객체들이 양방향 관계를 갖는게 적당한데 이를 지원해주는 기술이 JPA라서 사용하는건지를 생각해보시면 좋을 것 같습니다.
어떤 설계를 하든, 어떤 기술을 쓰든 가장 중요한 건 코드를 이해하기 편하냐에 있는 것 같아요.

2024-06-10 11:12 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationPaymentServiceTest.java
> +class ReservationPaymentServiceTest extends IntegrationTestSupport {
서비스 테스트에 Web 환경이 뜰 필요가 있을까요?

2024-06-10 11:12 UTC, ddaaac commented on src/main/resources/application.yml
> +      on-profile: test
test 관련 설정은 test 패키지에 있어도 되지 않을까요?

2024-06-10 11:12 UTC, ddaaac commented on src/main/java/roomescape/service/dto/AdminReservationBookedResponse.java
> +        LocalTime time,
타임존이 필요한 정보였다면 ZonedDateTime을 사용하는 게 맞지 않나 싶기도 하네요.

2024-06-10 11:44 UTC, Arachneee commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Long memberId;
필드에 `Reservation reservation` 으로 객체의 관계를 참조로 표현하는 것이 아닌 `Long reservationId` 로 표현하는 것은 테이블의 컬럼을 필드로 표현한 것과 같기 때문에 엔티티가 객체 중심으로 설계되지 않았다고 느꼈습니다.

북마크의 예시 적절한 것 같습니다.

2024-06-10 12:20 UTC, Arachneee commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +    }
```java
bookedMemberRepository.save(bookedMember);
return ReservationResponse.createByBooked(bookedMember);
```
이 부분이 BookedMember는 cascade에 의해 persist 되므로 로직 상 없어도 되는 부분인데 POST 호출 후 location 헤더와 응답 body 때문에 필요했습니다.
간접적으로 service에서 controller를 의존하는 형태라고 생각합니다. controller의 응답때문에 억지로 넣은 느낌이 들어 마음에 들지 않습니다.

확실히 양뱡향 연관관계를 사용하면 신경써야할 부분이 생기고 다른 개발자의 실수를 유발할 수 도 있는 것 같습니다.
`코드를 이해하기 편한가` 를 생각하고 있지만 뭐가 더 이해하기 편하지 판단하기 어렵네요. 더 많은 코드를 보면서 경험을 쌓아야 할 것 같습니다.

2024-06-11 00:57 UTC, Arachneee commented on src/test/java/roomescape/service/ReservationPaymentServiceTest.java
> +class ReservationPaymentServiceTest extends IntegrationTestSupport {
서비스 테스트에서 Web환경이 뜰 필요는 없습니다.
하지만 Web환경이 뜨고 안뜨고가 성능적으로 큰 차이가 없는 것으로 알고 있습니다. 성능 외에 문제가 될 수 있는 부분이 있을까요?
저는 컨트롤러 테스트와 서비스 테스트의 Web환경을 분리해서 Spring 컨테이너를 따로 2번 띄우는 것보다 통합해서 1번 띄우는 것이 테스트 속도에 더 이점이 있다고 생각합니다.
물론 프로그램이 더 방대해지고 테스트가 더 많아진다면 분리하는 것을 고려해볼 것 같습니다.

2024-06-11 01:32 UTC, Arachneee commented on src/main/resources/application.yml
> +      on-profile: test
패키지로 분리하는 것이 더 좋겠네요!

2024-06-11 01:39 UTC, Arachneee commented on src/main/java/roomescape/service/dto/AdminReservationBookedResponse.java
> +        LocalTime time,
ZonedDateTime 도 있었군요.
현재 타임존이 필요하지 않으므로 제거했습니다.

2024-06-11 03:57 UTC, ddaaac approved these changes
안녕하세요 백호 👋 

리뷰 반영 잘 해주셨어요.

이번 미션은 여기서 머지할게요. 고생 많으셨습니다.

2024-06-11 03:57 UTC, ddaaac commented on src/main/java/roomescape/domain/payment/Payment.java
> +    private Long memberId;
- 서비스가 커지고 요구사항이 많아지면 도메인은 정말 커지게 되고, 도메인끼리의 참조 관계도 복잡해집니다. 이를 모두 객체 참조로 표현했을 때 어떤 문제들이 발생할지 고민해보시면 좋을 것 같아요.
- 조금 더 생각해보면 id를 참조하는 건 객체지향이 아닌가?에 대해서도 고민해보셔도 좋을 것 같아요. 이번 단계의 학습 목표는 아니니 앞으로 쭉 고민해보시면 좋을 것 같네요.

2024-06-11 03:57 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationPaymentServiceTest.java
> +class ReservationPaymentServiceTest extends IntegrationTestSupport {
전체 테스트를 돌릴 때도 있지만 개별적으로 테스트를 돌릴 때도 있겠죠. 

코멘트를 남긴 의도는 이 테스트가 무엇을 테스트하는지에 집중해서 잘 표현하면 좋을 것 같아서였습니다. 다른 개발자들이 처음 이 코드를 본다면 "서비스 레이어에서도 웹 환경이 필요한가?"라는 의문을 갖게 되겠죠. 솔직히 스프링 컨텍스트 한두번 더 뜨는 건 테스트가 많아지면 딱히 시간 차이도 나지 않긴 합니다.

2024-06-11 03:57 UTC, merged