[2 ~ 4 단계 방탈출 예약 결제 / 배포] 클로버(이은정) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #86
Opened 2024-06-05 09:01 UTC by eunjungL

안녕하세요, 수달! 클로버입니다. 🍀 

2단계 요구사항에서 필요했던 결제 정보 저장을 1단계에서 이미 진행하여 미션이 조금 빠르게 끝났습니다!
혼자 계속 리팩토링하는 것보다 수달과 피드백을 주고 받는게 학습에 더 도움이 될 것 같아 리뷰 요청 드립니다.

## 데이터베이스 구조
![image](https://github.com/woowacourse/spring-roomescape-payment/assets/62099953/e15a295a-69f0-47bc-b5ad-c0678377e2a8)
데이터 베이스 구조는 1단계와 동일합니다!

## API 문서
이번에는 swagger를 사용하여 API 문서를 작성했습니다. 
- RestDoc은 이미 API가 많이 나온 상황에서 새롭게 제작하기에 공수가 많이 든다고 느꼈고 수정이 발생할 때 작성된 문서를 수정해줘야 하므로 유지보수 비용이 크다고 생각했습니다. 또한 API 문서에서 바로 테스트를 실행할 수 없어 불편하다고 느껴졌습니다. 
- Swagger는 자동으로 API 문서가 작성되어 편하고 (현재는 사용하지 않지만..) 인증이 필요한 상황에서 공통적으로 적용할 수 있는 장점이 있다고 생각했습니다. 또한 API 문서에서 바로 테스트가 가능한 것도 장점이라 생각해 Swagger를 선택했습니다.

API 문서 확인을 위한 주소는 `baseUrl/swagger-ui/index.html`입니다.
- 배포 서버: `http://54.180.235.218:8080/swagger-ui/index.html`
- 로컬 서버: `localhost:8080/swagger-ui/index.html`

## 요구사항 관련 정책
### 내 예약 목록 조회
- 관리자가 결제 없이 예약을 만들어줄 수 있으므로 "예약" 상태일 때도 결제가 없는 경우가 발생할 수 있습니다.

남은 미션 기간도 잘 부탁드립니다!
감사합니다. 🙇

2024-06-06 11:48 UTC, her0807 commented
클로버! 배포까지 잘 구현해주셨군요 👍🏻

올려주신 ERD 에는 1:N 과 같은 테이블간에 관계에 대한 설명이 누락되어 있는 것 같습니다. 
그부분도 같이 포함해서 올려주시면 좋을 것 같아요~

2024-06-06 11:50 UTC, her0807 requested changes
안녕하세요 클로버!

결제/ 배포 미션 빠르게 잘 구현해주셨군요 

문서화를 위한 툴 선정에 대해서 공유해주신 점 👍🏻
다음 레벨에서 팀플 할 때 유용하게 쓰일 겁니다 ㅎㅎㅎ 

그래서 소통하기 좋은 문서에 대한 내용도 조금 담아서 리뷰 남겼습니다. 
참고해서 빠르게 반영하고 재리뷰 요청해주세요!

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("해당 예약은 결제가 존재하지 않습니다."));
find vs get  이 두가지의 차이가 뭘까요? 🤔

사용하시는 jpa repository 내부에 존재하는 CRUD Repository 에서 힌트를 찾을 수 있습니다.

2024-06-06 11:50 UTC, her0807 commented on README.md
> +- [ ] logger를 통해 적절한 로깅을 처리한다.
적절한 요구사항 도출 👍🏻

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/auth/controller/AuthController.java
> +@Tag(name = "권한 컨트롤러")
적절한 태그로 분리 👍🏻

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/reservation/controller/AdminReservationController.java
>          return reservationFacadeService.createReservation(request);
스웨거는 다른 개발자에게 해당 API 사용하는 방법을 설명해주는 용도로 쓰이는데요~ 

특정 요청에 필요한 정보의 변수명으로만으로는 충분한 설명이 되지 않을 수도 있어요. 
그래서 description, example 을 활용해서 데이터의 설명과 더불어서 어떤 형태로 데이터가 들어오면 좋은지를 
구체적으로 명시해보면 좋을 것 같아요!

(참고사항) controller 에 description 을 적용해주신 것도 있는데 controller 에 사용하게되면 가독성이 떨어질 수 있어 
보통 requestDto 로 매핑해서 해당 오브젝트 내에서 선언해두곤 하는 것 같습니다. 


Parameter(description = "페이지 번호", example = "1")
<img width="672" alt="스크린샷 2024-06-06 오후 8 30 16" src="https://github.com/woowacourse/spring-roomescape-payment/assets/26570275/c80536ee-3bd1-4a79-b46c-45135799ae3c">

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/exception/PaymentFailureException.java
> +
전체적으로 불필요한 개행이나 컨벤션에 어긋나는 것들 한번 정리해볼까요?

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +        return paymentRepository.findByMemberReservation(memberReservation);
어떤곳에서는 find 인데 데이터가 없으면 예외를 반환하고, 어떤곳은 옵셔널을 반환하는데요~
위에서 남겨놓았던 코멘트와 함께 통일성 있게 개선되면 좋을 것 같아요 🙂

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/reservation/controller/MemberReservationController.java
> +                                                          Long id,
적절한 개행 맞춰볼까요?

2024-06-06 11:50 UTC, her0807 commented on src/main/java/roomescape/reservation/facade/ReservationFacadeService.java
> +    public List<MyReservationResponse> readMyReservations(LoginMember loginMember) {
적절한 메서드명에 대한 고민 후 리팩터링을 진행하셨군요 💯

실제 서비스에서는 요구사항이 바뀌는 일이 상당히 빈번한데요~ 
현재는 로그인 유저에 한해서 예약을 조회할 수 있지만, 추후 비로그인 유저에게 핸드폰번호만으로 방탈출 예약 정보를 
조회할 수 있게 변경할 수도 있습니다. 그래서 메서드 명은 최대한 범용적이게 적는게 좋은 것 같아요. 😄
메서드명에서는 행위, 리소스, 리소스를 찾기 위한 주체를 도메인이 명확하게 드러나게 적으면 재사용성도 올라가고, 
다른 개발자와 소통도 조금 더 쉬운것 같아요.

예를 들면, `findAllReservations` or `findAllReservationsByMember`

2024-06-07 07:53 UTC, eunjungL reviewed
안녕하세요, 수달! 클로버입니다. 🍀
세세한 리뷰 감사합니다, 덕분에 놓치고 있던 부분을 많이 채울 수 있었습니다!

## ERD
![image](https://github.com/woowacourse/spring-roomescape-payment/assets/62099953/5b936ac5-6f94-4ca7-b28a-64d4ac3289aa)

저번 ERD에는 1:N 등의 연관관계 표시를 하지않아 새롭게 그려봤습니다! 글자로 표시하는 것보다 화살표로 명시하는 것이 더 가독성이 좋을 것 같아 화살표를 사용해 표시했습니다.

## 개행 정리 제외 리뷰 주소
추가로 전체적으로 개행을 정리하느라 file changed가 많아 리뷰에 불편함이 있으실 것 같습니다.
개행 정리 커밋을 제외한 리뷰 주소는 [여기](https://github.com/woowacourse/spring-roomescape-payment/pull/86/files/16743ce848f4de00580389c1e8e016e9079a632c..01526f5a53dd8ce8cb2e6cbbd0a55e79e2c9c1f7)입니다! 
참고 부탁드립니다. 🙇 

## swagger 수정 관련
swagger와 관련된 부분도 파일이 너무 많이 변경될 것 같아 미션 범위인 `관리자 예약 컨트롤러`, `사용자 예약 컨트롤러`와 관련된 DTO만 우선적으로 리뷰를 적용하였습니다.
나머지 부분은 리뷰가 마무리된 후 추가하도록 하겠습니다!

남은 방탈출 예약 결제 미션 기간도 잘 부탁드립니다! 👍 👍

2024-06-09 07:10 UTC, her0807 approved these changes
안녕하세요  클로버~
리뷰어 수달입니다. 🙂

더이상 드릴 코멘트가 없을 정도로 잘 구현해주셨네요. 👍🏻
이제 협업할 준비가 되신 것 같습니다. 

미션 진행하느라 고생 많으셨습니다. 
이만 머지할게요 🥹

2024-06-09 07:10 UTC, merged