[2 ~ 4 단계 방탈출 예약 결제 / 배포] 안나(김민겸) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #87
Opened 2024-06-05 11:44 UTC by Mingyum-Kim

안녕하세요 제이미 😄
2, 3, 4단계의 요구사항을 구현하고 다시 리뷰 요청 드립니다.

👉 [배포 URL ](http://43.203.210.74:8080/) 

👉 [API 문서](https://github.com/Mingyum-Kim/spring-roomescape-payment/blob/step2/docs/api.md)

👉 [ERD 설계도](https://github.com/Mingyum-Kim/spring-roomescape-payment/blob/step2/docs/erd.md)

API문서의 경우 예약 페이지에 대해서 접근 가능한 모든 API를 수동으로 정리하였습니다.

# 생각해볼 점 

**결제 정보를 데이터베이스에 어떻게 저장할 것인가?** 에 대해 고민해보았습니다. 

저는 우선 예약 테이블에 paymentKey, amount 라는 결제에 대한  정보를 저장하였습니다. 이유는 아래와 같습니다. 
* 어짜피 예약과 결제는 일대일 매핑이기 때문에 테이블을 분리하는 게 테이블 정규화 관점에서 이득이 없다고 생각했습니다.
* Foreign Key 로 매핑해서 조회하는 것과 한 번의 조회에서 모두 가져오는 것 둘 중 성능을 비교한다면 한번에 조회하는 것이 더 성능이 좋을 것이라고 판단했습니다.

테이블로 분리하는 것이 좋다는 의견도 고려해보면 아래와 같은 이유였습니다.

* 예약 데이터를 삭제하면 결제 데이터도 삭제되는 것이 불안정할 수 있습니다. (하지만 결제 데이터를 현재 재사용하지 않고 있어서 충분한 이유로 받아들이지 않았습니다. )
* 도메인 상으로 분리되어있기 때문에 테이블 분리를 통해 관심사를 분리해야 합니다. 
* 저장할 결제 데이터가 paymentKey, amount 이상으로 많아지면 분리가 필수적이다.

저는 현재 요구사항에서는 테이블을 굳이 분리할 필요를 느끼지 못해서 예약 테이블에 paymentKey와 amount 데이터를 넣는 것으로 결정하였습니다. 미래에 요구사항이 심화될 것을 염두에 두지 않고 선택해보았는데 제가 생각한 장단점과 판단 근거에 대해 피드백을 주신다면 감사할 것 같습니다!

# 보완할 부분

이번 미션에서 보완할 부분이 많다고 생각하였지만, 우선 요구사항을 충족 후 부족한 상태에서 리뷰를 받아보는 것도 좋은 경험이 될 것이라고 생각하여 리뷰 요청 보냅니다.
피드백을 받으면서 개선할 수 있는 부분을 차츰 개선하도록 하겠습니다. 

* API 문서 자동화 
* 결제 대기 상태일 때 내 예약 페이지에서 결제하는 기능, 환불하는 기능, 결제 대기 상태일 때 관리자 취소 불가 등 추가로 떠오르는 구현 기능

그 이외에도 보완이 필요한 부분이 많을 것 같습니다. 보완이 더 필요한 부분이 있다면 피드백 주시면 감사하겠습니다. 

잘 부탁드립니다. 😃

2024-06-06 15:32 UTC, jamie9504 requested changes
안녕하세요, 안나 😄 리뷰어 제이미입니다.

이번에도 잘 구현해주셨네요 👏 👏 
코멘트 남겨두었습니다!

오늘도 좋은 하루 보내세요!

2024-06-06 15:32 UTC, jamie9504 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private Long amount;
paymentKey와 amount는 결제 관련된 정보이니 VO로 묶어주는 방식도 있겠네요 😃 
이 부분은 어떻게 생각하시나요?

paymentKey와 amount만 저장하는 이유는 무엇인가요?

2024-06-06 15:32 UTC, jamie9504 commented on src/main/java/roomescape/reservation/domain/Reservation.java
>      private void validateLastDate(LocalDate date) {
validate는 Date만 있어도 되나요?
해당 객체는 도메인으로의 역할을 충분히 수행할 수 있나요? 😃

2024-06-06 15:32 UTC, jamie9504 commented on src/test/java/roomescape/reservation/controller/AdminReservationControllerTest.java
> +        ReservationSaveRequest adminRequest = new ReservationSaveRequest(2L, TOMORROW, 1L, 1L, "paymentKey", 1000L);
테스트 전반적으로 `"paymentKey", 1000L`가 추가되었네요!
해당 컬럼은 NotNull 컬럼이 아닌데, 없는 경우의 테스트는 존재하지 않아도 괜찮을까요?

2024-06-12 17:45 UTC, Mingyum-Kim commented on src/main/java/roomescape/common/exception/ExceptionApiController.java
>      public ResponseEntity<String> exceptionHandler(RuntimeException exception) {
[반영 완료] 

결제 관련 핸들러와 일반적인 핸들러는 조금 다른 결과를 사용자에게 노출해주면 좋을 것 같아요.
결제 예외 발생 시 오류가 발생했음을 클라이언트에게 알려주기 위해 결제 오류 메시지를 수정하였습니다.

2024-06-12 18:01 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/controller/dto/request/ReservationSaveRequest.java
> +        long amount
[반영 완료] 

Nullable한 필드를 `long`으로 정의하고 있었군요. 😅 NOT NULL이 아니라서 따로 신경써주지 않았는데 long인 필드에는 자동으로 0이 들어간다는 것을 알게 되었습니다. 👍

2024-06-12 18:07 UTC, Mingyum-Kim commented on src/test/java/roomescape/reservation/controller/AdminReservationControllerTest.java
> +        ReservationSaveRequest adminRequest = new ReservationSaveRequest(2L, TOMORROW, 1L, 1L, "paymentKey", 1000L);
[반영 완료] 

아니요! 생각해보니 저 부분은 어드민 예약이므로 결제 정보가 없는 것이 정상일 것 같아요. 
더하여 예약의 경우에도 결제 정보를 제거해야하는데, 모두 추가하였기 때문에 예외 상황에 대한 테스트가 미비하였습니다. 
예약 결제가 NULL인 상황에 대한 테스트를 수행하였어요. 감사합니다 👍

2024-06-12 19:12 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private Long amount;
[답변] 

네 😀 만약 하나의 테이블에 paymentKey와 amount를 저장한다면 VO로 분리하여 @Embeddable을 통해 포함시켜주는 것이 좋을 것 같아요. 

[질문]

paymentKey와 amount만 저장한 이유는 단순히 요구사항에서 그 둘을 내 예약 페이지에서 조회하도록 주어졌기 때문입니다. 그래서 쓰이지 않는 다른 필드는 저장할 필요가 없다고 느꼈어요. 
성공 시 외부 API로부터 내려오는 여러 정보들 중 다른 정보를 저장할 필요가 있다고 생각하기 때문에 여쭤보신 걸까요? 궁금합니다!

2024-06-13 02:38 UTC, Mingyum-Kim commented on src/main/java/roomescape/reservation/domain/Reservation.java
>      private void validateLastDate(LocalDate date) {
[반영 완료] 

다른 필드들에 대해 null이 들어오는 상황을 도메인에서 검증해주어야 하겠네요. 👍 수정하였습니다.

2024-06-13 04:32 UTC, Mingyum-Kim commented on docs/erd.md
> +# ERD 설계도
[답변] 

> - 앞으로의 요구사항은 계속 일대일 매핑일까요?
> - 요구사항이 바뀔 때, 예약과 결제는 항상 동일하게 변경될까요?

연관관계 매핑에 대해 고민해본 결과 기존 방식에서 엔티티 설계를 수정할 필요성을 느꼈습니다. 결제 정보가 예약 정보와 유일하게 일대일로 연결됨을 보장할 수 없기 때문입니다. 예를 들어 예약이 아닌 굿즈를 구매하는 기능이 추가되었을 때 결제 테이블을 재사용하기 위해서는 결제 정보를 분리해야합니다. 
뿐만 아니라 예약이 삭제되어도 결제 정보를 유지하고자 요구사항이 추가된 경우 결제 정보를 예약으로부터 분리하는게 필수적이게 됩니다. 
이렇게 예약과 결제는 서로 다른 도메인이고 수정/삭제/조회 등에 대해 다른 요구사항이 주어질 수 있기 때문에 직접 연관되지 않도록 하는 것이 좋다고 느꼈어요. 

> - Foreign Key를 사용해 조회하는 것과 한 번의 조회에서 모두 가져오는 것 둘의 실제 성능은 얼마나 차이날까요? 😃 실행시간이라던가, DB에서 쓰이는 리소스라던가 등을 직접 비교를 해본 부분이 있을까요?
> - 직접 비교해보았다면 어느정도 차이가 났을까요? 이 차이는 유의미하다고 생각하시나요?

아니요 😅 성능은 직접 비교해보지 않았지만 내 예약 조회가 잦은 경우 유의미한 차이가 발생할 수 있다고 생각했던 것 같습니다. 요구 사항의 추가에 따른 유지보수 관점과 성능 등 여러 기준이 있을 때, 자주 요구사항이 변경되는 도메인인가 혹은 내 예약이 잦은 조회가 일어나는 가를 생각해보았습니다. 저는 방탈출 예약 도메인이 자주 요구사항이 변경되는 도메인이라고 판단하여 (혹은 가정하여) 매핑 테이블을 두어 예약 결제를 관리하도록 하였습니다.

어느 방법이든 다 장단점이 있지만 변경에 용이하다는 점에서 해당 방법이 이점이 있다고 판단하였어요.

2024-06-13 05:13 UTC, Mingyum-Kim commented on docs/erd.md
> +![erd.png](erd.png)
> 만약 사용자가 1시에 예약을 했는데, 추후 해당 방탈출 시간대를 1시 -> 3시로 변경하는 기능이 추가된다면 이미 예약한 건은 어떻게 될까요?

`ReservationTime`의 내용을 변경해버리면 참조하고 있던 예약들도 덩달아 의도와 다르게 시간이 모두 바뀌어 버릴 수 있겠어요.  흔치 않은 변경점이라는 생각은 들지만 시간을 변경하려고 시도하였다면 그 변경이 전파되기를 원하는 경계가 있을 것 같아요. 그 경계를 나누어서 시간을 저장하는 방식을 분리한 구조로 변경하는 게 좋다고 생각합니다. 

 > 테마마다 시간을 다르게 설정할 수 있게 된다면 어떻게 될까요?

이것도 마찬가지의 맥락으로 현재는 모든 테마가 같은 시간 자원을 참조하도록 설계되어있지만 테마마다 서로 다른 시간 리스트를 가질 수 있게 구조를 변경해야할 것 같아요. 
저도 이번 미션에서 엔티티 설계에 많은 고민을 하였지만 요구사항을 어디까지 미리 고민하고 코드로 적용할 지가 가장 어려웠던 것 같습니다. 하지만 변경에 용이한 설계를 위해서는 꼭 필요한 과정인 것 같아요. 
좋은 피드백 감사합니다! 🙇‍♀️

2024-06-13 08:02 UTC, Mingyum-Kim commented on docs/api.md
> +# 사용자 예약 페이지 API
[반영 완료] 

API 문서에서 실패에 대한 처리를 위해 실패 케이스의 API 요청과 응답을 주는 것도 중요하겠네요. 문서 상에서 실패 케이스도 추가하였습니다 👍

2024-06-13 09:43 UTC, Mingyum-Kim commented
안녕하세요 제이미 ~ 
피드백 반영 후 다시 리뷰 요청 드립니다 😆

API 문서를 RestDocs를 사용하여 자동화하였고, 매핑 테이블을 두어 엔티티를 설계해보았습니다. 
고민이 많아서 리뷰 요청 텀이 길었네요. 😥 부족한 점이나 새로 고민해볼 점에 대해 많이 제시해주시면 감사하겠습니다. 

ERD 설계와 API 문서 링크가 달라짐에 따라 URL을 다시 첨부 드립니다.

👉 [ERD 설계](https://github.com/Mingyum-Kim/spring-roomescape-payment/blob/step2/docs/erd.md)
👉 [API 문서 링크](http://43.203.210.74:8080/docs/index.html)
👉 [배포 링크](http://43.203.210.74:8080/)

2024-06-13 13:23 UTC, jamie9504 approved these changes
안녕하세요, 안나 😄 리뷰어 제이미입니다!

마지막 미션 잘 구현해주셨네요! 👏 👏 👏 
코멘트 아주 조금 남겨두었으니 시간 되실 때 확인해주세요~

요구사항은 충족하여 이만 Approve & Merge합니다!
신나는 방학 보내시고, 남은 기간도 재밌게 보내시길 바랍니다 💪

2024-06-13 13:23 UTC, jamie9504 commented on docs/erd.md
> +# ERD 설계도
안나가 생각하는 프로그램에서 결제와 예약의 변경 지점이 다르다면 분리를 하는 것이 좋고, 다르지 않다면 분리를 하지 않는 것이 좋을 수 있죠 😃
정답은 없지만, 본인의 프로그램에서 조금 더 적합한 것이 무엇일지는 항상 고민해보면 좋습니다.

성능상의 차이는 있지만, 100만 건에서 A와 B가 1초도 차이가 나지 않는 것과 10만 건에서 A와 B가 10초 이상 차이가 나는 것은 다른 선택을 가져오게 됩니다.
무언가 선택할 때 고민이 된다면 성능을 비교해보는 것도 좋은 방법이지요 😃 

앞으로도 안나만의 답을 찾아가길 바랄게요!

2024-06-13 13:23 UTC, jamie9504 commented on docs/erd.md
> +![erd.png](erd.png)
변경에 용이한 설계가 참 어렵습니다.
변경을 미리 예상한 설계는 오버엔지니어링과 같아지고, 변경을 고려하지 않은 설계는 유연성이 떨어지니까요.

어떤 프로그램을 개발하느냐, 그 프로그램이 추구하는 바와 가치는 무엇이냐, 고객이 얼마나 많고 도메인이 무엇이냐에 따라 변경에 용이한 설계가 달라질 수 있습니다.
그래도 이런 저런 고민을 할 수록 조금 더 적합한 설계를 찾아갈 수 있을 것이라 기대합니다.

2024-06-13 13:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/controller/dto/request/ReservationSaveRequest.java
> +        long amount
기본타입은 기본값이 무조건적으로 할당되기 때문에, 보통 DTO처럼 외부에서 주입받는 값은 포장타입으로 사용하는 편이에요 😃

2024-06-13 13:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private Long amount;
마찬가지로 필드를 보았을 때, 자주 쓰일 수 있을 것 같은 건 저장을 해도 되고 지금 단계에서 필요한 정보만 저장을 해도 되지요!
어떤 것을 저장할지에 대한 선택도 조금 더 시야를 넓혀서 고민할 수 있는 부분이기에 코멘트를 남겨두었어요.

2024-06-13 13:23 UTC, jamie9504 commented on build.gradle
> +    id "org.asciidoctor.jvm.convert" version "3.3.2"
RestDocs를 사용하면서 느꼈던 장/단점이 있을까요?
기존에 직접 문서를 관리했을 때와는 어떤 차이가 있을까요?
문서화를 하는 방법도 정답은 없지만 조금 더 취향이 있을 수는 있겠죠 😉

2024-06-13 13:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/domain/ReservationPayment.java
> +public class ReservationPayment {
매핑 테이블을 사용하는 것과 어느 하나에서 FK를 가지고 있는 것은 어떠한 장/단점이 있었을까요 😃

2024-06-13 13:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> -@Transactional(readOnly = true)
클래스단에서 제외하고 메서드단으로 옮겨간 이유가 있을까요?

2024-06-13 13:23 UTC, jamie9504 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +    private static void validateMember(Member member) {
Null Check는 항상 해주는 것이 좋을까요? 
Null Check만으로 validate가 엄청 많아지는데, 이 부분에 대해서도 고민해보면 좋겠네요!

2024-06-13 13:23 UTC, merged