[2 ~ 4 단계 방탈출 예약 결제 / 배포] 커비(이현지) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #88
Opened 2024-06-06 06:44 UTC by skylar1220

안녕하세요 웨지🍟 커비에요!

## 상황
스프링 부트, 외부 API 연동, 배포 모두 처음이라 재밌게 배우면서 미션을 진행했어요.

## 문서화
[API 문서](https://github.com/skylar1220/spring-roomescape-payment/blob/step2/docs/api.md)
[ERD](https://github.com/skylar1220/spring-roomescape-payment/blob/step2/docs/erd.png)
[배포 URL](http://13.124.90.87:8080/)

## 질문
### 1. 배포시 이미지 로딩 오류
로컬에서는 테마 썸네일로 넣은 이미지가 정상적으로 불러와지는데 
배포시 이미지가 불러와지지 않습니다. 배포 과정에서 보안 등의 문제 때문일까요?
아래와 같은 형식의 이미지 주소를 사용했습니다.
(https://postfiles.pstatic.net/MjAxOTA4MDJfMjQw/MDAxNTY0NzE0NTc5NzEz.HWRHs7Fs4z7RLwdMUzzwFE8OZ9NdycC9qAf2JruXJGQg.vhTopk-OUFx-WPPabFsqoolo8EqVBbg3Lq6xe14XIaQg.JPEG.qhfk1017/Pr_1532174669.jpg?type=w773)
<img width="608" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/110809927/b60d60d9-0a9a-4226-956f-be00df91ceeb">

## 참고
**[Admin 계정]**
- id : [admin@email.com](mailto:admin@email.com)
- pw : 123456

**[User 계정]**
- id : [test1@email.com](mailto:test1@email.com)
- pw : 123456

2024-06-08 00:11 UTC, sihyung92 requested changes
안녕하세요 커비! 리뷰어 웨지입니다
리뷰가 많이 늦었습니다 🥲 죄송합니다
리뷰 확인해주시고, 질문은 편하게 해주세요
감사합니다!

2024-06-08 00:11 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +        }
쿼리가 대량 발생할 수 있는 구조에요. for문 내부에서 쿼리를 날리는 상황이 생기면 신중하게 고려해주세요. (응답 지연과 DB 부하가 염려됨)

저라면 in절로 쿼리를 던질 수 있도록 변경하여 paymentService, waitingService에 쿼리를 한번 씩만 하도록 변경하고 어플리케이션 코드단에서 조합할거 같아요.

2024-06-08 00:11 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationCancelService.java
> +            if (waiting.isFirstOrder()) {
굳이 if가 없어도 되지 않을까요? 
`첫주문`, `첫주문 아님` 말고 다른 상태가 있나 생각하게 되는 것 같아요

2024-06-08 00:11 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
null을 허용하는 정책으로 가시나요?
현재는 reservation 1: 0..1 payment 인 구조로 보이는데 이러면 payment 쪽에서 reservation ID를 가지는 쪽이 낫지 않을까요?

2024-06-08 00:11 UTC, sihyung92 commented on src/main/resources/static/js/reservation-mine.js
> +    // TODO
미션과 상관없는 부분이지만 TODO 뒤에는 무엇을 할지 상황도 같이 적어주는 습관이 유용합니다

2024-06-08 00:11 UTC, sihyung92 commented on docs/api.md
> +# 사용자 예약 페이지 API
ERD 리뷰 ) 

ERD에 외래키가 명시적으로 표현되었으면 좋겠어요 
화살표로만 연관관계를 표현하니 헷갈리는거 같아요

2024-06-08 08:18 UTC, sihyung92 commented
1. 배포시 이미지 로딩 오류

질문에 대해서 생각 해두었다가 까먹었어요 ㅎ 외부업체 호스트 이미지를 사용하시고 있기 때문에 해당 업체의 파일제공 전략에 영향을 받게 됩니다.
예를들어 생산성 도구로 유명한 노션도 노션에 업로드된 이미지는 노션 호스트에서의 요청만 다운로드되고 다른 경로로는 다운로드를 401응답으로 주어요
이건 정말 호스트 맘이기 때문에 사용자 입장에선 갑자기 잘 내려오던게 안 내려와도 따지기 어렵습니다
그래서 대부분의 웹 서비스는 유저가 올린 이미지를 자기 서버에 저장하고, 새로운 URL을 만들어 조회할 수 있도록 바꾸어요. (당장 git 코멘트에 이미지를 올려보시면, 잠시 로딩 후 새로운 url로 내려오죠. 자기 서버에 업로드 시키고 그 주소를 내려주는 과정입니다)

로컬에선 되었고 배포환경에서 안 되는 원인은 정확히 짐작가는게 없긴 합니다. 결국 서버에선 바이너리 이미지 코드를 내린게 아니라 image URL을 응답했고, 그걸 호출하는건 프론트의 자바스크립트 코드, 즉 브라우저 이기 때문에 "로컬 환경의 크롬(혹은 커비가 쓰시는 브라우저) 프로그램이 외부업체 이미지를 다운로드 요청 보낸 것이 짤렸다"로 봐야겠죠. 서버의 보안정책 등 과는 무관할 것으로 보입니다.

2024-06-09 12:15 UTC, skylar1220 commented on src/main/java/roomescape/infrastructure/payment/PaymentProperty.java
> +public record PaymentProperty(String vendor,
[반영 완료]
1. application.properties를 yml 파일로 변경하였습니다.
2. 기존에 paymentConfig에 있던 타임아웃 설정 등을 application.yml으로 분리하였습니다. 
3. 여러개의 프로퍼티를 관리하기 용이하도록 @value 대신 @ConfigurationProperties를 적용해보았습니다.

이를 통해 토스 이외의 다른 결제 벤더사가 추가되어도 yml에 해당 벤더사의 프로퍼티만 간단하게 추가해줄 수 있습니다.

2024-06-09 12:26 UTC, skylar1220 commented on src/main/java/roomescape/infrastructure/payment/PaymentConfig.java
> +                TOSS, new PaymentProperty(TOSS, 5, 31)
[질문]
사실 설정하면서도 너무 길다는 생각이 들긴했는데, 토스 api 문서에서 아래와 같은 문구를 보아서 설정해주었습니다. 

> 토스페이먼츠 API의 [Read Timeout](https://docs.tosspayments.com/resources/glossary/timeout)은 30초에서 60초로 설정하면 돼요.

문서에서 명시한 내용은 개발자가 자체적으로 보수적으로 해석해도 되는 부분일까요? 
하지만 보수적으로 해석했을 때, 정상적인 처리가 타임아웃에 의해 계속해서 에러로 처리되는 것이 괜찮을까요?

2024-06-09 12:28 UTC, skylar1220 commented on src/main/java/roomescape/infrastructure/payment/TossPaymentClient.java
> +        }catch (HttpClientErrorException | HttpServerErrorException e) {
[반영 완료]
기본적인 컨벤션 체크 잘 챙기겠습니다😂

2024-06-09 12:28 UTC, skylar1220 commented on src/main/java/roomescape/infrastructure/payment/TossPaymentClient.java
> +        }  catch (Exception e) {
[반영 완료]
기본적인 컨벤션 체크 잘 챙기겠습니다😂

2024-06-09 12:29 UTC, skylar1220 commented on src/main/resources/static/js/reservation-mine.js
> +    // TODO
[반영 완료]
기본적인 컨벤션 체크 잘 챙기겠습니다😂

2024-06-09 12:55 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationCancelService.java
> +            if (waiting.isFirstOrder()) {
[답변]
해당 조건문은 대기 순서가 첫번째인지 아닌지에 따라 처리할 작업이 달라 적용해주었습니다!

대기 순서가 첫번째인 예약 대기에 대해서는 상태를 결제대기로 바꾸고,
첫번째가 아닌 예약 대기에 대해서는 대기 순서를 1 줄이기만 하는 처리를 합니다.

2024-06-09 13:10 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
[반영 완료]
두 구조의 장단점을 비교해보고 `reservation이 payment를 갖고있는 구조`로 변경하였습니다.

#### 1. 변경 전: reservation이 payment를 갖고있는 구조

> 장점

- 내 예약 조회시: 예약, 결제를 보여줘야하는 상황에서 쿼리가 한번만 날아가도됨
  - 하지만 view의 요구사항에 너무 종속적인 구조라는 점

> 단점

- 만약 결제를 하지 않는 단순 예약 사이트로 바꿔야한다면, 기존의 예약 테이블에서 payment를 싹 없애는 대이동이 필요함
- 결제를 예약이 갖고있다는 것이 과도한 책임이라는 느낌
- waiting, pending인 상태의 예약들은 payment를 null로 갖고있어 npe의 위험이 있다는 것.

#### 2. 변경 후: payment가 reservation을 갖고있는 구조
> 단점

- 예약이 삭제되었을 때 해당 결제 데이터가 갖고있던 예약의 외래키 참조가 깨짐

> 해결 방안

- soft-delete 방식

2024-06-09 13:11 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
[반영 완료]
위의 방식의 외래키 참조 문제를 해결하기 위해 soft-delete 방식을 적용해보았습니다. 
#### soft-delete 방식
> 장점

- 다른 테이블이 예약을 갖고있어도 외래키 참조가 깨지지 않음
- 예약 취소 내역을 확인할 수 있음

> 단점

- 정상 예약만 등을 조회할 때, delete된 데이터 역시 reservation 테이블에 남아있어 더 많은 양의 데이터를 전체 탐색해야함

2024-06-09 13:12 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
[질문]
soft-delete 방식을 적용했을 때의 단점으로 생각되는 '전체 탐색할 때의 데이터가 많다'는 점이 감수할 수 있는 정도의 리소스인지 궁금합니다.

2024-06-09 13:43 UTC, skylar1220 commented on src/main/java/roomescape/infrastructure/payment/TossPaymentClient.java
> +            logSaver.logInfo(paymentResponse);
[반영 완료]
말씀해주신대로 이해, 검색 측면에서 훨씬 효과적이네요.
반영하였습니다!

2024-06-09 13:52 UTC, skylar1220 commented
> 1. 배포시 이미지 로딩 오류
> 
> 질문에 대해서 생각 해두었다가 까먹었어요 ㅎ 외부업체 호스트 이미지를 사용하시고 있기 때문에 해당 업체의 파일제공 전략에 영향을 받게 됩니다. 예를들어 생산성 도구로 유명한 노션도 노션에 업로드된 이미지는 노션 호스트에서의 요청만 다운로드되고 다른 경로로는 다운로드를 401응답으로 주어요 이건 정말 호스트 맘이기 때문에 사용자 입장에선 갑자기 잘 내려오던게 안 내려와도 따지기 어렵습니다 그래서 대부분의 웹 서비스는 유저가 올린 이미지를 자기 서버에 저장하고, 새로운 URL을 만들어 조회할 수 있도록 바꾸어요. (당장 git 코멘트에 이미지를 올려보시면, 잠시 로딩 후 새로운 url로 내려오죠. 자기 서버에 업로드 시키고 그 주소를 내려주는 과정입니다) 다른 호스트가 제공하는 이미지를 사용한다는 리스크를 줄이기 위한 과정입니다.
> 
> 로컬에선 되었고 배포환경에서 안 되는 원인은 정확히 짐작가는게 없긴 합니다. 결국 서버에선 바이너리 이미지 코드를 내린게 아니라 image URL을 응답했고, 그걸 호출하는건 프론트의 자바스크립트 코드, 즉 브라우저 이기 때문에 "로컬 환경의 크롬(혹은 커비가 쓰시는 브라우저) 프로그램이 외부업체 이미지를 다운로드 요청 보낸 것이 짤렸다"로 봐야겠죠. 서버의 보안정책 등 과는 무관할 것으로 보입니다.
> 
> 미션하면서는 자체 S3 (AWS가 제공하는 스토리지) 같은거는 구현하기 어려우니까.. 꼼수로 github comment에 이미지 올려서 내려온 주소 따신담에요, 그거 쓰시는 방법도 있습니다 ㅋㅋ 마이크로소프트 스토리지 도둑질이지만 비교적 안정적(??)으로 이미지 다운로드가 제공됩니다

2024-06-10 00:51 UTC, skylar1220 commented
삭제 로직에서 WaitingCancelService(하위 서비스)의 cancel 메서드 중 어디에 트랜잭션을 붙이는 게 적절할까? 고민이 들었습니다.

### WaitingService(상위 서비스)에 붙여주는 게 맞다고 생각한 이유
1. 만약 WaitingService(상위 서비스)의 cancel 메서드에 WaitingCancelService이 아닌 다른 서비스를 이용하는 로직이 추가되는 상황을 고려했을 때. '삭제'라는 단위의 행위에 필요한 로직이 모두 포함되어있는 상위 서비스에 붙이는 것이 적절함.
2. 트랜잭션을 상위 서비스의 메서드에 붙여주는 것을 지양하는 다음과 같은 경우에 해당되지 않음.
   - 외부 api가 연동되어있어 다른 로직을 수행하는 트랜잭션과 함께 묶이지 않는 것이 나은 경우

하지만 이러다보니 어느 메서드는 호출되는 작은 단위의 하위 서비스에 트랜잭션이 걸려있고, 
어느 메서드는 상위 메서드에 트랜잭션이 걸려있습니다. 
이렇게 통일성이 떨어지면 이해에 어려움이 있을 수도 있다고 생각이 드는데요. 
현재 트랜잭션을 걸어주는 방식의 문제점이 더 있을지 궁금합니다!

2024-06-10 02:17 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +        }
[반영 완료]
for문을 돌때마다 쿼리가 나갈 수 있겠군요.
말씀해주신 방법대로 적용해보았습니다!

2024-06-10 02:24 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/waiting/WaitingService.java
>      }
삭제 로직에서 WaitingCancelService(하위 서비스)의 cancel 메서드 중 어디에 트랜잭션을 붙이는 게 적절할까? 고민이 들었습니다.

### WaitingService(상위 서비스)에 붙여주는 게 맞다고 생각한 이유
1. 만약 WaitingService(상위 서비스)의 cancel 메서드에 WaitingCancelService이 아닌 다른 서비스를 이용하는 로직이 추가되는 상황을 고려했을 때. '삭제'라는 단위의 행위에 필요한 로직이 모두 포함되어있는 상위 서비스에 붙이는 것이 적절함.
2. 트랜잭션을 상위 서비스의 메서드에 붙여주는 것을 지양하는 다음과 같은 경우에 해당되지 않음.
   - 외부 api가 연동되어있어 다른 로직을 수행하는 트랜잭션과 함께 묶이지 않는 것이 나은 경우

### 트랜잭션을 걸어주는 현재의 기준에 따른 문제점
1. 예약 생성 로직는 외부 api와 하나의 트랜잭션으로 관리하는 것을 피하고자, 작은 단위의 하위 서비스 메서드에 트랜잭션이 걸려있고, 
2. 위의 예약 대기 삭제 로직는 상위 메서드에 트랜잭션이 걸려있습니다. 
이렇게 통일성이 떨어지면 이해에 어려움이 있을 수도 있다고 생각이 듭니다. 

위와 같은 문제점을 감수하고 현재 트랜잭션을 걸어주는 방식을 유지하는 것이 괜찮은지,
혹은 현재 트랜잭션을 걸어주는 방식의 문제점이 더 있을지 궁금합니다!

2024-06-10 13:43 UTC, sihyung92 commented on src/main/java/roomescape/infrastructure/payment/PaymentConfig.java
> +                TOSS, new PaymentProperty(TOSS, 5, 31)
엄청 긴 트랜잭션이네요
사실 외부사에서 저렇게 60초 선언 해버리면 할 수 없죠.. 

이러면 개발을 떠나서 정치력 승부가 되는데요 
저희 회사 비즈니스가 상대한테 중요하면 좀더 줄여달라고 압박할 수 있고요 
반대면 그냥 넙죽 그러시군요... 하고 따라야죠
또 상대 사정상 정말 못 줄이는 경우도 있고요

read timeout 이란건 계속 늘린다고 능사는 아닌게 session idle time이 늘어나면 저희 서버와 토스 서버 사이에 있는 컴포넌트들 까지 설정값을 신경써주어야 합니다. 일례로 ALB (AWS에서 판매하는 load balancer 제품)은 idle_timeout.timeout_seconds
라는 타임아웃 설정이 default로 60s인데, (물론 toss 쪽에서 설정값 잡아줬겠지만) 이런 식으로 중간에서 거치는 서버들이 맘대로 잘라버릴 수 도 있습니다. 그럼 평소엔 보기 힘들던 503 같은 오류코드 등을 받게 되겠죠

유저 경험도 응답이 1s가 넘어가는 순간부터 급속도로 나빠지기도 하고요

이번 미션 범위는 아닙니다만 이런 경우 유저 경험과 서버 자원을 아끼기 위해 이런 긴 서버와의 요청/응답은 비동기 처리로 빼버리는 경우도 많습니다

즉 유저에겐 바로 200을 내려주고 ("완료되면 알려드림 ^^") 뒷단에서 처리하다가 완료돠면 확인할 수 있도록 처리하는거죠 (앱 경험상 몇 번 정도는 이런 처리를 보신 적 있을겁니다)
비동기 방식은 동기식 처리에 비해 손이 정말 많이 가기 때문에 정답은 아닙니다만.. 🥲

60s에 황망해서 이런 저런 소리를 해봤네요 
사실 open api는 최악의 시간대로 설정하는 경우가 많기 때문에 실제로 60s 가는 경우는 매우 드물거에요 
그래도 API에 명시해둔 처리를 해두는게 best이기 때문에 그냥 60s로 처리하시는 게 좋습니다 (30초면 30초고 60초면 60초지 30초~60초는 왜 적어둔건지 모르겠네요)

2024-06-10 13:50 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
동심파괴(?)를 해드리자면 현업 서비스에선 외래키 제약조건을 사용하지 않는 경우도 많습니다
외래키 제약조건은 DB 운영이 힘들기 때문인데요 (데이터 풀 마이그레이션 해야되는데 일일이 fk 제약조건 순서를 따라야 한다던지..) 

데이터 정합성은 DB를 거쳐야하는 소스코드 기반에서 방어하고요

2024-06-10 13:54 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
> soft-delete 방식을 적용했을 때의 단점으로 생각되는 '전체 탐색할 때의 데이터가 많다'는 점이 감수할 수 있는 정도의 리소스인지 궁금합니다.

데이터 성격에 따라 다르겠죠 
insert 트랜잭션과 delete 트랜잭션의 비율을 고민해보시면 좋을거 같습니다

방탈출 예약이란 걸 생각해보면 취소보다 생성이 빈번할거라고 예상은 드는데요 (실제로 런칭 후 추이를 봐야 함)
그럼 데이터량이 delete를 남기든 말든 별 차이 없을테니까요 (커봐야 1배 ~ 2배 사이) 
이러면 탐색비용의 증가가 무의미한 수준이겠죠

2024-06-10 14:00 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
그리고 좀 더 현업식으로 가이드를 해보자면 payment가 reservation을 잡은 순간의 스냅샷을 따로 떠놓을 필요가 있습니다
( 별도 테이블 혹은 payment 내에 칼럼으로 저장 ) (적용하진 마시고 생각만 해보셔요)

reservation은 가변값인데 비해 payment는 결제가 일어난 그 순간의 데이터가 중요하니까요,
말씀하신 상황처럼 결제를 했는데 예약을 날려버렸다던지.. 혹은 테마 명을 바꾸어버렸다던지.. 하면 좀 난감하죠

결제나 주문과 관련된 정보는 매우 민감해서 주문 당시 정보를 잘 보관해두어야 하는데, 그래서 그 당시 기준의 값을 따로 저장해놓는 방법도 있습니다. DB라는게 최종 결과만 보관되있지 중간에 어떤 히스토리가 흘러갔는지 없는게 아쉬운 점이니까요. (history 테이블이나 이벤트 소싱 같은게 이런 아쉬움을 달래는 방법론 들이죠)

미션에서 요구하는 수준에선 예약 id 정도만 살아있으면 된다고 가정해보면 soft delete해서 이후에도 결제 조회시에는 참조할 수 있게 해주는 것도 좋은 선택입니다

2024-06-10 14:19 UTC, sihyung92 requested changes
안녕하세요 커비! 리뷰어 웨지입니다.
리뷰 반영 잘 해주셨어요 👍 트랜잭셔널과 관련된 고민들을 하고 계신거 같아, 한번 더 request change를 보내겠습니다.
기존 코멘트 들에 대한 답변도 리뷰에 앞서 달아두었으니 확인해보셔요.
감사합니다!

2024-06-10 14:19 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/waiting/WaitingService.java
>      }
상위 서비스와 하위 서비스 모두에 붙여주세요.

Transactional 어노테이션에 대해 좀더 학습해보시면, isolation level을 따로 주지 않았을 경우 상위 트랜잭션이 하위 트랜잭션을 만났을 때 그냥 합쳐집니다 (WaitingService가 WaitinCancleService를 호출했을 때 WaitinCancleService의 트랜잭션을 자기 트랜잭션 안에 포함시켜 버립니다. 무시한다고 해야 좀 더 이해가 잘 될 수도요)

즉 WaitinCancleService에 Transactional이 붙어있든 말든 WaitingService가 호출하는 상황에선 같은 결과로 이어집니다.
그런데 하위 서비스에 붙여야 되는 이유는 WaitingCancelService에 method에 public 접근제어자를 주셨기 때문입니다 (접근제어자 바꾸라는 말은 아님)

그러면 WaitingCancelService는 WaitingService가 아닌 다른 클래스가 호출할 수 있다는 가능성을 염두에 두어야 합니다. 이때의 방어를 위해, 반드시 WaitingCancelService에도 트랜잭셔널 설정을 해주셔야합니다

2024-06-10 14:19 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +        }
Trasactional 안에 API 호출을 포함시키지 않으려는 태도는 좋지만, 현재 트랜잭셔널 설정으로 인해 손해보는 부분이 많습니다

1. paymentService.save에서 오류가 발생하면 기존 DB 데이터들이 롤백되지 않음
2. 트랜잭션을 이용할 수 없어 보상 트랜잭션을 수행하고 있음 ( reservationCancelService.deleteReservation(reservation.getId()); )

그런데 잘 보시면 API 호출이 먼저 되기만 하면 됩니다. 이런 경우라면 메서드 밖에서 payment 호출을 먼저 하고, DB insert는 트랜잭션으로 묶고 편하게 하면 될거 같아요.

2024-06-10 14:19 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +        }
두 번 째 문제로, Exception 전체를 catch 하고 있습니다. 이러면 토스 API에서 오류가 나도 유저는 정상 성공한 것 처럼 응답을 받게 됩니다.         
    
reservationCancelService.deleteReservation(reservation.getId()); 이후 다시 해당 예외를 throw 하시는 처리를 했었어야 될 것으로 보이네요. (예외 되던지기)

2024-06-11 07:27 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +        }
[반영 완료]
말씀하신대로 결제를 먼저하면 되는데 하지 않았던 이유를 생각해보았습니다.

사용자 경험 측면에서 결제 취소가 호출되는 상황이 자주 발생해서는 안된다고 생각하였습니다. 현재 구조상 결제 취소가 발생하는 경우는 결제 후, 예약 생성 시 예외가 발생할 경우입니다.

하지만 
현재 예약 생성을 위해 검증하는 중복 예약, 과거 날짜 예약은 프론트상에서 막혀있기때문에 그걸 뚫고 예외가 발생하는 상황은 적을 것,따라서 해당 리소스를 감수하고 결제를 먼저하는 구조의 장점을 취하는 것이 낫다고 생각이 드네요!

말씀하신 방향대로 수정해보았습니다😋

2024-06-11 07:37 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +        }
[반영 완료]
위에서 반영한 내용에 포함하여 반영하였습니다!

2024-06-11 10:23 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/waiting/WaitingService.java
>      }
[반영 완료]
1. 외부에서 호출하는 상황 고려 2. 어차피 하위 트랜잭션은 합쳐짐의 이유가 공감됩니다. 반영하였습니다!

2024-06-11 10:25 UTC, skylar1220 commented on src/main/java/roomescape/infrastructure/payment/PaymentConfig.java
> +                TOSS, new PaymentProperty(TOSS, 5, 31)
[반영 완료]
우선 API 명시대로 60초로 바꾸었습니다.
비동기 방식 등도 방안이 될 수 있겠네요. 트레이드 오프를 고려해 프로젝트를 할 때 적용해봐야겠습니다!

2024-06-11 10:28 UTC, skylar1220 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
[질문]
외래키 제약조건의 불편함을 이번에 많이 느껴서 공감이 됩니다.
다만, 해당 부분이 어떤 과정을 의미하는지 알 수 있을까요?
> 데이터 정합성은 DB를 거쳐야하는 소스코드 기반에서 방어하고요

2024-06-11 10:46 UTC, sihyung92 commented on src/main/java/roomescape/infrastructure/payment/PaymentConfig.java
> +                TOSS, new PaymentProperty(TOSS, 5, 31)
넵 사실 우테코 프로젝트 수준에서 비동기 처리가 필요할만큼 큰 처리량을 요구하는 작업은 잘 없을거에요.
간단한 방법을 두고 복잡한 개념을 도입하는 건 '최선'이 아니라 '차악'이라는 말씀을 드려봅니다 
(가능할 거 같다는 이유 하나로 굳이 어려운 방식을 도입했다가 1년 넘게 온갖 장애처리로 애를 겪는 개발자 입장에서..)

2024-06-11 10:49 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/module/ReservationRegisterService.java
> +        return request.toEntity(reservationTime, theme, member, Status.RESERVED, null);
FK를 사용하지 않는다는 건 중요한 정합성 방어수단 한 가지를 포기한다는 이야기니까요

예컨데 reservation 3번은 themeId 5번을 참조하는데, FK 제약조건이 없다면 themeId 5번이 theme 테이블에 실제론 없을 수 있습니다

이런 경우를 막기 위해선 theme을 삭제할 때 참조하고 있는 reservation이 없는지 소스 코드 단에서 validation을 수행해줘야 할 수 도 있는데 이런 과정을 말씀드려봤습니다

2024-06-11 11:40 UTC, sihyung92 approved these changes
안녕하세요 커비! 리뷰어 웨지입니다.
리뷰 반영 잘 해주셨어요. 계속 본인만의 고민과 결정을 쌓아 나가시는게 좋네요.
이번 미션은 이만 머지하겠습니다 🙏
레벨 2 수고많으셨어요! 남은 우테코 기간도 화이팅입니다

2024-06-11 11:40 UTC, sihyung92 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = PaymentCancelException.class)
PaymentCancelException는 PaymentException과 예외처리 과정이 같은데, 
PaymentCancelException에게 PaymentException를 상속시켜서 예외 핸들러에선 PaymentException 만 정의해도 되게 해두었어도 좋았을거 같습니다

2024-06-11 11:40 UTC, sihyung92 commented on src/main/java/roomescape/service/booking/reservation/ReservationService.java
> +            paymentService.cancelByToss(cancelRequest, paymentResponse);
꼼꼼한 처리네요 👍 오류 발생 후 보정한다고 난리법석 피지 않아도 되는 좋은 처리입니다

2024-06-11 11:40 UTC, merged