[2 ~ 4 단계 방탈출 예약 결제 / 배포] 호기(조호연) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #89
Opened 2024-06-06 07:46 UTC by hoyeonyy

안녕하세요 파랑👋 호기입니다!
배포와 문서화를 하는 게 조금 낯설기는 하네요..!

[사이트 주소](http://43.202.50.159:8080/)

[api 명세](http://43.202.50.159:8080/swagger-ui/index.html#/)
-> admin 계정 로그인 후 접근

![erdTable](https://github.com/woowacourse/spring-roomescape-payment/assets/114469256/8261466a-fef2-4c2d-b013-14f212205bab)

admin 계정
ID : hogi@email.com
PASSWORD : 1234

일반 계정
ID : kaki@email.com
PASSWORD : 1234

제가 고민했던 내용들을 공유해 드릴께요!

---

### Reservation 과 Payment 테이블의 분리
저는 예약과 결제 테이블을 분리했습니다! 물론 지금은 Reservation이 payment_key와 amount를 필드로 들고 있어도 문제가 없다고 생각합니다! 그 이유는 현재 결제를 할 것이 방탈출 예약 밖에 없기 때문입니다! 
하지만 만약 다른 결제할 것들이 생기면 예약과 결제는 분리해야 할 것 같았습니다. 뿐만 아니라 예약과 결제는 엄연히 다른 결의 도메인이라고 생각해서 테이블을 분리했습니다!
파랑의 생각은 어떠신지 궁금합니다!

### 그렇다면 Reservation 과 Payment 누가 연관 관계의 주인일까?
지금은 결제를 해야 대기를 걸 수 있게 만들어 놨습니다!
하지만 만약 대기를 할때에는 결제를 하지 않는 다는 요구사항이 생겼을 때 고민이 되었습니다.
만약 Reservation에 외래키가 있게 된다면 대기를 했지만 결제를 하지 않은 경우 payment_id 가 null로 박힐 수 있다고 생각했습니다. 
이러한 이유로 Payment가 Reservation_id를 갖게 했습니다!
이런 사고 과정이 올바른가? 궁금합니다!

---
현재 마지막 step4의 선택 사항인 로깅에 관련된 부분은 구현하지 않았습니다!
현재 부분에 대해 파랑에 리뷰를 받은 후 로깅 까지 처리해보고 싶습니다!

2024-06-06 14:45 UTC, summerlunaa requested changes
호기 안녕하세요~

이번에도 빠르고 깔끔하게 잘 구현해주셨네요 👍 API 명세와 ERD도 이해하기 쉽게 잘 첨부해주셨어요. 리뷰 남겼으니 확인 해주시고 더 궁금한 부분 있으면 코멘트나 DM으로 편하게 말씀해주세요!

2024-06-06 14:45 UTC, summerlunaa commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'    //Swagger
API 명세를 위해 swagger를 사용하셨군요! 👍  
Spring REST Docs나 노션 등에 작성해서 공유하는 방법도 있는데 스웨거를 써보니 어떠셨는지 궁금하네요~

참고로 요청/응답 DTO의 필드에 `@Schema(description = "예약 번호")` 애노테이션을 추가하면 해당 필드에 대한 설명이나 예시 등을 추가로 적어줄 수 있어요. GET API의 파라미터에서는 `@Parameter` 애노테이션으로 추가 가능하구요. 더 친절한 API 문서를 만들려면 스웨거에 어떤 애노테이션이 있는지 찾아보고 적용해보는 것도 좋을 것 같습니다 :)

2024-06-06 14:45 UTC, summerlunaa commented on src/main/java/roomescape/payment/domain/Payment.java
> +    private Reservation reservation;
> Reservation 과 Payment 테이블의 분리 & 그렇다면 Reservation 과 Payment 누가 연관 관계의 주인일까?

예약과 결제 테이블은 잘 분리하셨습니다 👍 설명하신 것처럼 둘은 분명히 별개의 데이터로 보여요. 이후에 예약이 아닌 다른 결제가 생길 수도 있구요, 오늘 에어비앤비를 결제했는데 총 금액의 50%는 지금 결제하고 나머지는 나중에 결제되는 기능도 있더라구요? 이런 기능을 보니까 경우에 따라 하나의 예약에도 두 번의 결제가 발생할 수도 있다는 생각도 들더라구욥 ㅎㅎ

Payment가 Reservation_id를 갖게 한 부분도 충분히 설득력 있다고 생각합니다. 저도 정책에 따라 결제 없이도 예약이 생길 수 있다고 생각합니다. 반대로 결제는 예약 없이는 존재할 수 없어 보이구요. 👍

2024-06-06 14:45 UTC, summerlunaa commented on src/main/java/roomescape/payment/domain/Payment.java
> +    private int amount;
보통 돈을 다루는 필드의 타입으로 int 보다 큰 최대값과 계산의 정확도를 가지는 BigDecimal도 많이 사용하더라구요. 이번 미션에서 사용할 필요는 없어보이지만 참고차 알려드립니다.

2024-06-10 09:08 UTC, hoyeonyy commented on src/main/java/roomescape/payment/repository/PaymentRepository.java
> +    Payment findByReservationId(Long reservationId);
파랑 말씀 처럼 뎁스가 깊어지는 경우에 lazyLoading을 신경 써야 할것 같아요,,
결국 전부 fetch join으로 해주어야 N+1문제가 안생길 것 같은데 매번 모든 구조를 고려해봐야할 것 같아요,,

> 해당 reservationId와 일치하는 데이터가 없으면 결과로 어떤 값이 나가나요?
null처리를 해주지 못한것 같아 Optional 로 감싸서 예외처리를 했습니다!

2024-06-10 09:18 UTC, hoyeonyy commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                        paymentService.findByReservation(reservation.getId())))
저도 이 부분 때문에 고민을 많이 했었는데요..!

이 부분을 고민하며 제가 생각했던 해결방법은 양방향 연관관계 이었습니다!
Reservation이 payment도 알고 있도록 양방향 설정을 해주고
처음 memberId를 입력받아 List<Reservation>을 가지고 올때 payment를 조인으로 같이 가져오는 거였는데요!

제가 알기로는 양방향을 피해야한다고 알고 있습니다!
그 이유는 순환참조에 대한 이야기때문으로 알고 있습니다.

이부분에 대해 파랑이 생각하는 양방향과 제가 생각한 해결방안 말고 다른게 있는지 궁금합니다!

2024-06-10 15:14 UTC, hoyeonyy commented on src/test/java/roomescape/config/DatabaseCleaner.java
> +        clearPayment();
파랑 덕분에 처음 보는 방법을 공부할 수 있었습니다 감사해요!

파랑 말씀대로 데이터베이스 이름을 반복문으로 돌아 테이블을 지우게 바꾸었습니다!

2024-06-11 14:56 UTC, summerlunaa approved these changes
호기 안녕하세요~

전체적으로 잘 구현해주셔서 크게 드릴 리뷰가 없네요 :) 결제 조회 쿼리가 예약 수만큼 나가는 부분만 한번 고민해보면 좋을 것 같습니다. 요구 사항은 모두 충족되어서 MR은 머지할게요. 더 궁금한 점 있으면 언제든지 DM 주세요.
드디어 레벨 2 마지막 미션도 끝이네요 🎊 방학동안 푹 쉬면서 충전하시고 남은 레벨도 잘 헤쳐나가시길 바랍니다~~ 넘 수고하셨습니다!! 👏

2024-06-11 14:56 UTC, summerlunaa commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                        paymentService.findByReservation(reservation.getId())))
굳이 관리하기 어렵게 양방향 맵핑을 설정할 필요가 있을까요? 
reservation + payment join을 통해 가져오거나 예약을 먼저 조회한 뒤, 예약 Id 리스트로 결제 정보를 한 번에 조회해와서 예약 데이터와 합치는 방법도 고려해보셨는지 궁금합니다~

2024-06-11 14:56 UTC, summerlunaa commented on src/test/java/roomescape/config/DatabaseCleaner.java
> +        clearPayment();
잘 적용해주셨군요! 이제 테이블이 추가될 때마다 매번 수정하지 않아도 되겠네요 👍

2024-06-11 14:56 UTC, summerlunaa commented on build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'    //Swagger
엇 크게 추가된 부분이 없네요! 실제로 다른 팀에게 제공할 때에는 설명도 작성해주는 게 좋습니다 :) 필드명만 보고서는 정확히 어떤 값을 의미하는지 모호할 때가 많거든요.

2024-06-11 14:57 UTC, merged