[2 - 4 단계 방탈출 예약 결제 / 배포] 감자(김주하) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #90
Opened 2024-06-06 10:38 UTC by khabh

2024-06-06 17:50 UTC, jamie9504 requested changes
안녕하세요, 감자 😄 리뷰어 제이미입니다.

이번 단계도 잘 구현해주셨네요! 👏 👏 
코멘트 남겨두었으니 확인 부탁드려요!

오늘도 화이팅입니다 💪

2024-06-06 17:50 UTC, jamie9504 commented on README.md
> +# ROOM ESCAPE
PR 코멘트의 배포 URL이 비어있어요 😃

2024-06-06 17:50 UTC, jamie9504 commented on build.gradle
> +    id "org.asciidoctor.jvm.convert" version "3.3.2"
> Spring REST Docs와 Swagger 사이에서 고민을 했습니다. Swagger 적용 시 프로덕션 코드에 수정 사항이 생긴다는 단점이 있어 Spring REST Docs를 적용했습니다.

Spring REST Docs의 장/단점과 Swagger의 장/단점은 어떤게 있었을까요?
실제로 적용해봤을 때 더 크게 느껴진 부분이 있을까요?

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/domain/Payment.java
> +        Long expectedAmount = reservation.getTheme().getPrice();
디미터의 법칙에 대해 다시 한 번 알아볼까요? 😃 
객체에게 메시지를 보내는 방법도 있을 것 같네요!

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/domain/ReservationPayment.java
> +public class ReservationPayment {
이 객체의 역할은 domain인가요 dto인가요 vo인가요?

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/domain/repository/ReservationRepository.java
> +    List<ReservationPayment> findReservationPaymentByMemberId(Long memberId);
JPA 양방향 매핑에 대해서도 알아보세요!

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/service/PaymentService.java
> +        Payment payment = new Payment(reservation, paymentDto.paymentKey(), paymentDto.orderId(), paymentDto.totalAmount());
결제 승인 후 (예 - 저장중) 오류가 나면 어떻게 되나요?

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/service/PaymentService.java
> +
❓

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/service/PaymentService.java
> +        }
ifPresent를 이용해볼까요!

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional
`@Transactional`을 붙인 곳과 붙이지 않은 곳은 어떤 차이가 있는 건가요?

해당 애너테이션의 readOnly 옵션도 알아봐도 좋을 것 같아요!

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +    private Reservation validateAndSave(ReservationSaveDto reservationSaveDto) {
안에서 validate를 한다는 것을 메서드에 명시해줄 필요가 있나요?

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/domain/Payment.java
> +    @OneToOne
`@OneToOne` 매핑이네요!
1:1 매핑을 하는 항목을 테이블을 나누게 되면 어떠한 이점이 있나요?

> 현재 애플리케이션에서는 예약 취소 시 대기가 자동으로 승인됩니다. 이에 따라 결제가 존재하지 않는 예약이 저장될 수 있습니다. 그래서 Reservavtion에 직접 결제에 대한 정보를 저장하지 않고 별도의 Payment 테이블로 분리했습니다.

Nullable한 컬럼이면 테이블을 분리하지 않아도 되지 않을까요?

2024-06-06 17:50 UTC, jamie9504 commented on src/main/java/roomescape/web/controller/api/PaymentController.java
> +        PaymentResponse paymentResponse = new PaymentResponse(paymentDto);
DTO 변환을 컨트롤러에서 하는 것과 서비스에서 하는 것은 각각 어떠한 차이가 있을까요?

2024-06-07 02:26 UTC, khabh commented on README.md
> +# ROOM ESCAPE
[배포한 페이지](http://43.201.48.215:8080/)를 URL에 추가해 주었습니다! 죄송합니다 😅

2024-06-08 09:28 UTC, khabh commented on build.gradle
> +    id "org.asciidoctor.jvm.convert" version "3.3.2"
Swagger는 이전에 다른 프레임워크에서 사용한 경험이 있었고, Spring REST Docs는 이번에 처음 적용해 봤는데 각각 다음과 같은 장단점이 있었습니다.

## Swgger
### 장점
- 어노테이션을 적용해 문서를 자동으로 생성해 문서화 과정이 간편합니다.
- 문서에서 제공되는 API를 직접 테스트할 수 있습니다.
- API 변경 사항이 있을 때 문서가 자동으로 업데이트됩니다.

### 단점
- 자동화되어서 복잡한 사용자 정의 문서화를 구현하는 것에 한계가 있습니다.
- 컨트롤러 코드에 Swagger 어노테이션을 추가해야 하므로, 프로덕션 코드가 변경됩니다. 

## Spring REST Docs
### 장점
- 테스트를 기반으로 문서를 생성하기 때문에 신뢰도가 높습니다.
- 문서 형식을 자유롭게 커스터마이징할 수 있습니다.
- 기존 프로덕션 코드에 변경 사항이 발생하지 않습니다.
###단점
- Swagger에 비해 초기 설정과 문서화 과정이 복잡합니다.
- API 변경 사항이 생겼을 때 수동으로 반영해야 합니다.
- 요청을 전송할 수 있는 UI를 제공하지 않아, API 테스트를 위해서는 별도의 도구가 필요합니다.

실제로 적용했을 때 requestField나 responseField를 작성함으로써 기존 컨트롤러 테스트가 올바른 API 스펙으로 데이터를 주고받고 있는지 한 번 더 확인할 수 있어서 좋았습니다! 그러나 gradle 설정이 어렵고 adoc을 작성하는 방법에 대한 학습 또한 필요해서 Swagger에 비해 진입장벽이 더 높다는 것을 느끼게 되었습니다 :)

2024-06-08 09:45 UTC, khabh commented on src/main/java/roomescape/domain/Payment.java
> +        Long expectedAmount = reservation.getTheme().getPrice();
결제 amount 검증하는 코드들에 모두 getter 대신 reservation의 isPriceEqual 메서드를 호출하도록 수정했습니다!

2024-06-08 10:00 UTC, khabh commented on src/main/java/roomescape/domain/ReservationPayment.java
> +public class ReservationPayment {
domain은 비즈니스 로직과 규칙을 포함하는 객체로, 데이터와 비즈니스 로직을 포함하며 상태 변경이 가능합니다. dto는 주로 계층 간 데이터 교환을 위한 읽기 전용 객체의 역할을 하고, vo는 특정 개념이나 의미를 가지는 값을 나타내는 불변 객체입니다.

위 개념들을 두고 비교했을 때, ReservationPayment는 비즈니스 로직보다는 데이터를 담고 전달하는 역할이 크기 때문에 현재는 domain이 아닌 dto로 분류하는 것이 더 적절하겠네요! 모든 Repository에서 domain을 반환하고 있어서 무의식적으로 ReservationPayment 또한 domain으로 취급했던 것 같습니다.

2024-06-08 11:25 UTC, khabh commented on src/main/java/roomescape/service/PaymentService.java
> +        Payment payment = new Payment(reservation, paymentDto.paymentKey(), paymentDto.orderId(), paymentDto.totalAmount());
데이터베이스에 Payment 정보가 저장되지 않았는데 결제가 승인되는 상황이 발생할 수 있습니다. 사용자가 불편함을 겪지 않도록 결제 승인 이후 실행되는 로직에 대해 try-catch를 적용하여 오류 발생 시 결제를 취소하도록 수정했습니다. 또한, 구현 난이도가 있을 수 있지만 Queue를 활용하여 승인되었으나 데이터베이스에 반영되지 않은 Payment들에 대한 저장 시도를 반복하는 방법도 하나의 해결책이 될 수 있을 것 같습니다 :)

2024-06-08 11:31 UTC, khabh commented on src/main/java/roomescape/service/ReservationService.java
> +    private Reservation validateAndSave(ReservationSaveDto reservationSaveDto) {
불필요하다는 걸 알면서도 자꾸 메서드 안에서 수행되는 모든 로직을 이름에 명시하게 되네요. 수정했습니다!

2024-06-08 11:56 UTC, khabh commented on src/main/java/roomescape/domain/Payment.java
> +    @OneToOne
1:1 매핑인 결제와 예약을 나누면 다음과 같은 이점이 있습니다:
- 데이터 정규화가 이루어져서 결제와 예약 데이터를 따로 조회하거나 변경하는 경우에 데이터베이스 성능이 향상됩니다.
- 결제에 컬럼이 추가되어도 예약 테이블에 영향을 주지 않으므로 유연성이 향상됩니다.
- 예약은 이미 관리하는 필드가 많기 때문에, 예약 테이블이 과도하게 커지는 것을 것을 방지할 수 있습니다.

Nullable한 컬럼으로 결제를 두어도 되지만, 저는 관리자의 예약 생성, 예약 취소로 인한 대기 자동 승인과 같은 기능 요구 사항에서 예약과 결제가 분리될 수 있는 개념이라는 점에 주목했습니다. 관심사가 다르다면 요구 사항이 추가됨에 따라 분리가 필요한 시점이 올 것이라는 생각이 들기도 했습니다. 토스 API 응답에서 어떤 값을 저장할지 고민해 보라는 미션 내용이 있었던 만큼, 변경 가능성이 높은 결제 정보를 별도의 엔티티로 분리하여 유지보수성을 높였습니다.

2024-06-08 12:14 UTC, khabh commented on src/main/java/roomescape/web/controller/api/PaymentController.java
> +        PaymentResponse paymentResponse = new PaymentResponse(paymentDto);
DTO 변환을 서비스에서 한다면 컨트롤러 코드가 조금 더 간결해지는 대신, 서비스에서 web 패키지에 의존하게 됩니다. 이렇게 되면 컨트롤러 계층의 DTO에 변경 사항이 생겼을 때 서비스에도 변경이 전파될 수 있습니다. 반면 컨트롤에서 DTO 변환을 수행하면 서비스는 비즈니스 로직에 더 집중할 수 있게 되고, 웹 계층과의 결합도를 최소화할 수 있습니다. 또한, 이미 컨트롤러가 서비스를 일방적으로 알고 있는 구조이기 때문에, DTO를 컨트롤러에서 직접 변환하도록 코드를 작성했습니다.

2024-06-08 12:39 UTC, khabh commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional
기본적으로 Repository의 메서드들은 하나의 트랜잭션 단위로 실행됩니다. `@Transactional`을 붙이지 않는 경우에는 서비스 메서드 내 Repository 메서드들이 독립된 트랜잭션 내에서 수행됩니다. 반면 서비스 메서드에 `@Transactional`을 붙이는 경우, 내부에서 호출되는 여러 repository 메서드들이 묶여서 하나의 트랜잭션 단위로 실행됩니다. 

기존 코드에서는 쓰기 작업이 두 번 이상 이뤄지는 메서드들에만 Transactional을 붙였습니다. 그러나 쓰기를 한 번만 하는 경우에도 검증을 위해 읽기 작업을 수행할 때가 있어 데이터 일관성을 위해 해당 메서드들에 @Transactional을 붙여 주었습니다.

제이미가 주신 readOnly 키워드로 공부를 해 보니, 해당 옵션을 적용하면 명시적으로 읽기 작업만 수행한다는 것을 알릴 수 있고, Dirty checking을 사용하지 않게 된다는 장점이 있다는 것을 알게 되어 서비스 코드에 반영했습니다!

2024-06-10 05:42 UTC, jamie9504 requested changes
안녕하세요, 감자 😄 리뷰어 제이미입니다!

벌써 이번 미션의 끝이 보이네요!
코멘트를 조금 더 달아두었습니다.

미션 요구사항은 충족한 것 간아서, 다음 리뷰 요청때는 Approve & Merge 예정입니다.
마지막까지 화이팅입니다 💪

2024-06-10 05:42 UTC, jamie9504 commented on src/main/java/roomescape/domain/Payment.java
> +package roomescape.domain;
domain 패키지에 클래스가 많아진 것 같죠? 😃

2024-06-10 05:42 UTC, jamie9504 commented on src/main/java/roomescape/domain/Theme.java
> +    private Long price;
`@Column(nullable = false)` 을 명시하는 것은 어떠한 효과가 있을까요?
`@NotNull`을 사용할 수 있을까요? 있다면 어떠한 효과가 있을까요?

2024-06-10 05:42 UTC, jamie9504 commented on src/main/java/roomescape/domain/Theme.java
> +        this.price = price;
역할을 가진 친구들은 VO로 분리해도 괜찮을 것 같기도 하구요.

2024-06-10 05:42 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +        return new ReservationDto(reservation.withPayment(payment));
매핑을 해주었으므로 Reservation만으로도 Dto를 생성할 수 있지 않을까요?

2024-06-10 05:42 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationService.java
> +    @Transactional(readOnly = true)
`@Transactional(readOnly = true)`를 클래스에 다는 것은 어떠한 효과가 있을지 알아보세요!

2024-06-10 05:42 UTC, jamie9504 commented on src/main/java/roomescape/service/ReservationWaitingService.java
> +        return reservationWaitingRepository.existsByDateAndTimeIdAndThemeId(date, timeId, themeId);
이렇게 추출할 것이면

`boolean existsByDateAndTimeAndTheme(ReservationDate date, ReservationTime time, Theme theme);`

를 사용하는 것과 어떤 차이가 있나요?

2024-06-10 07:41 UTC, khabh commented on src/main/java/roomescape/service/ReservationWaitingService.java
> +        return reservationWaitingRepository.existsByDateAndTimeIdAndThemeId(date, timeId, themeId);
실행해 보니 existsBy로 조회를 할 때 기존에 Id로 조건을 설정한 경우에는 다음과 같이 불필요한 join이 수행됩니다.
```SQL
    select
        rw1_0.id 
    from
        reservation_waiting rw1_0 
    left join
        reservation_time t1_0 
            on t1_0.id=rw1_0.time_id 
    left join
        theme t2_0 
            on t2_0.id=rw1_0.theme_id 
    where
        rw1_0.date=? 
        and t1_0.id=? 
        and t2_0.id=? 
    fetch
        first ? rows only
```
반면 필드인 Time, Theme을 넘기면 reservation_waiting의 time_id, theme_id 컬럼으로 조회를 하네요!
```SQL
    select
        rw1_0.id 
    from
        reservation_waiting rw1_0 
    where
        rw1_0.date=? 
        and rw1_0.time_id=? 
        and rw1_0.theme_id=? 
    fetch
        first ? rows only
```
코드 효율을 위해 후자로 변경했습니다 :)

2024-06-10 08:05 UTC, khabh commented on src/main/java/roomescape/domain/Payment.java
> +            throw new IllegalArgumentException("테마 가격과 결제 금액이 일치하지 않습니다.");
생각해 보니 해당 검증은 결제 승인 요청을 보내기 전에 하는 것이 맞다고 판단되어, 테마 가격과 결제 금액의 일치 여부는 Service에서 확인하고 Payment는 amount를 받지 않도록 수정했습니다!

2024-06-10 08:11 UTC, khabh commented on src/main/java/roomescape/service/PaymentService.java
> +    private Payment approveAndSavePayment(PaymentApproveDto paymentApproveDto, Reservation reservation) {
각 메서드가 하나의 일만 수행하도록 approve와 save를 분리했습니다.

2024-06-10 08:55 UTC, khabh commented on src/main/java/roomescape/domain/Theme.java
> +        this.price = price;
null이나 빈 문자열 확인이 아닌 별도의 검증이 필요한 price와 thumbnail을 VO로 포장해 주었습니다.

2024-06-10 09:06 UTC, khabh commented on src/main/java/roomescape/domain/Theme.java
> +    private Long price;
`@Column(nullable = false)`을 명시하면 데이터베이스 schema에서 컬럼에 NOT NULL 옵션이 추가되어 테이블에 비어 있는 값을 INSERT 할 수 없게 됩니다.
`@NotNull`을 적용할 경우에는 애플리케이션 레벨에서 해당 필드에 null 값이 들어가지 않는 것을 보장합니다. 

직접 작성한 validation 코드를 삭제하고 어노테이션으로 검증을 했을 때, 실행 시에는 애플리케이션 레벨에서 올바르게 예외 처리가 됐는데, 서비스의 Mock 테스트에서 케이스가 계속 통과되지 않았습니다. 그래서 확인해 보니 Theme 엔티티의 생성 시점이 아닌 ThemeRepository의 save() 메서드 호출 중에 내부적으로 검증이 이루어지고 있었습니다. 그래서 Repository가 모의 객체로 주입되어서 통과되지 않는 테스트들은 삭제하고 `@NotNull`을 적용하였습니다.

2024-06-11 04:07 UTC, khabh commented on src/main/java/roomescape/domain/repository/ReservationRepository.java
> +    List<ReservationPayment> findReservationPaymentByMemberId(Long memberId);
제이미가 말씀해 주신 대로 `@OneToOne`의 옵션들에 대해 알아봤습니다!
- cascade: Cascade.REMOVE를 적용하면 Payment가 삭제될 때 Payment가 가진 Reservation도 함께 삭제됩니다.
- orphanRemoval: Payment의 Reservation 필드를 null로 설정하고 merge하면 해당 Reservation이 삭제됩니다.

Payment만 삭제하는 실수를 했을 때 데이터 불일치가 발생하는 문제를 예방할 수 있겠네요. 현재 애플리케이션 설계에서는 Payment의 Reservation이 not null로 설정되어 있어서 Cascade.REMOVE만 적용했습니다!

2024-06-11 05:56 UTC, khabh commented on src/main/java/roomescape/web/controller/api/PaymentController.java
> +        PaymentResponse paymentResponse = new PaymentResponse(paymentDto);
만약 DTO를 web 패키지가 아닌 서비스 계층과 같은 패키지에 둔다면, web 패키지에 대한 직접적인 의존성은 사라집니다. 하지만 프레젠테이션 계층의 변경 사항이 서비스 계층으로 전파되어, 서비스 계층이 웹 계층에서 데이터를 어떻게 조회하는지 더 많이 의식하게 된다는 문제가 발생할 것 같습니다.

2024-06-12 05:22 UTC, jamie9504 approved these changes
안녕하세요, 감자 😄 리뷰어 제이미입니다.

2레벨 마지막 미션 고생 많으셨습니다 👏  👏  👏 
간단한 코멘트만 남겨두었으니 시간되실 때 가볍게 읽어보세요.

방학 푹 쉬시고, 남은 우테코 생활도 즐겁게 보내시길 바라겠습니다.
오늘도 좋은 하루 보내세요.

2024-06-12 05:22 UTC, jamie9504 commented on src/main/java/roomescape/domain/Reservation.java
> +    public void setPayment(Payment payment) {
setPayment메서드를 payment가 호출하지 않고, service에서 호출하게 되면 payment 안에도 해당 reservation을 넣어줘야할까요~?

2024-06-12 05:22 UTC, jamie9504 commented on src/main/java/roomescape/domain/Payment.java
>      private Reservation reservation;
예약이 삭제되면 결제도 같이 삭제되는 것이 맞을까요?
이렇게 되는 경우 remove reservation을 했을 때, 결제는 삭제될텐데 결제 취소는 되지 않아도 되는건가요?

2024-06-12 05:24 UTC, merged