[2 - 4 단계 방탈출 예약 결제 / 배포] 카키(서현준) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #94
Opened 2024-06-07 05:55 UTC by hyeon0208

안녕하세요 영이 오랜만에 인사드립니다! 😄
설계한 ERD와 배포 URL 첨부하면서
1단계 피드백으로 변경한 부분과 2단계를 진행하면서 추가한 부분 정리해 리뷰 요청 드립니다!
이번에도 잘 부탁드립니다 !  🙇🏼‍♂️

---
### 📌 ERD 이미지
<img width="1049" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/99153215/0776bb3b-bc0f-45dc-a272-ea5cc709e7e9">

reservation, member, theme, reservation_time 테이블의 연관관계는 이전부터 설정한 연관관계로 두었고
payment의 경우에는 테이블을 추가하지 않아도 지금 미션 요구사항을 구현할 수 있었지만
resrevation과 전혀 다른 성격을 가지고 있어 2정규화를 적용한 payment 테이블을 추가하게 되었어요.

하나의 예약에는 한 번의 결제만 가능하고, 하나의 결제는 하나의 예약을 들고 있다는 특징이 있어 1 : 1 연관관계를 적용했고
외래키가 reservation에 있을 경우 예약 대기를 추가하더라도 결제가 되어야 했기 때문에
payment 테이블에 reservation_id를 외래키로 두도록 구현했습니다.

---

### 📌 배포 URL
[방탈출 서비스 배포 URL](http://43.203.122.227:8080/)
[Swagger API 문서 URL](http://43.203.122.227:8080/swagger-ui/index.html)

---

### 📌 회원 데이터

||일반 회원|어드민|
|---|---|---|
|아이디|kaki@email.com|admin@email.com|
|비밀번호|1234|1234|

---

### 📌 1단계 피드백 반영사항

> 예약 서비스 로직 분기 처리해 하나의 메서드로 합치기

최대한 메서드 라인이  길어지지 않게 하면서 indent 1까지만 허용하도록 적용해보았는데
적절히 하나의 메서드로 합쳐진 진 모르겠네요 
이부분에 대해 영이는 어떻게 느껴지시는지 궁금합니다!

<br>

> 테스트 시에 실제 결제가 일어나지 않도록 결제 로직을 Mocking해 예약 성공 테스트 추가

실제 결제가 일어날 수는 상황을 방지하기 위해서라도 예약 성공에 대한 테스트가 필요하겠네요!
이 부분에 대해서는 paymentService를 실제 결제가 일어나지 않도록 Mocking해
예약 성공 테스트를 추가하였습니다!

---

### 📌 2단계 피드백 반영사항

> 서비스 로직에서 예약 대기 안되던 오류 수정
예약 대기 로직에 오류가 있어서 예약 대기 추가가 일정 조건에서 안되고 있었어요 😅
해당 부분 오류 수정하였습니다!

<br>

> 회원 예약 서비스와 어드민 예약 서비스 분리

관리자 페이지에서 관리자가 예약을 해줄 시에는 결제가 필요없다고 판단하여 일반 회원과 저장 방식이 달라 서비스를 분리해보았습니다.
이렇게 까지 분리하다보니 ADMIN과 USER의 컨트롤러와 서비스가 분리되어 
두 권한 사용자의 예약 요청 데이터가 달라 복잡했던 예약 저장 DTO `ReservationSaveRequest`를
`AdminReservationSaveRequest`와 `UserReservationSaveRequest`로 분리해보았습니다!

<br>

> 예약 취소 시 결제 취소 적용

확정된 예약이 취소 될 경우 해당 예약의 첫 번째 대기자가 예약 상태로 변경 될 시 예약의 상태가 결제 대기로 변경되도록 수정했습니다.
결제 대기로 바뀐 상태의 예약은 1시간 내에 결제 되지 않으면 예약 취소 되도록 기능 구현을 하고 싶었는데
이 부분을 구현하기 위해서는 Spring Batch를 사용해 구현할 수 있더라구요
하지만 Batch도 범위가 큰 기술이라 생각해 지금 적용하기에는 PR 요청하기까지 많이 느려질 수 있을것 같아
영익가 요구해주시거나 그렇지 않다면 버퍼 기간때 연습해보려 적용하지 않았습니다 🙃

---

### ❓ 질문

로깅에 대한 요구사항이 들어왔는데 현재는 에러에 대해서만 로그를 남기고 있어요.
에러 뿐 아니라 API 요청 응답에 대해서도 로그가 필요할 것 같은데

예약 저장의 경우에는
```
1. API 요청 받았을 때 log.info()로 요청받은 데이터 로그 남기기
2. 서비스 로직 처리 결과 로그 남기기
3. API 응답 정보 로그 남기기
```

이렇게 세세하게 로그를 남겨 디테일하게 분석할 수 있게 하는 편인지
아니면 로그를 간소화해서 로그를 분석하기 쉽게 최소한의 로그만을 남기는 편인지
보통은 어느 정도로 로그를 남기는 지 궁금해요 
컨벤션 처럼 정해진게 있을 까요 ? 
회사마다 다를 것 같아 영이의 생각이 궁금합니다!

2024-06-07 14:28 UTC, choijy1705 requested changes
안녕하세요 카키!
미션 잘 진행해주셨어요!
몇가지 코멘트 남겼으니 확인부탁드려요🙏

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/payment/dto/PaymentRequest.java
> +    public static PaymentRequest from(UserReservationSaveRequest userReservationSaveRequest) {
Request 를 다른 Request로 바꾸는 것은 조금 어색한것 같아요

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/payment/dto/TossPaymentResponse.java
> +public record TossPaymentResponse(String paymentKey, String orderId, String method, int totalAmount) {
amount 와 currency는 항상 세트로 다녀야할것 같아요!
toss에서 결제 response로 아마 currency가 내려올거에요

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                });
조회했을때 반드시 있어야 하는 경우에 대한 로직은 repository단에서 별도의 메서드를 만들어서 관리하면 
service 코드가 좀 더 보기 좋을것 같습니다!

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/AdminReservationService.java
> +public class AdminReservationService {
해당 클래스가 필요할까요?🤔
ReservationService에서 처리하지 못하나요?
중복으로 코드를 관리할때의 문제점에 대해 고민해보면 좋을것 같습니다!
중복 코드와 if문 분기중 어떤게 적절할까요

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/payment/service/TossPaymentClient.java
> +    public ResponseEntity<Void> requestPaymentCancel(String paymentKey, ReservationCancelReason cancelReason) {
결제 취소했을때 toss에서 response를 내려주지 않나요?

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/reservation/dto/ReservationWithPaymentResponse.java
> +                                          ReservationStatus status, String paymentKey, int totalAmount) {
```suggestion
    public ReservationWithPaymentResponse(
        Long id, 
        Theme theme, 
        LocalDate date, 
        ReservationTime time,
        ReservationStatus status, 
        String paymentKey, 
        int totalAmount
    ) {
```
지금 방식은 파라미터가 어떤게 있는지 파악하기 어려운것 같아요!
새로운 방식을 제안드립니다!

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        }
```suggestion
        validateReservation(loginMember, reservation);
        Reservation savedReservation = reservationRepository.save(reservation);
        if (status.isSuccess()) {
            paymentService.payForReservation(PaymentRequest.from(userReservationSaveRequest), savedReservation);
        }
```

이흐름으로 가고 validateReservaion 메서드 안에서 분기를 나눠 validate하는게 가독성 좋아보이네요

2024-06-07 14:28 UTC, choijy1705 commented on src/main/java/roomescape/exception/ApiControllerAdvice.java
> +                        "서버 에러입니다. 고객 센터에 문의 해주세요."));
요청이 올때마다 로그를 남기는건 비효율적일것 같네요
api요청이 얼마나 들어오는지에 대한 정보는 로깅이 아니더라도 충분히 알 수 있을것 같습니다(저희 회사의 경우 datadog을 사용해서 요청이 얼마 정도 오는지를 파악할 수 있습니다)
에러가 발생했을때만 로그를 잘 남기면 충분할 것 같습니다.

2024-06-08 08:18 UTC, hyeon0208 commented on src/main/java/roomescape/payment/domain/PaymentStatus.java
> +    DONE,
토스에서는 결제 완료된 상태를 DONE으로 표현하고 있어서 위와 같이 적용했었는데
토스의 DONE은 결제 승인의 상태를 나타내기 때문에
애플리케이션에서 DONE으로 결제가 성공되고 난 후의 결제의 상태가 DONE인건 약간 모호한 느낌이 있어보이네요 😅
해당부분 좀 더 직관적으로 표현되도록 `PAID`로 변경하고 결제 취소 상태 또한 `CANCELED`로 변경해보았습니다!

2024-06-08 08:31 UTC, hyeon0208 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    }
`Payment`가 생성되기 전에 해당 필드들이 입력에 대한 검증이 DTO에서 되고 있어
`Payment` 도메인 내부에 검증로직을 추가하지 않아도 된다고 생각했는데 
좀 더 안정성을 보장하기 위해 더블 체크가 필요하다는 뜻일까요 ??
제가 의도를 잘 이해하지 못해 다시 질문 드립니다🥲 🙇🏼‍♂️

2024-06-08 08:37 UTC, hyeon0208 commented on src/main/java/roomescape/auth/dto/LoginMember.java
> +        Role role,
아무래도 놓친것 같습니다 .. !
"회원 권한"이라는 설명을 추가했습니다 !

2024-06-08 08:46 UTC, hyeon0208 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    private int totalAmount;
`long` 타입 또는 `BigDecimical` 타입을 고려 했었는데
`long`의 경우에는 방탈출 예약할 때 정수범위 21억을 넘어갈 일이 없다고 생각했고
`BigDecimical`의 경우에는 결제 시에 소수점 까지 결제 될 일이 없다고 생각해 
좀 더 가볍고 성능상으로 이점이 있는 int 타입을 사용하게 되었어요

아직 다른 타입을 써야하는 이유를 느끼지 못해서 그런데 
제가 놓치는 부분이 있을 것 같아 이 부분에 대해서 영이의 생각이 궁금합니다 ! 🙇🏼‍♂️

2024-06-08 09:08 UTC, hyeon0208 commented on src/main/java/roomescape/payment/dto/PaymentRequest.java
> +    public static PaymentRequest from(UserReservationSaveRequest userReservationSaveRequest) {
예약 POST 요청을 할 때 클라이언트에서 예약 정보와 결제 정보도 함께 넘기고
애플리케이션에서는 이 정보에서 Toss에 결제 요청할 데이터만 추출해서 보내야 하므로
`UserReservationSaveRequest`내부에 `PamentRequest`로 변환하는 메서드명을 `extractPaymentRequest()`
로 네이밍 해보았어요

네이밍으로 어색함을 줄이려 했지만 이 것도 `Request -> Request`로 변환이라 조금 어색할 수 있을 것 같긴 합니다
Toss에 결제 요청을 할 데이터들을 `payForReservation()` 파라미터로 하나씩 넘겨
`Request -> Request`변환을 없애는 것도 어색한 느낌이 들었는데
영이는 어떻게 생각하시는 지 궁금합니다 !

2024-06-08 09:10 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/dto/ReservationWithPaymentResponse.java
> +                                          ReservationStatus status, String paymentKey, int totalAmount) {
이 부분 컨벤션 확인을 하지 못했네요 !
제안 해주신 방법으로 수정했습니다!

2024-06-08 09:40 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        }
레벨 1에서 학습했던 객체 지향 생활 체조의 "한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다."를
지키기 위해 예약 확정과 대기 검증 로직을 분기 처리하지 않도 위와 같이 검증하도록 했는데
너무 위 규칙에 매몰되었나 봅니다 😅
주어진 요구사항도 아니였기도 하고, 제시해주신 방법대로 검증로직을 분기 처리하는 것이 더 가독성이 좋은 것 같네요 👍🏻

2024-06-08 09:43 UTC, hyeon0208 commented on src/main/java/roomescape/exception/ApiControllerAdvice.java
> +                        "서버 에러입니다. 고객 센터에 문의 해주세요."));
말씀데로 모든 요청마다 로그를 남기게 되면 서버에 부하가 갈 수도 있어 비효율 적이겠네요 😀
적절한 로깅이 무엇인지 영이 덕분에 알 수 있게 되었어요 감사합니다 😊

2024-06-08 11:06 UTC, hyeon0208 commented on src/main/java/roomescape/payment/service/TossPaymentClient.java
> +    public ResponseEntity<Void> requestPaymentCancel(String paymentKey, ReservationCancelReason cancelReason) {
어떤 결제가 취소되었는지 클라이언트 측에도 전달해주는 것이 좋을 것 같네요 !
`TossPaymentCancelResponse` DTO를 추가해 취소된 결제에 대한 정보를 응답하도록 수정했습니다!

2024-06-08 11:07 UTC, hyeon0208 commented on src/main/java/roomescape/payment/dto/TossPaymentResponse.java
> +public record TossPaymentResponse(String paymentKey, String orderId, String method, int totalAmount) {
환화 뿐 아니라 달러도 결제가 가능할 수 있겠네요 👍🏻
currency도 응답으로 받아오면서 payment 테이블에도 currency 컬럼을 추가했습니다!

2024-06-08 11:09 UTC, hyeon0208 commented on src/main/java/roomescape/payment/dto/TossPaymentResponse.java
> +public record TossPaymentResponse(String paymentKey, String orderId, String method, int totalAmount) {
아래는 수정된 ERD 입니다!
<img width="1384" alt="image" src="https://github.com/woowacourse/spring-roomescape-payment/assets/99153215/55b10a81-c87e-429b-9f97-8a8ee07feb47">

2024-06-08 11:39 UTC, hyeon0208 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                });
말씀대로 existsByPaymentKey()로 boolean을 반환하게 되면 코드의 가독성이 좀 더 좋아지긴 했어요 👍🏻

하지만 Optional<>로 반환하게 되면 재사용 측면에서 좋지 않을까 해 위 처럼 코드를 구성했어요
지금도 결제를 저장하고 나면 paymentId가 없고 paymentKey를 가진 응답 DTO를 반환하는데 
PaymentService에서 아래와 같이 재사용하고 있습니다!
```
Payment canceledPayment = paymentRepository.findByPaymentKey(PAYMENT_KEY).get();
```
이 재사용 측면을 고려한다면 지금 코드에 대해 어떻게 생각하실까요 !?

2024-06-08 13:31 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/service/AdminReservationService.java
> +public class AdminReservationService {
ReservationService에서 예약을 하는 경우에는
권한 상관 없이 "방탈출 회원 예약 페이지"에서 예약을 해
로그인한 회원의 id로 예약을 저장하고 있어요

하지만 "방탈출 관리자 예약 페이지"에서는 
관리자 권한을 가진 회원이
관리자 본인의 예약이 아닌 `AdminReservationSaveRequest`로 요청 받은 회원 id로 
회원의 예약을 관리자가 해주고 있어요

그렇기 때문에 관리자 권한을 가진 사람이 "방탈출 회원 예약 페이지", "방탈출 관리자 예약 페이지"에서 예약을 할 때
예약되는 흐름이 달라 이 부분을 합치기에는 무리가 있었어요..
피드백을 보고 한번 합치기 위해 도전을 해봤는데 위에 말한 상황 때문에
로직이 중복 처럼 보이긴 하지만 회원과 어드민이 하나의 프로젝트(모듈) 안에  있고 배포도 한 번에 되어 있어
지금 상황에서는 불가피한 중복이라 생각이 들어요

중복을 피할 수 있다면 영이의 의견대로 if문으로 분기 처리할 수 있는 것이 적합한 것 같습니다
지금은 위 처럼 "방탈출 관리자 예약 페이지"에서의 예약 저장 로직을 `AdminReservationService`로 분리하는 것이
최선의 방법이라 생각이 드는데 영이는 어떻게 생각하시나요?

+ `AdminReservationService` 에서 `save()`시에 요청받은 memberId로 예약을 저장해주는 것이 아닌
로그인한 본인의 id로 예약을 저장하고 있는 오류가 있어 수정했습니다 !

2024-06-09 11:30 UTC, choijy1705 requested changes
카키 피드백 잘 반영해주셨습니다
간단한 몇가지 추가 코멘트 남겼습니다
확인 부탁드려요!

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                });
제가 의도한것은 findByPaymentKey도 있고 별도의 fetchByPaymentKey와 같이 별도로 반드시 존재함을 의미하는 메서드를 만드는거였어요 
```java
public interface PaymentRepository extends JpaRepository<Payment, Long> {

    Optional<Payment> findByPaymentKey(String paymentKey);

    Optional<Payment> findByReservationId(Long reservationId);

    default Payment fetchByPaymentKey(String paymentKey) {
        return findByPaymentKey(paymentKey).orElseThrow(RuntimeException::new);
    }
}

```
근데 지금 메서드의 사용성을 보니 존재하면 에러가 나는 구조라서 
여기서는 이 방법을 쓸 수는 없겠네요 findReservationId에 대해서 한번 고려해보면 좋을것 같습니다

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/reservation/domain/Waitings.java
>              return 0;
0이 의미하는 게 뭔지 쉽게 이해하기 힘들것 같아서
상수로 처리하면 좋을것 같습니다!

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/AdminReservationService.java
> +public class AdminReservationService {
관리자 권한에 대한 분기는 ReservationService의 save에서 충분히 admin인지 아닌지를 알 수 있지 않을까요?
일단 지금 adminReservationApiController를 보니 LoginMember를 argumentResolver로 받고 있지는 않네요
loginMember를 이용하거나 혹은 request를 잘 변경하여 하나의 service로 충분히 관리 가능해보입니다

거의 90프로 이상이 같은 로직인것이고 이에 해당하는 부분이 변경되었을때 두군데 다 변경해줘야하는 번거로움이 있고
혹시나 한곳만 변경했을때의 문제도 심각할 수 있을것 같습니다
실무에서는 여러사람들과 같이 작업하기 때문에 이런 중복에 대한 부분을 다른 사람들이 알기 어려워서 제대로 수정이 안되는 상황이 쉽게 발생할수 있을 것 같아요

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/domain/Payment.java
> +        this.totalAmount = totalAmount;
```suggestion
        this(null, reservation, paymentKey, orderId ....)
```

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/dto/PaymentRequest.java
> +    public static PaymentRequest from(UserReservationSaveRequest userReservationSaveRequest) {
PaymentRequest 가 toss에게 api를 쏠때 필요한 dto이군요
지금 방법도 나쁘지 않을것 같습니다

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    public PaymentSaveResponse payForReservation(@Valid PaymentRequest paymentRequest, Reservation reservation) {
`@Valid`가 정상적으로 동작하나요?
클래스 레벨에 `@Validated` 가 붙어야지 않나요?

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    }
dto는 외부요청 입력에 대한 빠른 에러를 response하기 위한 용도이고
도메인은 이후 로직의 처리과정이나 response로 받은 값으로 객체를 생성 혹은 수정하는 과정에서 검증을 위해 반드시 필요할것 같습니다

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    private int totalAmount;
넵
BigDecimal을 반드시 사용해야하는 이유가 부동소수점 문제 때문입니다!

2024-06-09 11:30 UTC, choijy1705 commented on src/main/java/roomescape/payment/dto/PaymentRequest.java
>  public record PaymentRequest(
TossPaymentRequest로 명명하는게 안헷갈릴것 같아요!

2024-06-09 12:56 UTC, hyeon0208 commented on src/main/java/roomescape/reservation/domain/Waitings.java
>              return 0;
0은 대기 순서가 없음을 뜻하므로 `NO_WAITING_RANK`로 상수화하였고
같은 맥락으로 count + 1에서 + 1 에 대한 의미도 부여해주는 것이 이해를 돕기 좋을 것 같아
`MEMBER_DEFAULT_WAITING_RANK`로 상수화 적용했습니다!

2024-06-09 12:59 UTC, hyeon0208 commented on src/main/java/roomescape/payment/dto/PaymentRequest.java
>  public record PaymentRequest(
네이밍 때문에 request -> request 변환에 혼동을 드렸었군요 😅
다시 보니 다른 Toss 요청 DTO는 "TOSS" 접두사가 붙었는데
위 DTO만 없어 충분히 혼동을 야기 시킬 수 있을 것 같습니다 🤯
해당 부분 반영했습니다 !

2024-06-09 15:20 UTC, hyeon0208 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                });
오호 😯 위 처럼 반드시 존재함을 의미하는 메서드를 사용할 수도 있겠네요 !
`PaymentService`에 `findReservationId()`로 `Payment`를 찾아 오는 것이 아닌 위 방식으로 데이터를 가져오도록 수정하면서
다른 도메인들의 레포지토리에도 해당 기능을 추가했습니다!
확실히 코드가 더 간결해진 것 같아요 👍🏻

2024-06-09 15:32 UTC, hyeon0208 commented on src/main/java/roomescape/payment/domain/Payment.java
> +        this.totalAmount = totalAmount;
어떤 방식인지 궁금해 알아보니 생성자 체이닝이네요 👍🏻
다른 엔티티들도 위 처럼 생성자 체이닝을 적용해봤는데 코드도 더욱 간결해지고 재사용성 또한 높아진 것 같습니다 !

2024-06-09 15:43 UTC, hyeon0208 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +    public PaymentSaveResponse payForReservation(@Valid PaymentRequest paymentRequest, Reservation reservation) {
이 부분에 대해 처음 알게 되었어요 🫣
컨트롤러 클래스는 `@Validated`를 명시하지 않아도
메소드 파라미터에 `@Valid`를 사용하는 경우 대부분의 상황에서 Spring MVC가 자동으로 검증을 수행해주지만

다른 계층은 Spring MVC와 같은 자동 검증 메커니즘이 활성화 되지 않아서
명시적으로 `@Validated`어노테이션을 붙여 검증 기능이 활성화 되도록 해줘야하네요 !
해당 부분 반영했습니다 ! 👍🏻

2024-06-09 17:18 UTC, hyeon0208 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    }
설명감사합니다 ! 🙇🏼‍♂️
토스 API로 부터 받은 `TossPaymentResponse`로 `Payment` 객체를 생성하기 때문에
이 부분에 대한 검증이 필요하다는 것으로 이해했어요

`Payment`가 가지고 있는 필드 중에서
`TossPaymentResponse`와 같은 필드에 대해 검증이 필요할 것 같다고 생각이 들었는데
어디까지 검증을 해야하나 고민이 되었어요

`paymentKey`, `orderId`는 클라이언트로 부터 요청 받을 때 검증을 하고 있고
만약 토스로 부터 잘못된 `paymentKey`, `orderId`가 왔다해도 `Payment`에서 유효한 값이 확인 할 수 없고
`null`만을 검증할 수 있었는데 사실 null을 검증한다는 건 토스 API를 아예 신뢰할 수 없는게 아닌가라 생각이 들었고
테이블의 제약조건도 null을 허용하지 않기 때문에 이 부분은 검증 로직을 적용하지 않아도 될 거 같다 생각했어요

`PaymentMethod`, `PaymentCurrency`도 `Enum`을 통해 응답으로 받은 데이터와 매칭되지 않으면 예외가 발생했기 때문에
검증을 적용하지 않아도 될 것 같다고 생각했습니다.

`totalAmount`는 조금 달랐는데
클라이언트에 결제 요청을 받을 때 `@Range()`로 범위 검증을 하지만 
정수에 대한 검증이기 때문에 `BigDecimal`의 정밀도를 고려하지 않고 단순히 숫자 범위만을 검증하고 있다는 부분에서 
`Payment` 내부에서 정밀도 있게 검증하도록 로직을 추가했어요
또한 결제 가능 금액은 잘못된 입력이 아닌 비즈니스 정책이라 생각해 DTO에서의 검증을 하지 않고 도메인 내부에서만 검증하도록 수정해보았습니다.

아래와 같은 이유로 `totalAmount`에 대해서만 검증을 적용하게 되었는데 영이의 생각이 궁금합니다 !

2024-06-10 09:50 UTC, hyeon0208 commented on src/main/java/roomescape/payment/service/PaymentService.java
> +                });
+ 추가

`JpaRepository<Payment, Long> `상속 받는 인터페이스에서 `IllegalArgumentException`를 던지면 
`EntityManagerFactoryUtils` 클래스 내부에서 `IllegalArgumentException`를 잡아 `InvalidDataAccessApiUsageException`로 변환해 에러를 던져 테스트가 깨지는 문제가 있었어요
이 부분을 해결하고자 엔티티가 없을 때 발생하는 `EntityNotExistException` 커스텀 예외를 추가해보았습니다!

2024-06-10 09:59 UTC, hyeon0208 commented
안녕하세요 영이 피드백 주신 부분 반영해서 다시 리뷰 요청드립니다! 🙇🏼‍♂️

스크롤 하시면서 보기 불편하실까봐 답글단 코멘트의 링크 첨부합니다! 

- [dto는 외부요청 입력에 대한 빠른 에러를 response하기 위한 용도이고
도메인은 이후 로직의 처리과정이나 response로 받은 값으로 객체를 생성 혹은 수정하는 과정에서 검증을 위해 반드시 필요할것 같습니다](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632355103)

- [findReservationId에 대해서 한번 고려해보면 좋을것 같습니다](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632322922)

- [관리자 권한에 대한 분기는 ReservationService의 save에서 충분히 admin인지 아닌지를 알 수 있지 않을까요?](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632871934)

- [0이 의미하는 게 뭔지 쉽게 이해하기 힘들것 같아서 상수로 처리하면 좋을것 같습니다!](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632236704)

- [생성자 체이닝 적용](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632324620)

- [@Valid가 정상적으로 동작하나요?](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632326625)

- [TossPaymentRequest로 명명하는게 안헷갈릴것 같아요!](https://github.com/woowacourse/spring-roomescape-payment/pull/94#discussion_r1632240242)

2024-06-10 15:35 UTC, choijy1705 approved these changes
카키 피드백 잘 반영해주셨습니다
몇가지 추가 코멘트는 확인한번 해주시면 좋을것 같아요
미션은 여기서 머지하겠습니다
고생하셨어요👍👍

2024-06-10 15:35 UTC, choijy1705 commented on src/main/java/roomescape/payment/dto/PaymentSaveResponse.java
> +public record PaymentSaveResponse(String paymentKey, PaymentStatus status, BigDecimal amount) {
지금 단계에서는 딱히 중요하지 않지만
amount와 currency는 항상 같이 다녀야 합니다! 참고해주세요

2024-06-10 15:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/AdminReservationService.java
> +public class AdminReservationService {
메서드를 두개를 만드는 것도 중복니다
하나의 메서드에서 안에서 분기로 처리하는게 유지 보수성에서도 좋을것 같습니다!
request도 거의 대부분 같다면 그리고 같은 동작이라면 하나로 관리하는게 더 관리하기 편할것 같아요!

2024-06-10 15:35 UTC, choijy1705 commented on src/main/java/roomescape/payment/domain/Payment.java
> +        this.status = PaymentStatus.CANCELED;
참고로 canceldAt과 같은 정보로 관리하는게 
더욱더 의미있을것 같습니다!

2024-06-10 15:35 UTC, choijy1705 commented on src/main/java/roomescape/payment/domain/Payment.java
> +    }
지금 상황에서는 totalAmount만 해도 크게 무리는 없겠지만
로직이 앞으로 어떻게 변할지는 모르기 때문에 웬만하면 중요 필드들은 모두 검증을 하는것이 좋을것 같습니다!

2024-06-10 15:36 UTC, merged

2024-06-12 04:05 UTC, hyeon0208 commented on src/main/java/roomescape/payment/dto/PaymentSaveResponse.java
> +public record PaymentSaveResponse(String paymentKey, PaymentStatus status, BigDecimal amount) {
앗 응답에도 추가했어야했는데 놓쳤네요 감사합니다 ! 👍🏻