[2 - 4 단계 방탈출 예약 결제 / 배포] 리비(이근희) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #97
Opened 2024-06-07 08:51 UTC by Libienz

안녕하세요 조앤 🙌

2-4단계를 거쳐 결제 정보 저장과 배포 및 문서화 진행해보았습니다.
미션의 최소 요구 단계는 만족한 것 같아서 리뷰 요청드립니다 🙇🏻‍♂️

이전에 말씀드렸듯이 배포와 문서화는 이번에 처음 경험해보았습니다.
배포는 EC2 인스턴스 하나에 진행하였고 문서화는 Rest Docs를 사용해보았습니다.

개념들이 아직 잘 정리되지 않는 것 같은데 관련해서 많은 코멘트 주시면 답하면서 공부해보고 싶습니다

배포 URL: http://43.203.212.58:8080/
API 문서: http://43.203.212.58:8080/docs/index.html

ERD
![image](https://github.com/woowacourse/spring-roomescape-payment/assets/85234650/b97165e7-7fd0-41de-9401-63b347cb1e5b)

2024-06-08 00:57 UTC, seovalue commented
<img width="1624" alt="Screenshot 2024-06-08 at 9 55 25" src="https://github.com/woowacourse/spring-roomescape-payment/assets/48412963/3b9291d5-1398-405c-ac09-8951c6f200f2">

http://43.203.212.58:8080/login
여기서 로그인하고 결제시도하면 계속 예약 결제 실패 메시지, console을 보면 로그인되어있지 않다고 나와요! (3트해봄)
로그인이 계속 풀리는 것 같아요?

2024-06-08 01:16 UTC, seovalue commented
> 배포는 EC2 인스턴스 하나에 진행하였고 문서화는 Rest Docs를 사용해보았습니다.

1. ec2에 배포할 때 어떤 과정으로 진행했어요? 전체적인 flow를 설명해주시면 좋을 것 같아요!
2. RestDocs를 선택해주신 이유가 궁금해요.

2024-06-08 01:17 UTC, seovalue requested changes
리비! 미션 잘 수행해주셨네요ㅎㅎ
코멘트 남겼는데 확인 후 리뷰 요청 주세요~ 오늘 비가 온대요☔

2024-06-08 01:17 UTC, seovalue commented on build.gradle
> +configurations {
configurations는 어떤 역할을 해주는 block이에요?

2024-06-08 01:17 UTC, seovalue commented on build.gradle
> +ext {
ext는 어떤 역할을 해줘요?

2024-06-08 01:17 UTC, seovalue commented on build.gradle
> +asciidoctor {
asciidoc이 생성되는 순서가 어떻게 돼요?

2024-06-08 01:17 UTC, seovalue commented on src/docs/asciidoc/admin-view.adoc
> +
pageview도 추가해주신 이유가 궁금해요~

2024-06-08 01:17 UTC, seovalue commented on src/docs/asciidoc/login.adoc
> +operation::login-controller-test/should_handle_login_request_with_wrong_password[snippets='http-request,http-response']
로그인 실패는 로그인 API에 대한 응답 케이스 인 것 같은데, 로그인에 대한 하위로 내리는 것은 어때요?

지금 구조 상 로그인 실패라는 API가 존재하는 것처럼 느껴져요!

2024-06-08 01:17 UTC, seovalue commented on src/main/java/roomescape/payment/dto/PaymentConfirmResponse.java
> +        BigDecimal totalAmount,
오홍! BigDecimal로 변경해주신 이유가 궁금해요~

2024-06-08 01:17 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/ReservationRepository.java
> +            SELECT new roomescape.reservation.domain.MyReservation(r1, COUNT(*), p.paymentKey,p.orderId,p.amount)
[시간나실 때 한번 생각해주세요~ 패쓰해도 돼요!]
이 쿼리는 지금 여러번 JOIN하고 심지어 연산 쿼리도 하고 있어요. 만약 엄청 많은 수의 유저가 내 예약을 조회한다면 성능이 어떻게 될까요?
이 쿼리를 개선할 수 있는 방법이 있을까요?

2024-06-10 07:43 UTC, Libienz commented on build.gradle
> +configurations {
build.gradle 내부에서 사용되는 종속성을 정의하고 그룹화할 수 있는 블록입니다.
```gradle
configurations {
    asciidoctorExt
    compileOnly {
        extendsFrom annotationProcessor
    }
}
```
현재의 코드에서는 asciidoctorExt라는 종속성을 정의하고 있으며 annotationProcessor를 compileOnly시점으로 grouping 및 설정하고 있습니다.

- ps. gradle 문법에 관해서 아는 것이 하나도 없어 제 설명이 틀렸을지도 모르겠습니다. 혹 어색한 부분이 있다면 적극적으로 말씀해주 시면 감사하겠습니다 🙇🏻‍♂️

2024-06-10 07:49 UTC, Libienz commented on build.gradle
> +ext {
ext 블록은 프로젝트 스크립트에서 사용할 수 있는 사용자 지정 속성을 정의하는 데 사용됩니다.
전역변수를 선언하는 느낌인 듯 합니다!

```gradle
ext {
    snippetsDir = file('build/generated-snippets')
}
```
해당 코드에서는 테스트 코드로 부터 생성된 스니펫 파일들이 저장될 위치를 정의하고 있습니다.

2024-06-10 07:51 UTC, Libienz commented on build.gradle
> +asciidoctor {
- 테스트 코드를 통해 스니펫들이 생성됩니다.
- 생성된 스니펫들은 저희가 정의한 adoc 템플릿에서 참조형식으로 사용됩니다.
- 완성된 adoc들은  asciidoctor에 의해 html로 변환됩니다.
- 변환된 html이 제가 정의한 태스크에 의해 static/resources 위치로 복사됩니다.

2024-06-10 07:54 UTC, Libienz commented on src/docs/asciidoc/admin-view.adoc
> +
`이런 요청을 보내면 이런 응답이 갈거야`라는 측면에서 페이지뷰도 명세로 정의하기에 위화감이 없다고 생각했습니다.

다만 현재는 api 명세는 api에 대해서 설명하는 것으로 충분하다는 생각을 가지게 되었습니다.
조앤은 어떻게 생각하시나요?

2024-06-10 10:47 UTC, Libienz commented on src/docs/asciidoc/login.adoc
> +operation::login-controller-test/should_handle_login_request_with_wrong_password[snippets='http-request,http-response']
계층화로 의미에 혼동이 없도록 처리했습니다!

2024-06-10 11:25 UTC, Libienz commented on src/main/java/roomescape/reservation/domain/ReservationRepository.java
> +            SELECT new roomescape.reservation.domain.MyReservation(r1, COUNT(*), p.paymentKey,p.orderId,p.amount)
Join과 연산 쿼리는 무거운 작업으로 성능이 좋지 않을 것 같습니다.
다만 여러방의 쿼리가 나가는 것보다는 극단적인 한방 쿼리가 유리한 지점이 있을 것이라고 생각했어요. 

> 이 쿼리를 개선할 수 있는 방법이 있을까요?

지금 당장에는 단순한 여러개의 쿼리로 처리하는 것 밖에 생각나지 않습니다.

그런데 사실 여러방의 쿼리를 나가도록 하는 것이 진정한 개선인지도 잘 모르겠습니다 🤔

물론 쿼리 개선에 대해서 고려해야할 벡터가 발생하는 쿼리 수 하나뿐인 것은 아닙니다.
네트워크 비용, 동시성, 데이터베이스 부하 상태 등등 고려해야 할 것들이 많은 것으로 알고 있어요.
트레이드 오프 맥락을 스스로 저울질 해보기 힘드네요..


이번 코멘트는 잘 모르겠습니다..!
조금 더 힌트주실 수 있을까요!!?

2024-06-10 11:57 UTC, Libienz commented
> ec2에 배포할 때 어떤 과정으로 진행했어요? 전체적인 flow를 설명해주시면 좋을 것 같아요!

- 우테코에서 관리중(?)인 AWS 계정에 IAM 계정으로 접근
- ec2 인스턴스 생성 
   - OS 이미지 선택
   - 인스턴스 유형 선택
   - 키 페어 생성 
   - 네트워크 및 서브넷, 보안그룹 선택
- ssh 이용, AWS EC2 접속
- 빌드 및 서버 어플리케이션 실행

제가 아는 만큼 써보았습니다.
어색한 부분이나 추가적인 질문 알려주시면 많은 도움 될 수 있을 것 같습니다 🙇🏻‍♂️

> RestDocs를 선택해주신 이유가 궁금해요.

문서화를 처음 접해보고 다음 3가지 방법이 있음을 알 수 있었습니다.
- 직접 작성하는 위키 방식
- Swagger
- RestDocs

직접 작성하는 방식보다는 Swagger나 RestDocs를 이용한 자동화를 경험해보고 싶었습니다.
그래서 이번 미션을 진행할 때 Swagger도 써보고 RestDocs도 적용해보았습니다.
(커밋 로그에는 Swagger를 적용했던 기록이 남아있지 않습니다)

스웨거를 사용해본 개인적인 소감은 다음과 같습니다.
우선 학습이 비교적 쉬웠습니다. 애노테이션 기반으로 명세를 작성하는 것이 그리 어렵게 느껴지지 않았어요.
그리고 api를 불러볼 수 있는 호출부가 문서에 자동으로 생성되는 것이 좋았습니다. 
다만 명세 코드가 컨트롤러에 침범하여 컨트롤러 로직이 복잡해지는 것이 마음에 들지 않았어요. 다른 크루들도 이를 제일 큰 단점으로 여기던데 저 역시 동감하게 되었습니다.

반면에 RestDocs는 테스트 코드를 강제하고 adoc을 작성해야 하는 번거로움이 있었습니다. 또한 개인적으로 느끼기에 학습이 조금 더 어려웠어요
다만  프로덕션 코드가 깔끔하다는 것이 굉장히 큰 이점이라고 생각하여 결국 RestDocs를 선택하였습니다

2024-06-11 13:13 UTC, seovalue commented on build.gradle
> +configurations {
저두 예전에 (지금도 그렇지만..) gradle에 대해서 잘 모르고 썼는데, 나중에 배포하고 빌드 스크립트 만들고 최적화할 땐 gradle에 대해서 잘 아는 것도 좋더라고요ㅎㅎ 그래서 하나씩 추가될 때마다 추가되는 것이라도 어떤 역할인지 알아두면 좋을 것 같아요!

2024-06-11 13:15 UTC, seovalue commented on src/docs/asciidoc/admin-view.adoc
> +
저는 보통은 서버에서 페이지를 응답한 경우는 적긴 한데요ㅎㅎ
API 명세를 보는 클라이언트를 생각한다면 pageview는 꼭 포함되진 않아도 될 것 같다는 생각이 들기도 하네용!

2024-06-11 13:25 UTC, seovalue commented on src/main/java/roomescape/reservation/domain/ReservationRepository.java
> +            SELECT new roomescape.reservation.domain.MyReservation(r1, COUNT(*), p.paymentKey,p.orderId,p.amount)
이거 요즘 제가 고민중인거라 한번 여쭤봤어요ㅎㅎ

서비스에서 사용되는 쿼리는 보통 인덱싱 요청을 드리긴 해요
조건절에 주로 사용되는 필드를 활용해서요
근데 이렇게 복잡하게 join이 많이 걸린다면, 인덱스를 탈 수가 없을 것 같아요
그렇다면, 적절한 인덱스를 탈 수 있는 여러 건의 쿼리로 나누는 것이 좀 더 나을 수 있을 것 같다는 생각도 들어요ㅎㅎ

예를 들어서 적절한 예시는 아닐 수 있지만, ㅎㅎ
책장에서 책을 찾을 때 ㄱ~ㅎ 까지 정렬된 곳에서 3번 찾는 것과 무작위로 섞인 책장에서 한 권의 책을 찾는 것을 따졌을 때, 전자가 더 나을 수도 있을 것 같다?는 생각이 들어서 한번 여쭤봤어요

쿼리는 항상 어려운 것 같아요..ㅎㅎ

2024-06-11 13:25 UTC, seovalue commented
리비는 새로 회원가입을 한 뒤 진행하셔도 로그인이 정상적으로 되시는 건가요?!?!

2024-06-11 13:28 UTC, seovalue approved these changes
안녕하세요 리비! 리뷰가 늦어졌네요ㅠㅠ
추가적으로 더 남길 코멘트가 없어서, 머지해도 될 것 같아요!
혹시라도 궁금한 점이 있으시면 남겨주시면 확인하고 답변드려볼게요!
고생 많으셨어요!~ 💯

2024-06-11 13:28 UTC, merged

2024-06-12 02:20 UTC, Libienz commented
> 리비는 새로 회원가입을 한 뒤 진행하셔도 로그인이 정상적으로 되시는 건가요?!?!

회원가입 -> 로그인 -> 예약 순으로 진행했을 때 저는 문제를 확인하지 못했습니다..!
우선 제 서비스에서 회원가입을 진행하면 자동으로 로그인 되지 않는데 아마 이부분에서 걸리신게 아닌가 싶네요.. 🥲