[2 - 4 단계 방탈출 예약 결제 / 배포] 미아(이종미) 미션 제출합니다.
woowacourse/spring-roomescape-payment pull request #98
Opened 2024-06-07 09:39 UTC by jongmee

안녕하세요 제이! 이번 단계도 잘 부탁드려요 😊

[API 문서](http://43.202.58.20:8080/docs/api.html)와 [배포링크](http://43.202.58.20:8080/)입니다! 배포 스크립트도 추가해두었습니다 :) (배포용 `application-deploy.yml` 파일은 올리지 않았습니다.)

** 어드민 계정: 아이디 - `admin@admin.com`, 비밀번호 - `1234`
** 일반 사용자 계정: 아이디 - `mia@mia.com`, 비밀번호 - `1234`

## ERD
<img width="452" alt="스크린샷 2024-06-07 오후 3 32 39" src="https://github.com/woowacourse/spring-roomescape-payment/assets/101439796/3c1db5ea-f2fb-4f47-9a45-fd0eacb92f1e">

이번 단계에서 Payment 테이블이 추가되었습니다. 

## 집중한 부분
### 서비스 정책 구체화
- 기존: `예약` 취소 시 첫 번째 `대기` 예약이 `예약`으로 승인된다.
- 변경된 후:
   - `예약` 취소 시 첫 번째 `대기` 예약이 `결제 대기`로 변경된다. (`예약` 건은 환불됨)
   - 관리자의 '대기 예약 목록 페이지'에 `결제 대기`와 `대기` 예약 목록이 조회된다. `결제 대기`에 한해서 '승인' 버튼이 생긴다. 수동으로 승인할 수 있다.

대기 예약에 대한 결제는 어플리케이션이 관리하지 않고 어드민이 (알아서) 진행할 수 있습니다.

### Reservation(예약 객체) 및 Payment(결제 객체) 생성 로직
- 저번 단계에서 예약 생성이 실패 되었을 경우 토스 결제 api에 요청이 가지 않게 하기 위해 하나의 트랜잭션 안에서 '예약 객체 생성' -> '결제 요청'을 하였습니다. 하지만 리뷰 주신 것처럼 외부 api 요청이 트랜잭션 안에 있을 경우 데이터베이스 connection을 오래 잡고 있을 수 있고, 결제 결과를 저장하는 Payment 객체는 api 요청 후 저장되어야 합니다. 

- 따라서 트랜잭션 시작 전에 토스 결제 요청을 하고, TransactionalEventListener를 사용하여 예약과 결제를 저장하는 트랜잭션이 롤백된다면 토스 결제 취소 api에 요청을 하도록 변경하였습니다. (`PaymentService`의`cancelCasedByRollBack` 메소드)

### PaymentClient 추상화
PaymentService가 추가되면서 구조를 더 고민해보았습니다. 저번 단계 리뷰에서 제시해주신 것처럼 PaymentClient를 인터페이스로 추상화하고 구현체 및 web client 관련 설정들을 infrastructure 패키지로 옮겼습니다. PaymentService는 도메인 계층에만 의존합니다.

### reservation 패키지와 payment 패키지 의존성 분리
- Reservation과 Payment는 별개의 도메인이라고 생각하여 패키지와 도메인 클래스를 분리하였습니다. 관심사도 다르고(라고 생각하고) 예약 대기, 승인된 대기는 결제 없이 존재합니다. 

- 하지만 첫 예약(Reservation)이 생성되면 Payment도 저장되고 Payment가 존재하는 Reservation이 삭제되면 Payment도 삭제됩니다. 이 점만으로 BookingManageService에서 PaymentService나 PaymentRepository를 사용하기 보다, 이벤트를 발행해서 의존성을 분리하였습니다. 의존성 관점에서는 이점이 있지만 불필요하게 로직의 흐름이 복잡해진 것 같기도 합니다 🥲

2024-06-08 05:34 UTC, JunHoPark93 requested changes
안녕하세요 미아~
미션구현하느라 고생많으셨어요.
많은 것들을 적용해보셨네요. 피드백이 너무 커질거같아서 키설계 & controller-service구조 위주로만 먼저 봐주시면 될거같습니다.

2024-06-08 05:34 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/application/PaymentService.java
> +    @TransactionalEventListener(value = ReservationFailedEvent.class, phase = TransactionPhase.AFTER_ROLLBACK)
TransactionalEventListener 까지 사용해보셨네요!
어떤 의도로 사용하셨을까요?

2024-06-08 05:34 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/domain/Payment.java
> +
paymentKey는 unique할까요?

2024-06-08 05:34 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/domain/Payment.java
> +
키 설계시 어떤 고려를 하셨나요?
복합키 사용을 한다면 어떻게 될지도 고려해보시고 내용정리해보시면 좋을거같아요.

비지니스요건상 paymentKey로 조회가많이 일어난다면 추가적으로 index관리에 대한 비용도 들텐데 트레이드오프를 어떻게 가져가면 좋을까요?

2024-06-08 05:34 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/domain/PaymentRepository.java
> +    @Query("SELECT p FROM Payment p WHERE p.reservation.id = :reservationId")
여긴 왜 Query를 사용하셨나요?

2024-06-08 15:19 UTC, jongmee commented on deployment.sh
> +echo ">>> Stop Running server"
stop하고 run 하는 사이에 서비스 이용을 못하게 됩니다. jar 파일을 실행할 때 포트 번호를 다르게 해주어서 먼저 run하고 stop하면 무중단으로 배포될 수 있을 것 같습니다 🤔

2024-06-08 15:31 UTC, jongmee commented on src/main/java/roomescape/reservation/presentation/ReservationController.java
> +        Reservation scheduledReservation = bookingManageService.scheduleRecentReservation(createdReservation);
> 미아가 생각하시는 컨트롤러의 역할은 무엇일까요?

컨트롤러는 요청을 받고 응답을 반환해주는 핸들러입니다. 비즈니스 로직과 뷰를 이어줍니다. 서비스 클래스에서 dto가 아닌 도메인 객체를 받는 것에 집중하다 보니 비즈니스 로직이 컨트롤러에 존재했네요 🥲

1. [예약 생성 API] 우선 예약을 생성하는 api에서 테마, 시간, 사용자를 조회하고 Reservation 객체를 생성하는 로직이 컨트롤러에 있어, 이 부분을 ReservationFactory라는 서비스 클래스로 뺐습니다. 
2. [예약 생성 API] 기존의 bookingManageService의 `scheduleRecentReservation` 메소드 기능을 reservationManageService의 `create` 메소드가 수행하도록 변경하였습니다.
3. [사용자 예약 조회 API] 기존의 BookingQueryService와 WaitingQueryService를 ReservationQueryService로 통합하여 사용자 예약 조회(예약, 대기 예약, 결제 대기 상태인 모든 예약의 조회)를 ReservationQueryService의 `findAllMyReservations` 메소드가 수행하도록 변경하였습니다. 따라서 ReservationController의 `findMyReservations` 메소드는 각 상태별 예약 조회 결과를 합치는 과정을 하지 않아도 됩니다.

우선 이렇게 비즈니스 로직의 흐름을 어플리케이션 계층에서 관리하도록 변경해보았습니다 😊 !

2024-06-08 15:34 UTC, jongmee commented on src/main/java/roomescape/payment/domain/PaymentRepository.java
> +    @Query("SELECT p FROM Payment p WHERE p.reservation.id = :reservationId")
JPA에서 제공하는 (이름으로 짓는) 쿼리 메소드의 경우 아래와 같이 left join 쿼리가 나갑니다.
```java
Optional<Payment> findByReservationId(Long reservationId);
```
```
    select
        p1_0.id,
        p1_0.order_id,
        p1_0.payment_key,
        p1_0.reservation_id,
        p1_0.total_amount 
    from
        payment p1_0 
    left join
        reservation r1_0 
            on r1_0.id=p1_0.reservation_id 
    where
        r1_0.id=?
```

left join할 필요 없이 reservation_id만 확인해주면 되기 때문에 직접 쿼리를 작성하였습니다 !

2024-06-09 00:58 UTC, jongmee commented on src/main/java/roomescape/payment/domain/Payment.java
> +
paymentKey는 `외부 결제 대행 서비스에 요청을 보낼 때 payment를 식별하는 역할`을 합니다. 한 결제 대행 서비스에 대해서는 unique하지만 여러 결제 대행 서비스를 사용할 경우 이 프로그램의 db에서는 paymentKey가 unique하지 않을 수 있다고 생각하여 unique 설정을 하거나 pk로 사용하지 않았습니다!(현재 사용하는 토스 페이먼트는 아니지만 다른 서비스(카카오페이 등)는 결제 후에 유니크한 값을 주더라구요) paymentKey를 `결제 api에 요청 보낼 때 쓰는 key`로 생각해 조회할 땐 일대일 관계인 reservation_id로 조회할 일이 많을 것이라고 생각했습니다. 이렇게 생각해보니 reservation_id를 pk로 해도 될 것 같네요 😅

payment key로 조회가 많이 일어날 것이라고 생각하지 못했는데, 더 생각해보니 결제 서비스에서 'payment를 식별하는 역할'을 한다는 것 자체로도 충분히 조회가 많이 일어날 수 있겠군요 ..! 

> 복합키 사용을 한다면 어떻게 될지도 고려해보시고 내용정리해보시면 좋을거같아요.

여러 컬럼으로 pk를 사용한다고 알고 있는데, 컬럼에 PG사 enum을 추가하고 paymentKey와 함께 pk로 설정하면 unique해질 수 있을 것 같습니다.

`reservation_id`와 `paymentKey & PG사 enum` 모두 pk가 될 수 있습니다. 두 경우 모두 조회가  해당 컬럼으로 많이 일어나서 index를 추가로 생성하는 일은 없어집니다.(장점) 
생각해본 단점은, 일단 `reservation_id`은 id 생성 전략이 테이블 간 연관 관계에 의존합니다.  연관 관계가 달라지면 id 생성 전략도 영향을 받습니다. `paymentKey & PG사 enum`는 auto_increment pk보다 순서 관련 조회에서는 성능이 떨어집니다. paymentKey로 조건을 걸어 조회하는 일 제외하고는 느립니다. 

우선 payment 테이블에 PG사 관련 컬럼이 없어 추가하였습니다. 반쪽짜리 설계였네요 🥲 우선 위와 같이 고려해보았는데 제이의 추가적인 의견이 궁금합니다!

2024-06-09 01:39 UTC, jongmee commented on src/main/java/roomescape/payment/application/PaymentService.java
> +    @TransactionalEventListener(value = ReservationFailedEvent.class, phase = TransactionPhase.AFTER_ROLLBACK)
예약 생성 및 결제 내역 저장에 실패(롤백)하면 결제 취소 api에 결제 취소 요청을 하도록 사용하였습니다!

2024-06-09 02:50 UTC, jongmee commented
안녕하세요 제이! 리뷰에 변경사항 및 답변 달아놓았습니다 :)

2024-06-09 10:50 UTC, JunHoPark93 commented on deployment.sh
> +echo ">>> Stop Running server"
해결책중 한가지를 찾아보셨네요 👍🏼

지금 상황에서 피드백을 드리는게 맞는지는 모르겠지만, 배포미션이 있다고 하기에 생각만 해보면 좋을거같아서 추가로 남깁니다.

1. 포트를 바꾸면 구현하신 앱서버 앞단에 있는 서버들에서 트래픽을 돌리는 추가작업을 해줘야하지않을까요?
2. 일반적인 배포종류는 어떤것들이 있을까요?

2024-06-09 10:52 UTC, JunHoPark93 commented on src/main/java/roomescape/reservation/presentation/AdminReservationController.java
> +        Reservation createdReservation = bookingManageService.create(newReservation);
많은 개선이 있었네요 고생하셨어요 👍🏼
개인적으로 요런 객체 만드는것도 컨트롤러에서는 안보이게끔 하고있어요. 필요한 서비스호출 + ResponseEntity생성 딱 이 2단계면 충분하다고 생각합니다.

2024-06-09 10:52 UTC, JunHoPark93 commented on src/main/java/roomescape/reservation/presentation/ReservationController.java
> +        Reservation scheduledReservation = bookingManageService.scheduleRecentReservation(createdReservation);
고생많으셨습니다! 해당 부분에 추가 코멘트 남겨둘게요

2024-06-09 10:57 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/application/PaymentService.java
> +    @TransactionalEventListener(value = ReservationFailedEvent.class, phase = TransactionPhase.AFTER_ROLLBACK)
음 예약생성이 확실히되고나서 (커밋이후) 이벤트를 받고 결제요청이 들어가는게 순서가 맞을거같긴한데 실패도 이런식으로 처리를 해보신거군요

2024-06-09 11:03 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/domain/Payment.java
> +
잘생각해보셨어요!
복합키사용시 조회우선순위가 높은 컬럼을 인덱스의 첫번째 위치에 두는등 고려해야될것들이 많아질거같아요. 또한 다른테이블들이 이 테이블의 키에 의존하게되면 데이터모델이 변경될때 영향도도 있을거구요.
지금 구조에서 유니크 제약조건만 잘 처리해주시면 충분할거같네요!

2024-06-09 11:07 UTC, JunHoPark93 approved these changes
안녕하세요 미아~
리뷰반영하느라 고생많으셨어요.
구조도 많이 나아졌네요! 질문주신 부분은 코멘트 남겨두었는데 확인 후 해결되지 않았다면 다시 노티부탁드려요. 
일단 머지는 하는데 배포이슈 등 다른 이슈들이 생긴다면 다시말씀주세요

2024-06-09 11:07 UTC, JunHoPark93 commented on src/main/java/roomescape/payment/infrastructure/PGCompanyPersistConverter.java
> +public class PGCompanyPersistConverter implements AttributeConverter<PGCompany, String> {
컨버터는 항상 테스트 만들어주세요 ㅎㅎ

2024-06-09 11:08 UTC, JunHoPark93 commented
배포 url은 접속이 안되는데 서버를 내려놓으신건가요?

2024-06-09 11:08 UTC, merged

2024-06-10 09:12 UTC, jongmee commented on src/main/java/roomescape/reservation/presentation/AdminReservationController.java
> +        Reservation createdReservation = bookingManageService.create(newReservation);
더 공부해보니 facade 패턴이라는게 있군요! 더 공부하고 나서 적용해보겠습니다. "필요한 서비스호출 + ResponseEntity생성 딱 이 2단계" 로만 컨트롤러를 사용할 수 있을 것 같네요 😊

2024-06-10 09:14 UTC, jongmee commented on src/main/java/roomescape/payment/infrastructure/PGCompanyPersistConverter.java
> +public class PGCompanyPersistConverter implements AttributeConverter<PGCompany, String> {
이런 🥲 🥲 작성해보겠습니다!

2024-06-10 09:28 UTC, jongmee commented on src/main/java/roomescape/payment/application/PaymentService.java
> +    @TransactionalEventListener(value = ReservationFailedEvent.class, phase = TransactionPhase.AFTER_ROLLBACK)
결제 내역 저장이 추가되면서 적절한 롤백과 트랜잭션 범위를 관리하는게 어렵네요 🥲 

 결제 api 호출을 예약 생성 로직보다 앞에서 하기 때문에 예약 생성 시 진행되는 검증 로직(서비스 클래스의 날짜 검증 등)이 존재한다면 사용자는 예외 메세지와 함께 결제 취소를 받게 되는게 단점인 것 같습니다. 잘못된 날짜로 요청했다면 결제 되기 전에 확인되는게 사용자 경험에서 좋을 것 같네요..!

모두 한 트랜잭션으로 묶되 (예외 처리와 함께) read timeout을 30초보다 훨씬 짧게 가져가는 것도 괜찮을 것 같습니다 🤔

2024-06-10 09:30 UTC, jongmee commented
주말에는 어째서인지 다른 크루들도 마찬가지로 배포 url에 접속이 안됐던 것 같은데 지금은 잘 됩니다!

(머지가 되어 리뷰 요청을 드리기 애매해서 코멘트로만 남겨둡니다 ☺️ )